WIP / DISCUSSION Cocoapods action with the ability to run pod update
fastlane/fastlane pull request #10046
Opened 2017-08-14 07:04 UTC by mRs-

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Sometimes it's crucial in my setup to run cocoapods update instead of cocoapods install to get the newest dependencies in my project. I made it possible to run the cocoapods command with the parameter update to run `pod update` instead of `pod install`.

### Discussion
I was not really sure about if this should be a new action or I can implement this directly in the current cocoapods action. If you have any feedback for me where to place this, I would be very happy.

2017-08-14 09:13 UTC, mRs- commented
I signed it!

2017-08-14 17:44 UTC, taquitos requested changes
This looks good to me, it would be great if you could update the unit tests 👍  It should be relatively quick since a bunch already exist for `pod install`

2017-08-14 19:12 UTC, mRs- commented
Yeah the unit tests should be no problem at all, wanted to check if this is appreciated first. Instead of working all the things to an end and it would be turned down anyway ;)

2017-10-24 19:00 UTC, ohayon commented
Hey @mRs- - just wanted to bump this PR to see if you had a chance to update those unit tests? Thanks!! 🦅

2017-12-04 20:39 UTC, ohayon commented
Hey @mRs-! I am going to go ahead and close this PR for now as it's been active for quite a while. But please feel free to reopen it if/when you have a chance to make those changes to the tests. Thanks!! 🚀

2017-12-04 20:39 UTC, closed without merging

2017-12-06 12:14 UTC, mRs- commented
Yeah, didn't have the time to look into this :(