Values are represented as strings in FL_OCLINT_SELECT_REGEX
fastlane/fastlane pull request #10084
Opened 2017-08-18 03:41 UTC by taquitos

Need to make them regexs, should fix #10069

2017-08-21 13:24 UTC, endocrimes requested changes

2017-08-21 14:44 UTC, snatchev commented on fastlane/lib/fastlane/actions/oclint.rb
> +              $SAFE = 1
++ for `Regexp.new`. Will probably have to strip the preceding and ending `/`

2017-08-21 15:34 UTC, taquitos commented on fastlane/lib/fastlane/actions/oclint.rb
> +              $SAFE = 1
Regexp requires that the string be single-quoted, otherwise you have to extra-escape things.

2017-08-21 17:45 UTC, taquitos commented
@DanToml + @snatchev any thoughts on a better way to ensure that strings which are double-quoted, as well as single-quoted are turned into Rexexps?

2017-08-22 14:25 UTC, snatchev commented
@taquitos could you explain the desired behavior? AFAIK it's not possible to determine if a string literal was created via single or double quotes (or `%q{}` / `%Q{}` for that matter).

2017-08-22 14:34 UTC, snatchev commented
If the goal is to turn a specific input into a regex v.s. literal string match, I propose something like this:

```ruby
if select_regex =~ %r{^/(.*)/$}
  select_regex = Regexp.new($1)
else
  select_regex = Regexp.new(Regexp.escape(select_regex))
end
```

2017-08-22 15:59 UTC, taquitos commented
@snatchev, in the referenced issue, setting `FL_OCLINT_SELECT_REGEX` to a string causes issues when passing the string through Regexp.new(). The issue is that depending on single vs double quoted, you may have to escape `/` . My thought was: allow whatever as a string, and don't worry about escapes because eval() will turn it into a regex. That way parsing single quotes or double quotes doesn't matter, people can just write the regex in a string without worrying which means fewer github issues. That being said, I'm starting to think we should just stick to Regexp and tell people to escape their regexes if needed.

2017-08-22 21:02 UTC, snatchev commented
@taquitos Sounds good. I agree that we shouldn't try to be too clever here.

In that case, we can simplify some of the logic in this method
```ruby
def self.ensure_regex_is_not_string!(regex)
  return regex unless regex.kind_of?(String)

  Regexp.new(regex)
end
```

2017-08-22 23:41 UTC, endocrimes approved these changes

2017-08-23 00:31 UTC, taquitos commented
Woo, thanks for the review @DanToml!

2017-08-23 00:31 UTC, merged