Fixed wrong working directory in cocoapods.error_callback call
fastlane/fastlane pull request #10309
Opened 2017-09-11 19:38 UTC by SiarheiFedartsou

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
See the issue: https://github.com/fastlane/fastlane/issues/10308

### Description
I'm just changing directory to default fastlane folder before calling `error_callback`. Also I'm not sure: maybe it should be fixed at global level in `sh_helper.rb:sh_control_output` method?

2017-09-11 19:39 UTC, SiarheiFedartsou commented
I signed it!

2017-09-12 16:40 UTC, ohayon approved these changes
Thanks @SiarheiFedartsou ! This is a great change. While it would be great to put this in the `sh_control_output` method, I'm a bit worried that it will break some people's existing configurations and we dont really hear of this being an issue very often with other actions so I think we should roll with this change. Thanks again! 🚀 🐙

2017-09-12 16:41 UTC, ohayon requested changes
Ah, before we merge this, should we check to make sure the `params[:error_callback]` is not nil before `call`ing it?

2017-09-12 19:12 UTC, SiarheiFedartsou commented
@ohayon Thanks for review! Just fixed the issue.

2017-09-12 21:05 UTC, ohayon approved these changes

2017-09-12 21:05 UTC, merged

2017-09-12 21:06 UTC, ohayon commented
Thanks @SiarheiFedartsou !! 🚀 !!