Show prettier error message when user has insufficient permissions in iTunes Connect
fastlane/fastlane pull request #10313
Opened 2017-09-12 12:21 UTC by MortenGregersen

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
A iTunes Connect user with 'Developer' role trying to update meta data for an app update will receive an error response like this:
```ruby
{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["insufficient privileges"]}, "statusCode"=>"ERROR"}`
```
This error is not handled and the user will get the above response printed in the log.

### Description
This change will print a prettier message when the above happens.

To ensure that the action/`calling_method_name` was correct in this case, I had to add a new option to `raise_insuffient_permission_error!`. Without this option the error would say that the user don't have permission to `parse_reponse`. I'm not sure this is the right way to do it.

2017-09-12 20:48 UTC, ohayon reviewed
Hey @MortenGregersen thanks for this change! It would be really nice to have a better message for that. I am a bit nervous about just checking this string as Apple is known to change things around pretty often. Is there any other way we can detect this error? 🐙

2017-09-12 20:53 UTC, MortenGregersen commented
@ohayon The only information we get back from Apple is the response I wrote above. If we should check for anything else we should look at the roles of the user.

2017-09-12 21:11 UTC, ohayon commented
I think that might be a little safer because I think at least those are less likely to change? Thoughts? 🐒

2017-09-12 21:34 UTC, MortenGregersen commented
But it will require that we make a new request. I don't think we have information about the user at this point.

Furthermore we need to analyze how the roles relates to the different actions the user can perform.

2017-09-14 17:20 UTC, taquitos commented on spaceship/lib/spaceship/client.rb
> +        raise_insuffient_permission_error!(caller_location: 3)
I think specifying `caller_location` is ok here, but lets add some comments around why you're passing 3, and what the effect is.

2017-09-14 17:49 UTC, taquitos requested changes
Just add some comments and 👍

2017-09-21 08:44 UTC, MortenGregersen commented
@taquitos I've added comments about the `caller_location`

2017-09-21 15:35 UTC, taquitos approved these changes

2017-09-21 15:36 UTC, merged

2017-09-21 15:36 UTC, taquitos commented
🎈🐐