Gym profile matching : ignore profile that do not match the correct platform
fastlane/fastlane pull request #10387
Opened 2017-09-20 18:41 UTC by nicolasbraun

### Motivation and Context
When a project has an iOS and a tvOS target the bundle identifier are the same.
It should not result in a duplicate error when matching.

Fixes: #10341

This PR includes PR #10386 but as it may lead to more discussion I made 2 PRs

### What did I do
- Detect what should be the base SDK in the build_settings based on the destination option in gym
- Filter target based on this configuration

2017-09-20 18:50 UTC, joshdholtz submitted a review, later dismissed
Also having some tests would be nice 😊 ❤️

2017-09-21 02:07 UTC, thasegaw requested changes

2017-09-21 02:07 UTC, thasegaw commented on gym/lib/gym/code_signing_mapping.rb
> +      return build_settings["SDKROOT"] != sdkroot
If the `SDKROOT` is `watchos` and `destination` is `iOS`, it should be handled as same platform.
The Provisioning Profiles for watchOS is necessary for archiving iOS app.

2017-09-22 21:02 UTC, nicolasbraun commented
@joshdholtz test added + some other changes / error catches

2017-09-28 14:30 UTC, nicolasbraun commented
@joshdholtz any chances this gets in the next release?

2017-09-28 14:31 UTC, nicolasbraun commented
Signed, changed email

2017-09-28 14:32 UTC, nicolasbraun commented
Test to trigger google bot :)

2017-09-28 15:50 UTC, joshdholtz commented
@nicolasbraun Will review today! Will be getting to my computer/office in about hour and half-ish 👀

2017-09-28 21:21 UTC, nicolasbraun commented
trigger cla

2017-09-28 22:40 UTC, taquitos commented on gym/lib/gym/code_signing_mapping.rb
> +      destination.slice! "generic/platform="
style nit, we like to use ()'s: 
`destination.slice! "generic/platform="` ->`destination.slice!("generic/platform=")`

2017-09-28 22:51 UTC, taquitos commented on gym/lib/gym/code_signing_mapping.rb
> +      return destination_sdkroot.include? sdkroot
(same here)

2017-09-28 22:53 UTC, taquitos approved these changes
I think this looks great. Thank you for adding that test! 🎈:goat:

2017-09-28 22:55 UTC, nicolasbraun commented
Goatta find a smiley signature :) Thanks for 👀

2017-09-28 23:06 UTC, merged