[spaceship] Add pagination support to Client#request
fastlane/fastlane pull request #10451
Opened 2017-09-28 15:52 UTC by Ruenzuo

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

We're using parts of the spaceship API to interact with TestFlight and we noticed that the method `get_builds_for_train` only returns the last 20 builds.

### Description

This PR adds an option to `Client#request` to auto-paginate results (inspired a bit by [Octokit](https://github.com/octokit/octokit.rb/blob/8404007e9e11d3695df0907adcb3514decd23287/lib/octokit/connection.rb#L87-L94)). This could be used in more methods besides `get_builds_for_train`, but it will add quite a lot of overhead. 

In the case of `get_builds_for_train`, it does make sense to return all builds available.

2017-09-28 17:27 UTC, KrauseFx requested changes
I think we should add paging, but it looks like there is HTML parsing involved?

2017-09-28 17:27 UTC, KrauseFx commented on spaceship/lib/spaceship/client.rb
> +        link_match = link.match(/<(.*)>/)
uhhhhh

2017-10-02 08:29 UTC, Ruenzuo commented on spaceship/lib/spaceship/client.rb
> +        link_match = link.match(/<(.*)>/)
ehhhhh

2017-10-02 08:33 UTC, Ruenzuo commented
This is how the "Link" response header looks like: 
<img width="1139" alt="screen shot 2017-10-02 at 10 26 13" src="https://user-images.githubusercontent.com/346590/31069416-ab9f0158-a75c-11e7-9e70-4396e14164e6.png">

Not sure if that qualifies as [parsing HTML with regex](https://stackoverflow.com/a/1732454). I looked for a better way to do this on the faraday API but I couldn't find anything, although [Octokit has a nice API](https://github.com/octokit/octokit.rb/blob/8404007e9e11d3695df0907adcb3514decd23287/lib/octokit/connection.rb#L88) for it. Will try to see how they're doing that and propose a better solution for this.

2017-10-02 11:33 UTC, Ruenzuo commented
I had a deeper look at how Octokit does this. Octokit uses [Sawyer](https://github.com/lostisland/sawyer) (based on Faraday) for hypermedia processing so I'm not sure if changing that in Spaceship is an alternative. Sawyer [uses regex to parse the response header](https://github.com/lostisland/sawyer/blob/master/lib/sawyer/response.rb#L43-L49).

Instead, I created a Faraday middleware that expands env a and adds a field to store the rels processing. Rels processing is now using the same method as Sawyer.

2017-10-02 16:53 UTC, KrauseFx approved these changes
Alright, this looks great, thanks for your work on this. Were you thinking about submitting a separate PR to make use of the new parameters/methods?

2017-10-04 08:00 UTC, Ruenzuo commented
I updated `Spaceship::TestFlight::Client#get_builds_for_train` to make use of the new parameter, because this is how I found out that fastlane was missing this feature.
By default, Apple API returns 20 items per request. This is probably configurable by a parameter in the query. For some methods like `get_builds_for_train`, it makes sense to retrieve all builds, but I don't think this should be the default behaviour in the rest of the API, as this potentially comes with a big overhead if we leave the default query on 20 items.
Not really sure what's the best way of doing this, and also I don't know if there are other people who have complaint about this already. My suggestion would be to make use of the new parameter when it makes sense, only to solve problems reported by users.

2017-10-04 08:18 UTC, merged

2017-10-04 08:18 UTC, KrauseFx commented
Alright, beautiful, thanks for your contribution ❤️

2017-10-04 08:18 UTC, KrauseFx commented
Also @Ruenzuo, can you drop me a quick email, would love to add you to the fastlane contributor slack :)