Add swift_version option to pod_push action
fastlane/fastlane pull request #10570
Opened 2017-10-11 20:56 UTC by marcuswu

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I was unable to push a pod spec which uses swift 4.0 using the pod_push action even with a .swift-version file. I was only able to push the pod spec once I passed --swift-version=4.0 to the pod command. This allows swift-version for the pod command to be specified.

Referencing issue: https://github.com/fastlane/fastlane/issues/10569

### Description
The changes simply add a swift_version parameter to the pod_push action. The value of the parameter is passed to the --swift-version parameter of the pod command.

2017-10-11 20:58 UTC, marcuswu commented
I signed it!

2017-10-11 21:35 UTC, taquitos requested changes
@marcuswu this is awesome, one request: could you add a test to `pod_push_spec.rb` for that new param?

2017-10-12 13:47 UTC, marcuswu commented
Absolutely, I just added that test in

2017-10-12 15:14 UTC, taquitos approved these changes

2017-10-12 15:14 UTC, taquitos commented
@marcuswu 🎈:goat:

2017-10-12 15:14 UTC, merged

2017-10-12 17:16 UTC, marcuswu commented
Boo, I forgot to change user.email. I've fixed the commit in my branch, but if it's already merged here I am not sure what's needed to fix it.

2017-10-12 17:18 UTC, taquitos commented
It's ok, you've confirmed it's you, thanks 😄