Refactored code signing to make sure keychain flag is passed to each …
fastlane/fastlane pull request #10600
Opened 2017-10-15 03:50 UTC by maschall

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
While making some other edits, I noticed that not all the /usr/bin/codesign usages had ${KEYCHAIN_FLAGS}.

### Description
Not really sure if this is too much refactor, but created a method to be called when codesigning both App bundles and framework bundles.  If you pass in an entitlement file, it will codesign with that entitlements.

2017-10-15 04:06 UTC, maschall commented
I signed it!

2017-10-17 12:53 UTC, jetersen approved these changes

2018-02-19 14:57 UTC, janpio commented on sigh/lib/assets/resign.sh
> +  # Must not qote KEYCHAIN_FLAG or $ENTITLEMENTS because it needs to be unwrapped and passed to codesign with spaces
typo `qote`

2018-02-19 14:59 UTC, janpio commented on sigh/lib/assets/resign.sh
>          log "and patched entitlements:"
these two lines shouldn't be here any more, correct?

2018-02-19 15:01 UTC, janpio requested changes
See comments.

2018-11-29 19:55 UTC, lyndsey-ferguson requested changes
requested a change

2018-11-29 19:55 UTC, lyndsey-ferguson commented on sigh/lib/assets/resign.sh
> +    cp -f "$LOCAL_ENTITLEMENTS" "$BUNDLE_PATH/archived-expanded-entitlements.xcent"
We don't need to copy `xcent` files into the bundle anymore. They're ignored because code sign embeds them into the app binary.

2019-02-19 13:36 UTC, joshdholtz commented
Heyyy 👋 Thanks for the time spent on making this PR! This PR seems to have gone stale and `resigh.sh` has changed a lot since then. Feel free to let me know if you want to reopen this or create a new PR for this and we can have another look!

2019-02-19 13:36 UTC, closed without merging