Import from git versioning
fastlane/fastlane pull request #10612
Opened 2017-10-17 08:20 UTC by bramseynhaeve

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

We're using the import_from_git method to use a shared Fastfile in our company. 1 Fastlane file to manage all our different projects. All changes to this file were always backwards compatible, but we wanted to create a new and better one that isn't backwards compatible anymore. To prevent all our builds from failing, we should be able to select a version range when importing the shared Fastfile.

This fixes https://github.com/fastlane/fastlane/issues/10189

We tested this by adding the version parameter in one of our projects, and using a local version of Fastlane by modifying the Gemfile of our iOS project.
```
import_from_git(url: 'git@bitbucket.org:------------/----------.git', version: '~> 2.0')
```

### Description
To solve this, we updated the already implemented `import_from_git` function. We added a new parameter `version` next to `branch`. Both do almost the same, except that version will use all git tags to find a matching version. When a version is found, it will checkout just like you would have used a branch.

Optimistic parameters are added to support auto updates with backwards compatible code.

2017-10-17 08:22 UTC, bramseynhaeve commented
I signed it!

2017-10-24 19:50 UTC, ohayon requested changes
Hey @bramseynhaeve - this is a really cool use case, idea, and PR! I just have one comment in the review, let me know your thoughts!

2017-10-24 19:50 UTC, ohayon commented on fastlane/lib/fastlane/fast_file.rb
> +          end
Any chance we could pull this into it's own method? Might be nice to just not have so much nested code right here in line.

2017-10-25 06:52 UTC, bramseynhaeve commented
Thanks @ohayon for the nice words and feedback! 
Sure, I moved the logic to separate functions to solve your PR remark.

2017-10-25 15:33 UTC, ohayon commented
Thanks @bramseynhaeve ! That looks great 🌟 ! I'm not sure those failing tests are related to your code, would you mind just taking a look at those to make sure that thats the case?

2017-10-25 18:03 UTC, bramseynhaeve commented
Thanks. I'm not having these failed test local and they showed up after I merged master into my PR. But I'll take a look.

2017-10-25 18:09 UTC, ohayon commented
Thanks @bramseynhaeve! Also, we are wondering if we could tweet about this change. We think this change is really awesome!

2017-10-25 18:34 UTC, bramseynhaeve commented
@ohayon A tweet would be nice, go ahead! A mention would be awesome. ;-)

2017-10-26 03:19 UTC, friederbluemle commented
Thanks @bramseynhaeve This looks very useful! 👍

2017-10-26 18:19 UTC, ohayon approved these changes

2017-10-26 18:19 UTC, ohayon commented
Thanks again for this @bramseynhaeve ! We are going to tweet about it at some point soon 🐦 ! This is an awesome first-time contribution! We hope to see more from you!

2017-10-26 20:02 UTC, merged

2017-11-01 13:41 UTC, bramseynhaeve commented
🙌🏻

2017-12-05 09:42 UTC, lacostej commented
@bramseynhaeve super feature! We were discussing the need to add this when I found out you already implemented it. Thanks a lot! 🍻