[fastlane] Add option to generate random password for setup_travis add setup_circle_ci
fastlane/fastlane pull request #10639
Opened 2017-10-19 00:21 UTC by matthewellis

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Cloud CI systems should never leak keychain data but it is possible that they could be attacked and keychains without passwords could leak distribution keys. This is a silm chance but genrating one time passwords for each build using these actions would mitigate this risk. 

### Description

The current default of a empty string has been respected but an option to enable a random password to be created has been added to both setup_travis and setup_circle_ci.

2017-10-27 14:50 UTC, milch requested changes

2017-10-27 14:50 UTC, milch commented on fastlane/lib/fastlane/actions/setup_circle_ci.rb
> +        ENV["MATCH_KEYCHAIN_PASSWORD"] = password
The password is set here but not actually used later ([line 49](https://github.com/fastlane/fastlane/blob/2b2e008502deac13210f06b33afe111beb02eb04/fastlane/lib/fastlane/actions/setup_circle_ci.rb#L49))

2017-10-27 14:50 UTC, milch commented on fastlane/lib/fastlane/actions/setup_circle_ci.rb
> +      def self.setup_keychain(params)
I'd suggest passing in either the password or the random password flag as parameter instead of the params hash for increased readability

2017-11-08 11:46 UTC, matthewellis commented
@milch Hey i have updated the PR following your feedback 👍

2017-11-08 12:13 UTC, milch approved these changes
Looks good now 👍🏼

2017-11-08 16:42 UTC, matthewellis commented
Closing due to this not providing much if any additional security

2017-11-08 16:42 UTC, closed without merging