Update Carthage action for new-resolver option
fastlane/fastlane pull request #11191
Opened 2017-12-12 19:10 UTC by gbrhaz

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Carthage has been updated to include a new resolver; add functionality for it in fastlane

### Description
Added the '--new-resolver' option for Carthage action

Rubocop is complaining because this action now has more than 18 options. Is this a breaker for an action? What's the resolution?

2017-12-13 08:50 UTC, gbrhaz commented
I signed it!

2017-12-15 12:55 UTC, gbrhaz commented
Perhaps I should increase the metric to 19 from 18?

2017-12-15 17:35 UTC, taquitos requested changes
Great addition, just 2 requests:
The `type: Boolean,` update
Also, it would be great if you could add a spec to test this change

2017-12-15 22:18 UTC, KrauseFx commented
Thanks, let us know when you had a chance to push an update for the PR 👍

2018-01-04 10:43 UTC, gbrhaz commented
@KrauseFx @taquitos Apologies for the delay, Christmas break got in the way. Changes have been made.

2018-01-04 11:39 UTC, KrauseFx commented
Awesome, thanks @gbrhaz, let's wait for @taquitos to confirm and merge the change 👍

2018-01-04 16:29 UTC, taquitos commented on fastlane/lib/fastlane/actions/carthage.rb
>              toolchain: "com.apple.dt.toolchain.Swift_2_3"   # Specify the xcodebuild toolchain
missing a `,` after `.Swift_2_3"`

2018-01-04 16:30 UTC, taquitos reviewed
One tiny missing comma and then 🎈🐐

2018-01-04 16:51 UTC, gbrhaz commented on fastlane/lib/fastlane/actions/carthage.rb
>              toolchain: "com.apple.dt.toolchain.Swift_2_3"   # Specify the xcodebuild toolchain
Done

2018-01-04 16:52 UTC, taquitos approved these changes

2018-01-04 17:06 UTC, merged