Use provisioning profile name instead of UUID for .mobileprovision
fastlane/fastlane pull request #11339
Opened 2017-12-24 21:12 UTC by Panajev

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

By default fastlane match generates the profiles with a descriptive name with Profile type (App Store, Enterprise, Development), and bundle id. 
Whenever profiles are recreated, which can happen for a multitude of reasons, such as adding new devices to the portal, a new entry appears inside the user's ~/"Library/MobileDevices/Provisioning Profiles" folder as each profile will have a different filename currently based on the profile UUID. With enough applications and enough variations of the profiles (One team for InHouse Distribution can have its enterprise, adhoc, and development profiles) which may easily lead to a folder growing a fair bit each time.

For the same reasons we use full manual signing with match or with our own match like setups, being able to have a single copy of a certain provisioning profile and not having to rely on Xcode or other tools to use the latest profiles created with all the devices you have just added, for example, it would be nice to have clear names for the profiles we install on our computer and replace the older one with the contents of the new one we have recreated. 

I am not sure if this Xcode behaviour was always there or if it occurred when the support for Provisioning Profile names instead of their UUID in your Xcode project signing settings landed (Xcode 8.x), but I have noticed that simply copying the files I downloaded from the Developer Portal in my ~/"Library/MobileDevices/Provisioning Profiles" folder ended up working just fine from Xcode's point of view. I also do realise that fastlane is a tool used by people that not only may have an appreciation for automation and DevOps-y stuff in general, but that have scaling needs (tons of apps, several Apple Developer Teams, mixing company and personal work, etc...).

This pull requests aims to have match copy the filename it has created as is, but adding a factor of uniqueness that should satisfy the needs we have. This would make the apparent structure of the final destination filename to be the following: 

> **<Apple_Developer_Team_ID>\_**<InHouse/Development/AppStore>\_<App Bundle ID>.mobileprovision

Part in bold is what this PR adds, the rest is the name match was already using.

The filename is calculated with the Team ID and the original name Fastlane created for the profile, helping the profile be unique (containing the risk of collisions), but not in such a way that we are providing protection from collision from itself, i.e. we allow by design the new profile name to be equal to the old profile name for the same Team ID, the same profile type, and the same bundle ID as before and we delete the older file if present before copying the new one.

### Testing

Ran the unit tests, followed the instructions in https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md#test-the-changes-for-your-application and used the local fastlane modified version  to sync all the provisioning profiles from the App Store, Enterprise, and Development provisioning profiles types 
```bash
#!/bin/bash

BUNDLE_IDS=("com.company.corp.app1" "com.company.corp.app2" "com.company.corp.app3" "com.company.corp.app4" "com.company.corp.app5" "com.company.corp.app6" "com.company.corp.app7" "com.company.corp.app8" "com.company.corp.app9" "com.company.corp.app10" "com.company.corp.app11" "com.company.corp.app12" "com.company.corp.app13" "com.company.corp.app14" "com.company.corp.app15")

for bundle_id in "${BUNDLE_IDS[@]}"; do
	echo "Building venture with bundle id $bundle_id"
	fastlane match development --readonly -a $bundle_id --team_name "Company" --skip_docs
done

[...]
```

```ruby
bundle exec rspec Match
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Changing stdout to /tmp/fastlane_tests, set `DEBUG` environment variable to print to stdout (e.g. when using `pry`)

Match::CommandsGenerator
  :appstore option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options
  :adhoc option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options
  :development option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options
  :enterprise option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options
  :change_password option handling
    can use the git_url short flag from tool options
    can use the shallow_clone flag from tool options
  :decrypt option handling
    can use the git_url short flag from tool options
    can use the shallow_clone flag from tool options
  nuke development option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options
  nuke distribution option handling
    can use the git_url short flag from tool options
    can use the git_branch flag from tool options

Match
  Match::Encrypt
    encrypt
    raises an exception if invalid password is passed
    raises an exception if no password is supplied

Match::Generator
  calling through to other tools
    configures cert correctly for nested execution
    configures sigh correctly for nested execution

Match
  Match::GitHelper
    generate_commit_message
      works
    #clone
      skips README file generation if so requested
      clones the repo
      clones the repo (not shallow)
      checks out a branch

Match
  Match::Runner
    creates a new profile and certificate if it doesn't exist yet
    uses existing certificates and profiles if they exist

Match
  Match::Setup
    works

Match
  Match::Utils
    import
      finds a normal keychain name relative to ~/Library/Keychains
      treats a keychain name it cannot find in ~/Library/Keychains as the full keychain path
      shows a user error if the keychain path cannot be resolved
      tries to find the macOS Sierra keychain too
    fill_environment
      #environment_variable_name uses the correct env variable
      #environment_variable_name_team_id uses the correct env variable
      #environment_variable_name_profile_name uses the correct env variable
      #environment_variable_name_profile_path uses the correct env variable
      pre-fills the environment

Finished in 1.34 seconds (files took 1.52 seconds to load)
38 examples, 0 failures
```

Robocop detected no issues:
```bash
bundle exec rubocop -a
Inspecting 989 files
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

989 files inspected, no offenses detected
```

When running all tests on my machine I have 4 failures in portions of the code I have n [...]

2017-12-25 13:54 UTC, KrauseFx commented
Is this gonna be fully backwards compatible for all users already using fastlane match?

2017-12-25 15:20 UTC, Panajev commented
I would imagine that for users that have match already, like it happened with the test profiles the unit tests install, nothing would change although they would have the same exact provisioning profile twice with the same effective UUID (unless they are recreating the profiles in which case they would have the profiles with the new name in addition to the old ones... you could take the new name as another different identifier like the UUID was).

Would you think that adding a check where if the same provisioning profile already existed with the old <UUID>.mobileprovision name (instead of <team id>_<buildType>_<bundle id>.mobileprovision one) we delete it? 

We can compute how the old name would have looked and delete the file before copying the new one... that would not be destructive and would avoid Xcode from having two copies of the same file with same contents but just a different file name and creation date. 

Do you have other backwards compatibility checks in mind?

2017-12-25 19:52 UTC, Panajev commented
Hey @KrauseFx, I have added a change to address backwards compatibility concerns, let me know if I am still away from the mark, as I was writing in my last comment and rebased on top of master. Thank you for the feedback :).

2017-12-27 09:14 UTC, KrauseFx requested changes
Hey @Panajev, thanks for your pull request, really appreciate. I don't fully understand the benefit of this yet. Please note that this change is a major change on how _match_ works and it involves quite some risk breaking existing and new setups. Those kind of changes we usually try to avoid to make sure things are super solid.

I don't fully understand why having more provisioning profiles in the local profiles folder is an issue. Does Xcode select the wrong profile? If so, you can specify the one to use using _fastlane_. Or does it slow down the build process?

2017-12-27 13:31 UTC, Panajev commented
Hey @KrauseFX, no worries... I did not think you just walk a patch into fastlane... or was it walking into Mordor you could not just easily do? Never mind that ;).

#Backwards compatibility musings
Would it help if this behaviour were hidden behind an environment variable, behaviour added to the docs, and letting this be battle tested (after some more review comments here of course if more eyes want to offer comments and suggest other potential issues I can address)? The change set is small enough that I could reasonably keep rebasing it on top of master, but I would rather be able to learn enough and improve this PR to land it into fastlane :D. I would like to help mitigate risks beyond shielding them behind an env variable (which would provide the old behaviour of the variable is not set)... might need some help with the unit tests and testing of this environment variable, but it is fine :).

#Additional Risk Mitigation
Could you and/or other core maintainers please expand on the risks so I can have a bit of a think and try my best to address them (maybe over time if the environment variable approach is acceptable) mitigating risks as much as possible?
 I am not sure how my PR could break existing setups the way it is and I do not think there is a likely chance of files collisions, but my lack of experience with fastlane core as well as the wildly different setups people may have would make my assessment not as solid as I think it is.

##Rational wise
We had had issues in the past where multiple versions of the same profile (or certificate in other cases) differing only by content (devices, entitlements, or other) could confuse Xcode and while I have not measured exact speed impact due to the number of profiles installed Xcode needs to do needless work to find the profiles that match the certificate and bundle id and then select the ones that matches best. I would like to have a solution that works with Xcode but does not need to track the uuid of the profile (I do not want to go back to those “dark ages” pre Xcode 8.x :)).

The spirit of fastlane, which  embraced IMHO by making it easier and better to do fully automated signing, is to automate users’ workflows with less and less dependencies on Xcode magic (hence match instead of relying on Xcode fully automated signing) and thus provide a more resilient solution: if we can avoid duplicating provisioning profile files and giving less work to Xcode there is less potential issues that can be dependent on third party code and not our fastlane/match/project setup.

2017-12-27 13:32 UTC, KrauseFx commented
Yeah, totally, if we find a good way to clean old provisioning profiles from the local machine, I'm all for it. It might be a little tricky, as we don't want to delete profiles that are still being used.

2017-12-28 18:53 UTC, Panajev commented
Hey @KrauseFx , so... I agree in the same sprit as this PR, cleaning up the old profiles if you decide to use the new option (uuid less) makes complete sense :). Just be patient with my questions as I still find some things here daunting hehe :).

One approach that should be safe, but maybe a bit slow, would be to read the **profile name** and **Team ID** (would profile name be enough) from the current provisioning profile that match is trying to install, then loop through the .mobileprovision files inside the MobileDevices/Provisioning Profiles folder and delete each of the profiles which have the same **profile name** and **Team ID** before installing the new profile.

> we don't want to delete profiles that are still being used
Fully agreed, but that would have to be a profile we already sync over match, a profile we are not installing a synced profile stored in the private match repo else why would it be a problem if we deleted it and replaced it with the profile we are installing at this time? 

I guess that the worry would be that some projects are using match and yet they are still specifying the provisioning profile by UUID inside Xcode or their .xcconfig files instead of using the profile display name. Is this an officially supported fastlane setup considering that 
1. Xcode supports the use of display name avoiding a lot of changes everytime profiles are recreated
2. If you were using the new uuid-less naming option for the provisioning profiles should be explicitly for people that are indeed using the profile display name in their projects.
3. In the "solution" I mentioned above we would not delete provisioning profiles you have not already migrated to fastlane match.

What do you think? I have a lingering fear of oversiplifying this, so please any feedback is welcomed! Thanks.

2017-12-29 13:01 UTC, KrauseFx commented
My feeling is is that it's not something that's worth the extra work. From my understanding, this still work nicely without this patch. Adding this logic adds quite some complexity and will probably end up causing other issues, that we don't think of yet.

2018-01-06 17:01 UTC, Panajev commented
Hey @KrauseFx , I have added the -m option to preserve backward compatibility with older setups. If you want to opt in the new behaviour introduced by this PR you would either use the -m flag or setup the corresponging environment variable (FASTLANE_MOBILE_PROVISION_FILES_NAMES_MODE).

I agree that the extra login to loop through all profiles by profile name and Team ID to remove older ones, but not if they have not been re-created with the new naming convention, would be a bit overkill compared to the benefits it brings.

2018-01-08 23:17 UTC, Panajev commented
Oh hello @fastlane-bot  :).

2018-01-09 08:48 UTC, Panajev commented
@KrauseFx rerunning the build again... sometimes I see odd issues on the Ubuntu agent... tested the build locally with ruby 2.5.0 on macOS High Sierra and the macOS agent (which uses ruby 2.3.3) also works... bit puzzled... hopefully it passes on both now...

2018-01-09 13:27 UTC, KrauseFx commented
Hey @Panajev, sorry to be the bad guy here, but I'd prefer not to go ahead with this change so far... thanks for your contributions and your ideas.

If you really really want this change, you can run and maintain your own fork, but I would recommend against it, as it will be hard to keep up. 

Again sorry we're not going ahead with this one 😢

2018-01-09 14:19 UTC, Panajev commented
@KrauseFx I understand :), no hard feelings. 

In the end for controlled environments one could go the way of deleting all the existing profiles, syncing with fastlane as normal, etc... I knew it would not be an easy thing to add and I have gotten some understanding of why this could bring problems (would like some more feedback if it is possible in terms of problems that could happen to people opting in this approach and just always using it consistently as it would give me a better understanding on the impact of my changes.... safe to learn as they say :)). 

Thanks anyways, will close the PR, but keep running the macOS test on my branch for as long as I can reasonably keep it up to date without including additional risks :).

2018-01-09 14:19 UTC, closed without merging