Swift lane parameters
fastlane/fastlane pull request #11401
Opened 2018-01-03 12:28 UTC by potemkinaleksey

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Fixes issue https://github.com/fastlane/fastlane/issues/11370

2018-01-03 12:35 UTC, potemkinaleksey commented
I signed it!

2018-01-03 12:43 UTC, KrauseFx commented
Awesome, thanks for your contribution @potemkinaleksey, and welcome to the fastlane community 🚀  Let's wait for @taquitos and see what he thinks 👍

2018-01-03 16:30 UTC, taquitos commented on fastlane/swift/ArgumentProcessor.swift
> +            return arg.name.lowercased() == "timeoutseconds"
🤦‍♂️

2018-01-03 16:32 UTC, taquitos commented on fastlane/swift/ArgumentProcessor.swift
> +    let laneParameters: [String: String]
> `[String: String]`

We prefer: `[String : String]`
I think we should probably add Swift linting so this is automatic too

2018-01-03 16:36 UTC, taquitos commented on fastlane/swift/ArgumentProcessor.swift
> +        var laneParameters = [String: String]()
Let's extract this out to a new function. There is enough going on that having a new function would make it clearer.

2018-01-03 16:38 UTC, taquitos commented on fastlane/swift/ArgumentProcessor.swift
> +            if lowercasedName != "timeoutseconds" && lowercasedName != "lane" && lowercasedName != "logmode" {
I think the intent of this could be made more clear by using `.filter()` instead of a for loop

2018-01-03 16:38 UTC, taquitos commented on fastlane/swift/LaneFileProtocol.swift
> +    static func runLane(named: String, parameters: [String: String])
`[String : String]`

2018-01-03 16:38 UTC, taquitos commented on fastlane/swift/LaneFileProtocol.swift
> +    public static func runLane(named: String, parameters: [String: String]) {
`[String : String]`

2018-01-03 16:40 UTC, taquitos requested changes
This is great, thank you! Just a couple changes and then it's ready for 🚀

2018-01-04 10:05 UTC, potemkinaleksey commented
@taquitos thanks for review! I made requested changes, hope it looks better now

2018-01-04 16:38 UTC, taquitos approved these changes
🎈🐐

2018-01-04 16:38 UTC, merged

2018-01-04 16:38 UTC, taquitos commented
Woo hoo, thank you!