Snapshot record video
fastlane/fastlane pull request #11744
Opened 2018-01-31 09:28 UTC by Jules2010

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

### Description

2018-01-31 12:23 UTC, Jules2010 commented
@laullon please will you sign the CLA again here please. I'm going to try and get this pushed through without the tcp listener.

2018-01-31 15:36 UTC, laullon commented
sure, I’ll sign it later.
What’s your plan?

2018-01-31 15:45 UTC, Jules2010 commented
Cheers.

I’ve not done any ruby yet.

Initially just get something working, I have 6 languages and 8 devices to produce videos for, I need something to automate this task.

However I may need to add some extra features, not sure what au be needed yet.

2018-01-31 15:51 UTC, Jules2010 commented
I timed my existing snapshot lane last night and found I'm going to need to remove some the functionality to make it fit within 30 seconds.

I'm hoping to do all this in-app, without having to pause the video.

I've already got a start and finish slide, with fading, that going to be around 7 seconds.

I figure I can dismiss view controllers without animation, then push without animation, to speed up the transition between several screens.

At least that's my plan.

Otherwise I may need to add some kind of pause then fade to fastlane.

2018-01-31 20:50 UTC, Jules2010 commented
I'm struggling, can't figure out how to call the start / stop methods :( https://github.com/fastlane/fastlane/pull/11744/commits/c6458f0ca66b79c76738d1ed4fee38247fbc4e86

2018-02-01 10:21 UTC, laullon commented
call the start / stop methods from where? UITest?

2018-02-01 10:22 UTC, laullon commented
I signed it!

2018-02-01 10:24 UTC, Jules2010 commented
Thanks.

Yes from the UITest any help appreciated.

2018-02-01 11:24 UTC, laullon commented
sure... That was the purpose of the "tcp listener"/"web server" ;)

2018-02-01 11:50 UTC, Jules2010 commented
Yeah. I’m just keen to get it merged, then hopefully it will get more features and discussion.

Any ideas how I need to add the start / stop in to the swift files, I couldn’t see it on snapshot or simulator. 

Maybe it needs exposing somehow? 

I’m a bit out of my depth with ruby.

2018-02-01 12:57 UTC, Jules2010 commented
I signed it!

2018-02-01 16:07 UTC, KrauseFx requested changes
Hey, cool to see some movement in this again. Please make sure to avoid adding a web server to this, as it adds a lot of complexity to the code base. I'm using `Request Change` to make sure this doesn't get merged until it's ready, it's still WIP, right?

2018-02-01 17:04 UTC, Jules2010 commented
@KrauseFx I’ve taken the web server stuff out. 

However I’m not familiar with ruby and am struggling to add calls to the start and stop functions to the swift can you help with this small change please?

2018-02-01 23:44 UTC, laullon commented
@KrauseFx any recommendation on how to communicated the UITest with the Fastlane process to start/stop the recording ?

I did used the web server because it was very easy of implement, I also tested to use a flag file, but that was not ok because I did used a 3rd party library to watch for file system changes.

2018-02-11 18:13 UTC, getaaron commented
There are a few other options:

- Swift can write to `STDOUT` using `print()`. Ruby can read from this process, potentially using `pty` or `IO`. Some [helpful-looking Stack Overflow discussion here](https://stackoverflow.com/q/1154846/1445366).
- The Swift code can write to a file and we can use something like [filewatcher](https://github.com/thomasfl/filewatcher) to watch for changes within fastlane.
- Since we know we're running on macOS, there are many other [macOS-specific interprocess communication methods](https://developer.apple.com/library/content/referencelibrary/GettingStarted/GS_InterapplicationCommunication/_index.html) available (XPC, copy and paste, notification center, etc.)

I think the `STDOUT` approach (using `print()` and `IO`) is least likely to require additional dependencies, but it may not be the most elegant.

@KrauseFx any thoughts here?

2018-02-16 19:34 UTC, janpio commented on snapshot/lib/assets/SnapfileTemplate
> +# Where should the resulting videos be stored?
this comment should take into account that by default no video will be create. So probably somethign like

2018-02-16 19:35 UTC, janpio commented on snapshot/lib/assets/SnapfileTemplate
> +# Choose which project/workspace to use
unrelated new feature or just new in SnapfileTemplate?

2018-02-16 19:39 UTC, janpio commented on snapshot/lib/snapshot.rb
> +module Snapshot
a `Snapshot` module should be placed in `snapshot/module.rb` relative from here,

2018-02-16 19:41 UTC, janpio commented on snapshot/lib/snapshot.rb
> +module Snapshot
When you rebase onto current `master`, this module will alredy exist in `snapshot/module` relative from here.

2018-02-16 19:43 UTC, janpio commented on snapshot/lib/snapshot.rb
> +module Snapshot
If not, and this is just a useless copy, one would have to make sure if there are no important changes here.

2018-02-16 19:44 UTC, janpio commented on snapshot/lib/snapshot.rb
> +module Snapshot
Quick comparison shows that they are indeed identical. This is probably just an artifact (that has to be fixed before a merge).

2018-02-16 19:44 UTC, janpio commented on snapshot/lib/snapshot/options.rb
> +      video_output_directory = (File.directory?("fastlane") ? "fastlane/videos" : "videos")
does this folder already exist by default?

2018-02-16 19:44 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +    def start_recording(dir_name, device, name)
maybe add `video` to the method name to make it clearer what this is?

2018-02-16 19:45 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +      return unless pid.nil?
what exactly does this do and why?

2018-02-16 19:46 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +      device_udid = TestCommandGenerator.device_udid(device)
extract into well named method as it is repeated below

2018-02-16 19:46 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +      return if pid.nil?
what exactly does this do and why?

2018-02-16 19:47 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +    def stop_recording(device)
also add `video` to method name maybe?

2018-02-16 19:48 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb
> +          @recording_pid = {}
should this also be in the `_xcode_8` version of this file?

2018-02-16 19:48 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb
> +    def start_recording(dir_name, device_type, name)
if this is identical to above, can this be moved outside of these files somehow and unified?

2018-02-16 19:49 UTC, janpio commented on snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb
> +                                                stop_recording
should this be in the other, non `_xcode_8` version of this file?

2018-02-17 13:13 UTC, Jules2010 commented
Hi @janpio 

I'd just like to mention that this pull request as it stands doesn't provide any additional functionality as it stands. It's based on PR https://github.com/fastlane/fastlane/pull/10121 I'm not 100% sure about your questions.

However this pull request has the http listener code removed and therefore doesn't have any means of triggering the video recording.

I started this PR at that point, in the hope that someone would step in and advise and contribute to it's completion. I understand that @laullon has moved on from his PR with other projects and doesn't have time to contribute further.

For information purposes, I have created a new branch https://github.com/Jules2010/fastlane/tree/snapshot-record-video-with-audio which includes @laullon  initial work and QuickTime Player to also record sound.

I hope this can move forward.

Jules.

2018-02-17 18:22 UTC, janpio commented
Yes, I got that, saw the other PR as well. 

I tried to understand what is already here and see if this is in an optimal state to solve the remaining problem - because I really like the possible functionality here! Using snapshot to record videos of the app would really be an awesome feature.

Maybe @laullon can also take a look at my comments?

2018-03-27 19:30 UTC, getaaron commented
@Jules2010 How is this work coming along? Were you able to get it working for your project locally without the HTTP server?

2018-03-27 20:03 UTC, Jules2010 commented
@getaaron unfortunately not, I didn’t write the code originally. But I was able to add sound via QuickTime and use ffmpeg to join the audio and video together.

However my code isn’t pretty and has hardcoded paths.

I did mention to @laullon on twitter but he obviously didn’t find the time to help further.

2018-04-30 11:30 UTC, Lausbert commented
If someone is looking for inspiration for a pull request without a http server: [https://github.com/Lausbert/Snaptake](https://github.com/Lausbert/Snaptake) :)

2018-04-30 11:49 UTC, Jules2010 commented
@Lausbert does this add sound to the videos too? My hack uses QuickTime and merged them together.

2018-04-30 11:55 UTC, getaaron commented
@lausbert I really like this approach; what do you think about setting this up as a fastlane plugin? We could add a comment about it in the Snapfile and link to it in the docs.

2018-05-01 12:17 UTC, Lausbert commented
@Jules2010 I haven't tested it so far, since all I needed to do in my specific case was to add a jingle later on with ffmpeg.

@getaaron Sounds great, but what about the changes in snapshotHelper.swift? Did I miss anything or is it impossible to integrate them by adding a plugin?

2018-05-01 12:24 UTC, Jules2010 commented
@Lausbert the simulator currently doesn’t provide sound. I filed a radar and was told it was a feature request.

2019-03-07 16:25 UTC, janpio commented
Closing this PR as I don't expect a solution to suddenly pop up.

But I created a new issue https://github.com/fastlane/fastlane/issues/14362 which links to this PR and also @Lausbert 's working solution - maybe we can restart a discussion there and find a solution that can be elegantly added to Snapshot.

Thanks all that were involved here!

2019-03-07 16:25 UTC, closed without merging