[Fastlane.swift] Fix wrong data type when convert Hash-type options to Swift
fastlane/fastlane pull request #11749
Opened 2018-01-31 13:33 UTC by thii

Options with `Hash` type were converted to `String` type in Swift.

2018-01-31 16:07 UTC, taquitos commented on fastlane/lib/fastlane/swift_fastlane_function.rb
> +      elsif default_value.kind_of?(Hash)
Great catch

2018-01-31 16:09 UTC, taquitos requested changes
This is great, thank you. 
If you can remove the changes to the `fastlane/swift/Fastlane.swift` file, we can get this merged.
Most of those `.swift` files are automatically generated during deployment time 🎉

2018-02-01 16:32 UTC, taquitos approved these changes

2018-02-01 16:32 UTC, merged

2018-02-01 16:32 UTC, taquitos commented
🎈:goat:

2018-02-02 15:20 UTC, antonino-u commented
@taquitos curious: this has apparently made it into 2.80.0 but the autogenerated files haven't been updated. There are also other fixes which I'm sure have been made that aren't in Fastlane.swift. Is there a way for me to force the project to regenerate them? Does someone have to do something to increment FastlaneRunnerAPIVersion?

2018-02-02 16:35 UTC, taquitos commented
You're right, it should have made it into this: https://github.com/fastlane/fastlane/pull/11760/files

If you check out the fastlane repo, you can run `fastlane generate_swift_api` and that will generate the files. It works for me, so I wonder if our deploy script doesn't work right.

2018-02-02 17:12 UTC, taquitos commented
Ahh, figured it out, we merged this PR after we version bumped. The version bump does the fastlane swift generation.