[frameit] Skip warning message for already framed screenshots
fastlane/fastlane pull request #11765
Opened 2018-02-02 04:49 UTC by KrauseFx

2018-02-16 19:29 UTC, janpio commented
```
[16:49:57]: ▸ Offenses:
[16:49:57]: ▸ frameit/lib/frameit/runner.rb:49:15: C: Metrics/BlockNesting: Avoid more than 3 levels of block nesting.
[16:49:57]: ▸ UI.error("Backtrace:\n\t#{ex.backtrace.join("\n\t")}") if FastlaneCore::Globals.verbose?
[16:49:57]: ▸ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[16:49:57]: ▸ 1024 files inspected, 1 offense detected
```

2018-05-20 15:07 UTC, revolter commented on frameit/lib/frameit/runner.rb
> +            if full_path.ends_with?("_framed.png") && !FastlaneCore::Globals.verbose?
Shouldn't this be `full_path.ends_with?("_framed.png")  !FastlaneCore::Globals.verbose?`

2018-05-20 15:08 UTC, revolter commented on frameit/lib/frameit/runner.rb
> +            if full_path.ends_with?("_framed.png") && !FastlaneCore::Globals.verbose?
Shouldn't this be `full_path.ends_with?("_framed.png") || !FastlaneCore::Globals.verbose?` instead?

2018-05-28 22:11 UTC, joshdholtz commented
@KrauseFx Do you still want this merged? If so, I can fix the lint errors 😉

2018-08-22 22:34 UTC, KrauseFx commented
@joshdholtz Yes I think this should still be merged, can you take this one over?

2019-01-16 14:00 UTC, janpio requested changes
I think this PR misses the problem it wants to solve - it should not be merged.

2019-01-16 14:00 UTC, janpio commented on frameit/lib/frameit/runner.rb
> +            #   [23:47:09]: Unsupported screen size [1295, 2590] for path './IMG_2343_framed_black.png'
Isn't this an error message from `deliver`?
https://github.com/fastlane/fastlane/blob/c79cb094721dd2e0f49f4eb11aca36adf3f73666/deliver/lib/deliver/app_screenshot.rb#L304

We are already skipping files ending with `_framed.png` in line 29 of this file, so they don't get framed _again_. 

Is there an issue for this actual problem? My guess is that someone tried to upload a framed, but un-backgrounded screenshot (`frameit` was used to add a frame, but not a background/title/keyword) which doesn't resize the screenshot to App Store compatible sizes.

2019-01-16 15:39 UTC, KrauseFx commented
Yep, good point, thanks @janpio 👍

2019-01-16 15:39 UTC, closed without merging