[WIP] remove emoji from changelog
fastlane/fastlane pull request #12191
Opened 2018-03-28 15:43 UTC by koenpunt

apple doesn't allow emoji to be used in the changelog value

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

When trying to submit a changelog containing emoji, the request fails with a response similar to:

```
ERROR-1: What to Test can't contain the following characters: ?.; ERROR-1: What to Test can't contain the following characters: ?.; ERROR-1: What to Test can't contain the following characters: ?.
```

### Description

WIP because the regex has to be updated to apply to a broader range of emoji, or maybe there's a gem that can do the heavy lifting for us.

2018-04-01 00:39 UTC, getaaron requested changes
I don't think we should arbitrarily change the changelog content. How about something like:

```ruby
UI.user_error!("Disappointingly, emojis aren't allowed in the changelog 🙄") if options[:changelog].match(/[\u{1F600}-\u{1F6FF}]/)
```

2018-04-02 11:46 UTC, joshdholtz commented
@koenpunt I agree with @getaaron on this one - we tend to stay away from automatically changing things on the use. **BUT**, since you said that this was from a changeling generated from git commands, it maybe be best to add a cleanse/sanitize emojis option in the `changelog_from_git_commits` action?

2018-04-02 13:14 UTC, koenpunt commented
Since emoji cause the problem for Apple, the flag should be with the `set_changelog` and `upload_to_testflight` actions IMO.
But since we're already truncating the changelog based on size, I don't really see a problem with just replacing the emoji, especially since it otherwise doesn't work. 
We could of course still warn the user about the fact that those symbols have been removed, which is what is what also happens when the changelog is truncated.

2018-04-02 14:35 UTC, joshdholtz commented
@koenpunt That is a fair point ^ I think if you can check if there is an emoji and then warn that user (with your current implementation) that be 👌

2018-04-02 20:01 UTC, koenpunt commented
Alright, I've updated the implementation

2018-04-03 00:13 UTC, getaaron approved these changes

2018-04-03 00:20 UTC, getaaron commented
We might want to add a unit test to [build_manager_spec.rb](https://github.com/fastlane/fastlane/blob/6649d0daa6d8c51105c33d380aa526b657f12d6f/pilot/spec/build_manager_spec.rb)?

e.g.

```
  it "removes emoji" do
    changelog = "I'm 🦇B🏧an!"
    changelog = Pilot::BuildManager.truncate_changelog(changelog)
    expect(changelog).to eq("I'm Ban!")
  end

  it "truncates spaces after removing emoji at the end" do
    changelog = "Why doesn't Apple support Emoji? 🤷‍♀️"
    changelog = Pilot::BuildManager.truncate_changelog(changelog)
    expect(changelog).to eq("Why doesn't Apple support Emoji?")
  end
```

…and now that I think about it, maybe `truncate_changelog` should come after the emojis are stripped?

2018-04-03 23:08 UTC, joshdholtz submitted a review, later dismissed
Yeah yeah, I agree with @getaaron. Can we add some tests to this and call truncate after sanitize?

2018-04-11 19:44 UTC, joshdholtz commented
@koenpunt Heyyy 👋 Are you still working on this PR? 😊

2018-04-12 13:00 UTC, merged

2018-04-12 13:01 UTC, getaaron commented
Thanks, @koenpunt. Great work!

2018-04-12 13:02 UTC, koenpunt commented
> Thanks, @koenpunt. Great work!

You're welcome! 🎉