Enable set 'NFC Tag Reading' at 'fastlane produce' cli. (#12179)
fastlane/fastlane pull request #12201
Opened 2018-03-30 00:40 UTC by kazuhidet

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I wanted to use the "NFC Tag Reading" function on the iPhone, but since it was not in "fastlane produce enable_services", I added it.

### Description

Added "- nfc - tag - reading" to "fastlane produce enable_services" option.
Added a description to switch between enable and disable for the missing items.
    --hotspot
    --multipath

At produce option I annotated some deprecated keywords and added new keywords.
    Deprecated keywords
      --passbook
      --vpn-conf
    New keywords
      --personal-vpn
      --wallet

*We kept the old keywords for maintaining compatibility.

Sorted so that the description of 'fastlane produce' is displayed in alphabetical order.

2018-03-30 20:34 UTC, joshdholtz requested changes

2018-03-30 20:34 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/create_app_online.md
> +    --nfc-tag-reading    Disable NFC Tag Reading
This looks like its in here twice? Should this be `--wireless-conf`?

2018-03-30 22:41 UTC, kazuhidet commented
@joshdholtz First of all, I will fix it.
Are there any other problems?

2018-04-02 11:17 UTC, joshdholtz approved these changes
Thanks for these changes! Looks good 💪

2018-04-02 11:17 UTC, merged