Update sync_code_signing.md
fastlane/fastlane pull request #12285
Opened 2018-04-11 13:56 UTC by hammadzz

Simple readme update fixes issue #12260
Documentation added. No code changes.

2018-04-11 15:03 UTC, hammadzz commented
I signed it!

2018-04-15 17:42 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +openssl aes-256-cbc -k <password> -in <fileYouWantToDecryptPath> -out <decryptedFilePath> -a -d
Can we keep the quotes in here? The quotes don't hurt but quotes can be needed if the file paths have spaces in them

2018-04-15 17:51 UTC, joshdholtz requested changes

2018-04-15 17:51 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +openssl aes-256-cbc -k <password> -in <fileYouWantToDecryptPath> -out <decryptedFilePath> -a -d
Can we keep the quotes in here? The quotes don't hurt but quotes can be needed if the file paths have spaces in them

2018-04-15 17:51 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +### Export Distribution Certificate and Private Key as p12 (pkcs12) file
Can we make this `####` since its a sub-section of `### Manual Decrypt`?

2018-04-15 17:51 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +The certificate is stores in the .cer file and the private key in .p12 file. They need to be decrypted and repackaged into a single encrypted p12 file.
```
_match_ stores the certificate (.cer) and the private key (.p12) files separately. The following steps will repackage the separate certificate and private key into a single .p12 file.
```

2018-04-15 17:51 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +### Export Distribution Certificate and Private Key as p12 (pkcs12) file
```
#### Export Distribution Certificate and Private Key as Single .p12 File
```

2018-04-15 17:51 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +Decrypt your cert found in certs/distribution/<unique-id>.cer as a pem file
I think we need to replace `/distribution` with `/<type>/` as the values could be `development`, `distribution` or `enterprise`

2018-04-17 13:42 UTC, hammadzz commented
Ready to go now

2018-05-02 11:37 UTC, joshdholtz requested changes

2018-05-02 11:37 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +openssl aes-256-cbc -k <password> -in <fileYouWantToDecryptPath> -out <decryptedFilePath> -a -d
@hammadzz I think one spot for the double quotes was forgotten 🙃 ^

2018-05-02 15:57 UTC, hammadzz commented
@joshdholtz now taken care of. Thanks

2018-05-03 01:06 UTC, joshdholtz approved these changes
Thanks for the changes! Looks good 😊

2018-05-03 01:06 UTC, merged

2018-05-04 21:50 UTC, svanzoest commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +openssl aes-256-cbc -k "<password>" -in "certs/<type>/<unique-id>.cer" -out "cert.dem" -a -d
do you mean cert.de**r** here?

2018-05-07 20:36 UTC, hammadzz commented on fastlane/lib/fastlane/actions/docs/sync_code_signing.md
> +openssl aes-256-cbc -k "<password>" -in "certs/<type>/<unique-id>.cer" -out "cert.dem" -a -d
Shoot you are right.