Fix broken markdown in actions' details
fastlane/fastlane pull request #12348
Opened 2018-04-20 20:17 UTC by revolter

### This is how the docs would look like if they would get updated using the lastest version:

![screen shot 2018-04-20 at 23 06 54](https://user-images.githubusercontent.com/5748627/39071412-a33de3c2-44ef-11e8-9e03-1ce43fa45929.png)

### And how it looks like in the present and also after this PR:

![screen shot 2018-04-20 at 23 07 11](https://user-images.githubusercontent.com/5748627/39071426-b2c9a010-44ef-11e8-86a3-e59a128e0a6a.png)

---

### Other differences between the live version and the new version combined from #12287 and this one:

Before:

![screen shot 2018-04-20 at 23 05 06](https://user-images.githubusercontent.com/5748627/39071339-5934ce58-44ef-11e8-8d81-9028efe7e6d4.png)

After:

![screen shot 2018-04-20 at 23 05 14](https://user-images.githubusercontent.com/5748627/39071346-5b29a698-44ef-11e8-8425-9e42b87e5d09.png)

Before:

![screen shot 2018-04-16 at 20 56 03](https://user-images.githubusercontent.com/5748627/39071518-1283e150-44f0-11e8-9c65-be966e9973ee.png)

After:

![screen shot 2018-04-16 at 20 56 11](https://user-images.githubusercontent.com/5748627/39071526-166054ca-44f0-11e8-8c9b-7d80fd2322bd.png)

Before:

![screen shot 2018-04-16 at 20 50 31](https://user-images.githubusercontent.com/5748627/39071542-251db1d8-44f0-11e8-9ae8-0c3806269f0a.png)

After:

![screen shot 2018-04-16 at 20 51 17](https://user-images.githubusercontent.com/5748627/39071548-28fd1488-44f0-11e8-8a63-f3ee5b7380b6.png)

Before:

![screen shot 2018-04-15 at 20 15 10](https://user-images.githubusercontent.com/5748627/39071564-38cbf992-44f0-11e8-9701-20d806a16f45.png)

After:

![screen shot 2018-04-15 at 20 15 17](https://user-images.githubusercontent.com/5748627/39071572-3f965c5e-44f0-11e8-8546-d0a9ec262d66.png)

Before:

![screen shot 2018-04-11 at 23 47 55](https://user-images.githubusercontent.com/5748627/38642600-2e3f1a86-3de3-11e8-889b-cadc38475db7.png)

After:

![screen shot 2018-04-20 at 23 12 24](https://user-images.githubusercontent.com/5748627/39071613-656e33ac-44f0-11e8-91c2-11348e07c2a8.png)

Before:

![screen shot 2018-04-20 at 23 17 12](https://user-images.githubusercontent.com/5748627/39071781-046a72ae-44f1-11e8-8f26-0200eb14ad02.png)

After:

![screen shot 2018-04-20 at 23 17 28](https://user-images.githubusercontent.com/5748627/39071786-076260a2-44f1-11e8-9a44-d62bae83ffa1.png)

2018-04-20 21:50 UTC, joshdholtz commented
@revolter I ran `fastlane action add` and got...
```sh
➜  fastlane git:(revolter-hotfix/deprecation-details-fixes) fl action adb
[✔] 🚀
bundler: failed to load command: fastlane (/Users/josh/.gem/ruby/2.2.10/bin/fastlane)
SyntaxError: /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/get_push_certificate.rb:33: syntax error, unexpected <<
        sample = <<~SAMPLE.markdown_sample
                   ^
/Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/get_push_certificate.rb:34: syntax error, unexpected tXSTRING_BEG, expecting keyword_end
          ```ruby
             ^
/Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/get_push_certificate.rb:40: syntax error, unexpected tXSTRING_BEG, expecting keyword_end
          ```
            ^
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:94:in `require'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:94:in `block in load_default_actions'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:93:in `each'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:93:in `load_default_actions'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane.rb:37:in `load_actions'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:34:in `start'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
  /Users/josh/Projects/fastlane/fastlane/bin/fastlane:20:in `<top (required)>'
  /Users/josh/.gem/ruby/2.2.10/bin/fastlane:23:in `load'
  /Users/josh/.gem/ruby/2.2.10/bin/fastlane:23:in `<top (required)>'
```

2018-04-20 21:52 UTC, revolter commented
Oh, right, I'm stupid. I'll see if I can fix it now.

2018-04-20 22:10 UTC, joshdholtz requested changes
All of the `<<~` need to be replaced with `<<-` 😊

2018-04-20 22:12 UTC, revolter commented
@joshdholtz, Fixed it. But I rebased it because I had a couple of useless commits and I didn't want to revert them.

2018-04-20 22:13 UTC, joshdholtz commented
@revolter Is this spacing too large for the lists when viewing in CLI? 🤔 
```sh
+----------------------------------------------------------------------------------------------------------------------------+
|                                                        add_git_tag                                                         |
+----------------------------------------------------------------------------------------------------------------------------+
| This will add an annotated git tag to the current branch                                                                   |
|                                                                                                                            |
| This will automatically tag your build with the following format: `<grouping>/<lane>/<prefix><build_number>`, where:       |
|                                                                                                                            |
| -           `grouping` is just to keep your tags organised under one 'folder', defaults to 'builds'                        |
| -           `lane` is the name of the current fastlane lane                                                                |
| -           `prefix` is anything you want to stick in front of the version number, e.g. 'v'                                |
| -           `postfix` is anything you want to stick at the end of the version number, e.g. '-RC1'                          |
| -           `build_number` is the build number, which defaults to the value emitted by the `increment_build_number` action |
|                                                                                                                            |
| For example, for build 1234 in the 'appstore' lane, it will tag the commit with `builds/appstore/1234`.                    |
|                                                                                                                            |
| Created by lmirosevic, maschall                                                                                            |
+----------------------------------------------------------------------------------------------------------------------------+
```

2018-04-20 22:28 UTC, revolter commented
@joshdholtz, Nope. But now, if the link text is the same as the URL, I remove one of them and add an emoji:

```
+----------------------------------------------------------------------------------------------------------------------------------+
|                                                              sonar                                                               |
+----------------------------------------------------------------------------------------------------------------------------------+
| Invokes sonar-scanner to programmatically run SonarQube analysis                                                                 |
|                                                                                                                                  |
| See http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner 🔗 for details.                                      |
| It can process unit test results if formatted as junit report as shown in [xctest](https://docs.fastlane.tools/actions/xctest/)  |
| action. It can also integrate coverage reports in Cobertura format, which can be transformed into by the                         |
| [slather](https://docs.fastlane.tools/actions/slather/) action.                                                                  |
|                                                                                                                                  |
| Created by c_gretzki                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------+
```

2018-04-20 22:29 UTC, revolter commented
I tried using `tty-markdown` but it doesn't work with our tables if a markdown elements needs to show up on 2 lines.

2018-04-20 22:29 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/create_app_online.rb
> +      def self.details
Good find!

2018-04-20 22:41 UTC, joshdholtz commented
@revolter Do we want the tickticktick and `no highlight` showing like it does in CLI here? 🤔 

```sh
+-------------------------------------------------------------------------------------------------------+
|                                          get_github_release                                           |
+-------------------------------------------------------------------------------------------------------+
| This will verify if a given release version is available on GitHub                                    |
|                                                                                                       |
| This will return all information about a release. For example:                                        |
|                                                                                                       |
| ```no-highlight                                                                                       |
| {                                                                                                     |
|   "url"=>"https://api.github.com/repos/KrauseFx/fastlane/releases/1537713",                           |
|    "assets_url"=>"https://api.github.com/repos/KrauseFx/fastlane/releases/1537713/assets",            |
|    "upload_url"=>"https://uploads.github.com/repos/KrauseFx/fastlane/releases/1537713/assets{?name}", |
|    "html_url"=>"https://github.com/fastlane/fastlane/releases/tag/1.8.0",                             |
|    "id"=>1537713,                                                                                     |
|    "tag_name"=>"1.8.0",                                                                               |
|    "target_commitish"=>"master",                                                                      |
|    "name"=>"1.8.0 Switch Lanes & Pass Parameters",                                                    |
|    "draft"=>false,                                                                                    |
|    "author"=>                                                                                         |
|     {"login"=>"KrauseFx",                                                                             |
|      "id"=>869950,                                                                                    |
|      "avatar_url"=>"https://avatars.githubusercontent.com/u/869950?v=3",                              |
|      "gravatar_id"=>"",                                                                               |
|      "url"=>"https://api.github.com/users/KrauseFx",                                                  |
|      "html_url"=>"https://github.com/fastlane",                                                       |
|      "followers_url"=>"https://api.github.com/users/KrauseFx/followers",                              |
|      "following_url"=>"https://api.github.com/users/KrauseFx/following{/other_user}",                 |
|      "gists_url"=>"https://api.github.com/users/KrauseFx/gists{/gist_id}",                            |
|      "starred_url"=>"https://api.github.com/users/KrauseFx/starred{/owner}{/repo}",                   |
|      "subscriptions_url"=>"https://api.github.com/users/KrauseFx/subscriptions",                      |
|      "organizations_url"=>"https://api.github.com/users/KrauseFx/orgs",                               |
|      "repos_url"=>"https://api.github.com/users/KrauseFx/repos",                                      |
|      "events_url"=>"https://api.github.com/users/KrauseFx/events{/privacy}",                          |
|      "received_events_url"=>"https://api.github.com/users/KrauseFx/received_events",                  |
|      "type"=>"User",                                                                                  |
|      "site_admin"=>false},                                                                            |
|    "prerelease"=>false,                                                                               |
|    "created_at"=>"2015-07-14T23:33:01Z",                                                              |
|    "published_at"=>"2015-07-14T23:44:10Z",                                                            |
|    "assets"=>[],                                                                                      |
|    "tarball_url"=>"https://api.github.com/repos/KrauseFx/fastlane/tarball/1.8.0",                     |
|    "zipball_url"=>"https://api.github.com/repos/KrauseFx/fastlane/zipball/1.8.0",                     |
|    "body"=> ...Markdown...                                                                            |
|   "This is one of the biggest updates of _fastlane_ yet"                                              |
| }                                                                                                     |
| ```                                                                                                   |
|                                                                                                       |
| Created by KrauseFx, czechboy0, jaleksynas, tommeier                                                  |
+-------------------------------------------------------------------------------------------------------+
```

2018-04-21 07:09 UTC, revolter commented
Well, one option would be to remove them, and I think that it will be a little bit harder to quickly scan the text and the different parts, so I'll leave them (some actions already had these too, so it's not new) as some kind of separators.

Another option would be to highlight them like a Markdown parser but that's complicated.

2018-04-23 10:16 UTC, joshdholtz commented
@revolter Ahhh yeah yeah, I _did_ notice that some of the actions previously used the markdown link syntax.

I'm not sure how clean this would be but could we use a regex like this (https://stackoverflow.com/a/31192012) to extract any markdown links and just replace it with the url?

2018-04-23 13:28 UTC, revolter commented
Let's take `sonar` for example.

Its details are:

```
See [http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) for details.
It can process unit test results if formatted as junit report as shown in [xctest](https://docs.fastlane.tools/actions/xctest/) action. It can also integrate coverage reports in Cobertura format, which can be transformed into by the [slather](https://docs.fastlane.tools/actions/slather/) action.
```

In terminal, it shows like this:

```
See http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner 🔗 for details.
It can process unit test results if formatted as junit report as shown in [xctest](https://docs.fastlane.tools/actions/xctest/) action. It can also integrate coverage reports in Cobertura format, which can be transformed into by the [slather](https://docs.fastlane.tools/actions/slather/) action.
```

Are you saying to change the second like to:

```
It can process unit test results if formatted as junit report as shown in https://docs.fastlane.tools/actions/xctest/ 🔗 action. It can also integrate coverage reports in Cobertura format, which can be transformed into by the https://docs.fastlane.tools/actions/slather/ 🔗 action.
```

?

_(the `🔗` is optional, I just added it for Markdown links where the text was the same, in which case I remove it)_

This would make incorrect phrasing for this `appetize`'s details line:

```
To integrate appetize into your GitHub workflow check out the [device_grid guide](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/device_grid/README.md).
```

where we want the text **and** the link too.

What if we get rid of the not user friendly Markdown syntax by replacing the links, in these example, like this:

```
See http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner 🔗 for details.
It can process unit test results if formatted as junit report as shown in "xctest" (https://docs.fastlane.tools/actions/xctest/ 🔗) action. It can also integrate coverage reports in Cobertura format, which can be transformed into by the "slather" (https://docs.fastlane.tools/actions/slather/ 🔗) action.
```

and

```
To integrate appetize into your GitHub workflow check out the "device_grid guide" (https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/device_grid/README.md 🔗).
```

2018-04-23 13:48 UTC, joshdholtz commented
@revolter I really like your suggestion with the `"link name" (link text)` 👌 That is actually much easier to read, IMO, than the other ways on CLI. Is that too much work to do? 😊

2018-04-24 16:35 UTC, joshdholtz commented
@revolter I'm always down for emojis 🙃

2018-04-25 02:08 UTC, joshdholtz commented
@revolter That markdown link change is so good ✊

2018-04-25 02:14 UTC, joshdholtz approved these changes
I'm good with merging this if you are good with merging this!

2018-04-25 07:51 UTC, merged