[slack] add link names arg and move message field as main text
fastlane/fastlane pull request #12389
Opened 2018-04-25 20:14 UTC by sujithvm

Motivation and Context
Mentioning a developer or pinging a slack channel in a slack message is often a nice feature in cases where a build/deployment fails. Currently it does not link them in a slack message.

Description
Slack API has link_names arg that can be use to link usernames and channels for main text message. which does not exist for attachments (currently way of sending text). So I have refactored text and fallback field as part of ping. text can still used in attachments as part of attachment_properties.

2018-04-26 12:56 UTC, joshdholtz requested changes
This is a good addition! Just a few small nit picks 😀 Can you also sign the CLA too?

2018-04-26 12:56 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/slack.rb
> +                                       description: "Find and link channel names and usernames. (true/false)",
Can you remove the `.` from the description? 🙃

2018-04-26 12:56 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/slack.rb
> +          results = notifier.ping('', link_names: options[:link_names], icon_url: icon_url, attachments: [slack_attachment])
Can you also set the option to a variable above and use that variable here? Since that is what it seems like this action tends to do 😊

2018-04-26 18:07 UTC, sujithvm commented
@joshdholtz Thank you very much for reviewing my PR. I have signed CLA. Let me know if any other change is required

2018-04-27 11:09 UTC, joshdholtz approved these changes
This is great! Thanks for the contribution 😊

2018-04-27 13:55 UTC, merged