Add `log_path` option to the carthage action
fastlane/fastlane pull request #12474
Opened 2018-05-08 16:26 UTC by taisukeh

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Carthage has the `--log-path` option to specify xcode build log path.

```
% carthage help bootstrap
...
[--log-path (string)]
        path to the xcode build output. A temporary file is used by default
...
```

But the carthage action has no  option to specify it.

### Description

Add `log_path` option to the carthage action.

2018-05-15 23:07 UTC, joshdholtz requested changes
One small thing!

2018-05-15 23:07 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/carthage.rb
> +          params[:log_path] = nil
Can we call `UI.user_error!(` instead so users know / aren't surprised why its getting cleared 🙃

2018-05-19 17:35 UTC, taisukeh commented
@joshdholtz Thanks for your feedback. I fixed it.

2018-05-21 15:23 UTC, joshdholtz requested changes
One more small nit pick 😉 then we will be 💯

2018-05-21 16:32 UTC, taisukeh commented
@joshdholtz I fixed it :bow:

2018-05-24 10:50 UTC, joshdholtz approved these changes
Looks great! Thanks 😊

2018-05-24 10:50 UTC, merged