[WIP] - changelog_from_git_commits fix from command line
fastlane/fastlane pull request #12477
Opened 2018-05-09 04:35 UTC by RishabhTayal

fixes: https://github.com/fastlane/fastlane/issues/10894

2018-05-09 05:03 UTC, RishabhTayal commented
@joshdholtz This is ready for review. 👀

2018-05-10 15:17 UTC, joshdholtz requested changes
A few comments to make sure unnecessary crashes don't happen based on data types and content. We should maybe add some tests for when data is bad? Ex: when a string is based in an there isn't a comma

2018-05-10 15:17 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/changelog_from_git_commits.rb
> +                                         unless value.kind_of?(String)
Can we verify if its a string that it has a comma in it?

2018-05-10 15:17 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/changelog_from_git_commits.rb
> +            if params[:between].include?(",") # running from shell
We might need check if its a string here before calling `include`?

2018-05-10 15:17 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/changelog_from_git_commits.rb
> +            else
And depending on how the above is structured.. we may need to add a check to make sure that this is an array?

2018-05-16 14:51 UTC, RishabhTayal commented
@joshdholtz all the comments are addressed. Ready to review again. 👍

2018-05-16 23:15 UTC, joshdholtz approved these changes
This is golden! Thanks for the contribution ❤️

2018-05-16 23:15 UTC, merged

2018-05-16 23:45 UTC, RishabhTayal commented
Just wanted to explain what we are doing here incase. The between option now takes both array of string and string with comma in it.

2018-05-17 05:39 UTC, BasThomas commented
Nice one @RishabhTayal!