[match] add new option to recreate deleted profiles in dev portal
fastlane/fastlane pull request #12539
Opened 2018-05-17 01:46 UTC by joshdholtz

## Wut
- `match` will error out if provisioning profile was deleted from the dev portal but remained in the match repo
- This can be a bit cumbersome for users as they either need to:
  1. delete the profile manually from the repo
  2. run nuke
- This proposed feature will automatically recreate the deleted profile
  - The deleted profile essentially behaves like an "invalid" profile 

## Additional Thoughts?
- I currently set the new option to default to `false`  as to not change existing behavior under current users **BUT** this could be set to default to `true` as it _could_ prevent some confusion for new users

2018-06-20 07:30 UTC, revolter commented
Is there a `match init`? If yes, it could set it to `true` for new inits. Maybe by simply adding it here: https://github.com/fastlane/fastlane/blob/master/match/lib/assets/MatchfileTemplate.

2018-07-13 16:21 UTC, RishabhTayal commented
Any update on this PR?

2018-08-11 19:15 UTC, getaaron requested changes
@joshdholtz I think a default value of `true` would be better since it's more helpful, even if it might confuse a few people, it won't hurt anything

2018-11-21 16:18 UTC, joshdholtz commented
@janpio That is correct! It errors out if not remote copy which always felt a little bit weird 😖 This will allow _match_ to recreate a new profile if it isn't found remotely (like expected).

2018-11-21 16:29 UTC, janpio commented
Would the now deleted profile be of any use of _another development machine_? So if my colleague still has it, do I harm him in any way when my own match creates a new one? Or is this broken for him anyway already? 

What happens if my colleague still has the old one on his machine and runs match after it recreated the profile when I ran it - will this recognize that the remote one is a new one and not the one they still have on their machine?

2018-11-21 19:32 UTC, KrauseFx commented on match/lib/match/runner.rb
> +      if spaceship && !spaceship.profile_exists(username: params[:username], uuid: uuid, return_if_missing: params[:recreate_deleted_profiles])
The "renaming" of the parameter here from `recreate_deleted_profiles` to `return_if_missing` adds unnecessary complexity, can we keep the name?

2018-11-21 19:33 UTC, KrauseFx commented on match/lib/match/spaceship_ensure.rb
> +        return false if return_if_missing
this would be a chance to tell the user about the parameter they can set, right?

2018-11-21 19:35 UTC, KrauseFx approved these changes
Overall this is a good change, and I like that it's not on by default yet. I ran into this problem myself in the past. I added a few comments.

2018-11-21 19:35 UTC, KrauseFx commented
I'd also be ok setting this on by default, and making sure to monitor GH issues after shipping

2018-11-21 19:46 UTC, getaaron commented
this should be on by default (can’t think of a good reason to have it off — I almost think it shouldn’t even be an option)

@janpio no, once deleted the profile is of no use on another dev machine. And the new profile would replace the old one 👍🏼

2018-11-21 19:48 UTC, getaaron requested changes

2018-11-21 19:48 UTC, getaaron commented on match/lib/match/options.rb
> +                                     default_value: false),
Should be true IMO

2018-11-21 20:13 UTC, KrauseFx commented
Yah I'm ok with what @getaaron said, let's make it the default, and not even an option

2018-11-22 04:30 UTC, getaaron approved these changes

2018-11-22 04:30 UTC, getaaron commented
🛳

2018-11-22 04:41 UTC, joshdholtz commented
@getaaron WOOAAAAHH DDUUUDDEEEEE, that was quick!

2018-11-22 04:44 UTC, merged