[spaceship] Updated Tunes.client so select_team returns team_id when executed jus…
fastlane/fastlane pull request #12605
Opened 2018-05-23 18:39 UTC by kumichou

…t like Portal.client does

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
When using Spaceship directly, and selecting a team based on the name, it was convenient to get the team_id back in Portal to use in any other calls. However, Tunes didn't work that way and just returned nil so you needed to make an extra call to Tunes.client.team_id to get the value.

### Description

2018-05-23 18:47 UTC, kumichou commented
I signed it!

2018-05-24 10:47 UTC, joshdholtz requested changes
One small change request 😊

2018-05-24 10:47 UTC, joshdholtz commented on spaceship/spec/tunes/tunes_client_spec.rb
> +        ENV["FASTLANE_ITC_TEAM_NAME"] = "Harry"
You can probably use `stub_const` to do this 😊 
```rb
stub_const('ENV', { 'FASTLANE_ITC_TEAM_NAME' => 'Harry })
```

2018-05-24 10:47 UTC, joshdholtz commented on spaceship/spec/tunes/tunes_client_spec.rb
> +        ENV.delete("FASTLANE_ITC_TEAM_NAME")
You can delete these if you use `stub_const`

2018-05-24 17:26 UTC, kumichou commented
Thanks for the feedback. I didn't realize I could do that so updated the code in the RSpec test.

2018-05-25 15:23 UTC, kumichou commented
@joshdholtz Didn't know if I needed to tag you or not that changes you requested have been implemented.

2018-05-26 02:37 UTC, joshdholtz approved these changes
Thanks for the contribution! 😊

2018-05-26 02:37 UTC, merged