Add timezone to timestamp
fastlane/fastlane pull request #12673
Opened 2018-06-01 22:03 UTC by duality72

Adding timezones to the timestamps. This makes logging indexers like Splunk happy. Otherwise, they may misinterpret the  true time of the timestamp depending on the time zone settings of the system and running process.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This makes logging indexers like Splunk happy. Otherwise, they may misinterpret the  true time of the timestamp depending on the time zone settings of the system and running process.

No issue open, as of yet.

Ran fastlane. The timestamps now have the time zone added.

### Description

Adding timezones to the timestamps.

2018-06-04 18:21 UTC, duality72 commented
I signed it!

2018-06-14 19:23 UTC, joshdholtz requested changes
~Can we make a new environment variable that adds the `%z` called `FASTLANE_SHOW_TIMEZONE`? Showing the timezone can be a bit cluttery for most users~ 🙃

2018-09-07 15:37 UTC, duality72 commented
Sorry for the delay. I am still interested. Will work to get it done next week.

2018-09-25 01:47 UTC, duality72 commented
Apologies for the delay. The timezone addition now keys off of FASTLANE_SHOW_TIMEZONE

2018-09-26 11:47 UTC, joshdholtz submitted a review, later dismissed
~One small request! Then we can merge~ 💪

2018-09-26 11:47 UTC, joshdholtz commented on fastlane_core/lib/fastlane_core/ui/implementations/shell.rb
> +      timezone_string = !ENV.key?('FASTLANE_SHOW_TIMEZONE') ? '' : ' %z'
Can we change 
```
timezone_string = !ENV.key?('FASTLANE_SHOW_TIMEZONE') ? '' : ' %z'
```
to
```
timezone_string = FastlaneCore::Env.truthy?("FASTLANE_SHOW_TIMEZONE") ? ' %z' : ''
```
???

Other than that this looks 💯 🚀

2018-09-26 21:58 UTC, duality72 commented
Updated, but there is a use of ENV.key not far above this code to check DEBUG.

2018-11-13 16:30 UTC, janpio approved these changes

2018-11-13 17:00 UTC, janpio commented
> Updated, but there is a use of ENV.key not far above this code to check DEBUG.

Would you be motivated to create another PR to fix that? Small thing, but I guess it would make @joshdholtz happy 🎂 🎁

2019-09-28 21:27 UTC, janpio approved these changes
This works.

Before:
```
C:\Users\Jan\Documents\throwaway\fastlane12466>bundle exec fastlane pay
 [✔] 🚀
[23:26:20]: ------------------------------
[23:26:20]: --- Step: default_platform ---
[23:26:20]: ------------------------------
[23:26:20]: Driving the lane 'pay' 🚀
```

After:
```
C:\Users\Jan\Documents\throwaway\fastlane12466>set FASTLANE_SHOW_TIMEZONE=1
C:\Users\Jan\Documents\throwaway\fastlane12466>bundle exec fastlane pay
 [✔] 🚀
[23:26:31 +0200]: ------------------------------
[23:26:31 +0200]: --- Step: default_platform ---
[23:26:31 +0200]: ------------------------------
[23:26:31 +0200]: Driving the lane 'pay' 🚀
```

And after with `--verbose`:

```
C:\Users\Jan\Documents\throwaway\fastlane12466>bundle exec fastlane pay --verbose
 [✔] 🚀
DEBUG [2019-09-28 23:29:57.92 +0200]: Checking if there are any plugins that should be loaded...
INFO [2019-09-28 23:29:57.94 +0200]: ------------------------------
INFO [2019-09-28 23:29:57.94 +0200]: --- Step: default_platform ---
INFO [2019-09-28 23:29:57.94 +0200]: ------------------------------
INFO [2019-09-28 23:29:57.94 +0200]: Driving the lane 'pay' 🚀
```

Thanks @duality72

2019-09-28 21:29 UTC, janpio commented
Also created a PR for the documentation that makes this discoverable: https://github.com/fastlane/docs/pull/868

2019-09-28 21:31 UTC, merged