Scan formatter backticks patch
fastlane/fastlane pull request #12754
Opened 2018-06-14 18:34 UTC by wag-miles

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

### Description

Fixed the 'formatter' argument for scan using backticks to quote the value. Couldn't run scan with a custom formatter.

2018-06-14 18:36 UTC, wag-miles commented
Signed

2018-06-14 18:46 UTC, joshdholtz requested changes
Can you remove the changes to ` fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj`?

This change is a side effect of running `rspec` but a fix for this was just merged in so this won't be an issue in the future 😊

2018-06-14 19:49 UTC, wag-miles commented
Done

2018-06-18 12:02 UTC, joshdholtz requested changes

2018-06-18 12:02 UTC, joshdholtz commented on scan/lib/scan/test_command_generator.rb
> +        formatter << "-f 'xcpretty-travis-formatter'"
The backticks are actually needed if you are loading a custom formatter as a gem (which is what this is doing so this needs to stay as backticks)

2018-06-18 12:02 UTC, joshdholtz commented on scan/lib/scan/test_command_generator.rb
> +        formatter << "-f '#{Scan.config[:formatter]}'"
Single quotes works if `:formatter` is a file path but this also needs to be backticks if `:formatter` is a gem 

I _think_ what we need to do is only use single quotes **if** `:formatter` end in `.rb` and if the file exists 🤔

2018-06-20 21:05 UTC, wag-miles commented
I applied the latest suggestions and created an additional test case

2018-06-21 13:32 UTC, joshdholtz requested changes
Can you run rubocop on this so it passes the linter? 😊

2018-06-21 18:08 UTC, wag-miles commented
Done. Aggressive formatter on the loose

2018-06-25 14:28 UTC, joshdholtz approved these changes
Looks good! Thanks for doing the changes 😊

2018-06-25 14:28 UTC, merged