Set ConnectHardwareKeyboard to false for all simulators. Issue #12325.
fastlane/fastlane pull request #12829
Opened 2018-07-02 03:37 UTC by onato

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The ConnectHardwareKeyboard doesn't work in Xcode 9 or greater.
Issue #12325.
I ran my UI Test suit and saw that the hardware keyboard had been disabled. I also looked in `~/Library/Preferences/com.apple.iphonesimulator.plist` and verified that it was correctly updated. 

### Description
The additional script inserts the `ConnectHardwareKeyboard` under each `DevicePreferences`. It first tries to set `ConnectHardwareKeyboard`. If that fails it adds `ConnectHardwareKeyboard`.

2018-07-02 12:18 UTC, joshdholtz commented
@onato Heyyy 👋 Thanks for the contribution! Do you know if there a good way for me to test that this works? 😊

2018-07-03 21:38 UTC, onato commented
1. In an iOS simulator set `Hardware->Keyboard->Connect Hardware Keyboard`.
1. Run `fastlane snapshot`.
1. Make sure that `Hardware->Keyboard->Connect Hardware Keyboard` is not set.

2018-07-05 12:02 UTC, joshdholtz requested changes
Looks like this works! One question about a comment and can you run rubocop to fix the lint issues? Then we should be good 😊

2018-07-05 12:02 UTC, joshdholtz commented on snapshot/lib/snapshot/fixes/hardware_keyboard_fix.rb
> +        Helper.backticks("/usr/libexec/PlistBuddy -c \"Print :DevicePreferences\" ~/Library/Preferences/com.apple.iphonesimulator.plist | perl -lne 'print $1 if /^    (\\S*) =/' | while read -r a; do
Can you add a comment above here with a link to a stackoverflow post or somewhere on where you got this from? (I'm assuming this is from a stackoverflow post) 😊

2018-07-08 22:42 UTC, onato commented
Done.

2018-07-12 11:44 UTC, joshdholtz approved these changes
Looks good! Thanks for making those changes 😊

2018-07-12 11:45 UTC, merged