[snapshot] fix bug getting the device width
fastlane/fastlane pull request #12881
Opened 2018-07-11 10:08 UTC by asam139

Fix bug: get first window to get the device width.

### Checklist
- [] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

In some cases and devices the SnapshotHelper.swift fails finding the window using the current way.

I have tested with all simulators for iOS 10 and iOS 11 (iPad an iPhone)

### Description

Change the way which the device width is obtained

2018-07-11 10:17 UTC, asam139 commented
I signed it!

2018-07-12 17:51 UTC, joshdholtz requested changes
This looks good! Can you also bump the last line to `// SnapshotHelperVersion [1.11]`? 😊 Then we should be good to go

2018-07-13 07:53 UTC, asam139 commented
Ready!! Thanks so much 💪🏽

2018-07-16 12:07 UTC, joshdholtz approved these changes
Perfect! Thanks for the contribution ❤️

2018-07-16 12:10 UTC, merged