Add new option to "jira" action
fastlane/fastlane pull request #12912
Opened 2018-07-16 19:35 UTC by Ikloo

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
After integrating fastlane into my project, I will need to use action `fastlane jira` to comment ticket at JIRA. But I have self-hosted JIRA server and that is a problem for me to use action with current options.
It resolves a problem for self-hosted JIRA servers via adding `"/jira"` into `context_path`.

### Description

Added `self_hosted_server` option to action. Option is optional, default - `false`
It appends `"/jira"` to context_path variable for self-hosted jira servers and corrects using in 'jira-ruby' gem.
Updated example with the new option.

2018-07-17 11:31 UTC, joshdholtz reviewed
@Ikloo Thanks for adding this! Quick question... Would it be more flexible for other JIRA installs to add a `context_path` option instead of `self_hosted_server` option?

I don't know much about self hosted JIRA instances but I'm assuming that there is a chance where the `context _path` might not be specifically `/jira`. It seems like adding an option for `context_path` might be more powerful? Just some thoughts 😊

2018-07-17 11:39 UTC, Ikloo commented
@joshdholtz Initially, I did, but then I thought that I did not see other possible `context_path`. Maybe it's because of my little experience.🤔
I will update the PR with this idea. 🚀

2018-07-17 11:42 UTC, joshdholtz commented
@Ikloo Thank you! I'm not sure **if** there will be another context path but that _kinda_ seems like what that `context_path` variable was meant for but it was just never finished 🙃

2018-07-17 11:44 UTC, Ikloo commented
@joshdholtz 
I agree with you.
Updated PR 👌

2018-07-17 11:45 UTC, joshdholtz requested changes

2018-07-17 11:45 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/jira.rb
> +          FastlaneCore::ConfigItem.new(key: :self_hosted_server,
Can you change this to `:context_path`?

2018-07-17 11:45 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/jira.rb
> +                                      description: "Is JIRA self hosted server and need custom context path",
Can you change this to `Appends to the url (ex: "/jira")`

2018-07-17 11:45 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/jira.rb
> +            context_path: "/jira", # append \'/jira\' path to your url
Can you remove the `# append \'/jira\' path to your url`? This information should be in the option description 😊

2018-07-17 12:05 UTC, Ikloo commented
@joshdholtz check it, please. All okay!

2018-07-17 12:08 UTC, joshdholtz approved these changes
Looks great! Thanks for adding this 😊 💪 🚀

2018-07-17 12:08 UTC, merged

2018-07-17 12:09 UTC, Ikloo commented
@joshdholtz Great! Thanks!

2018-07-19 19:33 UTC, Ikloo commented
Awesome 🎊  🎉 🚀