Update docs for importing external testers
fastlane/fastlane pull request #12936
Opened 2018-07-20 09:16 UTC by vjanssens

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Sample CSV provided by Apple does not show how to add testers to testing-groups. I had to dig in the implementation of pilot to find out it was actually possible.

### Description
I removed the link and provided an example CSV in-line.

2018-07-22 23:58 UTC, joshdholtz requested changes
One small request! 😊

2018-07-22 23:58 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/upload_to_testflight.md
> +Add external testers from a CSV file. Create a file called `tester_import.csv` and fill it with the following format:
>Create a file called `tester_import.csv` and

Can we change this to "Create a CSV file (ex: `tester.csv`) and"? Just wanted to make sure its clear that the file doesn't _need_ to be called `tester_import.csv`

2018-07-23 07:19 UTC, vjanssens commented
Done, thank you 👍

2018-07-24 04:12 UTC, joshdholtz requested changes
One more small change!

2018-07-24 04:12 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/docs/upload_to_testflight.md
> +Importing the CSV is as simple as:
Can we also 💣 this line? The example below is implied by the title 🙃

2018-07-24 05:35 UTC, vjanssens commented
Done 👍

2018-07-28 18:32 UTC, joshdholtz approved these changes
💪

2018-07-28 18:32 UTC, merged