[WIP] [snapshot] offer option for snapshot reports for generating rows by screenshot
fastlane/fastlane pull request #12952
Opened 2018-07-24 03:52 UTC by joshdholtz

Fixes #12949

## Description
- Adds new `html_summary_format` option to `snapshot`
  - Ex: `html_summary_format: "group_by_device"` (this is what original implementation was)
  - Ex: `html_summary_format: "group_by_screenshot"` (this is new implementation)
- `group_by_device`
  - Original implementation
  - Groups rows for each language and columns for each screenshot
- `group_by_screenshot`
  - Groups rows by screenshot and each column by language

<img width="630" alt="screen shot 2018-07-23 at 10 13 22 pm" src="https://user-images.githubusercontent.com/401294/43115936-19887838-8ecb-11e8-9ba4-3ecdee2bce43.png">

2018-07-25 20:16 UTC, BJap approved these changes
This is working well for me and does exactly what I needed for my team.

Source: https://github.com/fastlane/fastlane/issues/12949

2018-07-25 20:32 UTC, BJap commented
As a general test step I also ran the report builder after taking one screenshot out of one folder and confirmed it still works, and that language is just skipped for that row. (maybe some languages have a screen some don't so the screenshot might be skipped in some edge cases.

I may suggest testing it with something that makes multiple screenshots in a test run to make sure things are in the correct order but it looks great! I am hoping it grabs all screens by similar names.

2018-07-28 18:38 UTC, joshdholtz commented
@BJap Thanks for doing some testing on it and reporting back 😊 I will definitely need to update my _snapshot_ setup so its easier to test/debug this 😉 Flipping this table around wasn't as trivial as I thought due to the way the files are output but I can definitely find a way to get this working 💯. I will try to get this finished up this week for ya

2018-07-30 23:05 UTC, BJap commented
Agreed and thanks so much for doing this. I thought it through abstractly and thought it could be more difficult to rotate it, and started making a mental note of tests to run to make sure. I guess that served well to note what could go wrong.

2019-09-28 21:42 UTC, janpio requested changes
In the meantime unfortunately another PR was merged, that added a switcher between grouping by language and device - this will make merging this PR almost impossible. It will probably be easier to recreate it from scratch based on current `master`.

2020-06-04 15:42 UTC, closed without merging