[spaceship] Parametrize view_by in analytics API
fastlane/fastlane pull request #12967
Opened 2018-07-26 05:24 UTC by pauchan

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
When calling iTunes analytics IPA I had the need to get the analytics split by country/source so that 
I added an additional optional parameter that can be passed via command line.

### Description
This PR adds optional `view_by` parameter to `*_interval` methods that allow retrieving iTunes statistics split by country/source.
It also adds `measure_interval(start_t, end_t, measure, filter = nil)` method that will allow passing the measure as a command line parameter.

I don't have much experience in writing Ruby so please be easy on me 🙇

2018-07-28 19:54 UTC, joshdholtz requested changes
This looks great! Just two small comments 😊 

Also, can you add some new tests to `app_analytics_spec.rb` that uses these new parameters? I can help you out with these if you need. Just lemme know 🙃

2018-07-28 19:54 UTC, joshdholtz commented on spaceship/lib/spaceship/tunes/app_analytics.rb
> +      def measure_interval(start_t, end_t, measure, view_by = nil)
Can we rename this one to be `app_measure_interval` to be like the rest? 😊

2018-07-28 19:54 UTC, joshdholtz commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        return {
Can we add a comment here something like `# Using rank=DESCENDING and limit=3 as this is what the App Store Connect analytics dashboard uses`?

2018-07-30 03:29 UTC, pauchan commented
@joshdholtz thank you very much for the review!
I've applied the suggested changes.
Let me know if this is good enough for you, especially around specs 🙇

2018-07-30 03:33 UTC, pauchan commented on spaceship/spec/tunes/app_analytics_spec.rb
> +      expect(val['meetsThreshold']).to eq(true)
I've added only a single test case and a single stub for passing `view_by` parameter as they all would be pretty similar. To make it more understandable/distinguishable, I've extracted it to a separate test case.

Let me know if this is enough or do you want me to make stubs using `view_by` for each measure.

2018-07-30 12:04 UTC, joshdholtz approved these changes
This looks great! Thanks for the contribution 💪 🚀

2018-07-30 12:04 UTC, merged