[get_version_number] look into xcconfig for plist
fastlane/fastlane pull request #13024
Opened 2018-08-03 10:55 UTC by hartbit

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass: had 8 failures that seem unrelated to my change.
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context

`get_version_number` crashes when `INFOPLIST_FILE` is defined in a xcconfig file.

### Description

When `get_version_number` uses Xcodeproj's `target.resolved_build_setting` to look for the `INFOPLIST_FILE` build setting, it will crash if the value can't be found, as can happen if the value is defined in xcconfig files. I resolved this by adding a test to make sure we do find a value, and by also checking inside xcconfig files.

2018-08-03 11:02 UTC, hartbit commented
I signed it!

2018-08-06 11:26 UTC, joshdholtz requested changes
@hartbit This change looks 💯 Can you fix the failing test so that we can merge this? 😊

2018-08-28 13:14 UTC, joshdholtz commented
@hartbit Just wanted to ping you here about fixing the failing tests 😊

2018-09-11 10:42 UTC, hartbit commented
@joshdholtz sorry for the delay, I've been very busy lately, but I still plan to resolve this issue

2018-10-17 11:54 UTC, SpacyRicochet commented
This does look like a great addition. So great, our team has a WIP pull request regarding configuration files just waiting for this! 😬

That said, the test is failing because it seems to be looking for the `TargetSRC.plist` in the wrong location. It's looking for it in:

```
.../fastlane/spec/fixtures/actions/get_version_number/SRCROOT/TargetSRC.plist
```

Where the `SRCROOT` part looks like it doesn't make sense. Looks like it's not unwrapping a build variable properly, but I can't figure out from the changed code where exactly. The only relevant thing that changed looks to be adding the `true` parameter. However, I couldn't figure out what `resolved_build_setting` does exactly (I'm a Ruby newbie), so that's where my investigation stopped.

Hope this helps and you can resolve it soon!

2018-11-13 12:38 UTC, janpio commented
`target.resolved_build_setting` is from `xcodeproj`: https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/AbstractTarget#resolved_build_setting-instance_method

2018-11-13 12:39 UTC, janpio commented
I looked into what is going on here a bit:

Before the string contained `$(SRCROOT)/` which was replaced by an empty string:
https://github.com/fastlane/fastlane/pull/13024/files#diff-a4777685ff664e7042c36691b9beb54cR85

From the error message from CI, this now seems to be just `SRCROOT/` - which is not replaced and thus creates a path that does not exist.

The difference is probably/possibly because of the second param `resolve_against_xcconfig = true` for `target.resolved_build_setting`, but I couldn't really figure out why.

@hartbit We should probably add a fixture and test case for the variant you introduced here in `fastlane\fastlane\spec\actions_specs\get_version_number_action_spec.rb`, do you agree?

2018-11-26 20:57 UTC, ZevEisenberg commented
+1 on @janpio's comment about `SRCROOT`. I'm currently affected by this issue, and when I apply the suggested fix, I also get the non-expanded `SRCROOT` in the plist file path. Would love to help find a solution to this, if I can.

2018-11-26 21:05 UTC, janpio commented
If I had more time I would add a few `puts` for the path to see where it gets this faulty addition - and then understand why.

2018-12-04 09:18 UTC, SpacyRicochet commented
Any progress on this issue?

@ZevEisenberg I'm confused as to what the 'suggested fix' is you mention and as to whether it works. Does it?

2018-12-04 10:56 UTC, janpio commented
I assumed @ZevEisenberg meant the code changes of this Pull Request @SpacyRicochet.

Can someone please create a super simple Xcode project an put it on GitHub which can be used to 1) reproduce the current failure and 2) the new problem with this PR?

2019-09-28 22:12 UTC, janpio commented
@googlebot I consent.

I rebased this onto `master`, which surfaced a few different test failures.

Interesting enough the previous discussion about `SRCROOT` doesn't make sense any more as it doesn't appear in the error messages now. Did this get fixed in the meantime somehow!?

---

Anyway, now it seems to be strictly about duplicated paths:

```
Failures:

  1) Fastlane Fastlane::FastFile Get Version Number Integration gets the correct version number for 'TargetVariableParentheses'
     Failure/Error:
       result = Fastlane::FastFile.new.parse("lane :test do
         get_version_number(xcodeproj: '#{path}', target: 'TargetVariableParentheses')
       end").runner.execute(:test)

     FastlaneCore::Interface::FastlaneError:
       Cannot find plist file: /home/circleci/project/fastlane/spec/fixtures/actions/get_version_number/home/circleci/project/fastlane/spec/fixtures/actions/get_version_number/TargetVariableParentheses-Info.plist
     # ./fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
     # ./fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:113:in `get_plist!'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:18:in `run'
     # ./fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
     # ./fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
     # ./fastlane/lib/fastlane/runner.rb:227:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:227:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
     # ./fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
     # (eval):2:in `block in parsing_binding'
     # ./fastlane/lib/fastlane/lane.rb:33:in `call'
     # ./fastlane/lib/fastlane/runner.rb:49:in `block in execute'
     # ./fastlane/lib/fastlane/runner.rb:45:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:45:in `execute'
     # ./fastlane/spec/actions_specs/get_version_number_action_spec.rb:18:in `block (4 levels) in <top (required)>'

  2) Fastlane Fastlane::FastFile Get Version Number Integration gets the correct version with $(SRCROOT)
     Failure/Error:
       result = Fastlane::FastFile.new.parse("lane :test do
         get_version_number(xcodeproj: '#{path}', target: 'TargetSRC')
       end").runner.execute(:test)

     FastlaneCore::Interface::FastlaneError:
       Cannot find plist file: /home/circleci/project/fastlane/spec/fixtures/actions/get_version_number/home/circleci/project/fastlane/spec/fixtures/actions/get_version_number/TargetSRC.plist
     # ./fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
     # ./fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:113:in `get_plist!'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:18:in `run'
     # ./fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
     # ./fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
     # ./fastlane/lib/fastlane/runner.rb:227:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:227:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
     # ./fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
     # (eval):2:in `block in parsing_binding'
     # ./fastlane/lib/fastlane/lane.rb:33:in `call'
     # ./fastlane/lib/fastlane/runner.rb:49:in `block in execute'
     # ./fastlane/lib/fastlane/runner.rb:45:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:45:in `execute'
     # ./fastlane/spec/actions_specs/get_version_number_action_spec.rb:99:in `block (4 levels) in <top (required)>'
```

```
  1) Fastlane Fastlane::FastFile Get Version Number Integration gets the correct version number for 'TargetVariableParentheses'
     Failure/Error:
       result = Fastlane::FastFile.new.parse("lane :test do
         get_version_number(xcodeproj: '#{path}', target: 'TargetVariableParentheses')
       end").runner.execute(:test)

     FastlaneCore::Interface::FastlaneError:
       Cannot find plist file: /Users/distiller/project/fastlane/spec/fixtures/actions/get_version_number/Users/distiller/project/fastlane/spec/fixtures/actions/get_version_number/TargetVariableParentheses-Info.plist
     # ./fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
     # ./fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:113:in `get_plist!'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:18:in `run'
     # ./fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
     # ./fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
     # ./fastlane/lib/fastlane/runner.rb:227:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:227:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
     # ./fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
     # (eval):2:in `block in parsing_binding'
     # ./fastlane/lib/fastlane/lane.rb:33:in `call'
     # ./fastlane/lib/fastlane/runner.rb:49:in `block in execute'
     # ./fastlane/lib/fastlane/runner.rb:45:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:45:in `execute'
     # ./fastlane/spec/actions_specs/get_version_number_action_spec.rb:18:in `block (4 levels) in <top (required)>'

  2) Fastlane Fastlane::FastFile Get Version Number Integration gets the correct version with $(SRCROOT)
     Failure/Error:
       result = Fastlane::FastFile.new.parse("lane :test do
         get_version_number(xcodeproj: '#{path}', target: 'TargetSRC')
       end").runner.execute(:test)

     FastlaneCore::Interface::FastlaneError:
       Cannot find plist file: /Users/distiller/project/fastlane/spec/fixtures/actions/get_version_number/Users/distiller/project/fastlane/spec/fixtures/actions/get_version_number/TargetSRC.plist
     # ./fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
     # ./fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:113:in `get_plist!'
     # ./fastlane/lib/fastlane/actions/get_version_number.rb:18:in `run'
     # ./fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
     # ./fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
     # ./fastlane/lib/fastlane/runner.rb:227:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:227:in `execute_action'
     # ./fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
     # ./fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
     # (eval):2:in `block in parsing_binding'
     # ./fastlane/lib/fastlane/lane.rb:33:in `call'
     # ./fastlane/lib/fastlane/runner.rb:49:in `block in execute'
     # ./fastlane/lib/fastlane/runner.rb:45:in `chdir'
     # ./fastlane/lib/fastlane/runner.rb:45:in `execute'
     # ./fastlane/spec/actions_specs/get_version_number_action_spec.rb:99:in `block (4 levels) in <top (required)>'
```

```
  1) Fastlane Fastlane::FastFile Get Version Number Integration gets the correct version number for 'TargetVariableParentheses'
     Failure/Error:
       result = Fastlane::FastFile.new.parse("lane :test do
         get_version_number(xcodeproj: '#{path}', target: 'TargetVariableParentheses')
       end").runner.execute(:test)
     FastlaneCore::Interface::FastlaneError:
       Cannot find plist file: C:/projects/fastlane/fastlane/spec/fixtures/actions/get_version_number/C:/projects/fastlane/fastlane/spec/fixtures/actions/get_version_number/TargetVariableParentheses-Info.pli [...]

2019-09-28 22:25 UTC, janpio commented
So, my iOS knowledge is unfortunately lacking regarding what" if the value is defined in xcconfig files" actually means. 

It would be super awesome if someone could give me some pointers what exactly I have to change/add in `fastlane/spec/fixtures/actions/get_version_number` to be able to reproduce the crash you mentioned @hartbit. With that, we could add a test to `get_version_number_action_spec.rb` and first reproduce the crash, then test our changes if they fix it.

---

Right now it seems to me that replacing `plist_file = File.absolute_path(File.join(folder, plist_file))` with `plist_file = File.absolute_path(plist_file)` (so no more `File.join(folder, ...)` fixes the problem when we are using `true` as the second param of `target.resolved_build_setting`. Setting this param seems to change the returned value to include the full path somehow.

It also seems to take care of the SRCROOT stuff, so this can probably also be removed: https://github.com/fastlane/fastlane/blob/a4c0aa6882614e3e78c1ae57c0b2ae7cf9b434ea/fastlane/lib/fastlane/actions/get_version_number.rb#L104-L108

---

When we have a test case for the behavior we are actually trying to fix, this should be a simple merge here then 🚀

2023-11-19 15:21 UTC, closed without merging