[screengrab] replace double escape with simple escape so command also works on Windows
fastlane/fastlane pull request #13064
Opened 2018-08-08 19:05 UTC by janpio

for now this also includes changes from #12995 - has probably to be rebased after that one is merged.

closes #13060

2018-08-13 11:43 UTC, joshdholtz requested changes
The `\\` is needed for this to work on mac 😬 (I am not sure about Linux though)

I tested this PR on my mac and no screenshot were detected but things worked when switching back over to master

2018-08-13 12:12 UTC, janpio commented
Meh, there probably should be a test for that... 

I'll look into this a bit more.

2018-08-13 12:15 UTC, joshdholtz commented
That might be hard to test because that is a shell command that is actually getting run on an Android emulator I believe 🙃

2018-08-13 12:33 UTC, janpio commented
Hm, probably connected to the shell you are using :/

2018-08-13 13:15 UTC, janpio commented
Windows:

```
C:\Projects
λ echo $foo
$foo

C:\Projects
λ echo \$foo
\$foo
```

macOS:

```
MacBook-Pro:FastlaneDemoIonic sujan$ echo $foo

MacBook-Pro:FastlaneDemoIonic sujan$ echo \$foo
$foo
```

2018-08-13 13:32 UTC, janpio commented
New code now uses different command for Windows. 
I also added comment that explains, as I am sure this is not common knowledge.

I checked the codebase (searched for `\\$`) for similar cases, but didn't find anything relevant.

2018-08-14 13:04 UTC, joshdholtz approved these changes
This works on mac 👍

2018-08-14 13:04 UTC, merged