Git force with lease
fastlane/fastlane pull request #13098
Opened 2018-08-14 05:52 UTC by sprabhuanand

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I need to have the git option --force-with-lease, so that my changes to git will be pushed only when both local and remote is same. Force option sometimes overwrites the code when the remote is ahead of local

I ran the bundle exec fastlane test command and made sure all actions passed. I have pasted the output below

### Description

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Switch to validate_repo lane                                  | 0           |
| 2    | Switch to lint_source lane                                    | 0           |
| 3    | ensure_no_debug_code                                          | 0           |
| 4    | ensure_no_debug_code                                          | 0           |
| 5    | ensure_no_debug_code                                          | 0           |
| 6    | ensure_no_debug_code                                          | 0           |
| 7    | ensure_no_debug_code                                          | 0           |
| 8    | ensure_no_debug_code                                          | 0           |
| 9    | rubocop                                                       | 1           |
| 10   | find -E . -regex ".*\.(sh|bash)" -not -name "Pods-*" -name ". | 0           |
| 11   | Switch to execute_tests lane                                  | 0           |
| 12   | Switch to local_version lane                                  | 0           |
| 13   | PAGER=cat bin/fastlane --help                                 | 0           |
| 14   | bundle check || bundle install                                | 0           |
| 15   | rake install                                                  | 15          |
| 16   | bundle exec rake test_all                                     | 201         |
| 17   | Switch to validate_docs lane                                  | 0           |
| 18   | git clone https://github.com/fastlane/docs --depth=1          | 13          |
| 19   | Switch to verify_docs lane                                    | 0           |
| 20   | git clone https://github.com/fastlane/docs --depth=1          | 20          |
| 21   | bundle install                                                | 0           |
| 22   | bundle exec fastlane test skip_building:true                  | 3           |
| 23   | Switch to ensure_tool_name_formatting lane                    | 0           |
| 24   | Switch to ensure_code_samples lane                            | 0           |
| 25   | test_sample_code                                              | 0           |
| 26   | Switch to ensure_code_snippets lane                           | 0           |
| 27   | Switch to ensure_actions_config_items_formatting lane         | 0           |
+------+---------------------------------------------------------------+-------------+

2018-08-14 05:53 UTC, sprabhuanand commented
I signed it!

2018-08-21 11:44 UTC, joshdholtz requested changes

2018-08-21 11:44 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> +                                       is_string: false,
Can we change this line to `type: Boolean` instead? 😊

2018-08-21 11:44 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> +                                       is_string: false,
And while you are in there, can you change the other `is_string: false` in the other two options to `type: Boolean` as well? 😊

2018-08-21 11:44 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> +                                       is_string: false,
`type: Boolean` is preferred so the `Fastlane.swift` knows what type of arguments are needed

2018-08-28 13:13 UTC, joshdholtz commented
@sprabhuanand Just wanted to ping you to see if you could make these changes? 😊

2018-09-04 14:35 UTC, prabhuanand commented
I signed it!

2018-09-19 10:25 UTC, joshdholtz approved these changes
Looks great! Thanks for making those changes 😊

2018-09-19 10:26 UTC, merged

2018-09-19 10:52 UTC, janpio commented
`master` is broken after this merged:

```
[10:27:05]: Found errors in the documentation, more information below
[10:27:05]: Error found in code sample:
push_to_git_remote # simple version. pushes "master" branch to "origin" remote
push_to_git_remote(
remote: "origin",         # optional, default: "origin"
local_branch: "develop",  # optional, aliased by "branch", default: "master"
remote_branch: "develop", # optional, default is set to local_branch
force: true,              # optional, default: false
force_with_lease: true,   # optional, default: false
tags: false               # optional, default: true
)
'force' value must be a Fastlane::Boolean! Found TrueClass instead.
```
https://circleci.com/gh/fastlane/fastlane/24028?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link