[snapshot] added check for missing Snapshot Helper File (#13038)
fastlane/fastlane pull request #13205
Opened 2018-08-24 04:44 UTC by JonnyBeeGod

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Fixes #13038 

### Description

Added check for missing Snapshot Helper File. If there is no Snapshot Helper File found, snapshots exists with a descriptive user error. 

I tested the fix via manually deleting the Snapshot Helper File from my project and running `fastlane snapshot` afterwards.

2018-08-24 04:46 UTC, JonnyBeeGod commented
I signed it!

2018-08-24 08:18 UTC, janpio commented
Awesome!

What is missing right now is some instruction on _how_ to do what is missing. The best source I could find was https://docs.fastlane.tools/actions/snapshot/#quick-start. Maybe add  that (or something better I missed) to the error message?

2018-08-24 16:48 UTC, JonnyBeeGod commented
You're right that's more user friendly. Hope the wording is ok

2018-08-24 17:11 UTC, janpio approved these changes
I like it! 🥇

2018-08-27 13:14 UTC, joshdholtz requested changes
Two small nitpicks just to keep some `UI` formatting consistent in this file 😊

2018-08-27 13:14 UTC, joshdholtz commented on snapshot/lib/snapshot/runner.rb
> +        UI.error("in your project directory.")
Can we remove the "." on this line?

2018-08-27 13:14 UTC, joshdholtz commented on snapshot/lib/snapshot/runner.rb
> +        UI.user_error!("Please add a Snapshot Helper file to your project.")
Can we also remove the "." on this line?

2018-08-27 16:35 UTC, JonnyBeeGod commented
Right 😁 Fixed it now

2018-08-28 12:13 UTC, joshdholtz approved these changes
Thanks for making those changes and thanks for the contribution! 💪 ❤️

2018-08-28 12:13 UTC, merged