Add swift-version to pod_lib_lint action
fastlane/fastlane pull request #13524
Opened 2018-10-12 03:33 UTC by bdrelling

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The `swift_version` parameter currently exists on the `pod_push` action but _not_ the `pod_lib_lint` action, meaning we're still required to have a `.swift-version` file in our repo to run this action. Adding the `--swift-version` flag to the `pod_lib_lint` action maintains consistency across these commands.

Source: https://guides.cocoapods.org/terminal/commands.html#pod_lib_lint

### Description
- Added `--swift-version` to `pod_lib_lint.rb`, exactly as it exists in `pod_push.rb`.
- Added `swift_version` parameter documentation to `pod_lib_lint.rb`, exactly as it exists in `pod_push.rb`.
- Added `--swift-version='4.2'` test to `pod_lib_lint_spec.rb`.

2018-10-12 03:34 UTC, bdrelling commented
I signed it!

2018-10-29 13:42 UTC, bdrelling commented
Is there something more that I should be doing with this?

2018-11-02 03:42 UTC, joshdholtz requested changes
One small request about changing `is_string` to `true` otherwise this is 👌

2018-11-02 03:42 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/pod_lib_lint.rb
> +                                       is_string: false),
```suggestion
                                       is_string: true),
```

Can we change this to `true`? The test shows a string and I think making this true is safe and makes sense 👌

2018-11-02 15:47 UTC, bdrelling commented
@joshdholtz Thanks Josh, got it. Should we grab this too? They should be identical I think. [pod_push.rb:L90](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/pod_push.rb#L90)

2018-11-06 00:02 UTC, joshdholtz commented
@bdrelling Ah yes! If you could to change that too that would be 💯

2018-11-06 00:14 UTC, bdrelling commented
@joshdholtz Done!

2018-11-06 01:56 UTC, joshdholtz commented
@bdrelling Looks like some tests are failing 😱 Do you mind changing this over to a string at https://github.com/fastlane/fastlane/blob/master/fastlane/spec/actions_specs/pod_push_spec.rb#L34? 😇

2018-11-06 02:01 UTC, bdrelling commented
@joshdholtz Sure thing, my bad!

2018-11-06 02:11 UTC, joshdholtz approved these changes
This looks great! Thanks for working with me on the review 😊 Merging this 💪

2018-11-06 02:11 UTC, merged