Receive SMS code for 2fa without the need to bypass trusted device
fastlane/fastlane pull request #13554
Opened 2018-10-17 20:05 UTC by mariannegru

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I've updated the documentation if necessary.

### Motivation and Context

With this changes we do not need for the step # Bypass trusted device and use SMS for verification from [2 Step Verification](https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification)

### Description

I added a method to show a selection of trusted phones to select from for sending the code required on the next step in 2fa login

Using an account with 2fa enabled I executed `fastlane spaceauth -u jabran56@hotmail.com` and I was prompted with a list of phones to select from. After selecting the phone number I received the expected cookie

2018-10-17 20:10 UTC, mariannegru commented
> I signed it!

I signed it!

2018-10-25 19:39 UTC, RishabhTayal requested changes

2018-10-25 19:39 UTC, RishabhTayal commented on spaceship/lib/spaceship/two_step_client.rb
> +      puts("Please select a phone to send code too:")
```suggestion
      puts("Please select a phone to send code to:")
```

2018-10-30 09:29 UTC, mariannegru commented
@RishabhTayal can you please accept cla?

2018-11-02 20:18 UTC, joshdholtz commented
@mariannegru Thanks for making this PR! I'm actually going to close this PR in favor of #13507 (which was made first). I appreciate the time put in to make this PR though ❤️

2019-01-20 21:40 UTC, janpio commented
PR #14011 has been merged and this will be included in the next release 👍 Thanks for you work on this @mariannegru!

2019-01-20 21:40 UTC, closed without merging