feat: add skip_git_hooks to git_commit action
fastlane/fastlane pull request #13686
Opened 2018-11-14 22:06 UTC by ossareh

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I've some git commit hooks setup on a repository that do some quite time intensive checks / tests - when using fastlane to manage my application deployments it's not necessary to run these checks when committing the version bump.

This came up as part of setting up an android release lane. The same issue with running git commits happens on my ios release lane, but I figured I'd submit this one first, and if the change is desirable then I can also implement a similar fix for the `increment_build_number` action.

### Description
Added a ConfigItem option to git_commit which takes a boolean, defaults to false, and appends '--no-verify' if the value is true.

To test the changes I wrote an rspec test case, which passes, as well as did a couple of android builds / deploys using my local fastlane fork.

2018-11-27 02:11 UTC, ossareh commented
@janpio what steps are required to have this PR reviewed? Is there anything I can do to move this forward? Thanks :)

2018-11-27 19:21 UTC, ossareh commented
My apologies, since you had adddd a label to this PR you seemed the most
reasonable person to @ about it.

On Tue, Nov 27, 2018 at 03:22 Jan Piotrowski <notifications@github.com>
wrote:

> Please don't mention people that were not involved in a discussion before.
>
> There is not really a way to speed up the reviewing of Pull Requests. If
> someone from the time has the time and motivation, they will do so.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/pull/13686#issuecomment-441986078>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAP3r5r63kITBuuaC6Gr1FatR-w3D4G5ks5uzQRVgaJpZM4YerGA>
> .
>

2019-01-16 22:41 UTC, joshdholtz requested changes
Hey @ossareh! Sorry about this one getting lost in the pile 😔 That was myb. This PR looks solid 👌 Just two lines that can be removed and one small fix and then this can get pushed out in today's release 👍

2019-01-16 22:41 UTC, joshdholtz commented on fastlane/spec/actions_specs/git_commit_spec.rb
> +        allow(FastlaneCore::FastlaneFolder).to receive(:skip_git_hooks).and_return(nil)
You can remove this line ^ `skip_git_hooks` doesn't get called on `FastlaneFolder` at all 👌

2019-01-16 22:41 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/git_commit.rb
> +                                       is_string: false,
You can also remove this line as `type: Boolean` takes precedence over `is_string` 😊 And `is_string` will soon be removed 💪

2019-01-16 22:41 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/git_commit.rb
> +        skip_git_hooks = params[:skip_git_hooks] ? '--no-verify' : nil
```suggestion
        skip_git_hooks = params[:skip_git_hooks] ? '--no-verify' : ''
```
Can we make this an empty string inside of nil?

2019-01-17 21:33 UTC, janpio commented
(Please feel free to report your local test failures in a new issue - always interesting what is breaking in local environments. Maybe we can do something about that 👍 )

2019-01-18 21:46 UTC, ossareh commented
@janpio I have opened #14101 with details.

2019-01-19 18:16 UTC, joshdholtz approved these changes
Perfect! Thanks for making those small nitpicks and thanks for the contribution! ❤️

2019-01-19 18:16 UTC, merged