[resign.sh] Fix icloud-container-environment value
fastlane/fastlane pull request #13767
Opened 2018-11-26 21:10 UTC by ryanprobus

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The `com.apple.developer.icloud-container-environment` entitlement was being incorrectly set to `development` when using app entitlements if passing in a SHA1 fingerprint as the `CERTIFICATE` parameter. 

Partially fixes this [issue](https://github.com/fastlane/fastlane/issues/13740) pertaining to entitlements when resigning.

### Description

When iterating over the entitlement transfer rules, there is a specific check for `com.apple.developer.icloud-container-environment`, within this check, I added a regex to check if `CERTIFICATE` matches a SHA1 fingerprint. If it does, I get the name of the identity by grepping `security find-identity`.

Stripped away all the resigning log

```CERTIFICATE="CERTIFICATE_VALUE_HERE"
SHA1_PATTERN='[0-9A-F]{5,40}'
if [[ "$CERTIFICATE" =~ $SHA1_PATTERN ]]; then
  FOUND_CERTIFICATES="$(security find-identity -v -p codesigning | grep "$CERTIFICATE")"
  echo $FOUND_CERTIFICATES
  if [ -n "$FOUND_CERTIFICATES" ]; then
    CERTIFICATE_NAME="$( echo $FOUND_CERTIFICATES | sed -E s/[^\"]+\"\([^\"]+\)\".*/\\1/g )"
    echo $CERTIFICATE_NAME
  fi
fi`

2018-11-26 21:53 UTC, lyndsey-ferguson commented on sigh/lib/assets/resign.sh
> +                local sha1_pattern='[0-9A-F]{5,40}'
this should be a straight 40

2018-11-26 21:55 UTC, lyndsey-ferguson requested changes
one change requested

2018-11-26 22:30 UTC, lyndsey-ferguson approved these changes
LGTM

2018-11-26 22:40 UTC, kpink224 reviewed
LG just some minor changes

2018-11-26 22:40 UTC, kpink224 commented on sigh/lib/assets/resign.sh
> +                    local certificate_matches="$( security find-identity -v -p codesigning | grep "$CERTIFICATE" )"
Let's do `grep -m 1 "$CERTIFICATE"` to ensure we only get one option. It will cause problems if we get multiple.

2018-11-26 22:40 UTC, kpink224 commented on sigh/lib/assets/resign.sh
> +                        certificate_name="$( sed -E s/[^\"]+\"\([^\"]+\)\".*/\\1/g <<< $certificate_matches )"
you don't need `g` at the end of sed

2018-11-27 17:00 UTC, kpink224 approved these changes

2019-01-16 23:22 UTC, joshdholtz requested changes
@ryanprobus Sorry about just getting to this! I will admin that I am not a `resign.sh` expert but this looks like a solid change so 🙌🙌 to you for making this 😊

One request I have is if you could add to the change log at the top of the file since that is kind of what has been happening - https://github.com/fastlane/fastlane/blob/b188b9d9c9a3a739e875312a58fb2c008b23cff6/sigh/lib/assets/resign.sh#L42-L66

Thanks!

2019-01-18 14:20 UTC, ryanprobus commented
@joshdholtz No problem, thanks for taking a look at this. A lot of people are afraid of `resigh.sh`, but its definitely something could use some loving. I added a note to the change log and squashed the commit.

2019-01-19 18:24 UTC, joshdholtz approved these changes
@ryanprobus Thanks for adding that note and giving `resign.sh` the love that it needs 😊 You are a true hero 🙌

2019-01-19 18:24 UTC, merged