[scan] Use slack action to post scan test results
fastlane/fastlane pull request #13791
Opened 2018-12-01 07:24 UTC by gligorkot

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Hi team, this is the PR that addresses my question in #13783 

I've implemented the change as I'd like to have more consistent Slack messages when running test builds between iOS and Android, so using the Slack Action keeps them the same across the board.

### Description
Excuse the `rubocop` fails, I'm not very proficient with ruby, this is my first go at it. I think there's a cyclic dependency cause I call `Firebase` from within the `SlackPoster` class

2018-12-01 17:42 UTC, janpio commented
```
scan/lib/scan/slack_poster.rb:41:7: C: Require/MissingRequireStatement: Fastlane::Actions::SlackAction not found, you're probably missing a require statement or there is a cycle in your dependencies.
      Fastlane::Actions::SlackAction.run({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Find another part of the codebase that also uses an internal action and see how that one is required to not trigger this error.

2018-12-02 20:57 UTC, gligorkot commented
Hi @janpio, thanks for getting back to me so quick. I'm looking for a similar use case, but haven't found one so far. All I can find using internal actions is using `require` but these are all in the `fastlane/actions` subdirectory. I haven't found an example of using an internal action from outside of this directory. Is what I'm trying to do a bad practice? Is there appetite from people for the change I'm proposing at all?

Thanks!

2018-12-02 21:15 UTC, gligorkot commented
Hi @janpio, thanks again for your comments and guidance on this one. I've managed to fix the issue I was facing, so now it's a question if whether or not there's appetite for my change. I made this change as I personally like having more consistent slack messages between my builds, so this made sense.

In addition to this, I was hoping to add another PR to enable people to change the name of the Slack message poster as well as the icon, similar to how this is done using the Slack Action, and this change makes it easy to do the above.

Looking forward to hearing your thoughts?

2018-12-18 14:38 UTC, janpio reviewed
Could you share before/after screenshots? I can't really test this, and it is a bit hard to visualize from the code alone ;)

Your follow up idea makes total sense. Customizing this sounds like a great idea so it becomes usable for more companies and teams.

2018-12-18 14:38 UTC, janpio commented on scan/lib/scan/slack_poster.rb
> -          color: results[:failures].to_i > 0 ? "danger" : "good",
Is this represented in the rewrite?

2018-12-18 14:38 UTC, janpio commented on scan/lib/scan/slack_poster.rb
> -          color: "good",
Is this represented in the rewrite?

2018-12-18 14:38 UTC, janpio commented on scan/lib/scan/slack_poster.rb
> -          color: "good"
Is this represented in the rewrite?

2018-12-18 14:38 UTC, janpio commented on scan/lib/scan/slack_poster.rb
> -        color: results[:build_errors].to_i > 0 ? "danger" : "good",
Is this represented in the rewrite?

2018-12-18 19:21 UTC, gligorkot commented
Hey @janpio, thanks so much for taking this into consideration. I do think it's a worthwhile change as it standardises the slack message output across the `scan` and `slack` actions. I have also seen some previous issues raised around git commits and branches being added as part of the slack custom message of the `scan` action, so this kind of extends that by default instead of users having to do it using the custom message parameter `slack_message`.

Here's a screenshot of the output before the change:
![screen shot 2018-12-19 at 8 16 04 am](https://user-images.githubusercontent.com/7002604/50177477-f4caf500-0366-11e9-9c6a-a926540e9a0d.png)

Here it is, after the change:
![screen shot 2018-12-19 at 8 17 10 am](https://user-images.githubusercontent.com/7002604/50177482-f7c5e580-0366-11e9-862c-f4c93ee4071c.png)

2019-01-16 16:29 UTC, joshdholtz requested changes
This is great! Just one small change on the removing the hardcoding of `username` and then we can ship this 🚀

2019-01-16 19:38 UTC, gligorkot commented on scan/lib/scan/slack_poster.rb
> +        username: 'fastlane',
Hi @joshdholtz thanks for the review! This used to be up the top (line 18) in the original code. I can remove if needed, let me know.

2019-01-16 19:38 UTC, gligorkot commented on scan/lib/scan/slack_poster.rb
> +        username: 'fastlane',
Actually thinking about it, the slack action has `username = 'fastlane'` as the default value, so this can be removed. Doing it now.

2019-01-16 19:53 UTC, gligorkot commented
@joshdholtz, I just removed the hardcoded username and the message in slack now comes from `incoming-webhook`, not the most descriptive name. As mentioned above in the review, this used to be hardcoded in line 18 of the original `slack_poster.rb` so I kept that intact, but can remove. Let me know how you'd prefer it and I'll update it if a change is needed.

2019-01-17 00:05 UTC, joshdholtz commented
@gligorkot Ahhhhh, good point good point 🤔 Removing that would actually be a breaking change but I just don't like it being hardcoded like that 😱 But I guessssssss we can leave this like how it is. We could introduce another parameter if somebody has an issue with it being "fastlane" sooooo... I think we are good here 👍

2019-01-17 00:06 UTC, joshdholtz approved these changes
This is a super solid change 🙌 Thanks for contributing ❤️

2019-01-17 00:06 UTC, merged

2019-01-17 00:10 UTC, gligorkot commented
> @gligorkot Ahhhhh, good point good point 🤔 Removing that would actually be a breaking change but I just don't like it being hardcoded like that 😱 But I guessssssss we can leave this like how it is. We could introduce another parameter if somebody has an issue with it being "fastlane" sooooo... I think we are good here 👍

Yeah, I agree. I was hoping to add another PR to enable people to change the name of the Slack message poster as well as the icon, similar to how this is done using the Slack Action, and this change makes it easy to do that! I'll get that done in the next couple of days.