Add human-readable storage identifier string to various match outputs
fastlane/fastlane pull request #13886
Opened 2018-12-11 18:29 UTC by KrauseFx

So beautiful, this will make it much easier for developers to understand what's going on

**Git**
![screen shot 2018-12-11 at 1 27 09 pm](https://user-images.githubusercontent.com/869950/49821517-a0ad8880-fd48-11e8-8ee7-f8030b68929a.png)

**Google Cloud**
![screen shot 2018-12-11 at 1 26 38 pm](https://user-images.githubusercontent.com/869950/49821545-adca7780-fd48-11e8-9254-b3c0f77db226.png)

![screen shot 2018-12-11 at 1 26 31 pm](https://user-images.githubusercontent.com/869950/49821519-a0ad8880-fd48-11e8-99b0-9f08a857f42b.png)

2018-12-11 19:53 UTC, snatchev requested changes

2018-12-11 19:53 UTC, snatchev commented on match/lib/match/storage/git_storage.rb
> +      def human_readble_description
typo `human_readable_description`

2018-12-12 17:04 UTC, KrauseFx commented
updaeted

2018-12-12 17:28 UTC, snatchev approved these changes

2018-12-12 17:49 UTC, merged

2018-12-12 18:00 UTC, KrauseFx commented
Actually that other spelling mistake was by mistake 😂