[Swift] Fix frameit's Boolean options are generated as String? instead of Bool?
fastlane/fastlane pull request #13880
Opened 2018-12-11 12:00 UTC by jhandguy

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

See issue: https://github.com/fastlane/fastlane/issues/13879

When the `frameScreenshot` action is generated from Ruby to Swift, its implicit `Optional Boolean` parameters are interpreted as `String?` (default fallback for non-explicit Ruby types).

See issue: https://github.com/fastlane/fastlane/issues/13879

### Description

Giving the `Options Config type` explicitly allows the `generate_swift_api` action to detect the type.

### Discussion

Why are these Options `Optional` at the first place?
Could we simply have them required with a `default_value` of `false`?

2018-12-11 12:49 UTC, joshdholtz requested changes
These changes will work but if you could also remove the `is_string` that would be 💯  as that's not needed!

I actually have a PR that I'm working on that is removing the `is_string` from all options completely so this shouldn't be an issue for any tool/action in the future - https://github.com/fastlane/fastlane/pull/13816

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
You can remove this `is_string` 😊

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
And this one

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
And this one

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
And this one

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
And this one

2018-12-11 12:49 UTC, joshdholtz commented on frameit/lib/frameit/options.rb
> +                                     is_string: false,
And this one

2018-12-11 13:34 UTC, jhandguy commented
Done @joshdholtz ✅

How about having `default_value: false` instead of `optional: true`?
Would it break something?

2018-12-11 14:32 UTC, joshdholtz commented
@jhandguy That one is a little more difficult to answer 😇 Setting a `default: false` will never instead of `optional: true` _should_ be fine in _most_ cases but there are some instances where the code will actually check for a `nil` which won’t over happen if that `optional: true` is set. I don’t know if this is the case for anything in _frameit_ but it requires a deeper inspection of the underlying code 😬

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-12-11 14:42 UTC, jhandguy commented
@joshdholtz got ya, let's leave it as it is then! 😊

2018-12-12 16:11 UTC, jhandguy commented
@joshdholtz did you have time to take a look?

2018-12-12 20:17 UTC, joshdholtz approved these changes
🙌

2018-12-12 20:17 UTC, merged