[scan] Customizing the slack post action with custom username and icon/image
fastlane/fastlane pull request #14072
Opened 2019-01-17 03:27 UTC by gligorkot

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
As discussed with @joshdholtz in #13791, we agreed that hardcoding the username for the slack post is not great, same goes with the icon url I believe. This PR adds the ability for users to customize the username and icon/image for the slack webhook, or users can choose to use the webhook configured ones.

### Description
The `slack_username`, `slack_icon_url` and `slack_use_webhook_configured_username_and_icon` mirror the same parameters from the `slack` action, however with `slack_` prefix as these are specifically used for posting the slack message.

One thing I've had to disable is `# rubocop:disable Metrics/ClassLength` inside the Scan/Options class as this has become too big now. I did see that we do that elsewhere (ie. Deliver/Options class) so I took the liberty of disabling/enabling this, but let me know if you'd like me to change this.

2019-01-17 05:00 UTC, joshdholtz requested changes
One small change with getting rid of `is_string: false` and replacing with `type: Boolean` otherwise 🔥

2019-01-17 19:20 UTC, gligorkot commented on scan/lib/scan/options.rb
> +                                     is_string: false,
Perfect!

2019-01-17 19:38 UTC, gligorkot commented
@joshdholtz, does the fastlane docs get updated automatically for the new `options` added for the action, or do I need to raise a PR in the Docs repo as well?

2019-01-20 17:16 UTC, joshdholtz commented
@gligorkot Yup, they will update automatically when we cut a new release 💪

2019-01-20 19:20 UTC, joshdholtz approved these changes
This looks great! Thanks again for making another PR ❤️

2019-01-20 19:20 UTC, merged