[produce,deliver,spaceship] Support for new AppStore Connect languages: Catalan, Croatian, Czech, Hindi, Hungarian, Polish, Romanian, Slovak, and Ukrainian
fastlane/fastlane pull request #14110
Opened 2019-01-21 10:21 UTC by Zymantas

* New languages:
	Catalan, Croatian, Czech, Hindi, Hungarian, Polish, Romanian, Slovak, and Ukrainian

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

New App Store Connect languages were added some time ago and fastlane doesn't support them yet.

### Description

Added new language constants and language mappings

---
close #13938

2019-01-21 13:39 UTC, janpio commented
Awesome @Zymantas! Where did you get/extract the language codes to add to your files? Anything else worth writing down for future updates of these files?

2019-01-21 14:21 UTC, Zymantas commented
I've taken language codes from the Xcode project localisations (where you add/remove translated languages of your app) and put them here. As I hoped, it worked on both platforms - iOS and macOS! :)

I didn't find anything that's missing with these new languages, but I'll be retesting again when real-world translations will be ready (sometime next week as our translators promised). I'll let you know if this won't be merged till then.

2019-01-23 05:01 UTC, joshdholtz requested changes
One small change request! I think 😇

2019-01-23 05:01 UTC, joshdholtz commented on spaceship/lib/assets/languageMapping.json
> +        "itc_locale": "cz"
Should this be `cs`? 🤔

2019-01-23 05:02 UTC, joshdholtz commented
@janpio This can also be achieve by running `Spaceship::Tunes.client.available_languages.sort` (for getting the language codes at least) 💪 🚀

2019-01-23 07:55 UTC, Zymantas commented on spaceship/lib/assets/languageMapping.json
> +        "itc_locale": "cz"
Ahhhh, you're correct.

2019-01-24 15:11 UTC, janpio commented
Do we maybe also want to add comments that "interlink" these 3 files/locations? Because if you update one of them, you should always update the others, correct? Can we also add some information in a comment where the other data comes from?

2019-01-24 15:12 UTC, joshdholtz commented
Aye aye! Can do can do 💪

2019-01-25 04:52 UTC, joshdholtz commented
@janpio Updated with more info and link to this PR as an example 😊

2019-01-25 10:58 UTC, janpio commented
Ok, I fixed the comment a bit and added a similar one to the second file.

What about the JSON - we can't just add a comment there :/ What do we do there?

But ohoh, I found another one: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/assets/languageMappingReadable.json

2019-01-31 06:10 UTC, joshdholtz commented
@janpio I did some searching through there and it doens't look like https://github.com/fastlane/fastlane/blob/master/spaceship/lib/assets/languageMappingReadable.json actually gets used anywhere. There are two methods that reference it (`from_itc_readable_to_itc` and `from_itc_to_itc_readable`) but these actually don't get referenced anywhere either. I think its okay to not edit this language file and probably also okay to remove that file and those methods in a future PR? 🤔

Also going to ping @KrauseFx since he add this file back in 2015 😉 - https://github.com/fastlane-old/spaceship/commit/dd510037d377bff7efa9b8b5b7d3f5bc44f88672#diff-355ef28abf38992915b1a2e1724703eb

2019-01-31 14:36 UTC, janpio commented
Deleteable code is best code ❌ 💀

2019-02-12 16:19 UTC, joshdholtz approved these changes

2019-02-12 16:19 UTC, joshdholtz commented
Let's ship this 💪

2019-02-12 16:19 UTC, merged

2019-02-14 12:44 UTC, max-ott commented on spaceship/lib/assets/languageMapping.json
> +        "name": "Romanian",
@joshdholtz This should be `Slovak`

2019-02-14 13:43 UTC, janpio commented
Ohoh. Can you please create another PR? Thanks.

2019-02-14 13:46 UTC, Zymantas commented
Ohhh :(. Since this is my PR, I'll create new one with a fix.