[supply] Checking for interactive mode before user's input when creating from config
fastlane/fastlane pull request #14160
Opened 2019-01-29 17:53 UTC by juanimoli

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
These changes are being made to fix [#14128](https://github.com/fastlane/fastlane/issues/14128). This issue is an unexpected behaviour in CI with supply action.

### Description
When any `AbstractGoogleServiceClient` is being created from configuration, it searches for authentication parameters for authenticating with Google. I've moved this logic to an independent method, which can be overloaded from any of its child. 

`PlaycustomappClient` will still be using just the non deprecated way, so if you don't provide 'json_key' or 'json_key_data' params using `CreateAppOnManagedPlayStoreAction`, Fastlane will crash, as specified in [this PR](https://github.com/fastlane/fastlane/pull/13431). 

In the other hand, the old `Client` will still support both of the authentication types, but printing an important message on UI, making an advice on using the JSON files.

The issue was fixed by wrapping the input line into a condition, which asks whether the UI is interactive or not. If this checks fails, Fastlane will crash.

Existing tests were fixed in order to make them work with these changes, and also added a new case into the "without :json_key or :json_key_data" set.

2019-01-29 17:54 UTC, juanimoli commented
I signed it!

2019-02-04 23:23 UTC, joshdholtz requested changes
Left a few small questions about this refactor! Thanks for taking the time to do this and answer my questions 😊

2019-02-04 23:39 UTC, juanimoli commented on supply/lib/supply/client.rb
> +      end
@joshdholtz gonna do the cleanup. Regarding to the question, yes, somehow supply is being called with no initialized config (happened me in tests). Also this initialization was before in `Client.make_from_config`, which most of this logic came from.

2019-02-04 23:41 UTC, juanimoli commented on supply/lib/supply/client.rb
> +      kei_io = service_account_authentication(params: params)
@joshdholtz this was the old name for the extracted key data file. Maybe it can be changed to `service_account_data`?

2019-02-04 23:43 UTC, juanimoli commented on supply/lib/supply/client.rb
> +        if params[:key] && params[:issuer]
@joshdholtz good advice, gonna change that

2019-02-05 00:43 UTC, juanimoli commented on supply/lib/supply/client.rb
> +          UI.user_error!("Could not load authentication file. Make sure it has been added as an enviroment variable as 'json_key' or 'json_key_data' for raw data")
@joshdholtz it appears that the suggested change feature from Github changed CLA status leaving it in an inconsistent state :( Is there anything I can do to fix this?

2019-02-05 20:03 UTC, juanimoli commented
@joshdholtz it appears that the suggested change feature from Github changed CLA status leaving it in an inconsistent state :( Is there anything I can do to fix this?

2019-02-11 04:43 UTC, joshdholtz requested changes
It looks like I actually got an error while running `supply` with this 🤔 Below is one of my test lanes for Android that I usually use that now fails:

```ruby
  lane :release do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    mapping_path = File.absolute_path "../app/build/outputs/mapping/release/mapping.txt"
    supply(
      timeout: 900,
      apk: apk_path,
      mapping: mapping_path,
      package_name: 'example.screengrab.fastlane.tools.fastlanescreengrabexample',
      # track: 'Cute',
      track: 'alpha',
      # track: 'internal',
      #track: 'beta',
      # track: 'production',
      # track: 'rollout',
      # rollout: "0.5",
      skip_upload_aab: true,
      skip_upload_apk: false,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key: './fastlane/google_play2.json',
      check_superseded_tracks: false,
      version_codes_to_retain: [83]
      # validate_only: false
    )
  end
```

```sh
ArgumentError: [!] wrong number of arguments (given 1, expected 0)
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/client.rb:22:in `service_account_authentication'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/client.rb:102:in `service_account_authentication'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/client.rb:17:in `make_from_config'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/uploader.rb:262:in `client'
  /Users/josh/Projects/fastlane/fastlane/supply/lib/supply/uploader.rb:6:in `perform_upload'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:106:in `block (2 levels) in parsing_binding'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/josh/Projects/fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/josh/.gem/ruby/2.3.7/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/josh/Projects/fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
  /Users/josh/Projects/fastlane/fastlane/bin/fastlane:23:in `<top (required)>'
  /Users/josh/.gem/ruby/2.3.7/bin/fastlane:22:in `load'
  /Users/josh/.gem/ruby/2.3.7/bin/fastlane:22:in `<top (required)>'
```

2019-02-12 15:09 UTC, juanimoli commented
@joshdholtz fixed :D

2019-02-13 01:29 UTC, juanimoli commented
@joshdholtz I was missing the param name in super(...) call. Made some tests with your setup and it looks fine. Should be ready to go!

2019-02-19 04:44 UTC, joshdholtz approved these changes
This looks good! Thanks for making that fix 👍

2019-02-19 04:44 UTC, merged