added Appcenter plugin link to use instead of hockeyApp
fastlane/fastlane pull request #14325
Opened 2019-02-28 05:22 UTC by ksairi

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The change is required because is mentioning to use `hockeyApp`, which is obsolete, as an option to submit beta versions.
A note is added to refer to an `Appcenter` plugin instead

### Description

Added `Appcenter` link to refer to instead of HockeyApp
Tested my changes with the steps described in `Checklist`

2019-02-28 05:43 UTC, ksairi commented
I signed it!

El jue., 28 feb. 2019 a las 18:23, googlebot (<notifications@github.com>)
escribió:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project (if not, look below for help).
> Before we can look at your pull request, you'll need to sign a Contributor
> License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed (or fixed any issues), please reply here (e.g. I
> signed it!) and we'll verify it.
> ------------------------------
> What to do if you already signed the CLA Individual signers
>
>    - It's possible we don't have your GitHub username or you're using a
>    different email address on your commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>
> Corporate signers
>
>    - Your company has a Point of Contact who decides which employees are
>    authorized to participate. Ask your POC to be added to the group of
>    authorized contributors. If you don't know who your Point of Contact is,
>    direct the Google project maintainer to go/cla#troubleshoot (Public
>    version <https://opensource.google.com/docs/cla/#troubleshoot>).
>    - The email used to register you as an authorized contributor must be
>    the email used for the Git commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - The email used to register you as an authorized contributor must
>    also be attached to your GitHub account
>    <https://github.com/settings/emails>.
>
> ℹ️ *Googlers: Go here
> <https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ffastlane%2Ffastlane%2Fpull%2F14325>
> for more info*.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/pull/14325#issuecomment-468141986>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAkXgYbngLqIZxAnTy4sD9kGw2Pat08Kks5vR2e5gaJpZM4bWCRE>
> .
>

2019-03-01 12:12 UTC, janpio requested changes
We will have to properly deprecate the hockeyapp action and route people to the replacement plugin.

Is there a public timeline when stuff will stop working?

2019-03-03 21:54 UTC, joshdholtz commented
@ksairi Thanks for making this change! Can you check the "Allow edits from maintainers" button on this pull request so that I can add a few things on top of this change as well? https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks! ❤️

2019-03-03 21:55 UTC, joshdholtz requested changes
@ksairi I’m going to add a few commits to this PR to improve the deprecation message so that it stands out a bit more but thanks for starting this one!! ❤️

2019-03-10 21:21 UTC, joshdholtz commented
![3D18ADA1-5C6E-40EE-A489-373090985CFC](https://user-images.githubusercontent.com/401294/54091652-7fad0180-4350-11e9-9466-23e6150fc636.jpeg)
![7EADD2AC-D42A-414C-91A3-95A5FB6B65C9](https://user-images.githubusercontent.com/401294/54091653-80459800-4350-11e9-9bb9-c1b9130f7373.jpeg)
![81E7BA5A-4F21-405F-BA54-0398098C822A](https://user-images.githubusercontent.com/401294/54091654-80459800-4350-11e9-9a2e-06418747331a.jpeg)

2019-03-10 21:26 UTC, joshdholtz approved these changes

2019-03-10 21:27 UTC, merged

2019-03-14 16:35 UTC, janpio commented
Great changes @joshdholtz! And thanks again @ksairi for taking the initiative on this one.

2019-03-14 16:55 UTC, ksairi commented
@janpio pleasure!