[action] Add optional argument to filter git commits for changelog
fastlane/fastlane pull request #14441
Opened 2019-03-20 21:21 UTC by rukano

Added an optional argument `matching_pattern` to the `git_log_between` and `git_log_last_commits` actions. It injects the pattern to the `git log` command for the `grep` argument.

Added documentation and sample code.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
In some projects, might be needed to create release notes and Changelog entries from the commits, but only merge commits into a specific branch (e.g. `develop`). This feature will also  provide more flexibility to the users to choose their own commit naming schema to bypass or filter irrelevant commits for the release notes.

#14404 

### Description
The action `changelog_from_git_commits` provides some useful parameters already, but a `git log` parameter `--grep=""` is not implemented. Providing a parameter to pass to this function (e.g. `matching_pattern`) will allow the users to have more flexibility when generating their Changelogs.

Code examples:

In both functions `Actions.git_log_between` and `Actions.git_log_last_commits` an extra parameter will be added:

```ruby
def self.git_log_between(pretty_format, from, to, matching_pattern, merge_commit_filtering, date_format = nil, ancestry_path)
def self.git_log_last_commits(pretty_format, commit_count, matching_pattern, merge_commit_filtering, date_format = nil, ancestry_path)
```

In the function body, if the parameter exists, will be added as a `--grep=""` parameter to `git log`. Example:

```ruby
      command << "--grep=\"#{matching_pattern}\"" if matching_pattern
```

Since the parameter will be optional, if won't break the existing functionality.

I've been using the workaround for a while, and tested it on my local fork, from where I am creating this PR.

2019-03-24 22:30 UTC, joshdholtz requested changes, later dismissed
@rukano Thanks for this contribution! I would be 🔥 if we could add some tests here before we merge this. I tried to push a commit to your PR with a test but it doesn't look like I was given the ability to do that. So, can you add this test for this in `fastlane/spec/actions_specs/changelog_from_git_commits_spec.rb`...

```rb
       it "Uses grep matching pattern if requested" do
         matching_pattern = 'pizza'
         result = Fastlane::FastFile.new.parse("lane :test do
           changelog_from_git_commits(matching_pattern: '#{matching_pattern}')
         end").runner.execute(:test)

         inner_command = "git describe --tags `git rev-list --tags --max-count=1`"
         pseudocommand = "git log --pretty=\"%B\" --grep=\"#{matching_pattern}\" #{inner_command.shellescape}...HEAD"
         expect(result).to eq(pseudocommand)
       end
```

2019-03-25 00:11 UTC, rukano commented
@joshdholtz thanks, you are right. I pushed the test case you suggested. Thanks for reviewing and let me know if you want access to the branch, or if I should add something else. Cheers!

2019-04-01 02:52 UTC, joshdholtz commented
@rukano Ahhh, it looks like we have a merge conflict here! If you want to give me permission (and other contributors write access to your branch that would be 💯) and I can fix this for you if you don't want to 🙃

https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2019-04-01 11:24 UTC, rukano commented
Hi @joshdholtz 
I have mantainer edits activated actually, you should be able to make the changes. If it doesn't work, I can try to solve the conflicts and push again, if necessary. Or is there another way to give you access?
<img width="239" alt="Screenshot 2019-04-01 at 13 22 40" src="https://user-images.githubusercontent.com/97139/55324089-567c1e80-5481-11e9-8584-54dd4dec53cb.png">

2021-11-22 13:05 UTC, ahti commented
Is there anything preventing this from being merged? This functionality would come in very handy.

2022-06-15 09:58 UTC, lukebrandonfarrell commented
Why didn't this get merged?

2023-08-24 13:46 UTC, pzmudzinski commented
Any chance for a merge? That we could extract commits including ticket numbers from JIRA instead all of them.

2026-08-15 18:36 UTC, iBotPeaches approved these changes
tested locally. Works

2026-08-15 18:56 UTC, merged