Add double quotes to path in StringParser.encoding_type
fastlane/fastlane pull request #14452
Opened 2019-03-22 11:49 UTC by kacperd

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
It fixes #14451

### Description
I added double quotes in StringParser.encoding_type to enable proper encoding detection from files which contain spaces in their file paths.

2019-03-22 11:51 UTC, kacperd commented
I signed it!

2019-03-22 14:35 UTC, janpio commented on frameit/lib/frameit/strings_parser.rb
> +      `file --mime-encoding "#{path}"`.downcase
A better way to achieve this in a cross platform way would be to use `.shellescape` on the string: http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html#method-c-shellescape This is also how the rest of fastlane makes path shell safe.

2019-03-22 14:36 UTC, janpio requested changes
Let's use `.shellescape`

2019-03-24 23:30 UTC, joshdholtz approved these changes
@kacperd Thanks for finding this! ❤️

2019-03-24 23:30 UTC, merged