[download_dsyms] Fix wait for dSYM file to appear on App Store Connect
fastlane/fastlane pull request #15049
Opened 2019-07-19 10:48 UTC by jhandguy

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When running action `download_dsyms` right after action `upload_to_testflight`, the dSYMs are not yet compiled and `download_dsyms` throws:
`No dSYM files found on App Store Connect - this usually happens when no recompiling has happened yet`

Full logs:
```
[09:52:32]: Successfully finished processing the build 1.0.0 - 2647 for IOS
[09:52:34]: Successfully set the changelog for build
[09:52:34]: Distributing new build to testers: 1.0.0 - 2647
[09:52:34]: Successfully distributed build to Internal testers 🚀
[09:52:34]: ----------------------------
[09:52:34]: --- Step: download_dsyms ---
[09:52:34]: ----------------------------
[09:52:34]: Login to App Store Connect (*******@*****.**)
[09:52:35]: Login successful
[09:52:35]: Looking for dSYM files for '***.****.*****.*****' on platform ios v1.0.0 (2647)
[09:52:42]: No dSYM URL for 2647 (1.0.0)
[09:52:42]: No dSYM files found on App Store Connect - this usually happens when no recompiling has happened yet
[09:52:42]: -------------------------------------------
[09:52:42]: --- Step: upload_symbols_to_crashlytics ---
[09:52:42]: -------------------------------------------
[09:52:42]: Error setting value 'build/***.****.*****.*****-1.0.0-2647.dSYM.zip' for option 'dsym_path'
[09:52:42]: You passed invalid parameters to 'upload_symbols_to_crashlytics'.
[09:52:42]: Check out the error below and available options by running `fastlane action upload_symbols_to_crashlytics`
```

Related PR: https://github.com/fastlane/fastlane/pull/14137
Related issue: https://github.com/fastlane/fastlane/issues/14393

### Description

Same logic as `wait_for_build`, simply sleep for 30 seconds and try again, with a timeout of 5 minutes.

2019-07-19 11:19 UTC, jhandguy commented
I have tested the change locally, with 3 different scenarios:
1. The dSYMs are already there -> no waiting time, success.
2. The dSYMs are not yet there -> waits about a minute (2 times 30 seconds), success.
3. The dSYMs are not there (i.e. wrong build number) -> no waiting time, failure.

I can provide the logs if needed.

2019-07-22 06:21 UTC, joshdholtz requested changes
Thanks for taking the time to make this change 😊 I think my biggest concern here is that this could introduce a good amount of time to the process for builds that don't actually have dsym attached to them for whatever reason. I think we _may_ need to add an option around this called something like `wait_for_dsym_processing`? Thoughts about this 🤔

2019-07-22 07:30 UTC, jhandguy commented on fastlane/lib/fastlane/actions/download_dsyms.rb
> +              unless download_url
You are right, I was not aware of this issue, let's have the user decide then! 👌 
I'll make those changes soon 👍

2019-07-22 14:44 UTC, jhandguy commented
Here are some logs:
```
[...]
DEBUG [2019-07-22 16:37:58.41]: Found build version: 2651 , comparing to supplied build_number: 2651
DEBUG [2019-07-22 16:37:58.41]: Build_version: 2651 matches 2651, grabbing dsym_url
DEBUG [2019-07-22 16:38:01.39]: dsym_url: 
INFO [2019-07-22 16:38:01.39]: Waiting for dSYM file to appear...
DEBUG [2019-07-22 16:38:33.34]: dsym_url: http://iosapps.itunes.apple.com/itunes-assets/*****
INFO [2019-07-22 16:38:35.63]: 🔑  Successfully downloaded dSYM file for 1.0.0 - 2651 to 'build/*********.***.***-1.0.0-2651.dSYM.zip'
[...]
```

2019-07-22 14:45 UTC, jhandguy commented
I have a question @joshdholtz, are you running `bundle exec fastlane generate_swift_api` before releasing?
So I don't need to update the Swift files, right?

2019-07-22 15:23 UTC, joshdholtz commented
@jhandguy Nope nope, the swift generation is handled during our release process 💪 Thanks for asking though!

2019-07-22 16:24 UTC, joshdholtz requested changes
One more small thing otherwise this looks 💯

2019-07-23 08:18 UTC, jhandguy commented on fastlane/lib/fastlane/actions/download_dsyms.rb
> +                                       is_string: false)
Done! ✅

2019-07-25 09:18 UTC, jhandguy commented
@joshdholtz anything else I might have missed?

2019-08-12 14:34 UTC, radko93 commented
Waiting for this one!

2019-08-20 09:40 UTC, jhandguy commented
@joshdholtz I just rebased my branch along with your requested changes, can you have a last look? 👀

2019-08-23 13:17 UTC, joshdholtz approved these changes
This is 🏀er! Thanks for adding this 😊

2019-08-23 13:17 UTC, merged

2019-09-02 06:26 UTC, cheif commented
Hi!
We've just updated fastlane to 2.130.0 and this seems to break our build, the underlying cause is that we have builds where the dsyms can't be downloaded from appstoreconnect, i.e. the download_url is empty.

Earlier this was handled without erroring out: https://github.com/fastlane/fastlane/commit/06217dabe89372bce03b9de268297689198f5758#diff-65dfcad8f098c3c96688110dade15ed7L102 but now this results in an error instead.

I'm not sure if this is something that should be solved with another flag (fail_build_on_missing_dsym?) or if this was an unintentional side effect of this PR.

It would of course be preferable to fix this at the appstoreconnect side, but I doubt that'll be an easy fix.

2019-09-02 09:27 UTC, jhandguy commented
Hey @cheif! 
Have you tried using the `wait_for_dsym_processing` flag?

2019-09-02 09:30 UTC, jhandguy commented
If so I’m sure we can simply replace the Error with a Warning instead 👍

Then I’m curious why aren’t your builds having any dSYM 🤔

2019-09-02 11:12 UTC, cheif commented
@jhandguy the build missing dSYMs is an old one (from March 2019), so unfortunately they won't be coming in anytime soon. We're running a nightly job that fetches all dsyms and then uploads them to crashlytics, just because there was no `wait_for_dsym_processing` earlier, so we could possibly go down that route now instead.

Yeah, I'm also curious about why the dSYM is missing, but I guess we'll never know due to apple ;)

2019-09-02 13:11 UTC, jhandguy commented
Yeah I suggest you guys try using `wait_for_dsym_processing`, maybe you could even get rid of your nightly job then! 🚀 

Otherwise, I still pushed a PR to prevent this action from failing your builds, let's see if that is something we want or not @joshdholtz 👍