Update Fastlane.swift
fastlane/fastlane pull request #15105
Opened 2019-07-29 08:48 UTC by philCc

[swift] fixed changelogFromGitCommits between

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

https://github.com/fastlane/fastlane/issues/15104#issue-473914348

### Description

```swift
changelog = changelogFromGitCommits(
	between: ["\(commit_id)", "HEAD"]
)
```

2019-07-29 09:05 UTC, janpio requested changes
As far as I know this file is generated from the ruby code - so we would have to change the ruby side so that the generator knows how to generate this properly.

2019-07-29 09:20 UTC, philCc commented
ok

2019-08-12 11:25 UTC, joshdholtz requested changes
@philCc The Swift interface is generated from options defined in the action (so [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L78-L92)) so the properly place for this change would be to change the `type` of the option for how the Swift interface is generated.

This _does_ have an `is_string` type of `false` so (https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L82) so IMO the Swift interface should actually be `between: Any? = nil` 🤔 I'm not sure why its being generated as a `String?` in this case.

The reason this needs to be `Any?` is for backwards comparability since you can see [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb#L84-L91) there is logic for taking a string or an array

I'm going to look into why this is generating as a `String?` and not `Any?`

2019-08-12 11:52 UTC, philCc commented
May be?
Between configuration used commit_count: line:83
Commit_count used between line:98

2019-08-13 10:13 UTC, joshdholtz commented
Closing this in favor of #15165 (which fixes `is_string: false`) for a bunch of actions. 

@philCc Allowing support for plugins is 100% in the plans in the near future 😊

2019-08-13 10:13 UTC, closed without merging