For #14897: Update Screengrab to AndroidX
fastlane/fastlane pull request #15217
Opened 2019-08-22 21:43 UTC by colintheshots

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Android Gradle Plugin 3.5.0 UI tests now require AndroidX dependencies. These conflict with the Screengrab uiautomator dependency in a way that makes it impossible for them to co-exist. See #14897.

https://github.com/fastlane/fastlane/issues/14897

### Description

I upgraded both the Screengrab library and the example to work with the latest Android APIs and AndroidX libraries.

I verified that the code builds.

### Testing Steps

2019-08-23 07:01 UTC, janpio commented
Context: "APIs 8 to 17" means Android 3.x to 4.2

2019-08-23 15:42 UTC, colintheshots commented
I hate to be *that* guy, but our UI tests were broken by this issue. If we downgrade Android Gradle Plugin, we lose important performance benefits from the new R8. How likely can we get a new version of Screengrab built to fix this in the next week or so?

2019-08-23 16:52 UTC, janpio commented
My personal problem with AndroidX is that I don't understand the backwards compatibility story. If we decide to merge this, we basically break Screengrab for everyone testing Android <= 4.2, correct?

2019-08-23 17:59 UTC, colintheshots commented
I think the solution is to add a note that apps supporting screengrabs before 4.3 need to use library version `1.2.0`.

The issue isn't just a few fringe apps using AndroidX test dependencies anymore. As of the new Android Studio stable version, the current version of Screengrab will break for nearly everyone.

2019-08-25 16:14 UTC, janpio commented
That sounds viable.

I guess this PR then should also update https://github.com/fastlane/fastlane/blob/master/screengrab/version.properties. Would something like this be considered a breaking/major change in Android land and justify a `2.0.0` then?

Documentation for `screengrab` lives in https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/capture_android_screenshots.md. The comment to use `1.x` would probably be best placed at https://docs.fastlane.tools/actions/screengrab/#gradle-dependency, and maybe an additional headline below https://docs.fastlane.tools/actions/screengrab/#improved-screenshot-capture-with-falcon?

2019-08-25 17:17 UTC, colintheshots commented
I think this justifies a 2.0.0.

I updated the documentation. Would it make more sense to switch the default strategy to UIAutomator or to Falcon? I just updated the docs to UI Automator, since it's Google-supported and API 18 will definitely be an option for all users of 2.0.0. However, the docs seem to indicate Falcon might be better?

2019-08-25 20:11 UTC, janpio commented
Thanks!

I don't know re UIAutomator/Falcon. Ping @joshdholtz, you seem to have written the docs on that.

I would be good merging with default UIAutomator.

2019-08-29 16:18 UTC, colintheshots commented
I think we can review the code as it stands. If default UIAutomator isn't ideal, we'll hear about it.

2019-09-03 12:03 UTC, cboisen requested changes
The [documentation](https://docs.fastlane.tools/actions/screengrab/) states that the argument `test_instrumentation_runner` has a default of `android.support.test.runner.AndroidJUnitRunner`. 

That should be updated to `androidx.test.runner.AndroidJUnitRunner`, right?

2019-09-03 20:03 UTC, colintheshots commented
> The [documentation](https://docs.fastlane.tools/actions/screengrab/) states that the argument `test_instrumentation_runner` has a default of `android.support.test.runner.AndroidJUnitRunner`.
> 
> That should be updated to `androidx.test.runner.AndroidJUnitRunner`, right?

This was updated by the PR in the example. The PR is not landed yet, however. Until it is, you won't see that change.

2019-09-16 19:04 UTC, colintheshots commented
Could anyone give this a needed review please?

2019-09-17 08:13 UTC, VitaminPSG approved these changes

2019-09-17 08:15 UTC, VitaminPSG commented
Can some one have a look to this MR, AndroidX was add year ago, but still no possibility to use with fastlane.

2019-09-17 09:29 UTC, cboisen requested changes
I think the minSdk means that there's obsolete code in a couple of places. I sent a screenshot showing the lint report I get.

Also: I have some issues getting the example project tests to compile, so I cannot verify that it still works. Probably just me not knowing what to do to get it running :man_shrugging:

2019-09-17 09:43 UTC, hauthorn commented on screengrab/screengrab-lib/build.gradle
> +        minSdkVersion 18
@colintheshots I think it's worth spending the time to simplify the statements and remove the obsolete code as a result of it.

2019-09-19 00:53 UTC, colintheshots commented
@hauthorn I made the changes, pushed, and rebased.

2019-09-19 00:53 UTC, colintheshots commented on screengrab/screengrab-lib/build.gradle
> +        minSdkVersion 18
Done

2019-09-19 01:23 UTC, colintheshots commented
Okay, now the tests are also fixed. Updating Falcon seems to have fixed the reflection-based code.

2019-09-19 07:58 UTC, cboisen approved these changes
It seems like it's good to go now. Good job :+1: :clap:

2019-09-20 15:20 UTC, colintheshots commented
@janpio Could we now get this merged? Thanks!

2019-09-25 15:34 UTC, colintheshots commented
@janpio Friendly reminder. This PR just requires a merge. It has two approvals now.

2019-09-25 16:08 UTC, janpio commented
Yes, none of those are from team members of the fastlane team. I know this is not the answer you want to hear here, but it's the only one I can currently give you - sorry. I will try to get to this asap - but no ETA.

2019-09-26 13:50 UTC, hauthorn commented
@janpio That's cool. The CI doesn't really run any of the screengrab-related code, so it also meant that I/we had to guess how to verify that the changes work as intended.

2019-10-15 18:21 UTC, colintheshots commented
It's been about a month since the code revisions were finished. Could someone please review? We'd like to use this library for several projects.

2019-10-23 10:14 UTC, isabelrios commented
Hello @janpio @hauthorn, wondering if you have any updates about this PR and its testing. It has been almost one month and we are blocked on getting this library working for several projects as @colintheshots mentioned. Any idea when/if this could be merged? 

Thanks!

2019-10-23 13:59 UTC, hauthorn commented
@isabelrios please refer to the [comment](https://github.com/fastlane/fastlane/pull/15217#issuecomment-535095483) @janpio made above. I'm not a member of the fastlane core team, so I'm not in a position to help you.

2019-10-31 18:15 UTC, rpappalax commented
> Yes, none of those are from team members of the fastlane team. I know this is not the answer you want to hear here, but it's the only one I can currently give you - sorry. I will try to get to this asap (Actually test it myself) - but no ETA.

Thanks @janpio.  Do you by chance know whom on the fastlane team we might reach out to for final approval?  this is a big blocker for us and we just want to do all we can

2019-11-02 15:52 UTC, colintheshots commented
@joshdholtz Could you please recommend anyone to do an Android PR review here? A lot of Android projects cannot take screengrabs right now and it's been like this for months.

2019-11-05 15:38 UTC, felipe-silvestre-morais commented
@colintheshots I have no hope this PR will be merged soon, could you provide the steps to build it locally?

Thanks

2019-11-07 04:05 UTC, colintheshots commented
It looks to me like someone needs to take over maintainership or fork at this point. All Android PRs seem blocked. I'll look into it.

2019-11-07 16:24 UTC, taquitos commented
I'm digging into this, I haven't run screengrab in a while, I'm sorry this has taken so long.

2019-11-07 17:56 UTC, taquitos commented
I was able to check out, build and test this using the example project with some small changes to the `Screengrabfile`. I can't get the screenshots, which I'm assuming is because I'm not doing something correctly. 
`Screengrabfile` changes:
```
tests_apk_path 'build/outputs/apk/example-debug-androidTest.apk'
app_apk_path 'build/outputs/apk/example-debug.apk'
```
to:
```
tests_apk_path 'build/outputs/apk/androidTest/debug/example-debug-androidTest.apk'
app_apk_path 'build/outputs/apk/debug/example-debug.apk'
```
I was running `./gradlew assembleAndroidTest` and `./gradlew build`

Output:
```
[09:49:01]: Pulling captured screenshots from the device
ls: /sdcard/tools.fastlane.localetester/screengrab: No such file or directory
[09:49:01]: Exit status: 1
ls: /data/data/tools.fastlane.localetester/app_screengrab: Permission denied
[09:49:01]: Exit status: 1
[09:49:01]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
```

2019-11-07 18:07 UTC, joshdholtz commented
Hello 👋

I will get this and the rest of the Android PRs that time it deserves next week 😊 A majority of my time and brainpower has gone to the Android Publisher V2 to V3 migration (https://github.com/fastlane/fastlane/pull/15269) and that is getting finished up this week 🙏 I'll move my focus over to the rest of these Android PRs after that.

Sorry for the wait and I appreciate the patience ❤️

2019-11-12 14:24 UTC, joshdholtz approved these changes
@colintheshots This is 🔥 Thanks so much for making this change and my apologies again on taking so long. I have a few more screengrab PRs to get through today and then I will pop out a new release.

2019-11-12 14:25 UTC, merged