[automatic_code_signing] Add code_signing as alias
fastlane/fastlane pull request #15900
Opened 2020-01-15 04:05 UTC by att55

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

`automatic_code_signing` has `use_automatic_signing`, the key switches `Auto` to `Manual` code signing. And the defaulut value is `false`.

https://docs.fastlane.tools/actions/automatic_code_signing/#automatic_code_signing

Sample code is like below.

```
automatic_code_signing(
  path: "demo-project/demo/demo.xcodeproj",
  use_automatic_signing: false
)

automatic_code_signing(
  path: "demo-project/demo/demo.xcodeproj",
  use_automatic_signing: true
)
```

But, I feel the specifications below are strange and confusing users. 

1. Even though the action name is `automatic_code_signing`, the action allows to switch `Auto` to `Manual` code signing.
2. Even though the action name is `automatic_code_signing`, `Manual` code signing is executed by default because the default value of `use_automatic_signing` is `false`.

So, I added `code_signing` as alias of `automatic_code_signing` to prevent confusing users.

2020-01-27 12:34 UTC, joshdholtz requested changes
@att55 👋 This is a very interesting change! I'm a little bit for but also a little bit against this 🤔 I do agree that this action should have a different name but I also don't want to just introduce another action/alias.

Aliases are nice (in this cases since some of the options conflict with the name of the action) but it makes things a little bit harder to maintain and harder to find other actions. 

If we are going to do this, I would rather move the logic from `AutomaticCodeSigning` into one that is better named and add a message saying that we are deprecating `AutomaticCodeSigning` in the future.

The `code_signing` name feels a bit too generic to me (I actually thought this PR was for something like _sigh_ or _cert_ at first). I think it would need to be something like `update_code_signing_settings`

Thoughts?

2020-01-28 14:12 UTC, att55 commented
@joshdholtz Thank you so much for your review!

> I would rather move the logic from AutomaticCodeSigning into one that is better named and add a message saying that we are deprecating AutomaticCodeSigning in the future.
> I think it would need to be something like update_code_signing_settings

I think your plan is very good and `update_code_signing_settings` is effective to resolve this iseue! 😸 
I will try to adopt your plan in this PR 👍

2020-01-30 10:53 UTC, att55 commented
@joshdholtz I adopted our plan in this PR 👍Please check when you can 🙏 

The outline is below.
- added the message saying that we are deprecating automatic_code_signing in automatic_code_signing action .
- generated update_code_signing_setttings action instead of automatic_code_signing
- added a test file for update_code_signing_setttings
- added fixtures(xcodeproj) to exec the test of update_code_signing_setttings

2020-02-18 16:03 UTC, joshdholtz requested changes
Thanks SO much for making the changes I suggested 🥰 One more small change! If we could use `UI.deprecated` instead of `UI.important` that would be 💯

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("The `automatic_code_signing` action has been deprecated,")
```suggestion
      expect(UI).to receive(:deprecated).with("The `automatic_code_signing` action has been deprecated,")
```

2020-02-18 16:03 UTC, joshdholtz commented on fastlane/spec/actions_specs/automatic_code_signing_spec.rb
> +      expect(UI).to receive(:important).with("Please use `update_code_signing_settings` action instead.")
```suggestion
      expect(UI).to receive(:deprecated).with("Please use `update_code_signing_settings` action instead.")
```

2020-02-19 02:33 UTC, att55 commented
@googlebot I consent.

2020-02-19 02:36 UTC, att55 commented
@googlebot I consent.

2020-02-19 02:48 UTC, att55 commented
@googlebot I consent.

2020-02-19 02:58 UTC, att55 commented
I thought I've already consented CLAs... 🤔??

2020-02-19 03:10 UTC, att55 commented
@joshdholtz Thank you so much for your review and requesting suggested changes to this PR!  
I fixed to use `UI.deprecated` instead of `UI.important`. 👍 
Sorry to bother you, but please check when you can 😄

2020-02-19 03:13 UTC, att55 commented
Sorry... I didn't understand how to pass "size-label" and "cla/google"...

2020-03-09 03:08 UTC, att55 commented
@joshdholtz Sorry to bother you... please check this PR when you can 🙏

2020-03-09 03:08 UTC, joshdholtz commented
Yo yo yo! Will check first thing tomorrow morning ❤️

2020-03-11 09:03 UTC, att55 commented
Thank you so much ❤️ It's file, when you really have time 😸

2020-03-23 02:22 UTC, att55 commented
@joshdholtz ( When you can... 👀🙏 )

2020-03-23 02:23 UTC, joshdholtz commented
Aye aye! Getting back to things first thing tomorrow morning 👌

2020-03-23 11:27 UTC, joshdholtz commented
@googlebot I consent.

2020-03-23 11:31 UTC, joshdholtz approved these changes
Looks good to me! Thanks for making those changes 😊 Appreciate all your contributions ❤️

2020-03-23 11:31 UTC, merged