[match] Change http_auth_header capitalization
fastlane/fastlane pull request #15928
Opened 2020-01-23 13:58 UTC by sakul1991

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context
In bitbucket server the header for HTTP Basic Auth is case sensitive, contrary to http standard specifications, for this reason git cannot authorize against bitbucket server using the git_basic_authorization or git_bearer_authorization parameters. 

### Description
Changed the headers spelling to one more commonly used. Tested and verified against our corporate bitbucket server installation.

### Testing Steps
Unfortunately not possible without a bitbucket server and connecting via http basic auth.

2020-01-26 19:30 UTC, janpio commented
Is there some public documentation for this requirement of case sensitivity for HTTPS headers for Bitbucket? Super strange.

2020-01-27 12:49 UTC, joshdholtz requested changes
I'm not a really a fan of this but if its what we need to do 😬 A comment like the one I suggested would be great so somebody doesn't come back in here and change it

2020-01-27 12:49 UTC, joshdholtz commented on match/lib/match/storage/git_storage.rb
> +        command << " -c http.extraheader='Authorization: Bearer #{self.git_bearer_authorization}'" unless self.git_bearer_authorization.nil?
Can we had comment above here like like this?
```
# HTTP headers are supposed to be be case insensitive but 
# Bitbucket requires `Authorization: Basic` and `Authorization Bearer` to work
```

2020-01-27 14:07 UTC, joshdholtz approved these changes
Thanks for making this change! Hopefully this will work for everyone now 🙃 🤞 Appreciate the contribution ❤️

2020-01-27 14:07 UTC, merged