Use GITHUB_API_TOKEN for default for consistency
fastlane/fastlane pull request #15995
Opened 2020-02-08 23:23 UTC by chuganzy

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Other GitHub related actions use `GITHUB_API_TOKEN` but `get_github_release` does not. For consistency I thought it is better to use `GITHUB_API_TOKEN` here too.

### Description

Just use `ENV['GITHUB_API_TOKEN']` as the default value.

### Testing Steps

n/a

2020-02-11 05:23 UTC, eygraber commented
Is this related? https://github.com/fastlane/fastlane/issues/15979

2020-02-11 07:54 UTC, chuganzy commented
@eygraber Hi. I looked into the issue but I think it is not related to this PR.

2020-02-17 20:39 UTC, joshdholtz requested changes
Love this change! Just a need to add `code_gen_sensitive ` and `code_gen_sensitive` and then I think we should be good 😊

2020-02-17 20:39 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/get_github_release.rb
> +                                       default_value: ENV["GITHUB_API_TOKEN"],
```suggestion
                                       code_gen_sensitive: true,
                                       default_value: ENV["GITHUB_API_TOKEN"],
                                       default_value_dynamic: true,
```

Good call! Can we also add these too? ^

2020-02-17 22:08 UTC, joshdholtz approved these changes
Looks good to me now! Thanks for fixing this 😊  Hope all is well ❤️

2020-02-17 22:08 UTC, merged

2020-02-17 22:53 UTC, chuganzy commented
@joshdholtz Thank you! Yeah, doing good. Hope you are doing well too!