[push_to_git_remote] Avoid using master unexpectedly
fastlane/fastlane pull request #16141
Opened 2020-03-08 04:25 UTC by myihsan

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
There are 31 failures before I change anything, and no new failures appeared after my change.
Am I doing something wrong or should I just ignore them and check this box?
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

As I describe in #15615, the **master** branch will be used unexpectedly if `git_branch` failed, and it may cause an accident if the user is running with `force: true`.
So raising an error if `git_branch` failed may be better behavior than using **master** branch.

### Description

Raising an error if `git_branch` failed.
I have reconsidered the confirmation and find it's not necessary.

### Testing Steps

Sorry about the inconvenience. I don't know how to reproduce the issue in actual environment.
I submitted #15615 because `push_to_git_remote` tried to push to the **master** branch but the current branch is a branch named in Japanese instead of **master** in my previous job environment. But I cannot reproduce it in my personal mac even I name the current branch in Japanese.

2020-04-03 18:39 UTC, joshdholtz requested changes
Thanks for this contribution 😊 I do agree this error should happy but I think we need to keep the default to master and error out only if `git_branch` specifically fails. Thoughts? 😇

2020-04-04 14:18 UTC, myihsan commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> -        local_branch ||= 'master'
I totally agree with your point.

> users that didn't set :local_branch and rely on it using master by default 

However, I cannot imagine what kind of situation this is. Maybe I don't have enough Git experience.
Could you give me an example?

And what do you mean by specifically fails?
Should I add error handling to `git_branch` by checking the value of `$?.exitstatus`?

2020-05-13 21:10 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> -        local_branch ||= 'master'
Now that I thought about this a bit more... this is totally fine 😊

2020-05-13 21:12 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> -        local_branch ||= 'master'
I don't know what I was thinking on April 3rd 🤷‍♂️ :

2020-05-13 21:13 UTC, joshdholtz approved these changes
This is all good! Thanks for fixing this 😊 Appreciate the contribution ❤️

2020-05-13 21:13 UTC, merged