Fix warning in SnapshotHelper.swift
fastlane/fastlane pull request #16244
Opened 2020-04-03 12:27 UTC by 0xced

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

Note: two tests are failing but I can't see how this could be related to my change in a swift support file.
```
  1) FastlaneCore::FastlaneFolder#path returns the path if fastlane is being executed from the fastlane directory
     Failure/Error: expect(FastlaneCore::FastlaneFolder.path).to eq('./')
     
       expected: "./"
            got: "./fastlane/"
     
       (compared using ==)
     # ./fastlane_core/spec/fastlane_folder_spec.rb:16:in `block (4 levels) in <top (required)>'
     # ./fastlane_core/spec/fastlane_folder_spec.rb:15:in `chdir'
     # ./fastlane_core/spec/fastlane_folder_spec.rb:15:in `block (3 levels) in <top (required)>'

  2) FastlaneCore::FastlaneFolder#fastfile_path uses a Fastfile that's inside a fastlane directory if cd is inside a fastlane dir
     Failure/Error: expect(FastlaneCore::FastlaneFolder.fastfile_path).to eq(File.join(".", fastfile_name))
     
       expected: "./Fastfile"
            got: nil
     
       (compared using ==)
     # ./fastlane_core/spec/fastlane_folder_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./fastlane_core/spec/fastlane_folder_spec.rb:27:in `chdir'
     # ./fastlane_core/spec/fastlane_folder_spec.rb:27:in `block (3 levels) in <top (required)>'
```

### Motivation and Context
Get rid of this warning when using the `SnapshotHelper.swift` supplied by `snapshot`:
> SnapshotHelper.swift:236:9: Code after 'throw' will never be executed

### Description
I removed the `#else` branch that was doing `throw SnapshotError.cannotRunOnPhysicalDevice` and reorganised the code to make sure that no code is executed after a `throw`.

### Testing Steps
In order to test this change, compile the `SnapshotHelper.swift` with Xcode 11.4 and ensure that no warning is produced.

2020-04-06 20:31 UTC, janpio requested changes
You will need to increase the version at the end of the file, please.

2020-04-07 07:38 UTC, 0xced commented
I addressed the issues you raised and rebased on master.

2020-04-07 07:39 UTC, 0xced commented on snapshot/lib/assets/SnapshotHelper.swift
> +            return URL(fileURLWithPath: homeDirUrl.path).appendingPathComponent(cachePath)
Addressed in 69dc007f73f1e85c45a5983f7a8fe43eb952ec88

2020-04-07 07:39 UTC, 0xced commented on snapshot/lib/assets/SnapshotHelper.swift
> +            return usersDir.appendingPathComponent(user).appendingPathComponent(cachePath)
Addressed in 69dc007f73f1e85c45a5983f7a8fe43eb952ec88

2020-04-19 18:49 UTC, janpio reviewed
Theoretically this looks good now. 

Someone who actually knows Swift will need to do a proper review.

2020-04-19 18:49 UTC, janpio reviewed
👍

2020-04-19 18:50 UTC, janpio approved these changes

2020-05-13 17:29 UTC, joshdholtz approved these changes
This worked for me! Thanks for fixing this ❤ Really appreciate it!

2020-05-13 17:29 UTC, merged