[snapshot] Add -only-testing and -skip-testing options from scan
fastlane/fastlane pull request #16312
Opened 2020-04-15 17:15 UTC by jhandguy

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

To make retrying mechanisms possible, we need to leverage the `-only-testing` and `-skip-testing` options that already exist in `scan`.

### Description

This change brings both the options `-only-testing` and `-skip-testing` from `scan` to `snapshot`.
The `snapshot` implementation is extremely similar, if not identical, to the `scan` implementation.

### Testing Steps

I have tested this change in my project and I was able to create a retrying mechanism, that only do so with failing tests.

2020-04-19 18:09 UTC, janpio commented on scan/lib/scan/test_command_generator.rb
> +        options << "-parallel-testing-worker-count #{config[:concurrent_workers]}" if config[:concurrent_workers]
unrelated bugfix?

2020-04-19 18:10 UTC, janpio approved these changes
Looks great - thanks!

2020-04-19 20:35 UTC, jhandguy commented on scan/lib/scan/test_command_generator.rb
> +        options << "-parallel-testing-worker-count #{config[:concurrent_workers]}" if config[:concurrent_workers]
exactly, gave it its own commit too 👍

2020-04-20 01:19 UTC, joshdholtz requested changes
This looks good! Just one quick nit pick suggestion 😊

2020-04-20 01:19 UTC, joshdholtz commented on snapshot/lib/snapshot/test_command_generator_base.rb
> +          ext = FastlaneCore::Helper.xcode_version.to_i >= 11 ? '.xcresult' : '.test_result'
```suggestion
          ext = fastlanecore::Helper.xcode_at_least?(11) ? '.xcresult' : '.test_result'
```

Do we want to use this helper? ☝️

2020-04-20 08:09 UTC, jhandguy commented on snapshot/lib/snapshot/test_command_generator_base.rb
> +          ext = FastlaneCore::Helper.xcode_version.to_i >= 11 ? '.xcresult' : '.test_result'
Makes sense! 👌 Done! ✅

2020-04-30 07:32 UTC, jhandguy commented
@joshdholtz I fixed and rebased the changes! ✅

2020-05-07 08:08 UTC, jhandguy commented
@joshdholtz any news on this? Would be really cool to have it released along with https://github.com/fastlane/fastlane/pull/16350 🤗

2020-05-11 14:49 UTC, jhandguy commented
Rebased ✅

2020-05-12 21:10 UTC, joshdholtz approved these changes
Looks good to me! Will release this in a new version later this week 💪 Appreciate all your contributions ❤️

2020-05-12 21:11 UTC, merged