Make testflight command username param optional
fastlane/fastlane pull request #16390
Opened 2020-04-27 21:13 UTC by zackdotcomputer

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This change resolves #16389 and brings Fastlane.swift upload methods in line with the ruby versions for the use cases of uploading to testflight and appstore.

### Description
By making the username parameter to `uploadToTestflight` and related methods optional, we match the behavior of the Ruby version, allowing Fastfiles to be written agnostic to the authenticated user and without requiring a designated user for Fastlane to use.

2020-04-28 00:21 UTC, zackdotcomputer commented
@googlebot I signed it!

2020-05-02 20:30 UTC, janpio requested changes
The Swift API is generated based on the Ruby code. Changes need to be done there, and will then be reflected on generation of the Swift code.

2020-05-12 20:09 UTC, joshdholtz requested changes
Heyyy 👋 This `Fastlane.swift` file is a generated file. It takes the options defined in Ruby and generates this code. But after reading #16389 it looks like this is actually a bigger issue. It looks like Fastlane.swift doesn’t allow passing of ENV to any tools or actions. This actually requires some deeper thought and maybe a redesign on how the Fastlane.swift is bridged to Ruby 😬

2020-05-17 06:19 UTC, marymesohorny approved these changes

2020-05-18 13:50 UTC, zackdotcomputer commented
I'm going to close this since I misunderstood how this file was created (would suggest putting a banner comment at head letting people know it's autogenerated). Good luck with the deeper thought on the redesign of the bridging and I'll just hope that when it's done we can sort out the issues I've opened about these tight parameter constraints.

2020-05-18 13:50 UTC, closed without merging