[spaceship] Retry request when Developer Portal responds with a 403 status code
fastlane/fastlane pull request #16478
Opened 2020-05-19 16:42 UTC by ecamacho

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
To fix the [Issue 16430](https://github.com/fastlane/fastlane/issues/16430)
We started to see this happen a few weeks ago. Sometimes, requests done to the developer portal fail. If we retry a few times, the error goes away.  When requests fail, the Developer Portal response has a **403** status code  and this body.:
```html
<HEAD>
  <TITLE>Access Denied</TITLE>
</HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
  <H1>Access Denied</H1>
  <HR>
  <FONT FACE="Helvetica,Arial"><B>
Description: You are not allowed to access the document you requested.
  </B></FONT>
  <HR>
 </BODY>
```
### Description
1. I've added a new Error called `SpaceshipError::AccessForbiddenError` that is raised in the `send_request` method of `Spaceship::Client` when the status code of the response is `403`. 
2. I've modified the `with_retries` method in `Spaceship::Client` to retry when the `AccessForbidden` error is raised.
3. I've used my fork in my project and verified that the error I described wasn't present anymore. Since the error is intermittent, I leaved my project to run every 30 mins for a day. Before my change that test made my project to fail several times per day.
4. I've also added a unit test to verify that the new Error is raised in the presence of a 403 status code and modified the existing unit test to verify that the request is retried if the Error is raised.

### Testing Steps

In my project, the call that failed more often was the one done to the endpoint `https://developer.apple.com/services-account/<account>/account/ios/identifiers/getAppIdDetail.action` triggered by using the method `Spaceship::PortalClient::details_for_app`. Since the request to the endpoint doesn't fail all the times, the only way to reproduce it is to run a script that uses that method during a long period of time.

2020-05-19 16:45 UTC, ecamacho commented
@googlebot I signed it!

2020-05-19 16:46 UTC, ecamacho commented
@googlebot I fixed it.

2020-05-21 22:51 UTC, janpio commented
Interesting.

Wouldn't that have the potential to go into an infinite loop if you actually do not have permission to access that resource?

2020-05-25 12:11 UTC, ecamacho commented
@janpio That's a good point. The exception is raised inside a `with_try` block, from the reading I did to the code, it will try 5 times and then re raise the exception. So it won't loop forever. Unless I didn't understand it correctly.

2020-05-25 17:34 UTC, minuscorp requested changes
A little comment

2020-05-26 15:37 UTC, ecamacho commented on spaceship/lib/spaceship/client.rb
> +          raise AccessForbiddenError.new, "Access Forbidden"
Yes, that makes sense, thank you!

2020-05-26 15:43 UTC, minuscorp approved these changes
LGTM 🚀

2020-05-27 14:19 UTC, ecamacho commented
@minuscorp thank you! Do you know how can I get this merged?

2020-05-27 15:03 UTC, janpio approved these changes

2020-05-27 15:03 UTC, merged

2020-05-27 15:04 UTC, janpio commented
Approving reviews from collaborators and then someone who is bold enough to hit the button usually works :D

2020-05-27 15:05 UTC, ecamacho commented
@janpio That's great, thank you!

2020-05-28 16:18 UTC, JiaYangSF commented
Hey @ecamacho , thank you for the fix, for fastlane version  2.146.1, do we need to upgrade to the latest 2.148 to verify this fix?

2020-05-28 16:37 UTC, janpio commented
This has not been released yet but will be included in the next one. The bot will psot a comment here when that happened.