fix: paths with spaces fail
fastlane/fastlane pull request #16636
Opened 2020-06-20 18:36 UTC by rigor789

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

If the path has a space in it (for example `C:/Users/User Name/AppData/Local/Temp/....`), the command would ignore anything after the space, thus exiting with
```Can't open C:/Users/User for reading, No such file or directory```

### Description

The only change is wrapping the path in quotes.

### Testing Steps

I personally didn't test - because it requires creating a new user on Windows that has a home directory with a space in it, however this came up on the NativeScript discord by someone having trouble with it (screenshot submitted by a community member)

![image](https://user-images.githubusercontent.com/879060/85208833-b0d9f700-b333-11ea-9c49-0f3478541a66.png)

2020-06-20 18:37 UTC, rigor789 commented
@googlebot I signed it!

2020-06-20 19:03 UTC, janpio requested changes
The correct solution is to shellescape the parameter - searching for `shellescape` in the codebase should give some examples on how to use this.

2020-06-21 17:00 UTC, janpio approved these changes
Awesome, thank you @rigor789!

2020-06-21 17:06 UTC, rigor789 commented
No worries - I wasn't sure if just the quotes would be enough, but being safe with `shellescape` is definitely better!

2020-06-21 19:25 UTC, janpio commented
If I remember correctly it depends on the OS - some like `"`, some one `'` etc - which is why we have a modified version of `shellescape` that does the right thing on Windows.

2020-06-21 19:42 UTC, merged