[sigh] Resign OnDemandResources
fastlane/fastlane pull request #16669
Opened 2020-06-24 23:07 UTC by sjmh

Allows sigh to resign OnDemandResource assetpacks

fixes #16668

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

We have teams that create/sign IPAs with development provisioning profiles and then we centrally sign with fastlane before deploying to the store.  They would like to start using ODR's, however, when we resign, these ODR's are not being (re)signed.

### Description

Detects if an ODR folder is within the Payload folder, if so, removes any codesignature's from each pack and resigns each pack.

### Testing Steps

Modified a local installation of fastlane with these changes and ran an IPA with ODR through it.  IPA came out successfully signed.

2020-06-25 01:06 UTC, sjmh commented
@googlebot I signed it!

2020-06-28 08:13 UTC, janpio approved these changes
Looks safe enough to approve without actually understanding what exactly it does ;)

2020-06-29 17:42 UTC, sjmh commented
Thanks @janpio - I probably should have explained better.

Apple allows you to push certain assets to OnDemandResources ( https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html ).

Normally during your dev cycles, you can either host these extra resources on your own local web servers, or embed them directly in the app.  When you embed, it puts them in the Payload/<app name>/OnDemandResources, but that's really only for debug purposes..  In those instances though, fastlane signs them because it finds them in the app directory.

However, when you deploy to the AppStore, the AppStore must host the resources, but when you build the IPA for the AppStore, it actually creates the OnDemandResources folder in Payload, rather than the Payload/<app name>.   *sigh* currently doesn't detect that however, so the resources don't get signed/resigned.

2020-06-29 17:52 UTC, joshdholtz requested changes
@sjmh Thanks for adding this! Can you add a changelog to the top of the file? There should be a format you can follow up there 😇

2020-06-29 17:53 UTC, joshdholtz requested changes
@sjmh Thanks for adding this! Can you add a changelog to the top of the file? There should be a format you can follow up there 😇

2020-06-29 17:54 UTC, sjmh commented
Oops, of course!

2020-07-06 20:02 UTC, joshdholtz approved these changes
This seems good to me! Thanks for adding this ❤️

2020-07-06 20:02 UTC, merged