add shortcuts for getting current pending release and current in revi…
fastlane/fastlane pull request #16808
Opened 2020-07-09 04:54 UTC by addbrick

…ew app store version

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context

This adds short cuts for getting the app store version which is In Review via `get_in_review_app_store_version`, and Pending Developer Release via `get_pending_release_app_store_version`. This way I don't have to remember the filters when looking these versions up.

### Description

This adds short cuts for getting the app store version which is In Review via `get_in_review_app_store_version`, and Pending Developer Release via `get_pending_release_app_store_version`.

### Testing Steps

2020-07-09 20:27 UTC, joshdholtz requested changes
Thanks for adding these! Just a small request to remove the array and join that isn’t needed 😊

2020-07-09 20:27 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/models/app.rb
> +          appStoreState: [Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::IN_REVIEW].join(","),
```suggestion
          appStoreState: Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::IN_REVIEW
```

2020-07-09 20:27 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/models/app.rb
> +          appStoreState: [Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::PENDING_DEVELOPER_RELEASE].join(","),
```suggestion
          appStoreState: Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::PENDING_DEVELOPER_RELEASE
```

2020-07-10 20:49 UTC, addbrick commented
@joshdholtz Done! I also removed the join from the ready for sale version as well.

2020-07-28 12:28 UTC, joshdholtz approved these changes
Perfect! Thank you for adding this and making my requested changes ❤️ Really appreciate the contribution!

2020-07-28 12:28 UTC, merged