add codesign partition ID to keychain when importing
fastlane/fastlane pull request #16819
Opened 2020-07-10 12:38 UTC by jakubgs

From my research I found that adding the `codesign` partition ID to the keychain partition list helps with errors like:
```

2020-07-10 13:56 UTC, joshdholtz commented
@jakubgs Hey 👋  Do you mind signing the CLA when you get a chance? Can't merge without it 🤷‍♂️

2020-07-10 14:13 UTC, joshdholtz requested changes
I think this makes sense to me! I'll do some local testing on this too. But it does look like we got a few more failing tests 🤔

2020-07-10 15:16 UTC, jakubgs commented
I'm not really interested in reading or accepting any CLA. Maybe I should just open an issue instead?

2020-07-20 17:17 UTC, joshdholtz commented
@jakubgs If you want to open an issue that would be great! Sorry about the CLA 😔  Not something we are able to get around at the moment.

2020-07-21 08:08 UTC, jakubgs commented
Sure thing, there you go: https://github.com/fastlane/fastlane/discussions/16903

2020-07-21 08:08 UTC, closed without merging

2020-07-21 11:47 UTC, joshdholtz commented
@jakubgs Thank you! ❤