[deliver][submit][regression] Fix issue: Deliver failed to select IDFA agreement, if app uses IDFA
fastlane/fastlane pull request #16837
Opened 2020-07-12 19:45 UTC by crazymanish

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- Earlier (before 2.150.x version), Fastlane(spaceship) always select the IDFA agreement, if any app uses IDFA.
- More details: in the below-attached screenshot.

### Description
- After 2.150.x release (new AppStore API migration release), Fastlane(deliver) needs `add_id_info_limits_tracking: true` inside the submission information to select the IDFA agreement. 🤷🏻‍♂️
- If application uses IDFA then Fastlane(deliver) `must select` the mandatory agreement checkbox automatically. 😈

### Testing Steps
Run `deliver` without passing **add_id_info_limits_tracking** `submission_information`.
```ruby
deliver(username: "xxxx@catawiki.nl",
              app_identifier: "xxxx-app_identifier",
              app_version: 1.0,
              skip_screenshots: true,
              force: true,
              submit_for_review: true,
              submission_information: {
                add_id_info_uses_idfa: true,
                add_id_info_serves_ads: false,
                add_id_info_tracks_action: true,
                add_id_info_tracks_install: true
              }
        )
```

### More details (spaceship earlier implementation)
![spaceship](https://user-images.githubusercontent.com/5364500/87255076-e6cc5000-c487-11ea-9964-2f8467a7fd3d.png)

2020-07-12 19:50 UTC, crazymanish commented
cc: @joshdholtz 🚀

2020-07-12 20:34 UTC, crazymanish commented
Whoops! one test job failed because of the ruby-version mismatch in CircleCI, is it a known issue? 🤔

2020-07-13 18:50 UTC, rogerluan requested changes
I think this change is unwanted, because it sort of makes _fastlane_ legally liable for checking a checkbox that should be explicitly checked by the maintainer of your app. It's controversial, I know, because fastlane operates using an authentication you provide to _fastlane_ 🤷 but I read somewhere that changes like these were unwanted. Ref.: https://github.com/fastlane/fastlane/issues/16701#issuecomment-651260747

Instead, I add this to `submissionInformation` dictionary (aka `submission_information` hash): `"add_id_info_limits_tracking" : true,`, like you mentioned that was deprecated. This solves the issue :) maybe that key shouldn't have been marked as deprecated in the first place 🤔 ?

Anyways, let's also hear from @joshdholtz :)

2020-07-13 18:56 UTC, crazymanish commented
> I think this change is unwanted, because it sort of makes _fastlane_ legally liable for checking a checkbox that should be explicitly checked by the maintainer of your app. It's controversial, I know, because fastlane operates using an authentication you provide to _fastlane_ 🤷 but I read somewhere that changes like these were unwanted. Ref.: [#16701 (comment)](https://github.com/fastlane/fastlane/issues/16701#issuecomment-651260747)
> 
> Instead, I add this to `submissionInformation` dictionary (aka `submission_information` hash): `"add_id_info_limits_tracking" : true,`, like you mentioned that was deprecated. This solves the issue :) maybe that key shouldn't have been marked as deprecated in the first place 🤔 ?
> 
> Anyways, let's also hear from @joshdholtz :)

Hi @rogerluan, 
Fastlane already doing it for us for a long time, see below spaceship code, which stops working after 2.150.x release... 🤔
.
![spaceship](https://user-images.githubusercontent.com/5364500/87342135-08dad680-c54b-11ea-857a-cf4330870013.png)

2020-07-13 19:11 UTC, crazymanish commented
Also @rogerluan , my point is very simple
- If the application uses IDFA then Fastlane(deliver) `must select` the mandatory agreement checkbox automatically. 😈

Basically, to me we don't need to send two params always, `add_id_info_uses_idfa: true` should be enough to select the mandatory agreement checkbox automatically.:)

Option1:
```ruby
add_id_info_uses_idfa: true,
add_id_info_limits_tracking: true
```
vs 

Option2:
```ruby
add_id_info_uses_idfa: true
```

I will go with option2 always, less code in my release pipeline, less maintenance because I know Fastlane is super smart and select the `add_id_info_limits_tracking: true` if I am sending `add_id_info_uses_idfa: true` :)

2020-07-14 00:53 UTC, rogerluan commented
I agree! Let's wait for legal clearance then. The technical aspect of your solution looks good to me 👍

2020-07-14 06:39 UTC, crazymanish commented
> I agree! Let's wait for legal clearance then. The technical aspect of your solution looks good to me 👍

Glad, you liked the solution! 🙇🏻‍♂️
I think, there should not be any legal issue, we are just making Fastlane backward compatible, right? 🤔 
(we are telling Fastlane that Hey my App uses IFDA)

2020-07-14 13:03 UTC, joshdholtz commented
@crazymanish Thanks for the PR! I don't think we can actually accept this PR due to legal things 😔 Hardcoding this to `true` isn't an assumption we can make for our users.

Not every app uses IDFA and the App Store is now being more transparent about what kind of tracking apps all use. We need to allow the option for our users to actually set `true` or `false`. 

I think @rogerluan is correct in which that depreciation in the previous code was wrong or not applicable (especially since things changed a lot of the new App Store Connect API).

Thanks again for this PR and I do hope this isn't your last! PRs that touch legal things are always difficult ones. This does make things easier on most users but we need to take responsibility off _fastlane_ and allow flexibility on the users 🤷‍♂️ 

---

Side note 👇 

What I _am_ planning to do is reworking the whole `submission_information` option in `deliver`. It's not very easy to use or document at the moment and its also pretty verbose. I'm thinking of splitting that up and making the verbiage more aligned to what its shown on the App Store Connect website.

2020-07-14 13:09 UTC, crazymanish commented
Thank you @joshdholtz @rogerluan 🙌🏻 Closing the PR...:)

2020-07-14 13:09 UTC, closed without merging

2020-07-14 13:11 UTC, joshdholtz commented
@crazymanish Thanks for understanding! Always a little heart breaking closing PRs 💔 Hope to still see some more from you in the future!

2020-07-14 16:54 UTC, rogerluan commented
@joshdholtz refactoring `submission_information` to split up the hash into their own separate fields is 💯 🤩 looking forward to it!