[bug][gym][scan] xcodebuild -resolvePackageDependencies missing -derivedDataPath
fastlane/fastlane pull request #16986
Opened 2020-08-03 23:01 UTC by nxtstep

🔑 

Added `-derivedDataPath` parameter to xcodebuild when `derived_data_path` is set in options and or `SCAN_DERIVED_DATA_PATH` or `GYM_DERIVED_DATA_PATH` env are set.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
When adding SPM dependencies to your Xcode project the checkout repositories are cached within the `DerivedData` folder of your current project. However when building/testing your project with `fastlane gym/scan` the derived data path setting is not propagated to the `xcodebuild -resolvePackageDependencies` step. This can lead to confusion and bugs when adding/removing/updating said dependencies.

### Description
Added the `derivedDataPath` step to `Project` and skip setting/overwriting this parameter in `Scan` and `Gym`.

### Testing Steps
Just run a `fastlane scan [derived_data_path:your_path]` and/or `fastlane gym [derived_data_path:your_path]` on your project that **has** SPM dependencies (managed by Xcodeproj) and see that the `xcodebuild -resolvePackageDependencies` step has propagated the derivedDataPath when either `derived_data_path` is passed to gym/scan as an argument. Or respectively `SCAN_DERIVED_DATA_PATH` or `GYM_DERIVED_DATA_PATH` env are set.

2020-08-05 14:17 UTC, joshdholtz requested changes
👋 Thanks for making this change! We had a change similar to this that had to get reverted because it ended up breaking some things so I want to make sure we covered all cases before merging this one 😇 

For reference:
- Initial PR - https://github.com/fastlane/fastlane/pull/16534/files
- Issue - https://github.com/fastlane/fastlane/issues/16558
- Revert PR - https://github.com/fastlane/fastlane/pull/16560

I think this PR is also missing a change to `snapshot` to prevent double `-derivedDataPath` 🤔 Can we get that changed added in too? 🙃

2020-08-10 07:34 UTC, nxtstep commented
@joshdholtz updated the PR as requested :bowtie:

2020-08-10 16:37 UTC, joshdholtz approved these changes
This looks good to me! Thanks for making those changes ❤️ I really appreciate the contribution!

2020-08-10 16:37 UTC, merged

2020-08-11 18:04 UTC, bguidolim commented
@nxtstep @joshdholtz I know that I arrived here a little bit late, but it is not the same as the parameter `cloned_source_packages_path`?

2020-08-12 07:00 UTC, nxtstep commented
No it’s not the same. However, using the cloned_source_packages_path parameter c/would solve [e.g. work around] the described problem as well I suppose. Nevertheless, I would still expect the `derived_data_path` to be considered in all `xcodebuild` commands when available.

> On 11 Aug 2020, at 20:04, Bruno Guidolim <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> 
> @nxtstep <https://github.com/nxtstep> @joshdholtz <https://github.com/joshdholtz> I know that I arrived here a little bit late, but it is not the same as the parameter cloned_source_packages_path?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/fastlane/fastlane/pull/16986#issuecomment-672145537>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAEGKGPBUB2Q3GPCVSHNZODSAGB2HANCNFSM4PTZPVXQ>.
>