docs(upload to play store): update the quick-start requirement to set…
fastlane/fastlane pull request #17057
Opened 2020-08-15 16:34 UTC by renatobenks

…up supply correctly

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

According to https://github.com/fastlane/fastlane/issues/14686 which will be closed by inactivity, we should update the supply documentation to have the missing step to setup supply correctly and connect it with PlayStore without having errors.

### Description

Added to the quick-start section on upload to PlayStore documentation what is needed to do before trying to use supply.

**There are other places still missing this described step?**

By the way, there's not another way to upload a build to PlayStore on `supply init`? it wouldn't be possible at all?

### ~~Testing Steps~~

2020-08-15 16:36 UTC, renatobenks commented
@googlebot I signed it!

2020-08-16 23:26 UTC, rogerluan requested changes
Mere grammar & style review - I have no understanding of the issue itself

2020-08-16 23:26 UTC, rogerluan commented on fastlane/lib/fastlane/actions/docs/upload_to_play_store.md
> +> Before use _supply_ correctly to connect with PlayStore, you'll need setup your app manually first, uploading an only build to PlayStore, at least. Take a look into [fastane/fastlane#14686](https:/
```suggestion
> Before using _supply_ to connect to Google Play Store, you'll need to set up your app manually first by uploading at least one build to Google Play Store. See [fastane/fastlane#14686](https://github.com/fastlane/fastlane/issues/14686) for more info.
```

2020-08-17 19:31 UTC, renatobenks commented
there's anything else missing to merge it? it's just to additionally have the described the extra step required to use `supply`

2020-08-27 15:28 UTC, joshdholtz approved these changes
This is a great addition! Thanks so much for this ❤

2020-08-27 15:29 UTC, merged