[deliver] add retry when fetching edit app version and edit app info
fastlane/fastlane pull request #17235
Opened 2020-09-14 17:03 UTC by joshdholtz

### Motivation and Context
Fixes #16991

### Description
Add 5 retries to for fetching edit app version and edit app info

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-deliver-add-retry-fetching-edit-versions"
```

2020-09-14 18:56 UTC, rogerluan approved these changes
Logic looks good 👍 
Just a quick question: there are other places in fastlane where we retry after an ever-increasing amount of time (e.g. retry 5 times, first waiting for 5 seconds, then 10, then 20, etc... - fake example values). Why wasn't this same approach used here? (I don't think it's needed, but I'm just wondering why in some places we'd need that increasing timeout)

2020-09-14 19:06 UTC, joshdholtz commented
@rogerluan We could totally do that here if we wanted but my gut here is that just one try of 10 seconds will be enough. This probably works on the web because using users interfaces are slow. We are doing things programmatically so we are probably too fast for the API 🤷‍♂️

2020-09-15 21:41 UTC, rogerluan approved these changes

2020-09-15 21:41 UTC, rogerluan commented on deliver/lib/deliver/options.rb
> +                                     description: "Don’t create or update the app version that is being prepared for submission",
👌

2020-09-15 21:47 UTC, rogerluan requested changes

2020-09-15 21:47 UTC, rogerluan commented on deliver/lib/deliver/options.rb
> +                                     description: "Path to your App Store Connect API key JSON file",
```suggestion
                                     description: "Your App Store Connect API key",
```

This

2020-09-15 22:19 UTC, joshdholtz commented on deliver/lib/deliver/options.rb
> +                                     description: "Path to your App Store Connect API key JSON file",
Ah, good catch!

2020-09-15 22:56 UTC, merged