Fix comment about using `force` option
fastlane/fastlane pull request #17387
Opened 2020-10-06 10:02 UTC by frozenzia

Using `force` option in `upload_to_app_store` is designed to skip the HTML verification step.

Not 100% sure if there is or is NOT some sort of PDF report which is being referenced in line 29:
"If you don't want a PDF report for App Store builds, use the `:force` option." So I am not including any sort of change regarding that.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Just a simple documentation fix. Helps reduce confusion.

### Description

Changed single reference to "PDF" to "HTML"

Documentation change, no testing needed.

### Testing Steps

2020-10-06 10:09 UTC, frozenzia commented
@googlebot I signed it!

2020-10-06 13:26 UTC, rogerluan requested changes
I checked that the `upload_to_app_store` action uses _deliver_, and _deliver_ has this:

https://github.com/fastlane/fastlane/blob/5ee9f2e1f1d602e2af129e94eec2313091448abf/deliver/lib/deliver/options.rb#L153:L158

So in fact the code you're referencing sounds like it should print HTML instead of PDF.

You just missed another reference to PDF here:

https://github.com/fastlane/fastlane/blob/5ee9f2e1f1d602e2af129e94eec2313091448abf/fastlane/lib/fastlane/actions/upload_to_app_store.rb#L29

Can you also update it?

2020-10-06 18:13 UTC, frozenzia commented
On Tue, 6 Oct 2020, 16:26 Roger Oba, <notifications@github.com> wrote:

> You just missed another reference to PDF here:
>
>
> https://github.com/fastlane/fastlane/blob/5ee9f2e1f1d602e2af129e94eec2313091448abf/fastlane/lib/fastlane/actions/upload_to_app_store.rb#L29
>
> Can you also update it?
>

If u check the text in my PR, this is exactly the bit that I was unsure
about. If u are confirming this is talking about the same HTML summary,
then sure, I can do it.

-paul

>

2020-10-06 18:20 UTC, rogerluan commented
Yes, looks like it is :) Probably in the past we had some sort of PDF but then it got updated to a HTML page and these docs were never updated 😅

2020-10-06 19:35 UTC, frozenzia commented
Alright, changes made, actually tweaked it even further so it is more in line with what actually happens -- you get an HTML PREVIEW of the changes to be made, and are asked to verify that unless you use the `force` option. Also tweaked the text in 'deliver'.

2020-10-06 20:44 UTC, rogerluan approved these changes
Nice! Thanks for the contribution @frozenzia 🚀

2020-10-12 17:18 UTC, joshdholtz approved these changes
I think this change! Really appreciate the contribution ❤️

2020-10-12 17:18 UTC, merged