[sigh] fix undefined method owner_name with display_name in Sigh::Runner
fastlane/fastlane pull request #17432
Opened 2020-10-13 15:36 UTC by addbrick

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

`owner_name` was deprecated. `requester_first_name` + `requester_last_name` appears to be the new fields.

Fixes https://github.com/fastlane/fastlane/issues/17428

### Description

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/addbrick.git", :branch => "brick/cert_owner_name_helper"
```

2020-10-13 16:38 UTC, joshdholtz requested changes
Thanks for working on a fix for this! I got one suggestion that I think would make this 💯 Let me know your thoughts 😊

2020-10-13 16:50 UTC, addbrick commented on spaceship/lib/spaceship/connect_api/models/certificate.rb
> +        [requester_first_name, requester_last_name].join ' '
Yeah that sounds like a great idea, I can dig into. I am unfortunately really busy today and will not get a chance to get back to this until tomorrow. Thanks for the feedback!

2020-10-22 16:40 UTC, patrixxn commented
Hey guys, any update here? We're not able to resign apps because of the problem `owner_name is deprecated`. Thanks for your feedback.

2020-10-22 21:25 UTC, joshdholtz commented
@patrixxn I’ll step in and add a commit to this so we can get it out for you 😊 Should go out in a build tomorrow!

2020-10-22 21:38 UTC, joshdholtz commented
@googlebot I consent.

2020-10-22 21:38 UTC, joshdholtz commented
@patrixxn I made the change if you’d like to test it out! 👇 

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/addbrick.git", :branch => "brick/cert_owner_name_helper"
```

2020-10-23 07:32 UTC, IoT-Tobi commented
Hi guys,
I am quite new to fastlane.
I've checked out the repo https://github.com/addbrick/fastlane.git locally but I have no clue how to use this when I perform fastlane commands in terminal. It normally uses the "regular" fastlane installation there. Instead I want to use the local version with the bug fixed.

Thanks for any advice.

2020-10-23 15:25 UTC, joshdholtz approved these changes
Going to merge this in! Thanks for starting this @addbrick ❤️ This will get released today!

2020-10-23 15:25 UTC, merged