[pilot] update to new emoji regex
fastlane/fastlane pull request #17560
Opened 2020-11-05 19:06 UTC by joshdholtz

### Motivation and Context
The `emoji_regex` gem that is used in `pilot` has a new regex that is preferred and the other is deprecated - https://github.com/ticky/ruby-emoji-regex/releases/tag/v3.2.0

### Description
- Check if new regex constant exists and use it otherwise use the other

2020-11-09 05:44 UTC, rogerluan approved these changes
Cool! 😎

2020-11-09 05:45 UTC, rogerluan requested changes

2020-11-09 05:45 UTC, rogerluan commented on pilot/lib/pilot/build_manager.rb
>          changelog.gsub!(EmojiRegex::Regex, "")
What about this one? Shouldn't we...

```suggestion
        changelog.gsub!(emoji_regex, "")
```

2020-11-10 21:42 UTC, joshdholtz commented on pilot/lib/pilot/build_manager.rb
>          changelog.gsub!(EmojiRegex::Regex, "")
lol, you are right

2020-11-11 03:13 UTC, rogerluan approved these changes
🚀🚀

2020-11-11 15:52 UTC, merged