[ConnectAPI] added betaGroup delete and getBuilds for the group funct…
fastlane/fastlane pull request #17588
Opened 2020-11-11 03:01 UTC by krish722

…ions

### Checklist
- [ x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I've updated the documentation if necessary.

### Motivation and Context
Adding new features.

1. Delete TestFlight beta group.
2. Get builds for a TestFlight beta group.

### Description
1. Added a function delete! in BetaGroup class. We can call delete! will delete the group. It leaves the build as it is.
2. Added a function builds in BetaGroup class. We can call builds to get builds which are associated to the group.

### Testing Steps
```
Spaceship::ConnectAPI.login
platform = Spaceship::ConnectAPI::Platform.map('ios')
app = Spaceship::ConnectAPI::App.find('anyid')
group = app.get_beta_groups(filter: {name: "Gp1"}).first
group.builds.each do | build |
      puts  build.version
end
group.delete!
```

2020-11-11 16:47 UTC, joshdholtz requested changes
This looks great! Just one small thought/request 😊

2020-11-11 16:47 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/models/beta_group.rb
> +      def builds
Are you cool if we rename this to `fetch_builds`? I like to the method name as an action if its doing an API request 😇 

```suggestion
      def fetch_builds
```

2020-11-12 09:45 UTC, krish722 commented
Please merge it. Also want to know when is the next release planned?

2020-11-12 19:51 UTC, joshdholtz commented
@krish722 Next release should be later today or tomorrow morning 😊

2020-11-12 20:01 UTC, joshdholtz approved these changes
Thanks for making that change and for adding tests ❤️  Really appreciate the contribution!

2020-11-12 20:02 UTC, merged