[SwiftActionsAPIGenerator] fixed undefined method `action_name'
fastlane/fastlane pull request #17660
Opened 2020-11-24 03:06 UTC by philCc

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves https://github.com/FIRHQ/fastlane-plugin-fir_cli/issues/16

### Description

### Testing Steps

2020-11-30 22:33 UTC, joshdholtz reviewed
This fix seems legit but I'm very confused on how this error was even happening in the first place 😊 Do you happen to have a stack trace with this error? I'd like to see how this issue was happening!

2020-11-30 23:07 UTC, philCc commented
Hi @joshdholtz 

Here is an issue, you can have a look: https://github.com/FIRHQ/fastlane-plugin-fir_cli/issues/16

2020-11-30 23:17 UTC, philCc commented
If you use fastlane swift version and add plugin `fir_cli`, there will be happen a error:

`NoMethodError: [!] undefined method ‘action_name’ for Fastlane::Actions::FirHelper:Class `

2020-11-30 23:36 UTC, joshdholtz commented
@philCc Ahhhh, I see! I think the fix should actually be made in the plugin 😊 

The issue is these classes within the action itself 👉  https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb#L179-L200

1) You could fix this by putting a `private` above that section of code (I think)
2) Or these classes should get moved into https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/helper/fir_cli_helper.rb

Let me know your thoughts on that!

2020-12-01 00:09 UTC, philCc commented
> @philCc Ahhhh, I see! I think the fix should actually be made in the plugin 😊
> 
> The issue is these classes within the action itself 👉 https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb#L179-L200
> 
> 1. You could fix this by putting a `private` above that section of code (I think)
> 2. Or these classes should get moved into https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/helper/fir_cli_helper.rb
> 
> Let me know your thoughts on that!

@joshdholtz However, I think we should do a validation in the FastLane layer to prevent other plug-ins from experiencing the same problem

2020-12-01 00:35 UTC, joshdholtz requested changes
Good call on keeping this in here. How does something like this look though? I think this should still fix it for you!

2020-12-01 00:35 UTC, joshdholtz commented on fastlane/lib/fastlane/swift_fastlane_api_generator.rb
> +                 end).nil?
```suggestion
        next unless action.response_to?(:name)
```

2020-12-01 00:35 UTC, joshdholtz commented on fastlane/lib/fastlane/swift_fastlane_api_generator.rb
> +                 end).nil?
```suggestion
        next unless action.response_to?(:name)
```

2020-12-01 00:35 UTC, joshdholtz commented on fastlane/lib/fastlane/swift_fastlane_api_generator.rb
> +                 end).nil?
```suggestion
        next unless action.response_to?(:name)
```

2020-12-01 01:33 UTC, philCc commented on fastlane/lib/fastlane/swift_fastlane_api_generator.rb
> +                 end).nil?
Sorry, an error will occur here
```
Updating plugin dependencies...
[✔] 🚀
/Users/pz/.rvm/gems/ruby-2.6.5/bundler/gems/fastlane-plugin-fir_cli-45c6ca10c187/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:183: warning: already initialized constant FIR::VERSION
/Users/pz/.rvm/gems/ruby-2.6.5/gems/fir-cli-2.0.10/lib/fir/version.rb:4: warning: previous definition of VERSION was here
+---------------------------+---------+--------------------------+
|                          Used plugins                          |
+---------------------------+---------+--------------------------+
| Plugin                    | Version | Action                   |
+---------------------------+---------+--------------------------+
| fastlane-plugin-pgyer     | 0.2.2   | pgyer                    |
| fastlane-plugin-sentry    | 1.7.0   | sentry_upload_dsym       |
|                           |         | sentry_set_commits       |
|                           |         | sentry_upload_sourcemap  |
|                           |         | sentry_finalize_release  |
|                           |         | sentry_upload_file       |
|                           |         | sentry_upload_proguard   |
|                           |         | sentry_create_release    |
| fastlane-plugin-fir_cli   | 2.0.9   | fir_cli                  |
| fastlane-plugin-ding_talk | 0.1.1   | ding_talk                |
+---------------------------+---------+--------------------------+

[09:28:39]: Unknown method 'response_to?'

[!] To call another action from an action use `other_action.response_to?` instead
```

2020-12-01 01:58 UTC, philCc commented
> @philCc Ahhhh, I see! I think the fix should actually be made in the plugin 😊
> 
> The issue is these classes within the action itself 👉 https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb#L179-L200
> 
> 1. You could fix this by putting a `private` above that section of code (I think)
> 2. Or these classes should get moved into https://github.com/FIRHQ/fastlane-plugin-fir_cli/blob/master/lib/fastlane/plugin/fir_cli/helper/fir_cli_helper.rb
> 
> Let me know your thoughts on that!

The solution is feasible, I will create a PR for this plugin.
But, I still think we should do a validation on the Fastlane layer

2020-12-01 02:03 UTC, philCc commented
> Good call on keeping this in here. How does something like this look though? I think this should still fix it for you!

Hi, @joshdholtz 
An error will occur here
```
Updating plugin dependencies...
[✔] 🚀
/Users/pz/.rvm/gems/ruby-2.6.5/bundler/gems/fastlane-plugin-fir_cli-45c6ca10c187/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:183: warning: already initialized constant FIR::VERSION
/Users/pz/.rvm/gems/ruby-2.6.5/gems/fir-cli-2.0.10/lib/fir/version.rb:4: warning: previous definition of VERSION was here
+---------------------------+---------+--------------------------+
|                          Used plugins                          |
+---------------------------+---------+--------------------------+
| Plugin                    | Version | Action                   |
+---------------------------+---------+--------------------------+
| fastlane-plugin-pgyer     | 0.2.2   | pgyer                    |
| fastlane-plugin-sentry    | 1.7.0   | sentry_upload_dsym       |
|                           |         | sentry_set_commits       |
|                           |         | sentry_upload_sourcemap  |
|                           |         | sentry_finalize_release  |
|                           |         | sentry_upload_file       |
|                           |         | sentry_upload_proguard   |
|                           |         | sentry_create_release    |
| fastlane-plugin-fir_cli   | 2.0.9   | fir_cli                  |
| fastlane-plugin-ding_talk | 0.1.1   | ding_talk                |
+---------------------------+---------+--------------------------+

[09:28:39]: Unknown method 'response_to?'

[!] To call another action from an action use `other_action.response_to?` instead
```

2020-12-04 15:05 UTC, joshdholtz commented
@philCc I totally did lol 😛 I typo-ed 🤷‍♂️

2020-12-04 15:13 UTC, joshdholtz approved these changes
This looks great! Thanks for the contribution ❤️

2020-12-04 15:14 UTC, merged