Conditional compiler directive
fastlane/fastlane pull request #17687
Opened 2020-11-27 20:40 UTC by minuscorp

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Solves  #17423 

### Description

### Testing Steps

2020-11-30 21:06 UTC, joshdholtz reviewed
This looks great! Does this just need some testing for it to be ready to ship? 😊

2020-11-30 21:22 UTC, minuscorp commented
Yeah, i wrote this from the ipad because i was sure of what was the issue, but I haven't been able of testing it. Also, I wasn't totally sure of this being a real issue, but as we do support Swift 4, this directive had to be change, which is against of the apple docs (irony: _weird doesn't it?_) so tomorrow I'll compile in swift 4 mode and see if it works just fine!

2020-12-01 15:07 UTC, rogerluan requested changes

2020-12-01 15:07 UTC, rogerluan commented on snapshot/lib/assets/SnapshotHelper.swift
> +                #if Swift(<5.0)
>Unexpected platform condition (expected 'os', 'arch', or 'swift')

```suggestion
                #if swift(<5.0)
```

🎉

2020-12-01 15:08 UTC, rogerluan approved these changes
LGTM! 🚀

2020-12-01 16:19 UTC, merged