Update onesignal.rb
fastlane/fastlane pull request #17696
Opened 2020-11-30 22:41 UTC by brandon-carpenter

adds optional, organization_id, paramater to onesignal.rb

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This change adds the [Onesignal](https://documentation.onesignal.com/reference/create-an-app) organization_id as an optional parameter.  Presently, when new Onesignal applications are created, they are created without being assigned to an organization.  This allows end users to specify an organization_id if desired.  Apps created under an organization will delegate the Onesignal org-level-admins to that application.  Org-level-admins are unable to view/modify apps not within the organization.

No issue has been created.  Please let me know if you'd like an issue created for this PR.

### Description
The additional parameter was added inline with the other parameters in onesignal.rb.  Payload has been updated along with self.available_options, and self.example_code.  

Both `bundle exec rubocop -a` and `bundle exec rspec` as referenced [here](https://github.com/fastlane/fastlane/blob/master/Testing.md) were ran following the changes.
  

### Testing Steps
`bundle exec onesignal` was ran with a Fastfile containing the necessary parameters including `organization_id`.   This resulted in a new application being created within Onesignal under the provided organization_id. This allowed org-level-admins to view the newly created onesignal application.  Additionally,  the changes were ran on an app update successfully, and on an app without the organization_id provided.  On the latter, the app was created without being assigned to an organization. The changes will also update an application that was created outside of an organization and will move it under the provided organization.

2020-11-30 22:44 UTC, brandon-carpenter commented
@googlebot I signed it!

2020-12-02 17:14 UTC, joshdholtz requested changes
This looks good! Just a few small requests 😊

2020-12-02 17:14 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/onesignal.rb
> +        organization_id = params[:organization_id].to_s.strip
Calling `.to_s.strip` would never allow `organization_id` to be `nil` so I think we need to remove this 😊 

```suggestion
        organization_id = params[:organization_id]
```

2020-12-02 17:14 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/onesignal.rb
> +                                       env_name: "ORGANIZATION_ID",
```suggestion
                                       env_name: "ONE_SIGNAL_ORGANIZATION_ID",
```

2020-12-02 17:14 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/onesignal.rb
> +                                       description: "ONESIGNAL ORGANIZATION ID",
```suggestion
                                       description: "OneSignal Organization ID",
```

2020-12-02 19:16 UTC, brandon-carpenter commented
Updated with your suggestions.  Thanks!

2020-12-04 15:04 UTC, joshdholtz approved these changes
Looks great! Thank you so much for the contribution ❤

2020-12-04 15:04 UTC, merged