Scan retry after failure
fastlane/fastlane pull request #17765
Opened 2020-12-09 15:16 UTC by xavierLowmiller

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
(Solves https://github.com/fastlane/fastlane/issues/8648)

UI tests are still a bit too unpredictable to entirely trust them. Many developers use UI testing as E2E tests, which opens them up to more intermittent errors like network failures.
Making UI tests more resilient against any kind of failure is cumbersome to impossible. Mostly, testers want to just retry tests (as a human would in many situations), and this PR enables this for fastlane's `scan`.

There are some plugins that add the possibility to retry tests to fastlane (perhaps most notably [test-center](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center). I have tried many, but found that most of them have tradeoffs or just don't work.

### Description

Adds a new parameter to `scan`: `number_of_retries`, (which is zero by default, keeping current behavior.)
This will retry any failing tests (and only the failing tests) after a test run.
This works by

### Testing Steps
1. Create a new app for testing and run `fastlane init`
2. Create a test that fails randomly
```swift
func testCoinToss() {
    XCTAssert(Bool.random())
}
```
3. Run scan with the `number-of-retries` flag
```
bundle exec fastlane scan --number-of-retries 3
```

The tests should pass, even if `testCoinToss` initially fails. All passing tests should only run once, while `testCoinToss` should be run multiple times until it succeeds (at most 3 times).

2021-03-15 10:30 UTC, joshdholtz requested changes
I’ve tested this out and got a few issues I ran into. I don’t expect you to fix these since it took me so long ot get to looking at this 🤦  My apologies on that! This is a great addition and I’d love to get this merged in. I will be looking into how to fix the errors I’ve mentioned but I just wanted to put these notes here 😊

2021-03-15 10:30 UTC, joshdholtz commented on scan/lib/scan/runner.rb
> +      suites = failing_tests.split(/(?=\n\s+[\w\s]+:\n)/)
This is having issues parsing the output 🤔 I’m going to look into how to fix this 😊

2021-03-15 10:30 UTC, joshdholtz commented on scan/lib/scan/runner.rb
> +      execute(command: command, devices: Scan.devices)
Rerunning this throws an error with 👇 

```sh

xcodebuild: error: Existing file at -resultBundlePath "/Users/josh/Projects/fastlane/test-ios-2/fastlane/test_output/FastlaneApp.xcresult" 
```

I think I need to look at a way to remove this existing `xcresult` for the retries 🤷‍♂️

2021-03-15 11:32 UTC, joshdholtz commented on scan/lib/scan/runner.rb
> +      execute(command: command, devices: Scan.devices)
Got a fix for this 💪

2021-03-15 11:32 UTC, joshdholtz commented on scan/lib/scan/runner.rb
> +      suites = failing_tests.split(/(?=\n\s+[\w\s]+:\n)/)
I cannot reproduce this now but I’m going to make this a little bit safer 🤷

2021-03-15 11:35 UTC, xavierLowmiller commented
> I’ve tested this out and got a few issues I ran into. I don’t expect you to fix these since it took me so long ot get to looking at this 🤦 My apologies on that! This is a great addition and I’d love to get this merged in. I will be looking into how to fix the errors I’ve mentioned but I just wanted to put these notes here 😊

Hey Josh, thanks for looking at this!

Feel free to take over the PR, it's been a long time since I've worked on this and it would take some time until I could address the issues.
I think it's best if you just make the changes that are needed to get this merged.

2021-03-15 11:41 UTC, joshdholtz commented
@xavierLowmiller No problem at all! I want to apologize again for taking so long to get to this. Me and my wife were actually at the hospital the day this PR was made waiting for our son to be born so I got a little bit backlogged 🤷‍♂️ 

I think I got all the changes made but I’m going to be adding a few tests now. Would you be able to test out my changes once I push them? No problem if not though! It has been a while lol

2021-03-15 11:42 UTC, xavierLowmiller commented
Congrats on your baby son!

I'd love to test your changes ✌️

2021-03-15 13:31 UTC, joshdholtz commented
@googlebot I consent.

2021-03-15 17:03 UTC, joshdholtz commented
@xavierLowmiller Ready for you to test whenever you got time! No rush on my part though 😇

2021-03-18 22:39 UTC, xavierLowmiller commented
Just got a chance to check this out, and it works exactly like I intended!

Thanks for finishing this up!

2021-04-07 11:33 UTC, joshdholtz approved these changes
Thanks for making this PR! Excited to get this feature released 😊 Really appreciate the contribution ❤️

2021-04-07 11:33 UTC, merged

2021-04-08 01:41 UTC, lyndsey-ferguson commented
Color me sad. Too bad test-center didn't fulfill what you were looking for @xavierLowmiller .