Allow --enable-code-coverage option on spm action test command
fastlane/fastlane pull request #17805
Opened 2020-12-14 21:42 UTC by Ast3r10n

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Previously, the --enable-code-coverage option was only available for the generate-xcodeproj command.

Allowing its use for the test command would enable code coverage reports for the test command as well.

### Description

The --enable-code-coverage option is now also usable when using the test command.

### Testing Steps

Use the spm action with the test command and set the enable_code_coverage option to true: the command should now gather coverage reports.

2020-12-16 06:05 UTC, rogerluan requested changes
Thanks for your contribution! 🙌 

Left a minor copy change request. Also could you also update the description on line 318 of `spm_spec.rb` to add "for generate-xcodeproj"? 😊  https://github.com/fastlane/fastlane/pull/17805/files#diff-05fa981c4fb9fd6ca1fe98ee8a29caa1350f6062592e64c81b4798b7d3ed6b69R318

2020-12-16 06:05 UTC, rogerluan commented on fastlane/lib/fastlane/actions/spm.rb
> +                                       description: "Enables code coverage for the test command and the generated Xcode project when using the generate-xcodeproj command",
```suggestion
                                       description: "Enables code coverage for the generated Xcode project when using the 'generate-xcodeproj' and the 'test' command",
```

2020-12-17 16:10 UTC, rogerluan approved these changes
Nice work! 🚀 code LGTM!

2020-12-21 14:13 UTC, Ast3r10n commented
Hello @rogerluan, is this PR blocked by the unsuccessful checks? 
They actually failed for the new Homebrew requirements, so they should pass now. Would it be possible to re-run the checks to allow this PR to be merged?

2020-12-22 11:26 UTC, rogerluan commented
@Ast3r10n actually I don't have access to our CI to retrigger it 😬 But yeah CI would need to pass. Can you push something to retrigger to see if it passes? Maybe merge master into this branch?

We might get this merged later this week 🙏

2020-12-22 11:35 UTC, Ast3r10n commented
@rogerluan done, let's see what happens!

2020-12-22 12:23 UTC, rogerluan commented
> @rogerluan done, let's see what happens!

It worked! 💪 thanks!

2020-12-31 22:27 UTC, joshdholtz approved these changes
This is 🔥 Thank you for the contribution! Really appreciate it ❤️

2020-12-31 22:27 UTC, merged