update `application-identifier` key when parsing the provisioning pro…
fastlane/fastlane pull request #17865
Opened 2020-12-27 04:18 UTC by johndbritton

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
  - there are a few test failures currently (expected, due to not supporting the old key name yet)
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
  - none needed

### Motivation and Context

This is just a quick draft of trying to resolve https://github.com/fastlane/fastlane/issues/17864. This is my first time contributing to Fastlane (and also my first time using it) so I just wanted to file the issue and get a draft up to see if I'm going in the right direction.

### Description

When using the `build_mac_app` action, Fastlane parses the provisioning profile, but it errors out (see linked issue for more details) when it tries to read the application identifier from a key `application-identifier`. The profile contains the required info in the `com.apple.application-identifier` key, which I suppose was a change made by Apple, but I'm not entirely sure.

### Testing Steps

I made this change locally and it resolved my issue with parsing the provisioning profile.

2020-12-27 04:25 UTC, johndbritton commented
@googlebot I signed it!

2020-12-30 23:54 UTC, joshdholtz requested changes
This looks great! Thanks for finding this 😊 How do you feel about this suggestion so that it keeps backwards compatibility? 😇

2020-12-30 23:54 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/build_app.rb
> +                bundle_id = profile["Entitlements"]["com.apple.application-identifier"].gsub("#{app_id_prefix}.", "")
```suggestion
                entitlements = profile["Entitlements"]
                bundle_id = (entitlements["application-identifier"] || entitlements["com.apple.application-identifier"]).gsub("#{app_id_prefix}.", "")
```

2021-01-02 01:38 UTC, johndbritton commented
> This looks great! Thanks for finding this 😊 How do you feel about this suggestion so that it keeps backwards compatibility? 😇

@joshdholtz yep I expected we'd change this, all good.

2021-01-03 00:11 UTC, johndbritton commented
@joshdholtz I think this is good to go now. Not sure what is failing on CircleCI and I can't get access to the output without giving them read access to all private repositories on my account.

2021-01-09 15:47 UTC, rogerluan approved these changes
👌 nice find!

2021-01-09 15:48 UTC, rogerluan commented
@johndbritton if you update your branch with fastlane's latest master, those CI issues should be gone 🙏

2021-01-09 15:57 UTC, johndbritton commented
@rogerluan rebased off the latest master.

2021-01-09 21:54 UTC, rogerluan requested changes
@johndbritton could you fix the linter issues? 🙏 

```
Offenses:

fastlane/lib/fastlane/actions/build_app.rb:11:7: C: Perceived complexity for run is too high. [19/18]
      def self.run(values)
      ^^^
```

2021-01-11 14:32 UTC, johndbritton commented
@rogerluan This is what I get when I run the linter locally:

```
bundle exec rubocop fastlane/lib/fastlane/actions/build_mac_app.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

The `run` method is indeed quite complex, but I believe that's out of the scope of this pull request. Maybe someone else who is more familiar with this codebase can tidy that method up. Or we could ignore the complexity check for this method.

2021-01-11 16:20 UTC, rogerluan commented
@googlebot I consent.

2021-01-11 16:20 UTC, rogerluan commented
@johndbritton huh weird that it doesn't show the issue locally 🤔 

Anyway, usually I'd be against skipping these kind of lints because master is fine and this PR is supposedly adding the extra complexity that makes this function "too complex". However, I'm fine with adding a rubocop comment to disable complexity check for this function, because it already looks overly complex, and it looks like the # `rubocop:disable Metrics/PerceivedComplexity` should already be there anything (since there's a `:enable` matching comment at the end of that function).

I've added it, since I was already at it 😊 hope you don't mind. 

```
be rubocop fastlane/lib/fastlane/actions/build_app.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

2021-01-11 16:21 UTC, rogerluan approved these changes
👌

2021-01-11 19:03 UTC, johndbritton commented
> I've added it, since I was already at it 😊 hope you don't mind.

Thanks!

2021-01-13 01:14 UTC, johndbritton commented
@joshdholtz I think this needs your approval to be merged.

2021-01-20 10:46 UTC, joshdholtz commented
@johndbritton Ah sorry! Merging now and releasing today 💪 Being new parent has got me all sorts of behind 😅

2021-01-20 10:52 UTC, joshdholtz approved these changes
Thanks for making these changes! I really appreciate the contribution ❤️

2021-01-20 10:52 UTC, merged