Appetize timeout support
fastlane/fastlane pull request #18074
Opened 2021-01-29 17:12 UTC by raulriera

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Adding support for the `timeout` option in Appetize, as seen in their documentation https://docs.appetize.io/api/update-existing-app it would be ideal to support more than the default 2mins.

### Description
Expanded the `appetize` and `build_and_upload_to_appetize` actions to include this parameter. Also included the appropriate validations and test to make sure we always submit the values specified by Apptize themselves.

### Testing Steps
Running `bundle exec rspec ./fastlane/spec/actions_specs/appetize_spec.rb ` will result in green tests.

2021-01-29 17:13 UTC, raulriera commented
@googlebot I signed it!

2021-01-29 17:16 UTC, raulriera commented on fastlane/lib/fastlane/actions/build_and_upload_to_appetize.rb
> +                              timeout: params[:timeout])
Wasn't able to find a test for using this file

2021-02-05 20:25 UTC, Caiopia reviewed
Code looks good to me, just some minor suggestions. Haven't tested this yet though.

2021-02-05 20:25 UTC, Caiopia commented on fastlane/swift/Fastlane.swift
> +                     timeout: Integer? = nil)
Can't comment on the exact line, but we could update the docs for this new parameter too. Same with the `buildAndUploadToAppetize` function below.

2021-02-05 20:25 UTC, Caiopia commented on fastlane/swift/Fastlane.swift
> +                                     timeout: Integer?)
Any reason this shouldn't have the same default value as above?

2021-02-07 13:15 UTC, minuscorp requested changes
Initially it seems good to me. A few notes, don't push Swift changes add they are autogenerated by fastlane, and add to the `ConfigItem` the `:type` key to pass it correctly to the Swift code (I.e. `Integer`)

2021-02-07 16:42 UTC, raulriera commented
Hey @minuscorp , what are the request changes? GitHub is not showing any information

2021-02-07 16:57 UTC, raulriera commented
Thanks for the review @minuscorp, code is updated. I didn't found anything in the docs about generating the swift code. Is there a step I need to do for this?

2021-02-07 17:52 UTC, minuscorp commented
Just try to update it locally and see if the changes that you expect are done, there's a lane called `generate_swift_api` or similar that updates and build the whole interface and SPM package.

2021-02-07 18:42 UTC, raulriera commented
Thanks, that did it. Should I include the output of all that generation here? (more files were changed) or is that only a release process?

2021-02-07 19:15 UTC, minuscorp commented
That's part of the release process, but that way you can make sure that your changes are good. Useful for contributions 🎉

2021-02-07 20:29 UTC, minuscorp approved these changes
LGTM 🎉

2021-02-09 20:55 UTC, joshdholtz approved these changes
This is 🔥 Thanks so much for adding this! Really appreciate the contribution ❤️

2021-02-09 20:55 UTC, merged