Add skip_info parameter to increment_build_number to avoid updating Info.plist
fastlane/fastlane pull request #18372
Opened 2021-03-10 02:24 UTC by lhunath

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This is important when Info.plist is configured to reference $(CURRENT_PROJECT_VERSION).

Fixes #18367

### Description
The issue is caused by passing `-all` to `agvtool`. This change makes `-all` optional by allowing the developer to turn it off.

2021-03-10 04:57 UTC, joshdholtz requested changes
One small nit pick in the naming 😊 This PR look 💯 other than this! ❤️

2021-03-10 04:57 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/increment_build_number.rb
> +                                       env_name: "FL_BUILD_NUMBER_SKIP_INFO",
```suggestion
          FastlaneCore::ConfigItem.new(key: :skip_info_plist,
                                       env_name: "FL_BUILD_NUMBER_SKIP_INFO_PLIST",
```

2021-03-10 04:57 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/increment_build_number.rb
> +        mode = params[:skip_info] ? '' : '-all'
```suggestion
        mode = params[:skip_info_plist] ? '' : '-all'
```

2021-03-10 13:52 UTC, minuscorp commented on fastlane/lib/fastlane/actions/increment_build_number.rb
> +                                       default_value: false),
Add `type: Boolean` for a nice parsing into Swift 🙏

2021-03-11 11:49 UTC, joshdholtz commented
@googlebot I consent.

2021-03-11 12:29 UTC, joshdholtz approved these changes
Thanks for adding this feature in! I added a commit in here to add some tests but other than that this was 💯 Really appreciate the contribution ❤️

2021-03-11 12:29 UTC, merged

2021-03-11 12:56 UTC, Dinsen commented
@joshdholtz remember to change the title to contain the key that was updated doing the review `add skip_info_plist..` so release notes are correct 🥰

2021-03-11 12:57 UTC, joshdholtz commented
@Dinsen Thanks for reminder!