[match][change_password] re-encrypt using new password instead of MATCH_PASSWORD env var
fastlane/fastlane pull request #18389
Opened 2021-03-13 03:10 UTC by rogerluan

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #15942
Resolves #17968

### Description

`encrypt_files` was being called without informing the new password as an argument. As a result, it would invoke `fetch_password` which reads the password from the env var. Worst case scenario, if the env var is not set, it either asks the user for the password again (if interactive) or crashes.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan/fix-change-password-new-password"
```

And run `bundle install` to apply the changes.

The test scenario is: call `change_password` with an env var `MATCH_PASSWORD` set. After re-encrypting the files, check if the encrypted files can be decrypted using the password you provided in `change_password`

2021-03-15 17:08 UTC, mdentremont commented
Thanks @rogerluan -- unfortunately I've since recreated the repository, and also no longer have access to the machine where we were seeing this issue.

That being said, I looked at the diff and that would seem to solve the issue that I was running into 👍

2021-03-16 17:21 UTC, rogerluan commented
Thanks for getting back to this @mdentremont 🤗 and for the code review! 💪 

@stherold was able to confirm this solved his problem specifically (which symptoms were a bit different than the OP, but had the same root cause) - https://github.com/fastlane/fastlane/issues/17909#issuecomment-800123103

2021-03-17 02:17 UTC, joshdholtz requested changes
This change looks great! Thanks for fixing ❤️ Just a few small changes in the tests 😇

2021-03-17 02:17 UTC, joshdholtz commented on match/spec/encryption/openssl_spec.rb
> +      ENV["MATCH_PASSWORD"] = ""
This will prevent the `ENV` value from carrying over between tests

```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => "" }
```

2021-03-17 02:17 UTC, joshdholtz commented on match/spec/encryption/openssl_spec.rb
> +      ENV["MATCH_PASSWORD"] = "something else"
```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => "something else"}
```

2021-03-17 02:17 UTC, joshdholtz commented on match/spec/encryption/openssl_spec.rb
> +      ENV["MATCH_PASSWORD"] = new_password
```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => new_password}
```

2021-03-17 04:15 UTC, rogerluan commented
Thanks for the tip @joshdholtz ! Updated all the env vars in this file 😊

2021-03-18 08:45 UTC, joshdholtz commented
@googlebot I consent.

2021-03-18 09:49 UTC, joshdholtz approved these changes
This is 💯 now! Thank you so much going for fixing this ❤️

2021-03-18 09:49 UTC, merged