[screengrab] Fix screenshots on Android Q and above
fastlane/fastlane pull request #18434
Opened 2021-03-21 17:35 UTC by KartikSoneji

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Trying to capture screenshots with `screengrab` on Android versions >= Android Q (v10, API version 29) fails on Windows.
Resolves #18335

### Description
`FastlaneCore::Helper.which` uses the platform-specific path separator (`/` on UNIX, `\` on Windows).  
Adds a new method, `FastlaneCore::Helper.localize_file_path(path)` that fixes the path separator.

Fixes the command used to extract the screenshots as described in [the issue](https://github.com/fastlane/fastlane/issues/18335#issuecomment-790676320)
<blockquote>
Microsoft is including some UNIX commands like `tar` and `curl` in the standard install of Windows ([source](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)).

```batch
> where tar
C:\Windows\System32\tar.exe
```

The bundled `tar` is a version of `bsdtar`
```batch
> tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
```

Piping the output directly doesn't work
```batch
> type archive.tar | tar -xvC folder
tar: Error opening archive: Failed to open '\\.\tape0'
The process tried to write to a nonexistent pipe.
```

Fortunately, specifying the input file with `-f-` works
```batch
> type archive.tar | tar -f- -xvC folder
```
</blockquote>

### Testing Steps
On a Windows PC:
- Create an Android Emulator running Android Q or higher
- Setup Fastlane and Screengrab for an Android Project
- Run `fastlane screengrab` for the project

2021-03-24 14:20 UTC, joshdholtz requested changes
This is a good fix! Thanks for catching this 😊 Just one small suggestion!

2021-03-24 15:34 UTC, KartikSoneji commented on fastlane_core/lib/fastlane_core/helper.rb
> +      cmd_path = localize_file_path(cmd_path)
The `localize_file_path` function is used multiple times, so I think you mean something like this?
```diff
diff --git a/fastlane_core/lib/fastlane_core/helper.rb b/fastlane_core/lib/fastlane_core/helper.rb
index 72ab5f36a..20f66d759 100644
--- a/fastlane_core/lib/fastlane_core/helper.rb
+++ b/fastlane_core/lib/fastlane_core/helper.rb
@@ -398,7 +398,7 @@ module FastlaneCore
     # returns the path with the platform-specific path separator (`/` on UNIX, `\` on Windows)
     def self.localize_file_path(path)
       # change `/` to `\` on Windows
-      return self.windows? ? path.gsub('/', '\\') : path
+      return path.gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR)
     end
 
     # checks if given file is a valid json file
```

But that would mean duplicating the setup for all the tests:
```diff
diff --git a/fastlane/spec/actions_specs/adb_spec.rb b/fastlane/spec/actions_specs/adb_spec.rb
index c148b8cae..b2dfdb7a8 100644
--- a/fastlane/spec/actions_specs/adb_spec.rb
+++ b/fastlane/spec/actions_specs/adb_spec.rb
@@ -3,6 +3,7 @@ describe Fastlane do
     describe "adb" do
       before(:each) do
         allow(FastlaneCore::Helper).to receive(:windows?).and_return(false)
+        allow(File).to receive(:ALT_SEPARATOR).and_return(nil)
       end
 
       it "generates a valid command" do
@@ -78,6 +79,7 @@ describe Fastlane do
     describe "adb on Windows" do
       before(:each) do
         allow(FastlaneCore::Helper).to receive(:windows?).and_return(true)
+        allow(File).to receive(:ALT_SEPARATOR).and_return('\\')
       end
 
       it "generates a valid command" do
```

2021-03-25 02:15 UTC, joshdholtz commented on fastlane_core/lib/fastlane_core/helper.rb
> +      cmd_path = localize_file_path(cmd_path)
@KartikSoneji Oh shoot, it is used multiple times! 😱 I thought I only saw it used once which is why I suggested what I did. My bad 🤦‍♂️ 

Hmmmm... I don’t like those changes to the tests 😔 

I think what you had originally is okay 😊 We’ll go with that! Thanks for looking into!

2021-03-25 02:16 UTC, joshdholtz approved these changes
Turns out this is good and I was crazy during my first review 😛 Really appreciate the contribution! Thank you ❤️

2021-03-25 02:16 UTC, merged

2021-04-20 10:25 UTC, penn5 commented
Many devices don't have tar installed. There are also large issues with the current Android-side helper implementation across various android versions. Please see #18003 where I fixed (some of?) these. It looks like my PR fell through some cracks and just didn't get reviewed. :(