[action][app_store_connect_api_key] fixed `is_supported`
fastlane/fastlane pull request #18462
Opened 2021-03-28 13:08 UTC by crazymanish

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- I was going through the documentation https://docs.fastlane.tools/actions/
- Notice that: `app_store_connect_api_key` is showing support for all platforms `ios, android, mac` 

### Description
- Updated the `is_supported` and make it for `ios, mac` platform only

### Testing Steps
- 🤪

2021-03-28 19:23 UTC, Dinsen approved these changes

2021-04-02 17:12 UTC, joshdholtz requested changes
One small request to also add `:tvos` ☺️

2021-04-02 17:12 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/app_store_connect_api_key.rb
> +        [:ios, :mac].include?(platform)
```suggestion
        [:ios, :mac, :tvos].include?(platform)
```

2021-04-06 02:40 UTC, joshdholtz approved these changes
🔥 Thank you for the contribution! Really appreciate it ❤️

2021-04-06 02:41 UTC, merged