[action][git_submodule_update] documentation improvements
fastlane/fastlane pull request #18598
Opened 2021-04-24 21:10 UTC by crazymanish

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

- `git_submodule_update` action documentation was slightly off/incorrect 😇

### Description
- Updated the description
- Updated the ConfigItem(s), make them consistent, fixed alignment and added verify_block. 
- Added **example_code** 

### Testing Steps
- Nothing changed in functionality.
- All existing unit tests are passing i.e in `git_submodule_update_spec.rb`

2021-04-24 21:48 UTC, crazymanish commented
One match unit-test failed which is completely unrelated 😇

<img width="1134" alt="Screenshot 2021-04-24 at 23 47 29" src="https://user-images.githubusercontent.com/5364500/115973717-8b230d00-a557-11eb-8d6a-632165fe299f.png">

2021-04-30 15:53 UTC, joshdholtz requested changes
Some suggestions on things that can be removed 😊

2021-04-30 15:53 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/git_submodule_update.rb
> +                                       is_string: false,
`is_string` can be removed 😊 `type` overrides `is_string` and `is_string` is starting to get phased out

2021-04-30 15:53 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/git_submodule_update.rb
> +                                       is_string: false,
Same here - `is_string` can be removed

2021-04-30 17:12 UTC, crazymanish commented
Thank you for your review, applied suggestions! 😇 @joshdholtz

2021-04-30 17:32 UTC, joshdholtz approved these changes
This is much better! Thanks for improving this action ❤️ Really appreciate another one of your contributions!

2021-04-30 17:32 UTC, merged