[action][danger] Add fail-if-no-pr flag to Danger action
fastlane/fastlane pull request #18657
Opened 2021-05-07 20:19 UTC by minuscorp

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This PR adds the missing `fail-if-no-pr` flag of Danger action that was missing from the config.

### Description
Added the corresponding `ConfigItem` and append it to the command in the Danger call.

### Testing Steps
1. Checkout and install the following fastlane’s branch.
2. Use the Danger action and test that the `fail-if-no-pr` flag is added when configured like so.
3. 🚀

2021-05-13 16:51 UTC, ainame approved these changes
🥇

2021-05-13 16:51 UTC, ainame commented on fastlane/lib/fastlane/actions/danger.rb
> +                                       type: Boolean,
😉

2021-05-13 23:59 UTC, joshdholtz requested changes
Some small change otherwise 💯

2021-05-13 23:59 UTC, joshdholtz commented on fastlane/lib/fastlane/actions/danger.rb
> +                                       optional: true,
Optional can be removed if there is a `default_value` for a `type: Boolean` 😊

2021-05-14 13:35 UTC, joshdholtz reviewed
Perfect! Thanks for adding this ❤️

2021-05-14 13:35 UTC, joshdholtz approved these changes

2021-05-14 13:35 UTC, merged