[Regression][fastlane_core][pilot] Fix pilot is unable to select build when distribute_only is true and app_version is not provided
fastlane/fastlane pull request #18710
Opened 2021-05-18 21:15 UTC by lucgrabowski

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Pilot is unable to automatically select the build with `distribute_only` option, starting from version `2.181.0`. With changes from `2.183.0`, instead of infinite loop in `BuildWatcher`, there was a crash with error message "There is no app version to watch"
Resolves #18606 

### Description

Analysis done in comment in issue: https://github.com/fastlane/fastlane/issues/18606#issuecomment-842590188
`BuildWatcher` will send a request for the latest build if `app_version` is not provided even if `select_latest` is `false` (which happens for `pilot`).

### Testing Steps

Tested with specs

2021-05-19 08:49 UTC, joshdholtz requested changes
@lucgrabowski Thanks for taking the time to look into this and fix it! I think this works but can I suggest maybe doing a different change instead 😇 I think I’d like to keep this logic that raises an error if `select_latest` is `false` because `deliver` uses this behavior. So I think we can accomplish the correct behavior for `pilot` if we pass in `select_latest` if no app version and distribute only.

Thoughts? 🤔 

https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L102-L110

I think if we add…
```
select_latest: app_version.nil? && config[:distribute_only]
```

2021-05-19 23:23 UTC, lucgrabowski commented
@joshdholtz I've committed the change to raise an error if `select_latest` is `false` and started to think about it more.
I see a difference between `pilot` and `deliver`. 
For `deliver` `select_latest` is always `true` (we cannot get a `Found more than 1 matching build ...` crash, can we?)
For `pilot` it's possible to have `false` for `distribute_only` when `app_version` is not `nil`. If `build_number` is `nil` and there are 2 builds for the version (e.g. 1.0.0(1) and 1.0.0(2)), we will get a crash with `Found more than 1 matching build ...`. Is it the expected result if someone sets `app_version` but doesn't set `build_number` to get a crash?
Maybe we should leave either
`select_latest: config[:distribute_only]`?

2021-05-19 23:24 UTC, lucgrabowski commented
@joshdholtz I've committed the change to raise an error if `select_latest` is `false` and started to think about it more.
I see a difference between `pilot` and `deliver`. 
For `deliver` `select_latest` is always `true` (we cannot get a `Found more than 1 matching build ...` crash, can we?)
For `pilot` it's possible to have `false` for `distribute_only` when `app_version` is not `nil`. If `build_number` is `nil` and there are 2 builds for the version (e.g. 1.0.0(1) and 1.0.0(2)), we will get a crash with `Found more than 1 matching build ...`. Is it the expected result if someone sets `app_version` but doesn't set `build_number` to get a crash?
Maybe we should leave:
`select_latest: config[:distribute_only]`?

2021-05-28 14:54 UTC, joshdholtz commented
@lucgrabowski I think you are right here! Let's just use `select_latest: config[:distribute_only]` 😊 I'll add a commit and get this merged today

2021-05-28 15:23 UTC, joshdholtz commented
@googlebot I consent.

2021-05-28 16:23 UTC, joshdholtz approved these changes
This is great! Thank you so much for fixing this 😊 This will be going out today!

2021-05-28 16:23 UTC, merged

2021-05-28 17:25 UTC, lucgrabowski commented
Thanks for merging @joshdholtz. Should https://github.com/fastlane/fastlane/issues/18545 be also closed? It wasn't linked to this PR, but as @andrewclaus said, it might have been fixed with this.