[Fastlane.Swift] Treat `Bool` as optional to avoid config issues
fastlane/fastlane pull request #18827
Opened 2021-06-08 13:57 UTC by minuscorp

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes #17343. This PR aims to treat all `Bool` types as `OptionalConfigValue`s, so the Ruby's default one is used in order to avoid config issues

### Description
Adds `Bool` type to the list of candidates to be a `OptionalConfigValue`.

### Testing Steps
1. Checkout and install this branch
2. Build the interface with `bundle exec fastlane generate_swift_api`
3. Check the source in `Fastlane.swift` and check that all `Bool` arguments are now `OptionalConfigValue<Bool>`

2021-06-10 21:33 UTC, joshdholtz requested changes
I seem to still get the error mentioned in the issue 🤔 

```sh
[!] You can't enable both :developer_id and :adhoc  
```

Were you not getting that?

2021-06-11 10:28 UTC, minuscorp commented
With which parameters are you getting that? I'll try to debug it better this weekend🙏

2021-06-11 18:39 UTC, joshdholtz commented
@minuscorp I tried with exactly what was in the issue 🤷‍♂️ Even kept the "XXX" 😛 

```swift
func fetcherLane() {
        getProvisioningProfile(
            appIdentifier: "XXX",
            username: "XXX",
            teamId: "XXX",
            teamName: "XXX",
            provisioningName: "XXX",
            ignoreProfilesWithDifferentName: true,
            certOwnerName: nil,
            skipFetchProfiles: true,
            skipCertificateVerification: true,
            readonly: true
        )
    }
```

2021-06-11 19:10 UTC, minuscorp commented
I messed up with the code I was testing with and fixing it fixed another part that was failing because of it. So... all good now.

2021-06-11 21:58 UTC, joshdholtz approved these changes
Yessssssss, this worked!!! Thank you for fixing ❤️

2021-06-11 21:59 UTC, merged