[spaceship] Adding three missing beta testers/groups methods
fastlane/fastlane pull request #19039
Opened 2021-07-01 19:40 UTC by gsavit

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Implementing the following missing TestFlight endpoints for beta testers/groups related functionality:

[Add testers to build](https://developer.apple.com/documentation/appstoreconnectapi/assign_individual_testers_to_a_build)
[Remove testers from build](https://developer.apple.com/documentation/appstoreconnectapi/remove_individual_testers_from_a_build)
[Remove groups from build](https://developer.apple.com/documentation/appstoreconnectapi/remove_access_for_beta_groups_to_a_build)

2021-07-02 15:27 UTC, joshdholtz requested changes
This is great! Thanks for adding these 😊 Just a few suggestions about the order of method parameters so we can keep things consistent

2021-07-02 15:27 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/testflight/testflight.rb
> +        def delete_beta_groups_from_build(beta_group_ids: [], build_id: nil)
```suggestion
        def delete_beta_groups_from_build(build_id: nil, beta_group_ids: [])
```

2021-07-02 15:27 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/testflight/testflight.rb
> +        def delete_beta_testers_from_build(beta_tester_ids: [], build_id: nil)
```suggestion
        def delete_beta_testers_from_build(build_id: nil, beta_tester_ids: [])
```

2021-07-02 15:32 UTC, gsavit commented
> This is great! Thanks for adding these 😊 Just a few suggestions about the order of method parameters so we can keep things consistent

For sure, thanks for the review Josh! I wasn't too sure what to do with the ordering as it seemed to already vary within the file 😅

2021-07-06 14:18 UTC, kerrmarin-lvmh commented
This is awesome! And I believe it will fix #17899 ?

2021-07-07 14:12 UTC, gsavit commented
> This is awesome! And I believe it's a first step towards fixing #17899 ?

Thanks! I don't quite think this has anything to do with that other issue, unless I'm missing something? (Incidentally, separately, I've been poking around looking for `betaTesterMetrics` as well and noticing it's not actually available in ASC API, maybe related to that issue...)

2021-08-02 18:58 UTC, joshdholtz approved these changes
This looks good to me! Thank you so much for this PR. Really appreciate it 🥰

2021-08-02 18:59 UTC, merged