[precheck] remove all instances of `is_string` in options and use `type`
fastlane/fastlane pull request #19075
Opened 2021-07-11 11:40 UTC by crazymanish

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- `is_string` is slowly being replaced by `type` to make the docs clearer, options safer, and Swift generation more correct.
- This PR does this for only `precheck` tool.

### Description
In this PR,
- Remove `is_string: false` from precheck options
- Updated rubocop.yml for precheck linting

### Testing Steps
- No functionality changed, all existing unit tests should pass.

2021-07-14 06:15 UTC, lucgrabowski commented
Looks good @crazymanish 🚀 
It was the first time I've briefly taken a look at rubocop rules definition ;)

2021-07-16 15:13 UTC, joshdholtz requested changes
This looks good! Just one suggestion on the `default_rule_level` option

2021-07-16 15:13 UTC, joshdholtz commented on precheck/lib/precheck/options.rb
> +                                     skip_type_validation: true, # allow String, Symbol
This can be a `Symbol` type! It will auto convert a string to a symbol

```suggestion
                                     type: Symbol
```

2021-07-16 15:31 UTC, crazymanish commented
> This looks good! Just one suggestion on the `default_rule_level` option

I was very confused with this option, applied the suggestion. Thank you! 🚀

2021-07-23 15:19 UTC, joshdholtz approved these changes
🔥🔥🔥

2021-07-23 15:19 UTC, merged