[spaceship] Add x-csrf-itc header to requests
fastlane/fastlane pull request #19145
Opened 2021-07-24 00:50 UTC by petersonbill64

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes issues #19124 #19140

### Description

Adds a CSRF header to all requests in the tunes client. I discovered that this header was necessary by encountering the issue from #19140 (even on 2.188.0), doing a similar request via the App Store Connect UI, then diffing the requests, and binary searching through the headers to find the one that was missing for the request to succeed.

I verified that requests to create families, create iaps, update families, and update iaps fail without the header but succeed with it.

### Testing Steps

2021-07-26 12:41 UTC, torgefaehrlich approved these changes
Had the same problem, applied the changes locally, solved it!

2021-07-27 09:10 UTC, Mezmeraid approved these changes
I also had this problem with iap create, fixed with this ! thanks

2021-07-27 15:01 UTC, DagrutCr commented
From my tests, it seems that this header is also required for `get_shared_secret` and `generate_shared_secret` in this same file, it doesn't work without it.

2021-07-28 14:41 UTC, joshdholtz requested changes
Since it looks like almost every request needs this, thoughts on moving this into 👉  https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L720-L722

Seems like this might make things a little bit cleaner and easier to maintain 🤷‍♂️

2021-07-28 17:14 UTC, joshdholtz commented
@petersonbill64 Are you cool if I add a commit to make this change? 😇

2021-07-29 02:59 UTC, hziKen commented
I would like to ask whether the master has updated this code?

2021-07-29 03:21 UTC, joshdholtz commented
@googlebot I consent.

2021-07-29 03:23 UTC, joshdholtz commented
@petersonbill64 Added a commit to remove some of the duplication needed for this new header! I also looked and saw there was one similar for App Store Connect endpoints using Apple ID auth 🤷‍♂️ 

Do you mind taking a look at this to see if this still works for you? I did some testing and I'm pretty sure it does but just want to make sure 😇

2021-07-29 17:11 UTC, petersonbill64 commented
Thanks @joshdholtz, I tested this with my use case and it's still working correctly. I'm waiting on legal to get back on the CLA; if there's some urgency and you want to open a different PR as the owner to get it merged quickly I'm fine with that, especially since you ended up rewriting it anyway.

2021-07-29 23:05 UTC, petersonbill64 commented
@googlebot I signed it!

2021-07-29 23:06 UTC, petersonbill64 commented
@joshdholtz Should be good to go once you dismiss the requested changes. Thanks!

2021-07-30 02:56 UTC, hziKen commented
[fastlane/fastlane] [spaceship] Creation of in-app purchases returns NotFound error (#19140) this question not solve man

2021-07-30 03:03 UTC, hziKen commented
[fastlane/fastlane] [spaceship] Creation of in-app purchases returns NotFound error (#19140) this question not solve man

2021-07-30 14:11 UTC, joshdholtz approved these changes
Thanks so much for find this fix! Really appreciate the contribution ❤️

2021-07-30 14:11 UTC, merged