Add requests to remove or replace visible apps
fastlane/fastlane pull request #19200
Opened 2021-08-03 17:43 UTC by lucgrabowski

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Add 2 requests to remove or replace visible apps for user.
Add a helper to `remove_users` to `App` model - similar to `add_users`

### Description

Changes for `User`:
- `remove_user_visible_apps` request added to remove apps from `User`
- `replace_user_visible_apps` request added to replace apps for `User`
- tests for both requests added

Changes in `App`: helper to `remove_users` (similar to `add_users`)

Just to mention, I didn't add a similar `replace_users` because it would require more requests inside to make it work properly:
1. fetch every user, 
2. for each of those users: 
a) check apps for this user, 
b). replace apps by removing only 1 app for user without removing others

And I'm not sure if it makes sense to add such a helper.

### Testing Steps

Tested in `irb`:
```ruby
require 'spaceship'
Spaceship::ConnectAPI.login
Spaceship::ConnectAPI.select_team

# testing `remove_user_visible_apps` and `replace_user_visible_apps`
apps=Spaceship::ConnectAPI::App.all
apps.collect { |a| a.bundle_id + " => " + a.id }

user=Spaceship::ConnectAPI::User.find(email: EMAIL").first
Spaceship::ConnectAPI.add_user_visible_apps(user_id: user.id,  app_ids: [APP_ID_1])
Spaceship::ConnectAPI.add_user_visible_apps(user_id: user.id,  app_ids: [APP_ID_2])

Spaceship::ConnectAPI.remove_user_visible_apps(user_id: user.id,  app_ids: [APP_ID_1])
Spaceship::ConnectAPI.replace_user_visible_apps(user_id: user.id,  app_ids: [APP_ID_1])

Spaceship::ConnectAPI.replace_user_visible_apps(user_id: user.id,  app_ids: [APP_ID_2])
Spaceship::ConnectAPI::User.find(email: EMAIL").first.visible_apps

# testing `remove_users`
app=Spaceship::ConnectAPI::App.find(BUNDLE_ID)
user=Spaceship::ConnectAPI::User.find(email: EMAIL").first
app.remove_users(user_ids: [user.id])
app.add_users(user_ids: [user.id])
```

2021-08-04 14:18 UTC, joshdholtz requested changes
This looks good! Just a few naming tweaks 😊

2021-08-04 14:18 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/users/users.rb
> +        def remove_user_visible_apps(user_id: nil, app_ids: nil)
```suggestion
        def delete_user_visible_apps(user_id: nil, app_ids: nil)
```

2021-08-04 14:18 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/users/users.rb
> +        def replace_user_visible_apps(user_id: nil, app_ids: nil)
```suggestion
        def patch_user_visible_apps(user_id: nil, app_ids: nil)
```

2021-08-04 14:18 UTC, joshdholtz commented on spaceship/lib/spaceship/connect_api/users/users.rb
>          def add_user_visible_apps(user_id: nil, app_ids: nil)
We've been prefixing these methods with the HTTP method so I think I'd like to stick to that if possible 😇  I realized I should have caught this `add_` sooner so maybe update that to be deprecated and change it 🤷‍♂️  My apologies on that!

```suggestion
        # @deprecated Use {#post_user_visible_apps} instead.
        def add_user_visible_apps(user_id: nil, app_ids: nil)
          post_user_visible_apps(user_id: user_id, app_ids: app_ids)
        end

        def post_user_visible_apps(user_id: nil, app_ids: nil)
```

2021-08-04 14:38 UTC, lucgrabowski commented
@joshdholtz Thanks for review, I've applied changes and fixed tests.

2021-08-04 14:38 UTC, lucgrabowski commented
@googlebot I fixed it.

2021-08-04 14:40 UTC, joshdholtz commented
@googlebot I consent.

2021-08-06 01:31 UTC, joshdholtz approved these changes
This is working good for me! Thank you for adding this ❤️ Really appreciate the contribution!

2021-08-06 01:31 UTC, merged