[match] Adds identifiers supplied to match to the git commit message
fastlane/fastlane pull request #19303
Opened 2021-08-27 17:51 UTC by mikelrob

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
We have multiple teams developing multiple apps. We all use `fastlane` to automate our deployment, it's so great to have a reliable automated process. Recently we had to renew our iOS Distribution certificate which resulted in all teams renewing their respective Distribution provisioning profiles. This was super easy using `fastlane match` however the git repo we use for storage does not have a readable commit log. I wanted to include the identifiers supplied to `match` from the CLI or Matchfile in the commit message to give us better visibility at a glance of our log.

### Description
First I moved the `app_identifiers` block of code in the runner above the storage selection. I want to pass this into the storage object. 
I fixed up the `runner_spec` according to expect these extra params.
Next I added the `identifiers` to the `git_storage` and used them in the `generate_commit_message` func.
I updated the `git_storage_spec` with context block testing for single and multiple identifiers.
Ensuring it works with multiple identifers was important to us as we have an app with linked extensions.
After the changes were made I ran the test suite and rubocop analysis.

### Testing Steps
I ran:
```
bundle exec rspec
bundle exec rubocop -a
```

2021-08-30 19:46 UTC, joshdholtz requested changes
I think this is a great addition! However, I think this could be reworked to use the existing `custom_message` argument on  `def save_changes!(files_to_commit: nil, files_to_delete: nil, custom_message: nil)`. This way you don't need to pass the identifiers into the storage object 😇 

Let me know your thoughts on this!

2021-09-02 11:17 UTC, mikelrob commented
> I think this is a great addition! However, I think this could be reworked to use the existing `custom_message` argument on `def save_changes!(files_to_commit: nil, files_to_delete: nil, custom_message: nil)`. This way you don't need to pass the identifiers into the storage object 😇
> 
> Let me know your thoughts on this!

Thanks! Yea, I like your idea of using the existing mechanism. I guess I just need to create an option on the match command to accept the custom message and pass it through?

2022-03-30 09:57 UTC, CaseyCw1 commented
This works really well for me, thank you! Facing same issue here. Help is appreciated.

2022-07-28 01:25 UTC, getaaron commented
@mikelrob hey are you still working on this? we'd love to get it fixed up and merged in 😍

2025-11-19 19:02 UTC, closed without merging