Fix and ammend gemspec metadata
fastlane/fastlane pull request #19419
Opened 2021-10-01 08:45 UTC by aried3r

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Was browsing rubygems.org and wanted to see the official docs but got linked to rubydoc.info instead.

### Description

The `docs_url` key is called `documentation_uri`. Right now, because of the wrong key [rubygems.org](https://rubygems.org/gems/fastlane) links to [rubydoc.info](https://www.rubydoc.info/gems/fastlane/2.195.0) instead of the URL previously set in `docs_url`.

The other keys were set to show what could be done to also show up on RubyGems.org. While there is no "mailing list", I think GitHub discussions are the closest thing.

Happy to add, change, remove any attributes that are unwanted. See the [`metadata` docs](https://guides.rubygems.org/specification-reference/#metadata) for the possible keys.

2021-10-01 14:57 UTC, joshdholtz requested changes
This is great! Didn't know this was broken and also all of these exist 🙃 One small request to remove that and then this is good to ship 👍

2021-10-01 14:57 UTC, joshdholtz commented on fastlane.gemspec
> +    "mailing_list_uri" => "https://github.com/fastlane/fastlane/discussions",
I'd love to have a link to discussions but mailing list seems a little off 🤷‍♂️ I think we are good to ship after removing this one!
```suggestion
```

2021-10-02 19:56 UTC, aried3r commented
Good point about the mailing list. I applied the changes. :)

2021-10-11 16:09 UTC, joshdholtz approved these changes
This looks great! Thank you ❤️

2021-10-11 16:09 UTC, merged