Symbolize keys in options of type Hash
fastlane/fastlane pull request #19424
Opened 2021-10-02 07:11 UTC by keeshux

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When Hash options are provided via environment, they are parsed as JSON and auto-converted to a hash. However, Ruby treats string and symbol keys differently, and fastlane actions normally expect keys as symbols.

### Description

Converts keys to symbols when parsing an option from a JSON string in the environment.

A probably better alternative would be (only converts top-level keys):

````
Marshal.load( Marshal.dump(h) )
````

### Testing Steps

The `APP_STORE_CONNECT_API_KEY` environment variable is a common example exposing the issue. Any key inside the JSON would be parsed as nil, because accessing e.g. `"key_id"` (parsed) is different than `:key_id` (expected).

2021-10-11 16:29 UTC, joshdholtz requested changes
I like this theory! But it looks like this breaks some existing tests 😔 I think the correct solution for the issue here might be to fix the string/symbol lookup in the App Store Connect API Key area if that is where its happening 🤷‍♂️  Thoughts?!

2021-10-11 18:23 UTC, keeshux commented
> I like this theory! But it looks like this breaks some existing tests 😔 I think the correct solution for the issue here might be to fix the string/symbol lookup in the App Store Connect API Key area if that is where its happening 🤷‍♂️ Thoughts?!

Yeah! I saw that l10n tests failed in CI, probably for the opposite reason. In fact such a change might have subtle and undesired consequences.

Therefore, I reverted the global change and restricted the fix to the `app_store_connect_api_key` action, which is where the bug is most apparent to my experience.

2021-10-13 22:02 UTC, joshdholtz commented
@googlebot I consent.

2021-10-13 23:21 UTC, joshdholtz approved these changes
This is great! Thank you so much for fixing this 🥰

2021-10-13 23:21 UTC, merged