[snapshot][fastlane_core] Hotfix/simulator not starting Xcode 13
fastlane/fastlane pull request #19531
Opened 2021-10-26 20:47 UTC by MakakWasTaken

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves  #18762

### Description

Added a check to see if the Xcode version is 13 or newer. If so, runs the simulator with a working command.

### Testing Steps

`bundle exec rspec ./fastlane_core/spec/device_manager_spec.rb`

2021-10-29 18:57 UTC, joshdholtz requested changes
@MakakWasTaken Thanks for looking into this! Thoughts on using `xcrun simctl bootstatus` instead? This is used inside of `snapshot` for some things

I didn't get a chance to test my suggestions but its a copy of what we use in in `snapshot` when customizing the status bar 😇

2021-10-31 23:14 UTC, MakakWasTaken commented
I tried testing the code you provided by just running the commands. It seems that the command only monitors the boot status, but it does not actually start the simulator.

2021-11-22 08:39 UTC, MakakWasTaken commented on snapshot/spec/simulator_launcher_base_spec.rb
> +            .with("open -a Simulator.app --args -CurrentDeviceUDID #{device_udid} &> /dev/null")
@joshdholtz I tried testing the code you provided by just running the commands. It seems that the command only monitors the boot status, but it does not actually start the simulator.

2021-12-10 17:46 UTC, lucgrabowski commented on snapshot/spec/simulator_launcher_base_spec.rb
> +            .with("open -a Simulator.app --args -CurrentDeviceUDID #{device_udid} &> /dev/null")
Checks device boot status.
Usage: simctl bootstatus <device> [-bcd]
	-b       Boot the device if it isn't already booted.
	-d       Print data migration information, if it's available.
	-c       Continuously monitor boot status through multiple boot/shutdown cycles.

Monitors the specified device and prints boot status information until the device finishes booting. You can safely call this before you attempt to start booting the device.

2021-12-10 17:51 UTC, lucgrabowski commented on snapshot/spec/simulator_launcher_base_spec.rb
> +            .with("open -a Simulator.app --args -CurrentDeviceUDID #{device_udid} &> /dev/null")
@MakakWasTaken Thanks for the fix. Have you checked `bootstatus` with `-b` option as @joshdholtz advised? I've just checked it and it boots the simulator. Docs confirm it (`xcrun simctl help boostatus`):
> Checks device boot status.
Usage: simctl bootstatus <device> [-bcd]
	-b       Boot the device if it isn't already booted.
(...)

2021-12-17 00:59 UTC, MakakWasTaken commented on snapshot/spec/simulator_launcher_base_spec.rb
> +            .with("open -a Simulator.app --args -CurrentDeviceUDID #{device_udid} &> /dev/null")
I got it working on my end. Must have been a bug or something on my end before.

2021-12-17 01:07 UTC, MakakWasTaken commented
@joshdholtz The error in the CI seems to be from a missing MATCH_PASSWORD

`end.to raise_error("Invalid password passed via 'MATCH_PASSWORD'")`

Is this due to a missing secret on the CI?

2021-12-28 11:17 UTC, Kylmakalle commented
`xcrun simctl bootstatus` does not open `Simulator.app` for me. Tested on multiple machines. Xcode 13 & 13.2

2021-12-28 12:12 UTC, MakakWasTaken commented
> `xcrun simctl bootstatus` does not open `Simulator.app` for me. Tested on multiple machines. Xcode 13 & 13.2

After some testing I think it only starts the simulators if the Simulator.app already runs(Either in the background or foreground). I will further test this later today or tomorrow. 
But the instability of this command might lead the previous changes to be reimplemented.

2021-12-28 12:21 UTC, lucgrabowski commented
I did some tests some time ago and I noticed that when a simulator is in `Booted` state Simulator.app doesn't have to be visible on screen. You can check if a simulator is in Booted or in Shutdown state by running: `xcrun simctl list devices`

So to test it, you can run the `xcrun simctl list devices`, select one ID that is in `Shutdown` state, run
`xcrun simctl bootstatus <AAAAAAA-AAAA-AAAA-AAAA-AAAAAA> -b`
and later check that the state on the `xcrun simctl list devices` list for this ID changed to `Booted`

2021-12-28 12:29 UTC, Kylmakalle commented
Some our UI tests have issues _(probably related to hardware keyboard settings)_ if Simulator.app is not launched.

So the most stable way for me is to explicitly `open -a Simulator.app` and boot `xcrun simctl boot` if necessary.

2021-12-29 09:01 UTC, MakakWasTaken commented
  | simctl bootstatus (closed Simulator before) | simctl bootstatus (open Simulator before) | open Simulator.app command | Comment
-- | -- | -- | -- | --
Starts | x | x | x | Tested with xcrun simctl list
Visible |   | It closed the Simulator.app | x | Might cause issues with UI if not visible. 
Screenshots | Gives error on interaction | x | x | Checked by watching success of tests and output screenshots

Based on the results of tests I have reached that conclusion that the:
```open -a Simulator.app --args -CurrentDeviceUDID #{device_udid} &> /dev/null```
Appears to be the most stable command for taking screenshots

2022-01-09 21:05 UTC, lucgrabowski commented
Thanks for fixing this and for gathering test results :) LGTM 🔥

2022-01-09 21:06 UTC, lucgrabowski approved these changes
Thanks for fixing this and for gathering test results :) LGTM 🔥

2022-01-09 21:06 UTC, lucgrabowski approved these changes
Thanks for fixing this and for gathering test results :) LGTM 🔥

2022-01-14 11:15 UTC, Kylmakalle commented
@joshdholtz may we get these changes in next fastlane RC?

2022-02-02 03:23 UTC, joshdholtz approved these changes
This is awesome! Thank you for fixing this 🥰  This is going out in tonight's release!

2022-02-02 03:51 UTC, merged