[core] Skip repeating the output again when an sh command fails
fastlane/fastlane pull request #19545
Opened 2021-10-28 12:45 UTC by tutipeti

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #19416
Resolves #11140

### Description

I'm changing `sh` *not* to repeat the command output again when an error happens.
On output-heavy shell calls (in our case running Unity) this causes the entire output of Unity being repeated for absolutely no gain.
To make matters worse, without passing an `error_callback` there's even an exception raised that `bundler` picks up then and decides to repeat the output yet again. Yikes. :)

I've tested my changes both by running the rspec tests (which is also the reason why I had to change the tests) and by calling a script that fails through `sh` from my own project.

### Testing Steps

Simply call any script that should fail and observe the output only appearing once.

2021-10-29 19:30 UTC, joshdholtz requested changes, later dismissed
I'm so torn on this 😱  I've totally seen what you saw with large outputs that is very overwhelming but I also like how this error would print out as red (vs the purple/pink) so it was very easy to find the error 🤔 

I _almost_ think I'd like this output to be truncated to some length and then maybe have the full output stored somewhere so that it can be seen a bit easier? 🤔 

I know this is kind of asking a lot 😅 So I wouldn't mind helping more if you noodle on ideas or by adding some commits but I'd love to know your thoughts!

I really appreciate the effort on this though ❤️

2021-11-01 07:50 UTC, tutipeti commented
Yeah, I feel your "pain" when you say you were torn. I also wasn't sure which approach is the better and kept jumping between "let's just omit it" and "let's add a new parameter so people can control this behaviour!"

My internal argumentation as for why I went with option a) (omitting) was that I had a hard time seeing actual value in duplicating the output. And based on that I thought not keeping it around as a default case would benefit more users than adding a customisation option that nobody would even see 😅 

> I almost think I'd like this output to be truncated to some length ...

Yeah, I guess that makes sense, especially if your output isn't as bad as mine.
Do you also have a good enough guesstimate about a reasonable length you'd like to see the output being trimmed to? ;)
I _think_ what could make sense here is keeping the last, let's say 1000 characters, assuming that errors likely are printed at the end?
For the record: in my use-case (= Unity) keeping the last 1k characters wouldn't help, as Unity tends to output a lot of spam after errors too, before exiting 😄 

> and then maybe have the full output stored somewhere so that it can be seen a bit easier? 🤔

That is more or less available, right? Once you pass a callback, of course.
See https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/sh_helper.rb#L78

Another thought I had while looking at it, but got afraid as that feels like a bigger change, is that I could change from `popen2e` to some other method that isn't merging stdout and stderr of the executed process.
Which would mean that I would have the possibility to print stderr only in the error case, and not having to repeat the entire stdout again.

What do you think?

2021-11-11 07:55 UTC, tutipeti commented
Friendly reminder to @joshdholtz, if you have some time please don't forget this small PR ;)

Also, warm welcome to the newcomer 👶  👋

2021-11-16 03:19 UTC, joshdholtz commented
@tutipeti Ahhhh, I missed your response! Thank you for the friendly ping ❤️

2022-01-13 16:33 UTC, tutipeti commented
@joshdholtz I didn't really have a better idea so ended up placing back the repeated output, but shortened it to the last 500 characters.

If you have another wish please do tell me :) and happy new year 😅

2022-03-15 10:52 UTC, tutipeti commented
Hey @joshdholtz, fyi I'm still waiting for an approval here. And the fastlane bot keeps trying to close the issue related to this change request ;)

2023-04-05 03:56 UTC, mdcarter1 commented
Any chance we can get this approved?

2026-06-26 18:58 UTC, iBotPeaches approved these changes
This bugs me to no end. You get a single failure on a RN build and it spews out another 30-50k lines and it takes forever to find the error among the mess.

I don't know if this is the right fix, but I'm trying it out and will iterate. I'm set on changing this before next release since I have a strong opinion as it exists now is extremely annoying.

2026-06-27 11:50 UTC, merged