Identify skipped tests in `xcresult` and export to Junit format
fastlane/fastlane pull request #19836
Opened 2022-01-23 17:58 UTC by igor-makarov

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

### Description

### Testing Steps

2022-01-28 02:01 UTC, joshdholtz requested changes
The failure count does not take into consideration if a test has been skipped so I suggested a fix for that!

Can we also get the test result output table in `scan` to show number skipped? 😇 

And thanks for making this PR!

2022-01-28 02:01 UTC, joshdholtz commented on trainer/lib/trainer/test_parser.rb
>          row[:number_of_failures_excluding_retries] = unique_tests.find_all { |a| a[:success_count] == 0 }.count
```suggestion
        row[:number_of_failures_excluding_retries] = unique_tests.find_all { |a| a[:success_count] == 0 && a[:skip_count] == 0 }.count
```

2022-01-28 11:04 UTC, igor-makarov commented
Hey Josh! I've accepted your CR suggestion (with a minor variation to keep linter happy)!

I've also added the summary row to `scan` output but - I haven't had the chance to test it with a real-life test run and I wasn't able to figure out where to add testing for it in the runner specs.

2022-02-02 02:53 UTC, joshdholtz commented
This is getting close! It looks like `:number_of_skipped` needs to be added in these two places yet 👇 

![Screen Shot 2022-02-01 at 8 52 10 PM](https://user-images.githubusercontent.com/401294/152085985-678c34e4-2992-4585-a8f7-528c4dc45343.png)
![Screen Shot 2022-02-01 at 8 52 22 PM](https://user-images.githubusercontent.com/401294/152085987-276d8ef6-ac43-47d2-9661-8faa67526a55.png)

2022-02-02 02:54 UTC, joshdholtz commented
And side note: I'm not able to add commits from a fork from an organization 😔 I don't know why GitHub doesn't allow that. In the future you want to make a fork from your personal account I can help add some commits!

2022-02-11 21:11 UTC, closed without merging