upload 6.7inch screenshots
fastlane/fastlane pull request #20694
Opened 2022-09-25 20:55 UTC by cherpake

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context

### Description
Added new screenshot sizes for 6.7inch iPhone 14 Pro Max

### Testing Steps

2022-09-26 09:41 UTC, rogerluan reviewed
Thank you for this, @cherpake ! Have you confirmed it works by uploading 6.7" screenshots to the App Store?

Would you mind signing the CLA with Google? The instructions were posted by the bot, right above :)

Thanks once again!

2022-09-26 09:41 UTC, rogerluan commented on deliver/spec/app_screenshot_spec.rb
> +    it "should return iphone65 for 6.7 inch displays" do
```suggestion
    it "should return iphone67 for 6.7 inch displays" do
```

or 

```suggestion
    it "should return iphone14ProMax for 6.7 inch displays" do
```

🤔

2022-09-26 09:41 UTC, rogerluan commented on fastlane/lib/fastlane/version.rb
> +  VERSION = '2.210.2'.freeze
Please revert this change as it shouldn't be part of a PR 😊 this gets updated during deployment processes

2022-09-26 09:43 UTC, rogerluan requested changes
Could you also check for linter issues by running `bundle exec rubocop -a`? 🙏

2022-09-29 15:10 UTC, giginet reviewed
I just need this feature. So I'll try this patch. Good job ✨ 

LGTM except for existing comments.
Could you fix them?

2022-09-29 15:56 UTC, cherpake commented
> 

Done, fixed one issue

2022-09-30 04:41 UTC, giginet requested changes
Could you revert the changes for `Gemfile.lock`?

And I pointed out minor fixes.

After you fixed, it will be merged soon.

2022-09-30 04:41 UTC, giginet commented on Gemfile.lock
> +    fastlane (2.210.2)
Could you revert `Gemfile.lock`?
This file should not be changed by this PR.

2022-09-30 04:41 UTC, giginet commented on deliver/lib/deliver/app_screenshot.rb
> +          [2796, 1290]
You can add a trailing comma for conventions.

```suggestion
          [2796, 1290],
```

2022-09-30 04:41 UTC, giginet commented on deliver/lib/deliver/app_screenshot.rb
> +           [2796, 1290]
```suggestion
           [2796, 1290],
```

2022-09-30 04:41 UTC, giginet commented on deliver/spec/app_screenshot_spec.rb
> +      it "should calculate all 6.5 inch iPhone resolutions" do
```suggestion
      it "should calculate all 6.7 inch iPhone resolutions" do
```

2022-09-30 05:29 UTC, giginet commented
@cherpake  I'm so sorry for your inconvenience 🙏  our CI avoided placing trailing commas.
So my suggestion is completely wrong 🙇 
Could you revert them? 

https://github.com/fastlane/fastlane/pull/20694/commits/673e1b908f804554d0f182a28bf07e7aa4bd856c
https://github.com/fastlane/fastlane/pull/20694/commits/a758f8aa2bf41699ad9d7f2dfe4dcaa011e11ce9

2022-09-30 05:32 UTC, giginet commented on deliver/lib/deliver/app_screenshot.rb
> +          [2796, 1290],
My suggestion was wrong 🙇 

```suggestion
          [2796, 1290]
```

2022-09-30 05:32 UTC, giginet commented on deliver/lib/deliver/app_screenshot.rb
> +           [2796, 1290],
```suggestion
           [2796, 1290]
```

2022-09-30 05:33 UTC, cherpake commented
I want Fastlane t-shirt for this :)

2022-09-30 05:43 UTC, giginet commented
Could you revert Gemfile.lock?
https://github.com/fastlane/fastlane/pull/20694/files#r984199848

You just execute `bundle install`.

2022-09-30 06:00 UTC, cherpake commented
Done...

2022-09-30 06:06 UTC, giginet approved these changes
LGTM. Thank you for your contribution 😄 
I'll merge this after checking with other members.

2022-09-30 10:33 UTC, rogerluan requested changes

2022-09-30 10:33 UTC, rogerluan commented on deliver/lib/deliver/app_screenshot.rb
> +         ],
```suggestion
        ScreenSize::IOS_67 => [
          [1290, 2796],
          [2796, 1290]
        ],
```

2022-09-30 10:34 UTC, rogerluan approved these changes
🚀 LGTM! Thank you again for this PR @cherpake ! 
(and I wish we had fastlane T-shirts too! ❤️ )

2022-09-30 14:43 UTC, merged