Fail lane if dsyms upload fails
fastlane/fastlane pull request #20907
Opened 2022-12-01 15:01 UTC by acecilia

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Uploading dsyms to crashlytics after a build is critical, because dsyms may not be able to be uploaded later (the machine that performed the build may remove the generated archive after the build is completed). Successfully making a build without uploading dsyms is highly risky, because such build may be released to production, and without dsyms it will silently stop reporting crashes. This commit purposely fails the build in cases where dsym upload fails

Resolves #19213

2022-12-01 15:06 UTC, acecilia commented
I do not understand why CircleCI is failing, even after reading the documentation [here](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-).
```
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.
```

2022-12-07 16:34 UTC, acecilia commented
@rogerluan your feedback would be very much appreciated here 🙌

2022-12-07 16:35 UTC, acecilia commented
For context: I am experiencing sporadic failures which I reported to Crashlytics in https://github.com/firebase/firebase-ios-sdk/issues/10557

2022-12-13 19:24 UTC, acecilia commented
I do not want to give write access to CircleCI, is there another way?

<img width="479" alt="Screenshot 2022-12-13 at 19 23 34" src="https://user-images.githubusercontent.com/7938671/207425992-aba127f8-7189-4340-a869-632e0ee99382.png">

2022-12-21 12:41 UTC, rogerluan requested changes
@acecilia thanks for this PR 🙏 however, as it currently stands, this PR would be a breaking change for the portion of users who are relying on the fact that fastlane won't fail even if the dSYMs upload fails. This new behavior might not be the desired behavior for all the users. What do you think of providing users an opt-in parameter to change this behavior, which by default keeps the current behavior as is?

Regarding the CI failure, you don't have to give access to CircleCI. What you're observing is a bug on CircleCI's end AFAICT 😬 we can't retrigger it either, so just a new commit push would retrigger CI and hopefully build correctly 🙏

2026-07-26 15:18 UTC, closed without merging