Fetch profiles faster if name is known
fastlane/fastlane pull request #21016
Opened 2023-01-28 23:13 UTC by PaulTaykalo

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Speeding up some queries on AppStoreConnectAPI

### Description

When running `match` and `sigh` commands, and there's a need for searching specific provisioning profiles, the current general pattern is to search for all profiles by calling `Spaceship::ConnectAPI::Profile.all` and filter later i.e.
```
all_profiles = Spaceship::ConnectAPI::Profile.all(includes: "devices")
```

In this PR we're adding additional filtering when querying `ConnectAPI` which greatly reduces request times.

### Important notes
- While it seems that profile can simply be renamed, and have the same `uuid`, it's not actually true. When the profile is renamed, its `uuid` changes as well. 
- There's no visible way to require exact name matching when querying, so we're always adding later checks and not relying on names only. For example, if "Profile" is searched, "Profile1" and "Profile2" will be returned.

## # Some numbers
Numbers are greatly depend on the portal size, these are numbers for a real one
<img width="628" alt="image" src="https://user-images.githubusercontent.com/119268/215295386-278dd958-cf2a-479d-adc0-0dfb91673e13.png">

### Testing Steps

Basically, `sigh` and `match` should work exactly the same.

2023-01-29 22:52 UTC, gelosi approved these changes
Wow. Can’t wait to upgrade match 👏

2023-07-18 11:00 UTC, nekrich commented
@joshdholtz @rogerluan can you please merge this PR. We are using this improvement for 6 months already and are really happy with it.

2023-07-28 02:56 UTC, rogerluan approved these changes
💯 Nice!

2023-12-27 06:45 UTC, rogerluan requested changes
@PaulTaykalo , sorry that this PR didn't get merged yet 😬 it ended up developing merge conflicts, would you mind fixing them by merging master into this branch?

Also, since we've merged a PR that potentially improved match performance by up to 100x, would you mind running your tests again to check whether this PR still improves performance, and by how much? 🙇 

Thank you so much!

2023-12-30 21:28 UTC, closed without merging

2023-12-30 21:28 UTC, PaulTaykalo commented
@rogerluan from what I see all these changes were added in https://github.com/fastlane/fastlane/pull/21694 this PR
So, I'll close current PR

2024-01-10 11:44 UTC, rogerluan commented
Thanks for verifying this, @PaulTaykalo 🤗