[spaceship][deliver][pilot] add support for app clips default experience metadata and review information
fastlane/fastlane pull request #21180
Opened 2023-04-04 12:39 UTC by telip007

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
There is currently no app clips functionality within Fastlane. My team and I were using the changes from the following PR for a while now: https://github.com/fastlane/fastlane/pull/20300, however, the author no longer maintains the PR and has no interest in getting it merged, thus we decided to open a new PR.

This PR looks to implement the goals of https://github.com/fastlane/fastlane/pull/20300, but with some minor fixes to the metadata upload and additional features such as
- Specifying metadata through the filesystem
- Passing app clip review information
- Submitting beta app clip invocation

Resolves https://github.com/fastlane/fastlane/issues/17639

### Description
#### Deliver
The following app clip default experience functionality has been added to deliver:
- option to specify an action (PLAY, VIEW, ...)
- option to specify localized subtitles
- option to specify localized default experience header image
- option to specify app clip review information

Example with metadata inside deliver:
```ruby
deliver(
  app_clip_default_experience_action: "PLAY",
  app_clip_default_experience_subtitle: {
    "en-US": "this is a test from fastlane",
    "es-MX": "está es una prueba de fastlane"
  },
  app_clip_header_images_path: "./fastlane/app-clip-header-images",
  app_clip_review_information: {
    invocation_urls: ["http://localhost.com", "http://localhost.com/1"]
  }
)
```

Example with metadata through path:
```ruby
deliver(
  app_clip_default_experience_metadata_path: "./fastlane/app-clip-default-experience-metadata",
  app_clip_header_images_path: "./fastlane/app-clip-header-images",
  app_clip_review_information: {
    invocation_urls: ["http://localhost.com", "http://localhost.com/1"]
  }
)
```

The localized header images are read from the filesystem same as screenshots:
```
$ tree app-clip-header-images/
app-clip-header-images
├── en-US
│   └── random-header-image.jpg
└── es-MX
    └── another-header-image.jpg

2 directories, 2 files
```

The metadata is read as follows:
```
$ tree app-clip-default-experience-metadata/
app-clip-default-experience-metadata
├── app_clip_default_experience_action.txt
├── en-US
│   └── app_clip_default_experience_subtitle.txt
└── es-MX
    └── app_clip_default_experience_subtitle.txt

3 directories, 3 files
```

The review information can be passed through a `invocation_urls.txt` file inside `metadata/app_clip_review_information/`.
Example:
```
http://localhost.com/3, http://localhost.com/4
```

For more information, you can also look at https://github.com/fastlane/fastlane/pull/20300.

#### Pilot
The following app clip functionality has been added to pilot:
- option to specify TestFlight app clip invocations

Example:
```ruby
upload_to_testflight(
  app_clip_invocations: [{
    title: {
      "en-US": 'Try my AppClip'
    },
    url: 'http://localhost'
  }]
)
```

### Testing Steps
#### Basic Testing Setup

1. Update Gemfile to 👇 and run bundle install, bundle update fastlane, or bundle update
```ruby
gem "fastlane", :git => 'https://github.com/pace/fastlane.git', :ref => "app-clips-default-experience"
```
2. Upload a binary to ASC with an app clip target
    - you can follow [a project tutorial provided by Apple here](https://developer.apple.com/documentation/swiftui/fruta_building_a_feature-rich_app_with_swiftui)

#### What to Test
##### Deliver
Before specifying any deliver options:

- Confirm that fastlane uses the live version's app clip metadata for the current edit version
    - It should copy over the action, subtitle, and header image of the live version
 
After specifying the app clip default experience deliver options:

- Confirm the app clip default experience metadata specified in the deliver options reflects the ASC UI after running deliver
- Confirm that fastlane enforces that the app clip header image is exactly 1800x1200 in size
- Confirm that fastlane enforces only one app clip header image per locale
- Confirm that the additional fastlane messages via UI.{message,important,...} are appropriate

##### Pilot

- Confirm that the invocations appear on TestFlight

2023-04-05 08:24 UTC, EmDee commented
Hey @rogerluan, this is the follow-up PR for https://github.com/fastlane/fastlane/pull/20300, as discussed with @blesson3. Who do you think can help review this PR?

2023-04-05 11:43 UTC, rogerluan commented
Hi @EmDee 👋  I've tagged a couple people who could help with reviewing, and I could as well, but I've been busy and haven't been able to contribute as much time to fastlane as I used to 😞 

Just as a reminder, this PR doesn't have to be reviewed+merged for you guys (or anyone) to start using it, you can just point your fastlane installation directly to this branch by modifying your Gemfile as:

```ruby
gem 'fastlane', git: 'https://github.com/pace/fastlane.git', branch: 'app-clips-default-experience'
```

And running `bundle install` to apply the changes. I hope this helps unblock you guys! 🙏 Sorry if I couldn't be more helpful this time

2023-04-05 12:04 UTC, EmDee commented
Thanks @rogerluan! We have been using the changes in here for close to a year now, it's just a slight inconvenience to always have to keep this branch up to date with the main branch, therefore it would be nice to have this merged.

2023-04-27 09:46 UTC, telip007 commented
@ainame @revolter @rogerluan do you guys have an ETA to when this might be reviewed and hopefully merged? 🙂

2023-04-27 12:06 UTC, rogerluan commented
No ETA from my end at this point, sorry 😞 been busy with other life priorities, I hope you understand 🙏

2023-04-27 15:27 UTC, telip007 commented
@rogerluan of course! no worry, I just wanted to ping again and check on it :)

2023-06-11 14:01 UTC, revolter requested changes
I don't have experience with App Clips, and I also don't have time to test this, but I did take a look over all the changes, and, except the notes that I've left, I didn't see other worrisome things.

So, since you have been using this for a year, and it mainly adds new logic, I'd merge this in order to simplify the lives of the people that need this.

@rogerluan, what do you think? 😁

2023-06-17 20:10 UTC, danl3v commented
Definitely an advocate of this PR! I finally decided to remove my app clip since it would not work on my ci pipeline, but I can add back once this is merged

2023-07-06 13:37 UTC, revolter commented
@telip007, do you have time to address the review notes that I've left?

2023-07-24 10:18 UTC, TemperMichael commented
Any updates on this? @telip007 Looking forward to use that, would save me quite some time 😅

2023-09-07 21:24 UTC, fnuky commented
Please can be this PR finished? It would help me to solve my problem

2023-09-08 06:33 UTC, telip007 commented
Sorry, I was on parental leave and did not check GitHub. Will address the notes in the course of the day.

2023-09-08 08:12 UTC, telip007 commented on deliver/lib/deliver/loader.rb
> +    # list of AppClipHeaderImage that exist under given `root` directory
Used the suggested change.

2023-09-08 08:13 UTC, telip007 commented on deliver/lib/deliver/runner.rb
> +      UploadAppClipDefaultExperienceHeaderImages.new.find_and_upload(options)
You are right, I thought I had it in place for `upload_metadata` as well. This should now be included.

2023-09-08 08:14 UTC, telip007 commented on fastlane/lib/fastlane/actions/docs/upload_to_app_store.md.erb
> +You can also provide these values by creating files in a `metadata/app_clip_review_information/` directory. The file names must match the pattern `<key>.txt` (e.g. `invocation_urls`). The contents of
Used the suggested change.

2023-09-08 08:14 UTC, telip007 commented on fastlane/lib/fastlane/actions/docs/upload_to_app_store.md.erb
> +_deliver_ allows for metadata to be set through `.txt` files in the App Clip metadata folder. This folder can be set using `app_clip_default_experience_metadata_path`. Below are all allowed metadata
Used the suggested change.

2023-09-08 08:14 UTC, telip007 commented on fastlane/lib/fastlane/actions/docs/upload_to_app_store.md.erb
> +experience metadata even if the options above are not specified.
Used the suggested change.

2024-01-12 06:53 UTC, hoppsen commented
Any chance we can pick this one back up again? @telip007

2024-01-12 06:59 UTC, pf-AliKemal commented
This fix will help me to solve my problem. It would be great if you could merge/complete this PR

2024-01-12 08:06 UTC, pf-mahmoud commented
I have the same issue when happing AppClips, @telip007 Could you finalize this PR please?

2024-01-16 12:52 UTC, telip007 commented
Hey all, sorry for letting you wait. I'm currently running at total capacity, so finding time for this is a bit hard. I can't tell you when I will be able to continue working on this again.

2024-03-28 19:56 UTC, sa-ma commented
Hello, any update on this?

2024-04-18 09:39 UTC, pf-AliKemal commented
Hi @telip007,  Do you have any update on this?

2024-04-18 09:52 UTC, pf-mahmoud commented
Hi @telip007 ,
Any update, or any timeline for handling this?

2024-07-10 17:23 UTC, stephengilroy-grx commented
Hey @revolter @ainame 👋 ! Do you think you could review @sa-ma PR referenced above? https://github.com/fastlane/fastlane/pull/22041

I think it was based off this one and seems like it might be the best path forward to getting this functionality in fastlane?

2024-10-22 19:17 UTC, closed without merging

2024-10-22 19:17 UTC, revolter commented
Closed in favour of #22041.

2024-11-08 01:37 UTC, NickAtGit commented
Is there a way to download the metadata from ASC @telip007? I tried `fastlane deliver download_metadata` but it's not pulling the AppClip metadata. Any idea? Thanks in advance!