Do not advertise the skip_waiting_for_build_processing option when it is already set
fastlane/fastlane pull request #21730
Opened 2023-12-15 17:16 UTC by robinkunde

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Reduces superfluous output when uploading builds

### Description

### Testing Steps

2023-12-17 11:14 UTC, lacostej requested changes
Hello,

Thanks a lot for the contribution.

Can you please rebase your PR on top of master, to fix the build checks. Also consider the comment.

Thanks!

2023-12-19 02:34 UTC, robinkunde commented on pilot/lib/pilot/build_manager.rb
>        # Calling login again here is needed if login was not called during 'start'
Will do

2024-01-07 19:41 UTC, robinkunde commented on pilot/lib/pilot/build_manager.rb
>        # Calling login again here is needed if login was not called during 'start'
@lacostej Please take another look when you get a chance

2024-01-12 11:52 UTC, lacostej approved these changes
Thanks a lot for the effort :) LGTM

2024-01-14 14:29 UTC, rogerluan commented on pilot/lib/pilot/build_manager.rb
> +        UI.message("Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and
I know this wasn't written in this PR but I think we can improve it :)

```suggestion
        UI.message("Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on App Store Connect, update the changelog and then skip the remaining of the processing steps.")
```

2024-01-14 14:29 UTC, rogerluan commented on pilot/lib/pilot/build_manager.rb
> +          UI.important("`skip_waiting_for_build_processing` used and `changelog` supplied - will wait until build appears on AppStoreConnect, update the changelog and then skip the rest of the remain
```suggestion
          UI.important("`skip_waiting_for_build_processing` used and `changelog` supplied - will wait until build appears on App Store Connect, update the changelog and then skip the rest of the remaining of the processing steps.")
```

2024-01-14 14:29 UTC, rogerluan commented on pilot/spec/build_manager_spec.rb
> +        expect(FastlaneCore::UI).to_not(receive(:message).with("Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear
```suggestion
        expect(FastlaneCore::UI).to_not(receive(:message).with("Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on App Store Connect, update the changelog and then skip the remaining of the processing steps."))
```

2024-01-14 14:29 UTC, rogerluan commented on pilot/spec/build_manager_spec.rb
> +        expect(FastlaneCore::UI).to(receive(:important).with("`skip_waiting_for_build_processing` used and `changelog` supplied - will wait until build appears on AppStoreConnect, update the changelo
```suggestion
        expect(FastlaneCore::UI).to(receive(:important).with("`skip_waiting_for_build_processing` used and `changelog` supplied - will wait until build appears on App Store Connect, update the changelog and then skip the rest of the remaining of the processing steps."))
```

2024-01-14 14:30 UTC, rogerluan approved these changes
Thank you for your contribution @robinkunde 🤗 this LGTM!

2024-01-15 09:02 UTC, merged

2024-01-15 09:02 UTC, lacostej commented
Thanks @robinkunde :)

2024-01-15 12:25 UTC, rogerluan commented
Thanks for fixing the issue I accidentally caused @lacostej ❤️