[spaceship][deliver][pilot] add support for app clips default experience metadata and review information
fastlane/fastlane pull request #22041
Opened 2024-05-20 12:50 UTC by sa-ma

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.
- [ ] I've added or updated relevant unit tests.

### Motivation and Context

This PR improves #21180 which seems to have been abandoned. My team and I have been using the changes from #21180  for a while now. I have synced the branches and fixed failing tests.

Resolves #17639 

### Description

**Deliver**
The following app clip default experience functionality has been added to deliver:

- option to specify an action (PLAY, VIEW, ...)
- option to specify localized subtitles
- option to specify localized default experience header image
- option to specify app clip review information

See #21180 for examples

### Testing Steps

**Basic Testing Setup**
1. Update Gemfile to 👇 and run bundle install, bundle update fastlane, or bundle update
```ruby
gem "fastlane", :git => 'https://github.com/pace/fastlane.git', :ref => "app-clips-default-experience"
```
2. Upload a binary to ASC with an app clip target
    - you can follow [a project tutorial provided by Apple here](https://developer.apple.com/documentation/swiftui/fruta_building_a_feature-rich_app_with_swiftui)

#### What to Test

**Deliver**
Before specifying any deliver options:

- Confirm that fastlane uses the live version's app clip metadata for the current edit version
  - It should copy over the action, subtitle, and header image of the live version

After specifying the app clip default experience deliver options:

- Confirm the app clip default experience metadata specified in the deliver options reflects the ASC UI after running deliver
- Confirm that fastlane enforces that the app clip header image is exactly 1800x1200 in size
- Confirm that fastlane enforces only one app clip header image per locale
- Confirm that the additional fastlane messages via UI.{message,important,...} are appropriate

**Pilot**
- Confirm that the invocations appear on TestFlight

2024-05-27 04:20 UTC, sa-ma commented
@rogerluan and @AliSoftware please can you help review. There is no option to request for a reviewer on the PR

2024-09-15 23:41 UTC, jttoddy commented
+1'ing this PR to get some reviews. Can anyone help us out here?

2024-09-20 04:03 UTC, jttoddy requested changes
Been trying to integrate these changes into a test delivery workflow and ran into a few issues blocking from running correctly.

2024-09-20 04:03 UTC, jttoddy commented on deliver/lib/deliver/upload_app_clip_default_experience_header_images.rb
> +        UI.error("Could not find existing localization for #{header_image.langauge}") unless localization
Typo for `language` here, not `langauge`.

2024-09-20 04:03 UTC, jttoddy commented on deliver/lib/deliver/upload_app_clip_default_experience_header_images.rb
> +            localization.app_clip_header_image.delete
`delete!` needs to be called here instead of `delete`

2024-09-20 04:03 UTC, jttoddy commented on deliver/lib/deliver/runner.rb
> +      upload_metadata = UploadMetadata.new
Missing arguments `UploadMetadata.new(options)` here, otherwise it fails to initialise.

2024-10-10 23:53 UTC, jttoddy requested changes

2024-10-10 23:53 UTC, jttoddy commented on spaceship/lib/spaceship/connect_api/tunes/tunes.rb
> +          tunes_request_client.post("appClipDefaultExperienceLocalizations", body)
Missing `#{Version::V1}/` from API path, so when creating App Clip localizations on a new release page it fails with `Spaceship::UnexpectedResponse` exceptions.

2024-10-17 23:58 UTC, jttoddy commented
I've integrated a bunch of fixes mentioned above into my own fork/branch if folks were having the same issues using this.

https://github.com/jttoddy/fastlane/tree/pilot-app-clips

2024-11-08 01:39 UTC, NickAtGit commented
Is there a way to download the metadata from ASC @jttoddy @sa-ma? I tried fastlane deliver download_metadata but it's not pulling the AppClip metadata. Any idea? Thanks in advance!

2024-11-10 22:40 UTC, jttoddy commented
> Is there a way to download the metadata from ASC @jttoddy @sa-ma? I tried `fastlane deliver download_metadata` but it's not pulling the AppClip metadata. Any idea? Thanks in advance!

I don't believe this is currently supported in this PR. I suspect it would be possible given how the ASC API supports App Clip metadata, but I set mine up manually.

2024-12-04 08:11 UTC, stephen-oconnor-cp commented
Hello devs, can we get some movement on this?  This PR or the one that preceded it has been held up for a while and it's a pretty helpful feature for anyone making App Clips.  I'd also prefer to not have to execute fastlane from someone's branch.

2024-12-05 08:32 UTC, lacostej commented
@stephen-oconnor-cp I think you need to integrate @jttoddy 's changes at the minimum for your PR to be mergeable. Can you start by cherry picking them into your PR? His branch is here https://github.com/jttoddy/fastlane/commits/pilot-app-clips/

2024-12-05 15:09 UTC, stephen-oconnor-cp commented
@lacostej I'm not a contributor to the project.  No PR is mine.  I'm just hoping to see these features get integrated into fastlane soon.

2024-12-22 06:26 UTC, danl3v commented
Excited for this feature!

2025-07-18 07:27 UTC, doriand-itx commented
Excited for this feature too!

2025-09-18 15:02 UTC, arturonaredo commented
@jttoddy if we fork and fix the comments, would be any chance to get this merged? we are not able to upload metadata with deliver and we are doing a hack creating manually the version first, then executing the deliver pipeline.

2025-10-31 12:47 UTC, daniel-l2 commented
It seems that this PR is no longer active, so I’ve opened a new one at https://github.com/fastlane/fastlane/pull/29738￼
Please feel free to leave any additional feedback there — I’ll address it ASAP.

2026-05-15 13:24 UTC, closed without merging