Add "Beta App Description" support for `pilot`
fastlane/fastlane pull request #6435
Opened 2016-10-06 21:58 UTC by joeydong

Add support for setting a "Beta App Description" when uploading builds using `pilot`

This is required when uploading builds for the first time. I've also seen iTunes Connect "forget" the beta app description between versions so it needs to be set again.

This should solve https://github.com/fastlane/fastlane/issues/6351 and https://github.com/fastlane/fastlane/issues/6117

2016-10-07 03:08 UTC, KrauseFx approved these changes

2016-10-07 03:08 UTC, KrauseFx commented
This looks great, thanks 👍 I wasn't aware that _spaceship_ can already do that, we just didn't use it. 

Have you tried this locally too?

2016-10-07 12:41 UTC, matteo-harpoon commented
I'm trying to send a Testflight build to both internal and external uses and the message I get right now is the following
```
[!] The request could not be completed because:
	[English]: What to Test is required.
[English]: Beta App Description is required.
[English]: Feedback emails are required.
[English]: Feedback emails must be in the format: contact@example.com.
[English]: The marketing URL you entered is invalid. Make sure you entered it correctly and try again.
[English]: Marketing URLs are required. The phone number is missing. The email is required. The email must be in the format: contact@example.com. Enter a demo account user name, or deselect "A demo account is required to use all the features of the app." Enter demo account password, or deselect "A demo account is required to use all the features of the app." What to Test is required. Beta App Description is required. Feedback emails are required. Feedback emails must be in the format: contact@example.com. The marketing URL you entered is invalid. Make sure you entered it correctly and try again. Marketing URLs are required. The email is required. The email must be in the format: contact@example.com. The phone number is missing. Enter a demo account user name, or deselect "A demo account is required to use all the features of the app." Enter demo account password, or deselect "A demo account is required to use all the features of the app." Validation errors
```

Now except for the `What to Test` and `Beta App Description` (which you are currently working on), I think it should be also possible to send via metadata the following variables:
- `Test Information > en-US > Feedback Email`
- `Test Information > en-US > Marketing URL`
- `Test Information > en-US > Privacy Policy URL`
- `Test Information > en-US > License Agreement` (optional)

2016-10-07 17:08 UTC, joeydong commented
@matteo-harpoon Yeah there's definitely more fields we should add to fully support the first-run experience. I'm just pushing the "Beta App Description" one for now because iTunes Connect would ask our app to set it every version for some reason (some bug on their end).

2016-10-07 17:11 UTC, joeydong commented
@KrauseFx yup I've been sitting on this change for a while. I haven't tried it with the `.positive` syntax but I'll have a chance to test it out for our build early next week.

2016-10-07 18:23 UTC, KrauseFx requested changes

2016-10-07 18:23 UTC, KrauseFx commented on pilot/lib/pilot/build_manager.rb
> +      if options[:changelog].to_s.length.positive or options[:beta_app_description].to_s.length.positive
`positive` is is not an available method, this might be Rails specific?

2016-10-07 21:26 UTC, joeydong commented on pilot/lib/pilot/build_manager.rb
> +      if options[:changelog].to_s.length.positive or options[:beta_app_description].to_s.length.positive
Hmm okay. I just put it back to `> 0`. The houndci-bot might need some silencing then.

2016-10-07 21:27 UTC, joeydong commented on pilot/lib/pilot/build_manager.rb
> +      if options[:changelog].to_s.length.positive or options[:beta_app_description].to_s.length.positive
Maybe I was missing the `?` in `positive?`.

2016-10-10 16:29 UTC, joeydong commented
I just used the tool this morning with the new `beta_app_description` flag and it worked as expected.

2016-10-10 17:49 UTC, KrauseFx approved these changes

2016-10-10 17:50 UTC, merged

2016-10-10 17:50 UTC, KrauseFx commented
Looks great, thanks for your contribution and updating the PR 👍

2016-10-10 17:50 UTC, KrauseFx commented
This will be in the next release

2016-10-19 14:52 UTC, ryzn0518 reviewed
@joeydong  Can you tell me how to add `beta_app_description` when `pilot`,as I had the question
`Beta App Description is required. [English]: Beta App Description is required`
 As I enter the command `pilot -h`,I had not see any like`--beta_app_descripiton`,how can I add beta_app_descripiton in the command?

2016-10-19 17:27 UTC, joeydong commented on pilot/lib/pilot/build_manager.rb
Looks like a new release was just tagged 20 hours ago. Did you update the `pilot` gem?

2016-10-19 20:26 UTC, joeydong commented on pilot/lib/pilot/build_manager.rb
Oh we're waiting for the spec to be updated at https://rubygems.org/gems/pilot