Fix update_project_team with Xcode 8
fastlane/fastlane pull request #6453
Opened 2016-10-07 13:52 UTC by gcamp

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `rspec` for all tools you modified (didn't have any spec)
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Xcode now uses DEVELOPMENT_TEAM in addition to DevelopmentTeam.

Fixes https://github.com/fastlane/fastlane/issues/6452

2016-10-07 20:57 UTC, KrauseFx requested changes

2016-10-07 20:57 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/update_project_team.rb
> +        p = p.gsub(/DevelopmentTeam = .*;/, "DevelopmentTeam = #{team_id};")
You can use

```ruby
p.gsub!(/DevelopmentTeam = .*;/, "DevelopmentTeam = #{team_id};")
```

instead 👍

2016-10-10 20:08 UTC, KrauseFx approved these changes

2016-10-10 20:09 UTC, KrauseFx commented
I updated the pull request, this will be merged as soon as the build is green 👍

2016-10-10 20:35 UTC, merged

2016-10-10 22:09 UTC, gcamp commented
Thanks for updating, I would have done it tomorrow!

2016-10-11 15:31 UTC, Pierre-Loup commented
`params[:teamid]` has been replaced be `team_id` which rase the folowing error :

> [17:25:13]: Updating development team (RC2ZJG8GX8) for the given project '/Users/ptristant.ext/Developer/iOS/iOSRestructurationTydom/RestructurationTydom.xcodeproj/project.pbxproj'
[17:25:13]: Unknown method 'team_id'
[17:25:13]: Variable Dump:
[17:25:13]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"delivery_appstore"}
[17:25:13]: To call another action from an action use `OtherAction.team_id` instead

2016-10-11 15:50 UTC, gcamp commented
My bad, created a new pull request