Sigh/recreate profiles
fastlane/fastlane pull request #6518
Opened 2016-10-12 18:12 UTC by icecrystal23

Delete and recreate the profiles instead of simply updating it to include new devices.  This ensures the profile matches all of the parameters' requirements.

2016-10-28 18:10 UTC, ohwutup commented
Hey @icecrystal23, would you mind giving a little bit of background as to why you would like _sigh_ to work this way? It feels like if updating the devices is all that is intended, there would be no reason to delete and recreate the profile. Also, do you think this could break people's flows if they are modifying profiles that were not initially created by _sigh_?

2016-11-12 19:56 UTC, icecrystal23 commented
We wanted to have a simple build script to create-or-update a list of provisioning profiles that we want sigh to manage.

We end up with a list of commands like this
```
sigh --app_identifier com.mycompany.appname --team_id TEAMID --username user@mycompany.com --output_path provisioning-profiles --skip_certificate_verification --ignore_profiles_with_different_name --skip_install --force --cert_id CERTID --adhoc --provisioning_name com.mycompany.appname AdHoc

sigh --app_identifier com.mycompany.appname --team_id TEAMID --username user@mycompany.com --output_path provisioning-profiles --skip_certificate_verification --ignore_profiles_with_different_name --skip_install --force --cert_id CERTID --provisioning_name com.mycompany.appname AppStore

sigh --app_identifier com.mycompany.appname --team_id TEAMID --username user@mycompany.com --output_path provisioning-profiles --skip_certificate_verification --ignore_profiles_with_different_name --skip_install --force --cert_owner_name 'User Name' --development --provisioning_name com.mycompany.appname Development
```

When we run this with `sigh` as it is now, it often ends up creating brand new profiles (with a timestamp on the end) instead of updating the existing profiles.

The first change makes sure `sigh` is able to find invalid profiles, so that it can update existing ones instead of creating new ones unnecessarily.

The second change ensures that instead of simply updating the profile, it is recreated from scratch to the exact specifications of the command issued.  Otherwise if the certificate or some other thing changed, it might update the profile with new devices but still be in a different state than was requested by the command.

These changes ensure that `sigh --force` correctly creates the requested profile, and doesn't unnecessarily create new profiles.

2016-12-19 21:17 UTC, ohwutup commented
Hey @icecrystal23! Apologies for the delay here! Would love to get this merged, is it possible you could write a test or two to validate the behavior? Thanks! 🐙 !

2017-01-10 15:11 UTC, asfalcone commented
Hi there @icecrystal23. It looks like @ohwutup was [looking for some test to be written](https://github.com/fastlane/fastlane/pull/6518#issuecomment-268080895) so we can merge this PR. Could you take care of that?

If you don't plan to continue work on this PR please let us know so that we may close it. Thank you!

2017-01-10 15:20 UTC, icecrystal23 commented
Yeah, let me look into that.

2017-01-11 18:59 UTC, icecrystal23 commented
I added some tests.  Let me know if that's what you had in mind.  If not, please let me know specifically what you want demonstrated in the test code.

2017-01-11 20:33 UTC, asfalcone commented on sigh/spec/stubbing.rb
> +  puts expect_delete
Please remove `puts`

2017-01-11 20:34 UTC, asfalcone commented on sigh/spec/stubbing.rb
> +  puts expect_create
Please remove `puts` here too

2017-01-11 20:37 UTC, asfalcone requested changes
There are some extra `puts` in the code. 

Can you also rebase on master? There is a merge conflict right now as well as some failing tests, I think due to being behind on master.

Thank you! 👍

2017-01-11 20:42 UTC, icecrystal23 commented
Yeah, I'll clean up my commits too

2017-01-11 20:51 UTC, icecrystal23 commented
Now I am getting this when I try to run `bundle exec rspec`.  Any hints?
```tracyk:~/github/fastlane/sigh (fastlane) (sigh/recreate-profiles)
$ bundle exec rspec
bundler: failed to load command: rspec (/Users/tracyk/.rbenv/versions/2.2.5/bin/rspec)
NameError: uninitialized constant Sigh

2017-01-13 19:41 UTC, asfalcone approved these changes

2017-01-13 19:41 UTC, merged

2017-01-13 19:42 UTC, asfalcone commented
Thanks again @icecrystal23 🎉

2017-01-23 14:12 UTC, Morse-Code commented
Thanks @icecrystal23 for this. We've been having issues because the profiles used in our project (i.e. match AdHoc com.company.target) have been invalidated when new devices are added and the new profiles have a different name due to the date being appended (i.e. match AdHoc com.company.target 1484600119). Now, because the original profiles specified in our Xcode project are no longer installed by match, the project has to be updated to use the new profiles because the names have changed. Very inconvenient.