ask for Xcode version
fastlane/fastlane pull request #6524
Opened 2016-10-13 06:51 UTC by hjanuschka

i think having the xcode version is a good addition to make troubleshooting a bit easier

2016-10-13 17:10 UTC, KrauseFx requested changes

2016-10-13 17:10 UTC, KrauseFx commented on ISSUE_TEMPLATE.md
> +What Xcode Version do you use (e.g. 7, 8)
This should probably be `e.g. 8.0` instead

2016-10-13 17:10 UTC, KrauseFx commented on ISSUE_TEMPLATE.md
> +What Xcode Version do you use (e.g. 7, 8)
Version should be lower case

2016-10-13 17:35 UTC, hjanuschka commented
@KrauseFx  done

2016-10-14 04:01 UTC, KrauseFx approved these changes

2016-10-14 04:01 UTC, merged