Correcting DELIVER_USER env var name
fastlane/fastlane pull request #6527
Opened 2016-10-13 14:47 UTC by dombarnes

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [X] Run `rspec` for all tools you modified
- [X] Run `rubocop -a` to ensure the code style is valid
- [X] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Fix for incorrect ENV VAR in `deliver` options as discussed in https://github.com/fastlane/fastlane/issues/6478

2016-10-13 17:09 UTC, KrauseFx requested changes

2016-10-13 17:09 UTC, KrauseFx commented on deliver/lib/deliver/options.rb
> +                                     env_name: "DELIVER_USER",
This is a breaking change, we'd have to support both parameter. The easiest way to do so is to change the default value to

```
default_value: user || ENV["DELIVER_USER"]
```

2016-10-24 19:12 UTC, KrauseFx requested changes

2016-10-24 19:12 UTC, KrauseFx commented on deliver/lib/deliver/app_screenshot.rb
> +      UI.user_error!("Could not find or parse file at path '#{path}'") if size.nil? or size.count.zero?
These are actually not changes we want in here. We recently updated the rubocop rules to not include this

2016-11-02 10:24 UTC, dombarnes commented
Thanks @KrauseFx. I've just revered those changes and added the change to the default so as not to break backwards. Upon running `rake` I get one test error though, which seems to be failing due to reading an ENV var on my system. Not sure if this test needs adjusting at all?

````
1) Fastlane::CrashlyticsBetaUserEmailFetcher Email fetching does not find an email
Failure/Error: expect(fetcher.fetch).to be_nil
expected: nil
     got: "user@example.com"# fastlane/spec/setup/crashlytics_beta_user_email_fetcher_spec.rb:22:in `block (3 levels) in <top (required)>'

Failed examples:
fastlane/spec/setup/crashlytics_beta_user_email_fetcher_spec.rb:20 # Fastlane::CrashlyticsBetaUserEmailFetcher Email fetching does not find an email

================
| Exceptions 💣 |
================

fastlane: Command failed with status (1): [bundle exec rspec --format documentation -...]
spaceship: Command failed with status (7): [bundle exec rspec --format documentation -...]
rake aborted!
All tests did not complete successfully. Search for '[[FAILURE]]' in the build logs.
/Users/domster83/projects/fastlane/rakelib/test_all.rake:152:in `block in <top (required)>'
Tasks: TOP => default => test_all
(See full trace by running task with --trace)
````

2016-12-20 17:01 UTC, ohayon requested changes
Hey @dombarnes, I just left a couple comments about keeping the 0 checks as `==` rather than `zero?`. Also, it looks like there are some merge conflicts, would you mind resolving those and we can move forward with the PR?

2016-12-20 17:01 UTC, ohwutup commented on deliver/lib/deliver/detect_values.rb
> +      search_by = options[:app] if search_by.to_s.length.zero?
I think we would like to keep this as `== 0`

2016-12-20 17:01 UTC, ohwutup commented on deliver/lib/deliver/upload_screenshots.rb
> +        next if files.count.zero?
I think we would like to keep this as `== 0`

2017-01-10 15:42 UTC, asfalcone commented
Closing this in favor of #7806

2017-01-10 15:42 UTC, closed without merging