Add option to clear existing screenshots
fastlane/fastlane pull request #6540
Opened 2016-10-14 06:49 UTC by giginet

- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Formerly, I had been uploaded screenshots of all available sizes via deliver.
Thanks to recent iTunes Connect updates, we have only to upload the largest size.
So I dropped other sizes and submitted via deliver. But these are not removed and old ones published onto App Store.

So I added the new option for deliver to remove all existing screenshots forcibly.

2016-10-14 19:26 UTC, KrauseFx commented
I'm not sure it's a great solution to add yet another parameter to _deliver_. Could you provide some more use cases on why this is useful? 👍

2016-10-17 13:35 UTC, hjanuschka commented
related to an jurassic issue ? https://github.com/fastlane/fastlane/issues/1529
i love the functionality but i personally would love to see screenshots deleted by default (as the # commented code did back then.) - and only the ones on disk should get uploaded

2016-10-17 20:01 UTC, KrauseFx commented
We've had multiple people complain that _deliver_ removed screenshots and they didn't have a copy anywhere, so they lost the screenshots. That's why now _deliver_ only deletes the old screenshots when new ones are provided.

2016-10-17 20:22 UTC, hjanuschka commented
good point you r right about it - its really frustrating to loose them.

2016-10-24 19:07 UTC, KrauseFx requested changes

2016-10-24 19:07 UTC, KrauseFx commented on deliver/lib/deliver/upload_screenshots.rb
> +            v.upload_screenshot!(nil, index, t.language, t.device_type)
I haven't tested this yet, just setting `nil` will delete the screenshot?

2016-10-24 19:07 UTC, KrauseFx commented on deliver/lib/deliver/options.rb
> +                                     description: "Clear all previously uploaded screenshots",
Let's use `Clear all previously uploaded screenshots before uploading the new ones`

2016-10-24 19:08 UTC, KrauseFx commented
Hey @giginet, putting some more thought into this, I think the feature makes sense, and by having to explicitly setting a flag, it's very clear that screenshots get removed, and therefore it won't happen that someone deletes their screenshots by mistake.

I added one request for change, and one question before it's ready to be merged 👍 

Thanks for your contribution

2016-10-25 00:32 UTC, giginet commented
OK, I'll add requested changes soon.
Sorry for late reply.

2016-10-25 00:47 UTC, KrauseFx commented
Thanks @giginet, no need to say sorry, it's just been a few hours 👍  I appreciate your help

2016-10-25 00:54 UTC, giginet commented on deliver/lib/deliver/upload_screenshots.rb
> +            v.upload_screenshot!(nil, index, t.language, t.device_type)
Yes. I tried this method following ways.

1. Add 4.7 and 5.5 inch screenshots on Finder
2. Run deliver
3. Remove the 4.7 inch screenshot
4. Run deliver with `overwrite_screenshots` option
5. the 4.7 inch screenshot was removed on iTunes Connect

Then it seems work well.

2016-10-27 16:36 UTC, giginet commented
I've fixed a few days ago. However CI is still failing. Could you fix it?

2016-10-27 16:39 UTC, KrauseFx commented
There is merge conflicts, could you resolve them?

2016-11-02 17:26 UTC, nolanwilson commented
@KrauseFx I see that your latest comment mentioned merge conflicts. I tried a merge with the fastlane master and [was able to do so without conflict](https://github.com/nolanwilson/fastlane/tree/overwrite-screenshots).

Is there action still required for [this task](https://github.com/fastlane/fastlane/pull/6540#pullrequestreview-5517693)?

Would love to see this get in soon since we have several apps per day that get submitted with fewer screenshots than the previous version in the store and the remaining screenshots are still sticking around until this gets merged in :)

2016-11-03 02:43 UTC, KrauseFx approved these changes

2016-11-03 02:43 UTC, merged

2016-11-03 02:43 UTC, KrauseFx commented
This looks great, thanks everyone involved. The change will be available in the next release  🚀

2016-11-03 03:59 UTC, giginet commented
:tada: