For lane support all configuration files
fastlane/fastlane pull request #6549
Opened 2016-10-14 19:34 UTC by maschall

- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

#6531

I'm not sure a good reason for the silent ignoring duplicate values in config files, but if you review AppFile, the example given is no longer valid, you can overwrite the same value with duplicate lines.

Also I started with the tests for Gymfile but realized quickly that the configuration effects Dangerfile, Matchfile, Scanfile, etc...

I can help update docs if this looks good

2016-12-13 04:27 UTC, KrauseFx commented
Oh wow, thanks for the pull request, I somehow completely missed that notification. Definitely something we should look into.

2016-12-13 04:32 UTC, KrauseFx requested changes
Great tests, great change, I love it 👍 

Please add some documentation somewhere, probably in Advanced.md for now, and we're good to go. 

Sorry it took so long, and thanks again for working on this :rocket:

2016-12-13 04:32 UTC, KrauseFx commented on fastlane_core/spec/configuration_file_spec.rb
> -      it "ignores the same item being set after the first time" do
By changing this, would this break setups where you have the same line in one config file twice, and you are used to them being ignored? Is there a way we can leave that test and make it pass, while still adding this new feature?

2016-12-13 04:32 UTC, KrauseFx commented on fastlane_core/spec/fixtures/ConfigFileForLane
> +end
Can you add a new line here

2016-12-13 15:10 UTC, maschall commented on fastlane_core/spec/configuration_file_spec.rb
> -      it "ignores the same item being set after the first time" do
I was wondering about this, I'll take another stab at it, but I believe (and may be wrong) is that Appfile is not behaving in this same manner, and that was why I looked at removing this.

I'll see what I can do to get this back in there.

2017-01-03 16:48 UTC, asfalcone commented
@maschall It looks like there are a few changes still needed for this PR.

2017-01-14 15:38 UTC, mfurtak commented on fastlane_core/spec/fixtures/ConfigFileForLane
> +end
Done

2017-01-14 18:13 UTC, mfurtak commented
Since it seems like we were still pretty keen on getting this merged, I did some more work on it in #7859 to reconcile what I perceived to be the blocking problems here.

2017-01-15 20:40 UTC, mfurtak commented
Carried forward and merged as part of #7859 👍

2017-01-15 20:40 UTC, closed without merging