Add Bundler detection and change message from update_checker
fastlane/fastlane pull request #6586
Opened 2016-10-17 16:40 UTC by Onejjy

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Here is the code for the Issue #6560

It simply add a `is_bundler` is `Helper` and change the displayed message in `update_checker`.

2016-10-17 20:04 UTC, KrauseFx requested changes

2016-10-17 20:04 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/helper.rb
> +    def self.is_bundler?
We don't actually need this method, we only have some of those duplicates to support legacy code bases. Let's remove this and stick with `bundler?`

2016-10-17 20:04 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +        puts "# Update using 'bundle update #{gem_name.downcase}'.".green
😍

2016-10-17 20:04 UTC, KrauseFx commented on fastlane_core/spec/helper_spec.rb
> +        expect(FastlaneCore::Helper.is_bundler?).to be false
Let's  test `bundler?` directly here

2016-10-17 20:04 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +      if Random.rand(5) == 1 && !Helper.is_bundler?
Let's use `bundler?`

2016-10-17 20:04 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +      if Helper.is_bundler?
Let's use `bundler?`

2016-10-17 20:04 UTC, KrauseFx commented
This is a great addition, thanks @Onejjy 👍  I added some smaller comments before it's ready to be merged 🚀

2016-10-18 07:05 UTC, Onejjy commented
@KrauseFx all requested changes have been made :)

Rubocop report 1 offense on the code:

```
lib/fastlane_core/helper.rb:5:3: C: Module has too many lines. [106/100]
  module Helper ...
  ^^^^^^^^^^^^^

```

I don't really see how to get rid of that. Maybe by splitting into a new module `All Xcode Related things` (from `xcode_path` to `itms_path`) ?

2016-10-18 19:54 UTC, KrauseFx commented
You can add the following right above `module Helper`
```ruby
module FastlaneCore
  # rubocop:disable Metrics/ModuleLength
  module Helper
    ...
```

2016-10-18 19:54 UTC, KrauseFx commented
Thanks for updating the PR 👍

2016-10-18 19:55 UTC, KrauseFx commented
I updated the PR with the new rubocop rules, let's see if the build is happy now 👍

2016-10-18 20:07 UTC, Onejjy commented
Rubocop is happy now ! Thank you for the tip :)

2016-10-18 21:15 UTC, KrauseFx approved these changes

2016-10-18 21:15 UTC, merged

2016-10-18 21:15 UTC, KrauseFx commented
This is great, thanks again for your contribution, this will be in the next release  🚀