[Spaceship] Get and set territories
fastlane/fastlane pull request #6601
Opened 2016-10-18 03:22 UTC by enozero

Allow for iOS territory updating with Spaceship [https://github.com/fastlane/fastlane/issues/6592]

2016-10-24 15:56 UTC, enozero commented
Hello! Any thoughts or questions about this request?

2016-12-19 19:39 UTC, ohwutup commented
Hey @enozero! Apologies for the delay here, would you mind rebasing on master and we can take a closer look at this PR without merge conflicts? Thanks!! 👍 🐙

2016-12-19 20:49 UTC, enozero commented
@ohwutup done

2016-12-21 22:08 UTC, kevinlondon commented
This will be great because it will enable us to programmatically remove apps from sale 👍

2017-01-03 21:43 UTC, mpirri requested changes
This is awesome functionality, I can't wait to get this merged.  So sorry about the delay with reviewing this!

2017-01-03 21:43 UTC, mpirri commented on spaceship/lib/spaceship/tunes/application.rb
> +      def update_availability!(territories, opts = {})
In this implementation, `update_availability` does not take the same type of object as what is returned by `availability`. I.e., `update_availability` takes an array of territories, while `availability` returns an `Availability` object.

So, you can't do something like this without an error:
```
availability = app.availability
app.update_availability!(availability)
```
I could see this as a source of confusion for users.

Some ideas:
- Make `update_availability` take an `Availability` object and create a constructor for `Availability` that takes an array of territories and an optional `include_future_territories` value.
- Split the `availability` accessors into separate `availability_territories` and `availability_include_future_territories` accessors

Thoughts?

2017-01-04 05:11 UTC, enozero commented on spaceship/lib/spaceship/tunes/application.rb
> +      def update_availability!(territories, opts = {})
Thanks for the review! I completely see where you are coming from and like that approach.

2017-01-09 08:56 UTC, enozero commented
@mpirri I have updated the PR with your requested changes. Please let me know if you have any questions about them!

2017-01-12 16:21 UTC, mpirri commented
@enozero Are you sure you committed/pushed up changes to `application.rb`?  It looks to me like it is out of sync with `tunes_client.rb` - for instance, the number of arguments it is passing to `client.update_availability!()` is inconsistent - 3 passed in `application.rb` and 2 accepted in `tunes_client.rb`.

2017-01-12 17:48 UTC, enozero commented
@mpirri Great catch! I forgot to update the `Application` class. That has been updated (along with new added tests). The commit has been updated. Sorry about that!

2017-01-24 20:41 UTC, mpirri approved these changes

2017-01-24 20:41 UTC, mpirri commented
This looks awesome!  Thanks for your work (and patience) on this, @enozero .  🚀

2017-01-24 20:42 UTC, merged

2017-01-24 21:39 UTC, enozero commented
Thanks for the review! Looking forward to contributing more to the project.