Jverdi feature/match multiple appids
fastlane/fastlane pull request #6635
Opened 2016-10-19 22:10 UTC by KrauseFx

Taken from https://github.com/fastlane/fastlane/pull/6080

2016-10-19 23:05 UTC, mfurtak requested changes

2016-10-19 23:05 UTC, mfurtak commented on match/lib/match/runner.rb
> +          params[:app_identifier] = app_identifier
I don't really like the pattern of mutating the `params` `Configuration` object for every iteration over the `app_identifiers` that we do. If these `SpaceshipEnsure` methods don't actually need `Configuration` objects, can we just provide them hashes with the right keys instead?

2016-10-19 23:05 UTC, mfurtak commented on match/lib/match/runner.rb
> +        params[:app_identifier] = app_identifier
Same thought about mutating the `Configuration` object in the loop.

2016-10-19 23:05 UTC, mfurtak commented on match/lib/match/runner.rb
> +        params[:app_identifier] = app_identifier
Same thought about mutating the `Configuration` object in the loop.

2016-10-22 00:27 UTC, KrauseFx commented on match/lib/match/runner.rb
> +          params[:app_identifier] = app_identifier
I agree, I'll update the PR 👍

2016-10-22 00:52 UTC, KrauseFx commented
@mfurtak Perfect, thanks for your feedback. I refactored _match_ to properly pass the `app_identifier` around, great feedback - let me know what you think about the updated code

2016-10-22 00:59 UTC, mfurtak approved these changes

2016-10-22 00:59 UTC, mfurtak commented
🍕 🎉

2016-10-22 01:06 UTC, merged

2016-11-11 18:16 UTC, jcampbell05 commented
Awesome !