[deliver] Print out absolute path if file can't be found
fastlane/fastlane pull request #6651
Opened 2016-10-20 23:52 UTC by KrauseFx

This way it's clear in what path _fastlane_ is running

2016-10-21 00:25 UTC, mfurtak commented
`File.exist?` has trouble with certain kinds file paths. Specifically, I've noticed in the past that it can't handle paths that start with '~'.

```
$ irb
>> File.exist? '~/Documents'
=> false
>> File.exist? File.expand_path('~/Documents')
=> true
```

So, for all of these checks, I think it may be better to capture the `File.expand_path` value first, and then check it in `File.exist?`, and then use it in the message if needed.

2016-10-21 00:27 UTC, mfurtak requested changes
`File.exist?` should ideally only be called on expanded paths.

2016-10-21 22:16 UTC, KrauseFx commented
@mfurtak Yeah, that's true, and we do it in some tools, not everywhere yet though. Let's merge this PR that just improves the error message to make it more clear on how _fastlane_ accesses the files, and have a separate PR that improves file checking and loading across all tools 👍

2016-10-22 10:10 UTC, mfurtak approved these changes

2016-10-23 02:29 UTC, merged