Match enterprise type mismatch
fastlane/fastlane pull request #6708
Opened 2016-10-24 23:43 UTC by milch

There was a mismatch in comparing the types of provisioning profiles when `type: "appstore"` was used with the `MATCH_FORCE_ENTERPRISE`. Generating the profiles would work, but when cloning on a different machine it would try to generate a new certificate or error out in `readonly` mode. 

The error now includes more useful information on why no provisioning profile was found. Conversion of type strings to symbols is now centralized, so the above error doesn't happen anymore.

2016-10-24 23:49 UTC, KrauseFx requested changes
This is awesome, I love how we move the type detection out to its central place, and how we now show additional debug information when something fails  🚀
I added some notes before it's ready to be merged

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match.rb
> +    Match.enterprise? && type != "development"
So running _match_ with type `adhoc` or `appstore` will both use the `enterprise` type? Is that by design?

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match.rb
> +  def self.type_is_enterprise?(type)
Could you add a comment above this method and the `self.enterprise?` to describe what the method returns?

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match/generator.rb
> +      prov_type = Match.profile_type_sym(params[:type])
😍

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match/nuke.rb
> +      cert_type = Match.cert_type_sym type
Please add `( )` around `type`

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match/runner.rb
> +      cert_type = Match.cert_type_sym params[:type]
Please add `( )` for method calls

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match/runner.rb
> +      prov_type = Match.profile_type_sym params[:type]
Please add `( )` for method calls

2016-10-24 23:49 UTC, KrauseFx commented on match/lib/match/runner.rb
> +          UI.error "Certificates in your repo for type `#{prov_type}`:"
This should be `Provisioning profiles` instead of `Certificates`

2016-10-25 01:18 UTC, milch commented on match/lib/match.rb
> +    Match.enterprise? && type != "development"
Previously there were two different checks: `type != "development"` and `type == "enterprise"`. I chose to go with the more permissive one.

2016-10-25 02:42 UTC, KrauseFx approved these changes

2016-10-25 02:43 UTC, merged

2016-10-25 02:43 UTC, KrauseFx commented
Great changes, thanks 👍