[spaceship] Add update check to ensure people are running the latest release
fastlane/fastlane pull request #6800
Opened 2016-10-31 01:06 UTC by KrauseFx

<img width="388" alt="screenshot 2016-10-30 15 31 17" src="https://cloud.githubusercontent.com/assets/869950/19841611/920dc5ca-9ecb-11e6-911e-67eae9407eb7.png">

We’ve had many issues around users not using the latest version of spaceship.
While we show update messages in the tools themselves, spaceship didn’t show a warning before. This way we also had to push new releases for all tools depending on spaceship

We don't use the update manager from _fastlane_core_ as _spaceship_ doesn't have a dependency to it.

2016-10-31 13:58 UTC, ohwutup commented on spaceship/lib/spaceship/update_checker.rb
> +      version = JSON.parse(response.body)["version"]
Just curious here: why don't we check RubyGems for the most up to date version here instead of _refresher_?

2016-10-31 17:01 UTC, KrauseFx commented
Update: this needs to work better when we have no internet connection

2016-10-31 18:09 UTC, KrauseFx commented
This is ready now  🚀

2016-10-31 23:28 UTC, milch requested changes
⛔

2016-10-31 23:28 UTC, milch commented on spaceship/lib/spaceship/update_checker.rb
> +      puts "You're on spaceship: #{local_version}".yedllow
`.yedllow`

2016-10-31 23:28 UTC, milch commented on spaceship/lib/spaceship/update_checker.rb
> +      puts "Latest spaceship   : #{live_version}".yellow
Also might be worthwhile to say "[Latest|You're on] spaceship version" for these two lines, doesn't hurt to be verbose.

2016-11-01 00:34 UTC, KrauseFx commented
@milch: Perfect, thanks. Fixed 👍

2016-11-01 01:14 UTC, milch approved these changes

2016-11-01 01:25 UTC, merged