[WIP] Support Uploading iMessage screenshots
fastlane/fastlane pull request #6823
Opened 2016-11-01 19:43 UTC by JustinJiaDev

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [ ] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [ ] Run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2016-11-01 19:44 UTC, JustinJiaDev commented
This is an attempt to fix https://github.com/fastlane/fastlane/issues/6124

2016-11-02 00:52 UTC, KrauseFx submitted a review, later dismissed
Hey @JustinJiaDev, this is great, thanks for tackling this issue, I'm sure it will help a ton of people. Since this is affecting both _spaceship_ and _deliver_ would you mind splitting the two up, so we can first merge and release the change in _spaceship_?

What parts are missing? 👍

2016-11-02 00:52 UTC, KrauseFx commented on deliver/lib/deliver/app_screenshot.rb
> +      devices = path_component.eql?("iMessage") ? device_messages : self.devices
So the screenshots must be inside of an `iMessage` folder or contain it in the name? If so, we have to document this somewhere

2016-11-02 08:18 UTC, JustinJiaDev commented
Okay! I'm going to split this one.

2016-11-02 08:27 UTC, JustinJiaDev commented
@KrauseFx This is for `spaceship`. I think it's ready to be merged.

2016-11-02 17:35 UTC, KrauseFx commented
Is this and https://github.com/fastlane/fastlane/pull/6830 ready for review and merge?

2016-11-02 22:19 UTC, JustinJiaDev commented
@KrauseFx Not yet. Something is still broken. But I think I can fix it in a few hours.

2016-11-06 02:12 UTC, JustinJiaDev commented
@KrauseFx This and #6830 are ready. A little bit more work than I expected since iTC handles iMessage screenshots using different JSON format and their sizes are same as normal screenshots.

2016-11-08 20:48 UTC, JustinJiaDev commented
@KrauseFx Is there anything I need to change? 😄

2016-11-16 23:11 UTC, JustinJiaDev commented
@KrauseFx I hope this can be merged soon. If there are things I need to change, please let me know. Thanks!

2016-11-17 18:59 UTC, milch commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ship iMessage Sticker Pack compatibility](https://trello.com/c/H1epLhZJ/533-ship-imessage-sticker-pack-compatibility)

2016-11-17 19:03 UTC, JustinJiaDev commented
@milch Thanks for the link but seems like it's a private card. I can't view it.

2016-11-17 19:04 UTC, milch commented
Whoops, that wasn't supposed to end up here. 

@JustinJiaDev I'm working on this right now, we'll try to make sure it ships today!

2016-11-17 19:06 UTC, JustinJiaDev commented
@milch Thanks for the information! Please let me know if I need to do anything!

2016-11-17 23:49 UTC, milch requested changes
The code seems solid, I just have a small change request. I'll review the other PR's code, then do some testing to see if everything works on iTunes Connect, and if everything checks out I'll merge!

2016-11-17 23:49 UTC, milch commented on spaceship/lib/spaceship/tunes/app_version.rb
> +          next unless display_family_screenshots
Unless the value of display_family screenshots is explicitly set to `nil` in the hash, this line never triggers because of the `fetch` above

2016-11-18 07:02 UTC, JustinJiaDev commented on spaceship/lib/spaceship/tunes/app_version.rb
> +          next unless display_family_screenshots
I forget why I exactly did that, but I'm pretty sure under certain circumstances `display_family_screenshots` is nil. I fixed the bug specifically in a commit: https://github.com/fastlane/fastlane/pull/6823/commits/355403ec5bff4f9029dc5416650a6eb356e38906

2016-11-18 22:10 UTC, milch approved these changes

2016-11-18 22:12 UTC, merged

2016-11-18 22:12 UTC, milch commented
Thanks a lot for your contribution! 🚀