[deliver] Support iMessage Screenshots
fastlane/fastlane pull request #6830
Opened 2016-11-02 08:38 UTC by JustinJiaDev

2016-11-02 17:35 UTC, KrauseFx commented
Is this and https://github.com/fastlane/fastlane/pull/6823 ready for review and merge?

2016-11-06 02:10 UTC, JustinJiaDev commented
@KrauseFx This and #6823 are ready now!

2016-11-17 18:59 UTC, milch commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ship iMessage Sticker Pack compatibility](https://trello.com/c/H1epLhZJ/533-ship-imessage-sticker-pack-compatibility)

2016-11-17 19:04 UTC, JustinJiaDev commented
@milch Thanks for the link but seems like it's a private card. I can't view it.

2016-11-18 04:31 UTC, milch requested changes
Seems solid as well! Just a small typo here.

2016-11-18 04:31 UTC, milch commented on deliver/lib/assets/ScreenshotsHelp
> +screenshots, like Apple TV screenshots, should also be stored in a subdirectory name iMessage
`... in a subdirectory named...`

2016-11-18 05:26 UTC, milch commented
I tried doing some tests with this, and regular screenshot upload is still working fine (as expected), however, I couldn't get iMessage screenshots to upload. I created a folder titled `iMessage` in my `./fastlane/screenshots` folder and put the screenshots in the language-coded subfolder, e.g. `./fastlane/screenshots/iMessage/en-US/screen1.png`. Should there be any other steps necessary?

2016-11-18 06:39 UTC, JustinJiaDev commented on deliver/lib/assets/ScreenshotsHelp
> +screenshots, like Apple TV screenshots, should also be stored in a subdirectory name iMessage
Fixed!

2016-11-18 06:41 UTC, JustinJiaDev commented
@milch 

I tested using my personal account and I worked as expected. Did you test it with the updated version of `spaceship`? Are iMessage screenshots being collected?

2016-11-18 22:10 UTC, milch commented
@JustinJiaDev I just reset the whole screenshots folder and re-did everything, it seems to work now. Maybe I had a typo somewhere, although it's weird that uploading the regular screenshots worked then. 

Anyway, this is a great PR, thanks a lot for your contribution! 🚀

2016-11-18 22:10 UTC, milch approved these changes

2016-11-18 22:12 UTC, JustinJiaDev commented
Thanks for the review!

2016-11-18 22:12 UTC, merged