[fastlane] Update error message when using fastlane_version with bundle
fastlane/fastlane pull request #6831
Opened 2016-11-02 08:43 UTC by Onejjy

Here is a PR to fix #6828 :)

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2016-11-02 15:13 UTC, milch requested changes
Looks good, except for the commit history: there's merge commits, duplicate commits, reverts, ... 

Please fix the history, e.g. by cherry picking your changes on top of the current master and force-pushing to this branch to get rid of the old history, then we can merge this.

2016-11-02 17:55 UTC, Onejjy commented
Indeed, it was a mess 🙈. It should be better now !

2016-11-02 20:09 UTC, KrauseFx commented on fastlane/spec/actions_specs/fastlane_version_spec.rb
> +      it "raises an exception if it's an old version in a non-bundler environement" do
tests ❤️

2016-11-02 20:09 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/fastlane_version.rb
> +          update_message = nil
You don't need to init this to `nil`

2016-11-02 20:12 UTC, milch commented
@Onejjy Thanks for fixing the history! Once you fix Felix's suggestion we'll merge.

2016-11-03 08:02 UTC, Onejjy commented
This is fixed :)

2016-11-03 20:36 UTC, milch approved these changes

2016-11-03 20:36 UTC, merged