[WIP] Implement `fastlane_require` to automatically install gems into bundle
fastlane/fastlane pull request #6858
Opened 2016-11-04 01:43 UTC by KrauseFx

2016-11-04 01:45 UTC, KrauseFx commented on fastlane/lib/fastlane/fast_file.rb
> +        next if current.include?("/")
This could be improved

2016-11-04 15:40 UTC, ohayon approved these changes
I think this looks really awesome! 💯

2016-11-04 15:40 UTC, ohwutup commented on fastlane/lib/fastlane/fast_file.rb
> +        next if current.include?("/")
What is this looking for exactly?

2016-11-04 15:40 UTC, ohwutup commented on fastlane/lib/fastlane/fast_file.rb
> +      content.scan(/.*require (.*)/).each do |current|
Are we looking for `.*require` because we want to check both `fastlane_require` and regular `require`?

2016-11-04 19:55 UTC, hjanuschka commented
@KrauseFx will this work  on Fastfiles imported with `import_from_git` too? (would be awesome!)

2016-11-08 00:08 UTC, milch requested changes

2016-11-08 00:08 UTC, milch commented on fastlane/lib/fastlane/fast_file.rb
> +        next if require_command.include?("fastlane_require")
Use a regex that only matches require and not `fastlane_require`, like `^\s*(require) (.*)`

2016-11-08 00:08 UTC, milch commented on fastlane/lib/fastlane/fast_file.rb
> +      FastlaneRequire.install_gem(gem_name: gem_name, require_gem: true)
`install_gem` should probably be called `install_gem_if_needed`

2016-11-08 00:08 UTC, milch commented on fastlane_core/lib/fastlane_core/helper.rb
> +      ENV["FASTLANE_IS_BUNDLED"].to_s.length > 0
Maybe do an explicit check for `== "true"` here or something, or things will break if someone sets `ENV["FASTLANE_IS_BUNDLED"]="false"` in the future

2016-11-08 00:14 UTC, milch commented on fastlane_core/lib/fastlane_core/helper.rb
> +      ENV["FASTLANE_IS_BUNDLED"].to_s.length > 0
Note: I've left this comment to link to in the other PR, this should be removed if we split this into 2 PR's

2016-11-08 00:41 UTC, KrauseFx commented
@milch Thanks for the feedback, I updated the PR 👍

2016-11-08 00:55 UTC, milch commented on fastlane/lib/fastlane/actions/cocoapods.rb
> +        cmd << ['bundle exec'] if params[:use_bundle_exec] && shell_out_should_use_bundle_exec?
Still not 100% satisfied with this. I'd go for 

```ruby
def self.shell_bundle_exec_prefix
    shell_out_should_use_bundle_exec ? "bundle exec" : ""
end
```

and then do 

```ruby
cmd << shell_bundle_exec_prefix if params[:use_bundle_exec]
```

everywhere (or something).

2016-11-08 00:56 UTC, milch commented on fastlane/lib/fastlane/actions/cocoapods.rb
> +        cmd << ['bundle exec'] if params[:use_bundle_exec] && shell_out_should_use_bundle_exec?
Although I'm willing to conceded that that would be the cherry  on top, more or less, so if the `contained_fastlane?` thing is fixed I'd be okay to merge.

2016-11-08 01:42 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/cocoapods.rb
> +        cmd << ['bundle exec'] if params[:use_bundle_exec] && shell_out_should_use_bundle_exec?
Yeah, let's try to get the first version working and refactor this later on.

2016-11-08 01:45 UTC, milch commented on fastlane/lib/fastlane/actions/cocoapods.rb
> +        cmd << ['bundle exec'] if params[:use_bundle_exec] && shell_out_should_use_bundle_exec?
Makes sense

2016-11-08 01:48 UTC, milch approved these changes

2016-11-09 19:25 UTC, merged