[fastlane] add troubleshoot option 🔫
fastlane/fastlane pull request #6889
Opened 2016-11-07 13:59 UTC by hjanuschka

as proposed here - to help debugging/troubleshooting.
https://github.com/fastlane/fastlane/issues/6878

adds `--troubleshoot`  enables `log:true`  on all `.sh` calls.
this should not be run on CI

2016-11-08 02:08 UTC, milch commented
I think this needs some more discussion, see my comments in #6878. I'll add [WIP] to the title for now to reflect this.

2016-11-08 06:57 UTC, hjanuschka commented
@milch i did a confirm arround the option.

`fastlane demo --troubleshoot`

![bildschirmfoto 2016-11-08 um 07 57 18](https://cloud.githubusercontent.com/assets/2891702/20089719/07166fc0-a589-11e6-9bea-baa2f87d5317.png)

2016-11-09 22:38 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +        UI.user_error!("Do not use --troubleshoot in CI")
Do we really want to force people not to do that? Showing a warning is fine, but I think we should still let them do their thing.

2016-11-09 22:39 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +      if agree("(y/n)", true)
Please use `UI.confirm` instead, which should add the `y/n` for you 👍

2016-11-09 22:39 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +      global_option('--troubleshoot', 'Enables extended verbose mode, beware this eventually includes passwords, should not be run on CI')
Besides here, do we want to document this anywhere?

2016-11-09 22:40 UTC, milch commented on fastlane/lib/fastlane/commands_generator.rb
> +        UI.user_error!("Do not use --troubleshoot in CI")
See the discussion here: #6878

2016-11-10 07:08 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +        UI.user_error!("Do not use --troubleshoot in CI")
both are right  - please just let me know if we should keep or remove it.

2016-11-10 07:10 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +      global_option('--troubleshoot', 'Enables extended verbose mode, beware this eventually includes passwords, should not be run on CI')
where would be a good place?

2016-11-10 07:10 UTC, hjanuschka commented
@KrauseFx  feedback adressed

2016-11-10 17:29 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +        UI.user_error!("Do not use --troubleshoot in CI")
I wasn't aware of the previous discussion, let's keep it then

2016-11-11 21:14 UTC, milch requested changes

2016-11-11 21:14 UTC, milch commented on fastlane/lib/fastlane/commands_generator.rb
> +      UI.error "Are you sure to enable '--troubleshoot'."
`Are you sure you want to enable '--troubleshoot'?`

2016-11-11 21:14 UTC, milch commented on fastlane/lib/fastlane/commands_generator.rb
> +      UI.error "Beware that there maybe passwords printed to the console/log."
`Sensitive data, like passwords, could be printed to the log.`

2016-11-11 21:14 UTC, milch commented on fastlane/lib/fastlane/commands_generator.rb
> +      global_option('--troubleshoot', 'Enables extended verbose mode, beware this eventually includes passwords, should not be run on CI')
For the description: `Enables extended verbose mode. Use with caution, as this even includes ALL sensitive data. Cannot be used on CI.`

2016-11-12 18:21 UTC, hjanuschka commented
@milch  feedback adressed

2016-11-14 23:39 UTC, milch approved these changes

2016-11-14 23:40 UTC, milch commented
Looks good, thanks!

2016-11-14 23:40 UTC, merged