[match] print certificate info ℹ️
fastlane/fastlane pull request #6907
Opened 2016-11-08 14:14 UTC by hjanuschka

this one redoes https://github.com/fastlane/fastlane/pull/5061 - credit goes to @punksta
i had to rework it - as merging/rebasing was to heavy.

![bildschirmfoto 2016-11-08 um 15 10 20](https://cloud.githubusercontent.com/assets/2891702/20102273/db28315e-a5c5-11e6-94d7-a2c7fc3262ef.png)

2016-11-14 23:32 UTC, milch requested changes
Just tried it, I really like this change, thanks! 🚀  Needs some simplification, then we can merge.

2016-11-14 23:32 UTC, milch commented on match/lib/match/utils.rb
> +    def self.fill_environment_cert(params, identity)
This seems to be unused, in that case, remove please.

2016-11-14 23:32 UTC, milch commented on match/lib/match/runner.rb
> +        if cert_name.length > 0
Why is this check needed? When would the length be 0?

2016-11-14 23:32 UTC, milch commented on match/lib/match/utils.rb
> +      oppenssl_keys_to_readable_keys = {
typo: `oppenssl_keys_to_readable_keys` -> `openssl_keys_to_readable_keys`

2016-11-14 23:32 UTC, milch commented on match/lib/match/utils.rb
> +      subject_value = output[0][output[0].index('=') + 2, output[0].length]
Do `.gsub(/\s*subject=\s*/, "")` and `.gsub("/", "\n")` before running `.split("\n")` instead, that's a bit more clear and doesn't introduce 2 temporaries.

2016-11-14 23:32 UTC, milch commented on match/lib/match/utils.rb
> +      table_data = key_value_pairs.map { |k, v| [oppenssl_keys_to_readable_keys.fetch(k, k), v] }
We don't need to introduce temporaries here, with the changes from above you can do:

```ruby
       output.map { |x| x.split(/=+/) if x.include? "=" }
                  .compact
                  .map { |k, v| [oppenssl_keys_to_readable_keys.fetch(k, k), v] }
```

2016-11-15 07:44 UTC, hjanuschka commented
@milch feedback addressed.

about the `cert_info.length > 0` check on `common name` - i took it from the original PR - i think its because of "in X.509 the Common Name is not mandatory." - but i think its ok to skip/remove that check, as in ios world - common name is always set.

  * rebased current master

2016-11-16 23:24 UTC, milch approved these changes

2016-11-16 23:26 UTC, milch commented
@hjanuschka Alright, this looks good to me then. Thanks for your contribution! 🚀 

PS: In the future, when addressing reviews and/or rebasing on master, please don't `--amend` and force push. It makes it easier to just quickly scan over just the requested changes, instead of having to go through all the code again. We squash anyway before merging 😉

2016-11-16 23:26 UTC, merged

2016-11-17 06:46 UTC, hjanuschka commented
@milch - ok thx for the info, will do so in the future - just a bad habbit (from back in the days when it was not possible to squash) to submit only one commit!

2016-12-02 22:21 UTC, KrauseFx commented
Is the country always US?

2016-12-03 10:45 UTC, hjanuschka commented
@KrauseFx seems to be always US - not sure why - either apple or sigh (in the crt) ?

2016-12-03 18:31 UTC, hjanuschka commented
@KrauseFx  infact i think its defaulting to US - because  fastlane/spaceship - does not set a country code.


https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb#L195 the country should be included in the subject of the CSR.


sample on how to set country code:
https://gist.github.com/mitfik/1922961#file-ruby_csr_example-rb-L31