[fastlane] add locale envs
fastlane/fastlane pull request #6915
Opened 2016-11-08 19:07 UTC by hjanuschka

as proposed here: https://github.com/fastlane/fastlane/issues/6914

2016-11-08 19:10 UTC, KrauseFx commented on fastlane/lib/fastlane/environment_printer.rb
> +      env_output << print_system_locale
Isn't that something we could fix, instead of just showing in the output?

2016-11-08 19:16 UTC, hjanuschka commented
yeah i am not sure what happens once you enforce en_US.utf8 - on a system wich hasn't installed the locale.

for debugging/troubleshooting, having it in `fastlane env` is nice anyway.
(not 100% sure about the emojis, there are a lot of charsets without problems - that are not US)

2016-11-08 21:02 UTC, milch commented
I agree, I'm not sure about all the things that could possibly break if we just set the locale for the user. At least now we know the error message, it's easy to debug, and if we spot that the locale is set incorrectly in the `env` output (after merging this PR) it'll be easy to close issues that have this problem as well.

2016-11-08 22:12 UTC, milch requested changes

2016-11-08 22:12 UTC, milch commented on fastlane/lib/fastlane/environment_printer.rb
> +        if ["en_US.UTF-8", "de_DE.UTF-8"].include?(ENV[e]) || !ENV[e]
How about we just test that it is ending in `.UTF-8` instead? I've read reports from users using it with all kinds of UTF-8 locales and it fixed their issues.

2016-11-08 22:14 UTC, milch commented
I think we should merge this for now since I think it's going to be useful, we can always revert it later if we decide to just set the environment ourselves. There's some other code we'd need to remove too, anyway.

2016-11-09 07:08 UTC, hjanuschka commented
yeah i think it is not bad to have locale info in issues - once we decide to set it on startup our self,
i am happy to do a PR and remove the code or rework it - to print all `FASTLANE_|FL_|DELIVER....` env (only if they exists, without value for sure 👍 )


@milch ok i redid it with `end_with?` - UTF8

and removed the broken sign on undefined envs.
and also check if atleast one of the vars has UTF8 otherwise output this table:

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

2016-11-09 22:32 UTC, milch approved these changes

2016-11-09 22:32 UTC, milch commented
Thanks, looks good!

2016-11-09 22:33 UTC, merged