Webpush Id support added for spaceship.
fastlane/fastlane pull request #6943
Opened 2016-11-10 07:33 UTC by ilhanadiyaman

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2016-12-19 20:50 UTC, ohwutup commented
Hey @ilhanadiyaman! Thanks for the PR! Would you mind just writing down a bit of a summary of these changes? Thanks!

2017-01-24 17:42 UTC, ohwutup commented
Hey @ilhanadiyaman! Thanks for this PR! I am going to go ahead and close it for now because there has not been any activity on it in quite some time. Please feel free to provide more context around why this PR is helpful and we would be happy to reopen it and consider getting in merged in! Feel free to ping any of us on here when you have the time! Thanks again! 🚀 🐙

2017-01-31 12:43 UTC, RafaelPlantard commented
I like it!

2017-01-31 15:21 UTC, ilhanadiyaman commented
Hi @ohwutup! Sorry for my late response, I forgot to add my comments. This PR is actually adds web push notification identifier creating/listing/deleting operations to spaceship. Web push identifiers are another entities in the portal and it would be helpful for people who wants to automate their web push identifier generation process. In our [web push notification startup](https://frizbit.com/?utm_source=github), we need to automate this process. Because, most of our customers were having trouble with creating web push identifier via Apple Developer Portal. With the help of this PR, we solve this issue. This is why I thought there may be other people who were suffering from the same problem. Cheers! 🚀

2017-01-31 15:44 UTC, RafaelPlantard commented
@ilhanadiyaman is possible generate a web push identifier and also creating certificate (pem, p12) files?

2017-01-31 15:45 UTC, hjanuschka reviewed
@ilhanadiyaman looking good so far, i think its a good thing for spaceship.
left one comment. and could you please add samples on how to interact with the new api. like here: https://github.com/fastlane/fastlane/pull/8047

then i am going to test this 👍

2017-01-31 15:45 UTC, hjanuschka commented on spaceship/spec/portal/website_push_spec.rb
> +require 'spec_helper'
i dont think that is required

2017-01-31 15:59 UTC, hjanuschka requested changes
see comment before - also can you please fix the merge conflicts.

2017-01-31 15:59 UTC, ilhanadiyaman commented
@RafaelPlantard yes actually this is how we are using it on our startup right now. We are creating first the web push identifiers over spaceship then generating certificates by using pem(it already supports web push certificates no need to change.).

@hjanuschka I will take a look probably tonight or tomorrow.

2017-01-31 16:00 UTC, hjanuschka commented
@ilhanadiyaman thats awesome so this is the missing piece to fully automate webpush things, maybe add a pem sample too ;)

2017-01-31 16:00 UTC, RafaelPlantard commented
@ilhanadiyaman Can you show me how to generate a pem file with PEM? please, rsrs

2017-01-31 16:04 UTC, ilhanadiyaman commented
@RafaelPlantard I will provide sample codes about our process. Hopefully, tomorrow..

2017-01-31 16:15 UTC, RafaelPlantard commented
Thanks @ilhanadiyaman

2017-02-02 02:10 UTC, RafaelPlantard commented
@ilhanadiyaman can you help me with the samples?

2017-02-02 03:48 UTC, KrauseFx commented on spaceship/spec/portal/website_push_spec.rb
> +require 'spec_helper'
👍

2017-02-05 00:49 UTC, ilhanadiyaman commented
@hjanuschka ready for review. @RafaelPlantard I have checked my forked repository. But regretfully, in order to create certificates I just realized that I made changes on pem as well. Those changes are not well tested. This is why I couldn't added that feature to this pull request.

2017-02-05 01:41 UTC, RafaelPlantard commented
Any release date to merge this PR @ohwutup?

2017-02-05 18:40 UTC, hjanuschka approved these changes
🚀 awesome! many thx for your contribution.

2017-02-05 18:41 UTC, merged

2017-03-02 07:30 UTC, hjanuschka commented
@ilhanadiyaman am i right that only pem changes are missing, to complete the website push creation? have you found any time to finish it?

2017-03-03 16:37 UTC, ilhanadiyaman commented
@hjanuschka Last month I couldn't find enough time to work on it. I will take a look at it to finalize pem testing. If I can't finish this week, I will pass it to you..