Pilot update description on upload
fastlane/fastlane pull request #6946
Opened 2016-11-10 13:32 UTC by tadelv

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [] Run `bundle exec rubocop -a` to ensure the code style is valid
- [] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

an update to https://github.com/fastlane/fastlane/pull/6631. This is a new version of the previous pull request. The changes are rebased to the current master.

2016-11-15 01:38 UTC, milch requested changes
Thanks for your submission! 

Looks good to me, just a small change needed please 🚀

2016-11-15 01:38 UTC, milch commented on pilot/lib/pilot/build_manager.rb
> +            must_update_build_info = false
This doesn't do anything, remove please.

2016-11-15 10:45 UTC, tadelv commented on pilot/lib/pilot/build_manager.rb
> +            must_update_build_info = false
I'm not sure I understand. I need to set this flag in order **not** to update build info on every pass of the loop while still waiting for the build to be fully processed. Am I missing something?

2016-11-15 20:48 UTC, milch commented on pilot/lib/pilot/build_manager.rb
> +            must_update_build_info = false
Ah, true. I must've blacked out there for a second and missed the loop.

2016-11-15 20:48 UTC, milch approved these changes

2016-11-15 22:35 UTC, merged

2016-12-13 17:52 UTC, KrauseFx commented on pilot/lib/pilot/build_manager.rb
> +          build.update_build_information!(whats_new: options[:changelog], description: options[:beta_app_description], feedback_email: options[:beta_app_feedback_email])
Seems like `build` is undefined here

2016-12-13 18:11 UTC, milch commented on pilot/lib/pilot/build_manager.rb
> +              build.update_build_information!(whats_new: options[:changelog], description: options[:beta_app_description], feedback_email: options[:beta_app_feedback_email])
For posterity: This line introduced the issue #7439