[fastlane_core] Move update command to its own method
fastlane/fastlane pull request #6953
Opened 2016-11-11 01:42 UTC by KrauseFx

- Better support for bundled fastlane update command
- Little refactoring to make the code nicer
- Don’t show `gem cleanup` message for bundled fastlane
- Add tests for that

2016-11-11 23:15 UTC, milch requested changes

2016-11-11 23:15 UTC, milch commented on fastlane_core/spec/update_checker_spec.rb
> +    describe "#update_command" do
❤️ Tests

2016-11-11 23:15 UTC, milch commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +      gem_name ||= "fastlane"
Why use `nil` as default and then set it to fastlane if it's nil?

2016-11-11 23:15 UTC, milch commented on fastlane_core/lib/fastlane_core/update_checker/changelog.rb
> +        puts "\nPlease update using `#{UpdateChecker.update_command(gem_name: gem_name)}`".green if did_show_changelog
`puts "", ...` instead of the `\n` at the beginning of the line

2016-11-14 22:52 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +      gem_name ||= "fastlane"
That's how I did it until now across the fastlane code base. Should I just include it inside the brackets?

2016-11-14 22:53 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/update_checker/changelog.rb
> +        puts "\nPlease update using `#{UpdateChecker.update_command(gem_name: gem_name)}`".green if did_show_changelog
So I can do the following? 
```ruby
puts "", "Please update using `#{UpdateChecker.update_command(gem_name..."
```
I feel like this is more confusing, especially for non-Ruby developers, as you have to know how Ruby handles this. `\n` is universally understood by developers.

2016-11-14 22:53 UTC, milch commented on fastlane_core/lib/fastlane_core/update_checker/update_checker.rb
> +      gem_name ||= "fastlane"
Yeah, I think that'd make more sense.

2016-11-14 22:54 UTC, milch commented on fastlane_core/lib/fastlane_core/update_checker/changelog.rb
> +        puts "\nPlease update using `#{UpdateChecker.update_command(gem_name: gem_name)}`".green if did_show_changelog
Then how about this:

```ruby
  puts ""
  puts "Please update using `#{UpdateChecker.update_command(gem_name..."
```

Reason is consistency, we almost never use explicit '\n' in the code

2016-11-15 20:45 UTC, KrauseFx commented on fastlane_core/spec/update_checker_spec.rb
> +    describe "#update_command" do
The best

2016-11-15 20:45 UTC, KrauseFx commented
Updated 👍

2016-11-15 20:46 UTC, milch approved these changes

2016-11-15 20:46 UTC, milch commented
🎷

2016-11-15 21:58 UTC, merged