[fastlane] output contained in env
fastlane/fastlane pull request #6955
Opened 2016-11-11 07:49 UTC by hjanuschka

as proposed here: https://github.com/fastlane/fastlane/pull/6950#issuecomment-259813816

2016-11-12 00:53 UTC, milch requested changes

2016-11-12 00:53 UTC, milch commented on fastlane/lib/fastlane/environment_printer.rb
> +        "Contained Version" => Helper.contained_fastlane?.to_s
`"Is contained"` would be better, since the value will be `true` or `false`

2016-11-12 18:15 UTC, hjanuschka commented
@milch feedback addressed.

2016-11-14 22:40 UTC, milch approved these changes

2016-11-14 22:43 UTC, merged