Allow commit_version_bump to find the Settings.bundle in the project
fastlane/fastlane pull request #6997
Opened 2016-11-14 22:39 UTC by jdee

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x ] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
 Some tests are failing in master and continue to fail here. This action actually has no tests. I may add some.
- [x ] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x ] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Please see issue #5758.

This change allows the `commit_version_bump` action to infer the location of the Settings.bundle from the project. It also adds a new optional :settings_file parameter that allows the user to specify a plist file in the Settings.bundle other than Root.plist.

2016-11-14 22:43 UTC, jdee commented
This is also related to #6482.

2016-11-25 16:55 UTC, jdee commented
There are probably not too many cases where an app might include multiple settings plist files in a version bump, but it doesn't seem too far-fetched to think that someone might want to update their `Root.plist` as well as an `About.plist` and so on.

A common Ruby idiom is to allow different types to be passed to an argument, e.g.

```ruby
commit_version_bump xcodeproj: "MyProject.xcodeproj", settings: true # Root.plist
commit_version_bump xcodeproj: "MyProject.xcodeproj", settings: "About.plist"
commit_version_bump xcodeproj: "MyProject.xcodeproj", settings: [ "Root.plist", "About.plist" ]
```

This might be simpler than adding multiple new arguments like `settings_file:` (currently in this branch) and `settings_files:`. But I'm not sure if the `ConfigItem` can support this. I suppose I could check. Either way, it wouldn't be hard to support including multiple files. 

Please let me know if further work is needed for this PR to be merged. Thanks.

2016-12-08 20:32 UTC, ohwutup commented
Hey @jdee ! Thanks for the PR, apologies for the delay in reviewing! 

This looks good... I think it would be great to have everything in one option (`ConfigItem`). I don't think you should have a problem allowing it to be multiple types by not specifying the type and then just inspecting the type at runtime.

Let me know if you have any questions!

2016-12-08 20:33 UTC, ohayon requested changes

2016-12-08 20:33 UTC, ohwutup commented on fastlane/lib/fastlane/actions/commit_version_bump.rb
> +          file = params[:settings_file]
Would be great to combine these.

2016-12-08 20:33 UTC, ohwutup commented on fastlane/lib/fastlane/actions/commit_version_bump.rb
> +                                       type: String),
Just skip the type specification here.

2016-12-09 05:02 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/commit_version_bump.rb
> +          File.join project_parent, settings_bundle.path, settings_file_name
Please surround this with `(` and `)`

2016-12-21 19:05 UTC, jdee commented
Hi @ohwutup. Sorry for the delay. I had an app to get out. Thanks for the feedback. I think this is much nicer now. In fact these are all now equivalent:

```ruby
commit_version_bump xcodeproj: "MyApp.xcodeproj", settings: true
commit_version_bump xcodeproj: "MyApp.xcodeproj", settings: "Root.plist"
commit_version_bump xcodeproj: "MyApp.xcodeproj", settings: ["Root.plist"]
```

I also added some tests for the methods I added. Please let me know if there's anything left to be done. Thanks.

2016-12-21 19:11 UTC, ohwutup commented
Thanks for making those changes @jdee ! If you don't mind, can we just change one more little thing about this? I think that `settings` is a bit of an ambiguous name for the option. Can we change that to be something a bit more descriptive?

2016-12-21 19:41 UTC, jdee commented
Hi @ohwutup. I'd be happy to change that. Any suggestions? Maybe `include_settings`, `settings_plist(s)`, `settings_file(s)`, `include_settings_file(s)`, `include_settings_plists(s)`?

Also, what if someone is using the current syntax. I know it was broken, but in a couple of apps at my last job, I was using `settings: true, force: true` and I just put the Settings.bundle at the top of the repo. Maybe the action could report an error if the old argument is supplied and say, "Please use the new syntax." Or both could be supported for now. Or just forget about it and change it?

2016-12-21 20:59 UTC, ohwutup commented
Oh! My bad @jdee! Was there already a flag called `settings`? Sorry, there are so many options for different tools I must have gotten mixed up! If there was already a `settings` we should just go with that! Really sorry for the back and forth!

2016-12-22 16:25 UTC, jdee commented
No worries, @ohwhtup. I thought that might be the case. I'll revert that commit and submit a PR to the docs repo. Thanks.

2016-12-22 18:55 UTC, ohayon approved these changes

2016-12-22 18:55 UTC, merged

2016-12-22 18:56 UTC, ohwutup commented
Thanks for the PR and working through all the changes @jdee !! 🚀

2016-12-22 20:02 UTC, jdee commented
My pleasure. Fastlane is a nice tool. I'm glad to be able to contribute.