Anonymize paths in `fastlane env` output
fastlane/fastlane pull request #7037
Opened 2016-11-16 00:02 UTC by 0xced

- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

---

This way, the username is not leaked. Also, it makes it easy to visually spot when a path is in the user’s home directory.

2016-11-16 07:35 UTC, hjanuschka commented
i really like that. recently was thinking about doing a `UI.input`  before copy&paste - and asking the user for strings that they wan't to be removed? like (app identifier ...) - what do you think about it @0xced

2016-11-16 08:41 UTC, 0xced commented
@hjanuschka This is a good idea, but it should be done in another pull request IMHO. I wonder how much data we could anonymize automatically, without needing `UI.input`.

2016-11-16 23:45 UTC, milch requested changes

2016-11-16 23:45 UTC, milch commented on fastlane/lib/fastlane/environment_printer.rb
> +      return ENV['HOME'] ? path.gsub(/^#{ENV['HOME']}/, '~') : path
In the super edgy edge case that the user's home dir is the prefix of other folders this is gonna output garbage. Example: `$HOME=/work`, `anonymized_path("/workspace/whatever/fastlane")` => `~space/whatever/fastlane`. 

Might be more applicable to linux where the user's home dir is not generally inside the `/Users/` folder.

2016-11-17 06:50 UTC, hjanuschka commented
@milch @0xced 

how about this PR here -> https://github.com/fastlane/fastlane/pull/5982
we could refactor all options and set the flags on all critical parameters, and use this in some way to anonymize?

2016-11-17 18:52 UTC, milch commented
@hjanuschka Yeah, I've thought about something like that before. Sounds good to me, @0xced do you have any thoughts about that?

2016-11-18 16:09 UTC, 0xced commented
I updated the code, and added a [spec](https://github.com/0xced/fastlane/blob/8a93790d8ecee25e9b6b8e83499592b6e7443c41/fastlane/spec/env_spec.rb#L39-L42).

With $HOME == /Users/john
`/Users/john/.fastlane/bin/bundle/bin/fastlane` → `~/.fastlane/bin/bundle/bin/fastlane`
`/Users/john` → `~`
`/Users/john/` → `~/`

With $HOME == /work
`/workspace/project/test` → `/workspace/project/test`

2016-11-18 19:28 UTC, milch approved these changes
Looks good now! Thanks for your contribution 🚀

2016-11-18 19:28 UTC, merged