[snapshot] support for built-for-testing, test-without-building
fastlane/fastlane pull request #7131
Opened 2016-11-22 12:36 UTC by hjanuschka

This one refactors snapshot to use `build-for-testing` and `test-without-building`
to massive improve snapshot runtime.

run with (in fastlane clone):

`bundle exec snapshot --project snapshot/example/Example.xcodeproj -s Example`

```
+----------------------+---------+
|        snapshot results        |
+----------------------+---------+
| Device               | en-US   |
+----------------------+---------+
| iPhone 5             |  💚      |
| iPhone 6             |  💚      |
| iPhone 6 Plus        |  💚      |
| iPhone 7             |  💚      |
| iPhone 7 Plus        |  💚      |
| iPhone SE            |  💚      |
| iPad Air             |  💚      |
| iPad Pro (9.7-inch)  |  💚      |
| iPad Pro (12.9-inch) |  💚      |
+----------------------+---------+
```

Time with all simulators (all sims, atleast one time booted, on my machine):  *8m25.228s*

without this PR: 

related issues:
  * https://github.com/fastlane/fastlane/issues/6992

2016-11-22 14:22 UTC, greencoppercompany commented
That's a really good improvement for timing. Hope this PR will be merged soon :)

2016-11-22 16:16 UTC, samskiter commented
+1

2016-11-22 16:31 UTC, mfurtak commented
Hi @hjanuschka - thanks for looking into this promising opportunity! 🙌  While the approach here seems like it should be a big win, I'm not seeing the same improvement when I run your test.

Runs:

master | This PR
------- | -------
5m30.245s | 5m50.148s
5m36.411s | 5m49.829s
5m37.685s | 5m48.498s

Average time in seconds:

master | This PR
------- | -------
334.78s | 349.49s

I think before we could make a change like this become the new default, we'd want to allow people to opt-in to the changes. That way people can try them out and report back about speed improvements, or any problems, without immediately affecting all of our users. 👍 

Check out 
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/features.rb and https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L295 for an example of how to define and check a feature switch to allow people to opt-in to behavior changes.

2016-11-22 16:32 UTC, mfurtak requested changes
A change to the core of how building and testing works should be protected behind a feature switch, so that we can get community feedback before affecting all users.

2016-11-22 16:34 UTC, hjanuschka commented
ok i am trying to find out how to feature flag it.

how big was your test project, because i think if you have a lot of pods and so on, it should get a lot bigger from point of improvement.

2016-11-22 16:36 UTC, samskiter commented
Just my 2 cents - if this get's held up going into snapshot, I'd really love to have the feature available as a flag to `scan` 👍  🙏

2016-11-22 16:49 UTC, mfurtak commented
@hjanuschka I ran it against `snapshot/example` to try to replicate your results :+1:

2016-11-22 18:38 UTC, hjanuschka commented
@mfurtak  ok feature flagged it - sadly you first have to merge this one https://github.com/fastlane/fastlane/pull/7135 - or apply it locally before running snapshot, otherwise the env is ignored.

2016-11-22 18:48 UTC, mfurtak commented
@hjanuschka Ah, I should have been more specific, sorry! Each tool can and should have a `features.rb` that sets up the feature flags for itself.

Please add `lib/snapshot/features.rb` with that line that you'd added in _fastlane_core_. Then, require it after `require 'snapshot/version'` in `lib/snapshot.rb` 👍

2016-11-22 19:13 UTC, hjanuschka commented on snapshot/lib/snapshot/runner.rb
> +      test_command = TestCommandGenerator.generate(device_type: device_type, build_type: "test-without-building")
it is prepared to be not feature flagged, and ignored/forced-old-values in test_command_generator.rb

2016-11-22 19:20 UTC, mfurtak commented on snapshot/lib/snapshot/runner.rb
> +      test_command = TestCommandGenerator.generate(device_type: device_type, build_type: "test-without-building")
Oh, I see. 👍

2016-11-22 19:22 UTC, mfurtak commented
OK, looking pretty good! Are you interested in updating `test_command_generator_spec` to cover these new possibilities?

2016-11-22 19:24 UTC, hjanuschka commented
@mfurtak i am not sure how to feature flag inside a spec, you have a sample ?

2016-11-22 19:33 UTC, mfurtak commented
Great question. Here's what I would suggest:

This is from `fastlane_core/spec/spec_helper.rb`

```ruby
# Executes the provided block after adjusting the ENV to have the
# provided keys and values set as defined in hash. After the block
# completes, restores the ENV to its previous state.
def with_env_values(hash)
  old_vals = ENV.select { |k, v| hash.include?(k) }
  hash.each do |k, v|
    ENV[k] = hash[k]
  end
  yield
ensure
  hash.each do |k, v|
    ENV.delete(k) unless old_vals.include?(k)
    ENV[k] = old_vals[k]
  end
end
```

So far, I don't think we have a great solution for sharing helper code between tests in different projects... so I've been copying this over where I need it. 😅 

That helper will let you switch on the ENV variable that controls the feature switch for the duration of your test (and then turn it back off afterwards). See:

https://github.com/fastlane/fastlane/blob/master/fastlane_core/spec/itunes_transporter_spec.rb#L130

2016-11-22 22:09 UTC, hjanuschka commented
@mfurtak thx for the sample - doing test cases tomorrow, even if the build times are not really faster than with current `build test` approach, i would like to see this as a feature-flag option.

and hopefully apple improves the test-without-building

2016-11-25 11:51 UTC, samskiter commented
OOI does this look like it's going to go in?

2016-11-25 19:47 UTC, hjanuschka commented
@mfurtak  spec added  - thx for the env helper!

@samskiter we tested it on different apps (different size) multiple runs (different machines), and in fact it never was faster than with the traditional snapshot.

anyway i think we should get this into snapshot (behind feature flag, until we are sure it works)

2016-11-29 14:06 UTC, samskiter commented
@hjanuschka it will be faster for us - we aren't using this for snapshot - we need it for `scan` so we can build once and then run on multiple machines

2016-11-29 14:09 UTC, samskiter commented
ah, sorry i didn't realise this was different from https://github.com/fastlane/fastlane/pull/7130

my bad

2016-12-11 18:28 UTC, Jules2010 commented
Is the time on failed ci run, saying 41 mins ago correct @hjanuschka I'm sure nothing had changed on this thread for a couple of weeks.

It would be great to get this feature.

Cheers.

2016-12-11 18:33 UTC, hjanuschka commented
@Jules2010  i just rebased master, so that the PR's stays mergeable.

@mfurtak - any ideas on how the core team proceeds on the whole `build-for-testing` stuff?

2016-12-12 14:06 UTC, batesyuk commented
@hjanuschka love this idea but how do you get this to work now it is a 'feature' with fastlane? tried setting `--env FASTLANE_SNAPSHOT_BUILD_FOR_TESTING` but it still compiles for every iteration. What am I missing?

2016-12-12 14:15 UTC, hjanuschka commented
you need to set the env before you run it (and for sure, you need this PR checked out 👍 )

```
FASTLANE_SNAPSHOT_BUILD_FOR_TESTING=1 fastlane ...
```

or for snapshot

```
FASTLANE_SNAPSHOT_BUILD_FOR_TESTING=1 snapshot
```

2016-12-12 19:33 UTC, Jules2010 commented
@hjanuschka 

How do I go about getting this to run on my machine, presumably the code needs building?

I use git a work on windows, but I'm not sure about connecting to remote server from the command line.

I've found your branch, I think...
https://github.com/hjanuschka/fastlane/tree/snapshot_testing/snapshot

2016-12-14 14:15 UTC, batesyuk commented
I might be mis-understanding the concept of build-to-test but isn't it meant to compile once and then use that to run the tests? When I use this it still seems to compile the same amount of times as before?

2016-12-14 15:01 UTC, Jules2010 commented
That's what I asked in my original question which was said to be a duplicate

2016-12-18 10:53 UTC, Jules2010 commented
@batesyuk are you implying that, that isn't the functionality that @hjanuschka has provided ?

2016-12-18 10:55 UTC, Jules2010 commented
@batesyuk I think you mean this one, I got confused too https://github.com/fastlane/fastlane/pull/7130

2017-02-05 11:09 UTC, Jules2010 commented
@hjanuschka can the build once feature from fastlane be introduced into snapshot now?

2017-02-23 16:03 UTC, mfurtak commented
This has merge conflicts and seems to be stalled, so I'm going to close this for now.

2017-02-23 16:03 UTC, closed without merging

2017-05-19 09:40 UTC, ergunkocak commented
Hi,

So do we have this feature or not? I could not see in documentation (fastlane action snapshot)

In my opinion this is a very helpful feature to have. Also after first run if a test fails and we just want to rerun that would be great to have a switch for not to compile bu just use the one installed or compiled already.

Cheers

2017-05-19 09:50 UTC, samskiter commented
@ergunkocak Great point about retrying - we'll have to do the same. I believe we do have this feature now (see: https://github.com/fastlane/fastlane/issues/7130)

Another interesting thing worth considering is Bluepill: https://github.com/linkedin/bluepillI I wonder if we could add support for this into fastlane

2017-05-19 09:55 UTC, ergunkocak commented
So how can i test this feature? What shall i do in Snapfile?

PS: Tnx for fast response and bluepill link :)

2017-05-19 13:25 UTC, samskiter commented
@ergunkocak so it should be available on scan commands (you can see examples here https://github.com/fastlane/fastlane/pull/7130)

There is a great WWDC talk about this option here here http://devstreaming.apple.com/videos/wwdc/2016/409jh83sf1h8dqrt00q/409/409_advanced_testing_and_continuous_integration.pdf

2017-05-19 14:03 UTC, ergunkocak commented
@samskiter when i run scan (if i am not wrong) it does not save screenshots?

By the way i could not find a comparison chart for scan vs snapshot. What are most important differences between scan and snapshot?

Cheers

2017-05-19 14:17 UTC, samskiter commented
hey @ergunkocak you might be jumping in a bit at the deep end with this PR - have a read of these: https://github.com/fastlane/fastlane#fastlane-toolchain

`scan` is actually for running tests

2017-06-08 16:23 UTC, potmo commented
Is someone working on this PR? I'd really like to have this feature. I have a very slow build that I would like to run on multiple devices and multiple languages and it's super slow to recompile every for each entry in that matrix

2017-06-08 17:12 UTC, Jules2010 commented
+1