[fastlane_core] reset by os version 1/2
fastlane/fastlane pull request #7196
Opened 2016-11-28 07:12 UTC by hjanuschka

# PR 1/2
Split of: https://github.com/fastlane/fastlane/pull/7194

2016-11-29 23:05 UTC, milch requested changes

2016-11-30 06:58 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/device_manager.rb
> +        return false until os_version
@milch  holy crap! - thx for the catch! - changed it

2016-12-01 00:36 UTC, milch commented on fastlane_core/lib/fastlane_core/device_manager.rb
> +        version_sim.each(&:reset) if version_sim
I think the `if version_sim` is unnecessary here, as `select` should always at least return an empty array. If it is, Let's just do this on one line without creating a temporary var:

`all.select { |device| device.os_version == os_version }.each(&:reset)`

2016-12-01 07:56 UTC, hjanuschka commented
@milch  awesome! thx 
feedback addressed.

2016-12-01 22:13 UTC, milch approved these changes

2016-12-01 22:13 UTC, merged

2016-12-01 22:13 UTC, milch commented
Great, thanks! 🚀