[fastlane] reset by version 2/2
fastlane/fastlane pull request #7197
Opened 2016-11-28 07:13 UTC by hjanuschka

# PR 2/2
Split of: https://github.com/fastlane/fastlane/pull/7194

2016-11-30 00:36 UTC, mgrebenets commented
👍

2016-12-01 00:40 UTC, milch requested changes
Looks good, but let's merge the alias PR first and then rename this action + add the alias in one go. Just so that no one gets the wrong idea if they just have this change.

2016-12-01 00:40 UTC, milch commented on fastlane/lib/fastlane/actions/reset_simulators.rb
> +                                       description: "Which versions of Simulators you want to reset",
We should make it clear here that this corresponds to the `Reset content and settings...` option in the simulator menu bar, and is different from the `snapshot reset_simulators --ios ...` option.

2016-12-01 07:52 UTC, hjanuschka commented
@milch feedback adressed, action renamed and alias added  - do not merge before #7217  is merged.

2016-12-01 21:57 UTC, milch approved these changes

2016-12-01 21:58 UTC, milch commented
@hjanuschka Great, thanks! 🚀

2016-12-01 21:59 UTC, milch requested changes
Let's please the ruby style gods

2016-12-01 21:59 UTC, milch commented on fastlane/lib/fastlane/actions/reset_simulator_contents.rb
> +      def self.aliases
`rubocop` demands empty lines between method definitions here

2016-12-01 21:59 UTC, milch commented on fastlane/lib/fastlane/actions/reset_simulator_contents.rb
> +      def self.output
Same here

2016-12-02 07:05 UTC, hjanuschka commented
@milch updated, this was the first file for a long time i commited without rubocop'ing it first - and straight to a fail 😫

2016-12-02 20:56 UTC, milch commented
You can put the following file into your `.git/hooks` folder as `pre-commit` if you want:

```bash
#!/bin/bash

bundle exec rubocop
bundle exec rake test_all
```

2016-12-02 21:02 UTC, hjanuschka commented
@milch  thx, but i try to avoid git hooks - as they hardly sync across machines.

can you approve the changes the alias PR got merged 👍

2016-12-05 23:30 UTC, milch approved these changes

2016-12-05 23:30 UTC, merged