[fastlane] anon. the sensitive options
fastlane/fastlane pull request #7335
Opened 2016-12-06 10:09 UTC by hjanuschka

this one try's to replace sensitive option values from a `captured_output` run.

anyone has a idea how to find sensitive options in `fastlane env` - without capture output?

2016-12-06 19:53 UTC, KrauseFx submitted a review, later dismissed

2016-12-06 19:53 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/configuration/configuration.rb
> +      unless @sensitive_strings
Use
```ruby
def self.sensitive_strings
  @sensitive_strings ||= []
end
```

2016-12-06 19:53 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/configuration/configuration.rb
> +          if element.sensitive
use
```ruby
next unless element.sensitive
self.class.sen....
```

2016-12-06 19:54 UTC, KrauseFx commented
> anyone has a idea how to find sensitive options in fastlane env - without capture output?

what do you mean?

2016-12-06 19:58 UTC, hjanuschka commented
@KrauseFx  feedback addressed.
with this PR - we can filter out all sensitive options - when run with `--capture_output` - as it triggers the `Configuration.initialize`  - atleast on all actions that will be run (before an exception).


but it does not satisfy me 100% - as in the case of normal `fastlane env` - the `Fastfile` is loaded.
and i am looking for a "thing" to parse the Fastfile, get all actions, parse the options (matching to the action) - checking if it is sensitive and put it to the `sensitive_strings`.


hope you understand what i mean.

2016-12-06 19:58 UTC, KrauseFx commented
There is no good way to do that

2016-12-07 20:24 UTC, milch commented
@hjanuschka Yeah I don't think that'll be easy to do - one way would be to construct regexes like `/<action_name>\s*\([^\)]*<param_name>\s*(:|=>)\s*([^,\n]*),[^\)]*\)\s*\n/gm` (and a second one for the case where the param is the last parameter in the list) for each sensitive option and run them on the Fastfile contents. Depending on the length of the Fastfile and the amount of sensitive options, this might take a while though. 

Doing this might just be a bit too much magic though 🎩 ✨

2016-12-07 20:30 UTC, milch commented
Another thing that would be possible would be to create a simple Fastfile parser that'd just get the actions and all their parameters from the Fastfile. I've thought about this before so that we could make a kind of linter and/or dry-run option for fastlane `*`, but a parser like that could also be used for anonymizing the Fastfile. 

`*`: i.e. a thing that runs through the Fastfile and doesn't execute anything, but just tell you things like "this action doesn't have a parameter like that", "this parameter expects a bool but you passed a String", etc... I've ran fastlane too often and had it error out after building for 10 minutes only to tell me that I had misspelled a configuration parameter.

2016-12-07 20:54 UTC, hjanuschka commented
@milch https://gist.github.com/hjanuschka/fa7241a2462d36cb35ded66021188604 there you go, i talked about this to @KrauseFx  - in fact it seems to be to much effort.

the GIST is a working sample - which parses the fastfile - detects all actions, shims them through a `face_action` - which loads the available options from the original actions, looping `*args`  to see if this value has to be removed.


let me know what you think, i know it may be "propesed" to not use sensitive data inside fastfile (e.g: use ENV) - but in fact users are not used to this, i use api-keys myself on a few projects directly in the fastfile 👎

2016-12-07 21:14 UTC, milch commented
@hjanuschka Hmm, that looks pretty good! Can you open up an issue where we can discuss this instead of here? Then we can merge this and discuss that other code snippet in your issue 👍

2016-12-08 00:03 UTC, milch requested changes

2016-12-08 00:03 UTC, milch commented on fastlane_core/lib/fastlane_core/configuration/configuration.rb
> +      unless @sensitive_strings
+1

2016-12-08 18:13 UTC, hjanuschka reviewed
@milch, @KrauseFx  feedback addressed

2016-12-08 18:13 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/configuration/configuration.rb
> +      unless @sensitive_strings
awesome - thx!

2016-12-09 18:37 UTC, milch commented on fastlane/lib/fastlane/environment_printer.rb
> +        env_info.gsub!(sensitive_element, "#########")
I don't think it matters to be honest, we could also put `"<REDACTED>"` in there to make it more clear that the value was automatically replaced.

2016-12-09 18:40 UTC, milch approved these changes

2016-12-09 18:46 UTC, hjanuschka commented on fastlane/lib/fastlane/environment_printer.rb
> +        env_info.gsub!(sensitive_element, "#########")
i also think it does not matter if # or * - can we keep the #?

2016-12-12 17:31 UTC, milch commented on fastlane/lib/fastlane/environment_printer.rb
> +        env_info.gsub!(sensitive_element, "#########")
cc @KrauseFx

2016-12-20 20:32 UTC, merged