support mailgun reply_to
fastlane/fastlane pull request #7374
Opened 2016-12-08 11:41 UTC by iCell

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [ ] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [ ] Run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2016-12-08 19:17 UTC, ohayon requested changes
Hey @iCell, thanks for the PR! 

I just left one note about a typo in the `env_name` key of the `ConfigItem`.

Just to be safe, would you mind adding a test to `maligun_spec.rb` as well?

2016-12-08 19:17 UTC, ohwutup commented on fastlane/lib/fastlane/actions/mailgun.rb
> +                                      env_name: "MAILGUN_REPLAY_TO",
I think this should be `MAILGUN_REPLY_TO`.

2016-12-08 19:44 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/mailgun.rb
> +                        "h:Reply-To": options[:reply_to],
What happens when the value is nil? does the API handle this properly? Maybe this value shouldn't be passed when it's not set by the user.

2016-12-12 22:24 UTC, KrauseFx commented
Hey @iCell, have you had the time to look into the proposed changes and update the PR? 👍

2016-12-13 09:29 UTC, iCell commented
@KrauseFx Sorry for not responding, I'm really busy with my recent work, I'll update the PR in a few days.

2016-12-13 09:42 UTC, iCell commented on fastlane/lib/fastlane/actions/mailgun.rb
> +                                      env_name: "MAILGUN_REPLAY_TO",
@ohwutup  Sorry for the misspell

2016-12-13 15:02 UTC, iCell commented
I have run the command `bundle exec rspec`, but it raised an exception `Fastlane Fastlane::FastFile Mailgun Action raises an error if no mailgun apikey is given`, is this exception normal？

2016-12-13 16:37 UTC, iCell commented
I have run `bundle exec rspec` from the subdirectory of each tool I've modified, and the result is 0 failure. But through the results of Github CI, these errors are not caused by my code in the PR.

2016-12-20 21:02 UTC, closed without merging