[gym] Remove promotion for use_legacy_build_api
fastlane/fastlane pull request #7379
Opened 2016-12-08 18:33 UTC by hjanuschka

lets get rid of the legacy_build_api

2016-12-08 19:22 UTC, ohwutup commented
Hey @hjanuschka, was there some discussion around this that you could reference?

2016-12-08 19:23 UTC, KrauseFx commented
I talked in the fastlane slack about this with Helmut, since there are so many people still asking about using the legacy build API, and it's not something we should recommend, since it's deprecated for over 2 years now. It's causing issues with Swift, WatchKit and apps with extensions.

2016-12-08 19:23 UTC, KrauseFx commented
We should try to get as little number of legacy build API users as possible and solve the underlying issue instead.

2016-12-08 19:25 UTC, KrauseFx requested changes

2016-12-08 19:25 UTC, KrauseFx commented on gym/lib/gym/detect_values.rb
> +        UI.deprecated("it should not be used anymore - e.g.: if you use app-extensions")
Don't we have this message somewhere else already?

2016-12-08 19:25 UTC, KrauseFx commented on gym/lib/gym/options.rb
> +                                     deprecated: 'Do not use this option anymore.',
Let's replace this with 
```
Don't use this option any more, as it's deprecated by Apple
```

2016-12-08 19:25 UTC, KrauseFx commented
Maybe we should also make the warnings bigger and more prominent? I think we already show the message somewhere.

2016-12-09 06:43 UTC, hjanuschka reviewed
@KrauseFx feedback addressed
do you have any idea where we can put to this to address the "more prominent" thing?

2016-12-09 06:43 UTC, hjanuschka commented on gym/lib/gym/options.rb
> +                                     deprecated: 'Do not use this option anymore.',
done

2016-12-09 06:43 UTC, hjanuschka commented on gym/lib/gym/detect_values.rb
> +        UI.deprecated("it should not be used anymore - e.g.: if you use app-extensions")
i don't find it anywhere - do you have a hint?

2016-12-16 02:36 UTC, KrauseFx approved these changes
Let's ship this 🎷

2016-12-16 02:36 UTC, KrauseFx commented on gym/lib/gym/detect_values.rb
> +        UI.deprecated("it should not be used anymore - e.g.: if you use app-extensions")
Never mind

2016-12-16 02:37 UTC, KrauseFx commented
Could you resolve the 2 merge conflicts, and I can merge 👍

2016-12-16 07:00 UTC, hjanuschka commented
@KrauseFx should be mergable 🐙

2016-12-16 21:12 UTC, merged

2016-12-16 21:12 UTC, KrauseFx commented
This is a great change, thanks for preparing this  🚀