[fastlane_core] add buildwatcher class
fastlane/fastlane pull request #7386
Opened 2016-12-08 21:06 UTC by hjanuschka

# PR 1/4

This series of PR's try's to de-duplicate the various blocks that check if a build is finished processing.
by moving the logic to fastlanecore.

 * 1/4 ->  (fastlane_core)
 * 2/4 ->  (pilot)
 * 3/4 ->  (deliver)
 * 4/4 ->  (watchbuild)

a full branch is at this PR: https://github.com/fastlane/fastlane/pull/7381
(i am going to keen the full branch updated, if during review the singel PR's change)

the fastlane_core PR is mandatory for the other ones, but the tools could be merged one by one.
let me know what you guys think.

2016-12-09 00:48 UTC, KrauseFx commented
This is great, how about we merge this and roll out a new _pilot_ release to see how it works before rolling out the change for _deliver_ and _watchbuild_? 

I didn't go through the source code yet

2016-12-09 06:06 UTC, hjanuschka commented
@krausefx seems to be a good plan
can we have some more eyes first on the actual change in pilot+core 🤓

2017-02-08 07:17 UTC, hjanuschka commented
updated to a single PR - should be ready for review

2017-02-08 12:13 UTC, lacostej requested changes

2017-02-08 12:13 UTC, lacostej commented on deliver/lib/deliver/submit_for_review.rb.orig
> +<<<<<<< HEAD
merge issue?

2017-02-08 12:13 UTC, lacostej commented on deliver/lib/deliver/submit_for_review.rb.orig
> +<<<<<<< HEAD
and probably lack some tests if this wasn't detected!

2017-02-08 12:14 UTC, lacostej commented on deliver/lib/deliver/submit_for_review.rb.orig
> +<<<<<<< HEAD
I can see it, it's just a `.orig` file that shouldn't have been commited.

2017-02-08 12:19 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +      while full_build.nil? || full_build.processing
could we get stuck here?

2017-02-08 12:19 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +    def self.wait_for_train(app = nil, platform = "ios", sleep_time = 30)
should that method be `private`?

2017-02-08 12:38 UTC, hjanuschka commented on deliver/lib/deliver/submit_for_review.rb.orig
> +<<<<<<< HEAD
ooops - thx!

2017-02-08 12:38 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +    def self.wait_for_train(app = nil, platform = "ios", sleep_time = 30)
not sure if its required. - maybe there is a use case for using it public?

2017-02-08 12:39 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +      while full_build.nil? || full_build.processing
seems to be, actually i moddeled it after the existing code. what is a good abort condition?
running longer than 60 minutes?

2017-02-08 14:07 UTC, negebauer commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +        break if builds.count == 0
Here we should put #8152

2017-02-09 07:57 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +        break if builds.count == 0
hey @negebauer - i am unsure how to apply your pr, could you help me with this?

best would be if you checkout this branch, and modify it push it to your fork, so i can have a look.


to test run a PR/branch from a user see this here: https://gist.github.com/hjanuschka/3040fc6f371f46acff72a5e67f649b27

2017-02-09 09:08 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +        break if builds.count == 0
I suggest we revisit #8152 after this one is merged, and not mix the refactoring with the bug fix.

2017-02-09 09:08 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +      while full_build.nil? || full_build.processing
We can revisit that after this is merged.

2017-02-09 09:09 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +    def self.wait_for_train(app = nil, platform = "ios", sleep_time = 30)
I am usually defensive when it comes to exposing code public unless needed, so I would prefer it to be private unless there's a strong argument / existing use case.

2017-02-09 10:12 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +        break if builds.count == 0
@lacostej sounds like a solid plan ;)

2017-02-09 10:44 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +    def self.wait_for_train(app = nil, platform = "ios", sleep_time = 30)
i am unsure about that.
how'd i make a instance method private?

`private_class_method :wait_for_train` - will that work on older ruby's ?

2017-02-09 10:44 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +      while full_build.nil? || full_build.processing
k

2017-02-09 16:44 UTC, negebauer commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +        break if builds.count == 0
@lacostej Good plan

2017-02-13 18:42 UTC, lacostej commented on fastlane_core/lib/fastlane_core/build_watcher.rb
> +    def self.wait_for_train(app = nil, platform = "ios", sleep_time = 30)
👍 

we have used `private_class_method` several times already :)

2017-02-13 18:55 UTC, lacostej approved these changes

2017-02-21 07:35 UTC, merged

2017-02-21 08:52 UTC, KrauseFx commented
Oh yeah, this got merged, let's make sure to monitor for new issues as we roll out a new release  🚀

2017-02-21 10:18 UTC, hjanuschka commented
@KrauseFx, @lacostej  yeah - i am bit blocked by corporate work, if you need any assitance, please direct ping me in slack, as my github notifications are a bit out of control, i think at the end of the week i am back to normal and can work a bit more on oss stuff 👍