[WIP] Fastfile parser/linter best-practice-analyzer
fastlane/fastlane pull request #7448
Opened 2016-12-12 23:05 UTC by hjanuschka

as discussed in: https://github.com/fastlane/fastlane/issues/7368

![bildschirmfoto 2016-12-12 um 23 24 13](https://cloud.githubusercontent.com/assets/2891702/21120458/c92edaa8-c0c7-11e6-9ff5-298d791b9e63.png)

2016-12-29 20:03 UTC, KrauseFx commented
❤

2017-01-08 14:41 UTC, KrauseFx submitted a review, later dismissed

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/README.md
> +:ghost: | [Jenkins Integration](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Jenkins.md): Show the output directly in the Jenkins test results
Should this change be part of the PR?

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/README.md
> +:ghost: | [Jenkins Integration](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Jenkins.md): Show the output directly in the Jenkins test results
The link to docs.fastlane.tools seems correct to me 👍

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +      command "validate-fastfile" do |c|
Should we call this `fastlane lint` instead?

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +            fl_parser = FastfileParser.new(content: File.read(args.first), filepath: args.first, name: "Fastfile", platforms: plat)
This should look for the default Fastfile by default. Use `FastlaneFolder.fastfile_path` and make sure to test it with and without a Fastfile

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +            raise "File not found"
This should be `Fastfile at path not found: #{File.expand_path(path_here)}`

This it's very clear on where _fastlane_ looked

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +            plat = []
Let's write this out to be `platforms`

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +            fl_parser = FastfileParser.new(content: File.read(args.first), filepath: args.first, name: "Fastfile", platforms: plat)
Move detecting of the path out

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/commands_generator.rb
> +            puts "Found: Errors/Deprecations/Info: #{counters[:errors].to_s.red}/#{counters[:deprecations].to_s.yellow}/#{counters[:infos].to_s.blue}"
`Fastfile has some issues: ...`

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fast_file.rb
> +    def import_from_git(url: nil, branch: 'HEAD', path: 'fastlane/Fastfile', return_file: false)
1 line above, make sure to add a comment

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fast_file.rb
> +        return clone_folder if return_file
Wrong spacing here, make sure it's aligned with `import`

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      "REMOVE_IT"
Hehe :)

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fastfile_parser.rb
> +        fl = Fastlane::FastFile.new
Wrong spacing

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fastfile_parser.rb
> +        @content << "#########################################\n"
That's a lot of code just to import from Git. How about we don't support this here, but just show a message that only the local Fastfile will be linted, with instructions on how to also lint/test the Fastfile that should be imported?

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      if options_avail.length > 0 && options_avail.first.kind_of?(FastlaneCore::ConfigItem)
Please don't use short forms of words, use `options_available`

2017-01-08 14:41 UTC, KrauseFx commented on fastlane/lib/fastlane/fastfile_parser.rb
> +              result = eval(dropper + src_code) # rubocop:disable Lint/Eval
Why do we have to `eval` code here?

2017-01-08 14:42 UTC, KrauseFx commented
Hey @hjanuschka, I love the outcome, this is some really cool things. Did I understand correctly that this doesn't eval the Fastfile, but uses a Ruby code parser instead to iterate over the different checks? I also noticed that one eval code is inside. Also some more notes.

I'd love to have this feature, however I'm also a little worried about maintainability.

2017-01-08 17:16 UTC, hjanuschka commented
@KrauseFx  thx for the review, i ll address the issues later (still a bit lazzy out of vacation ) 
but basically - yes it uses ruby parser to parse Fastfile - extracting lanenames actionnames and so on.

but to further validate options from various actions, it extracts the action names - replaces it with a `dummy` method name and evals it.

i am not really worried about this eval, in that special case.
about the maintainability you are right, we would atleast need a few more eyes on it.

2017-01-08 19:32 UTC, hjanuschka reviewed
feedback addressed, and `sh` should validate now again.

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/README.md
> +:ghost: | [Jenkins Integration](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Jenkins.md): Show the output directly in the Jenkins test results
done - not sure why this happened :(

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +      command "validate-fastfile" do |c|
done

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +            plat = []
done

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +            fl_parser = FastfileParser.new(content: File.read(args.first), filepath: args.first, name: "Fastfile", platforms: plat)
done - awesome, did'nt know about the FastlaneFolder

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +            raise "File not found"
done

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +            puts "Found: Errors/Deprecations/Info: #{counters[:errors].to_s.red}/#{counters[:deprecations].to_s.yellow}/#{counters[:infos].to_s.blue}"
done.

![bildschirmfoto 2017-01-08 um 20 12 49](https://cloud.githubusercontent.com/assets/2891702/21752785/e12363a0-d5de-11e6-9a06-b6bfecf76b97.png)

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fast_file.rb
> +    def import_from_git(url: nil, branch: 'HEAD', path: 'fastlane/Fastfile', return_file: false)
done

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fast_file.rb
> +        return clone_folder if return_file
done

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      "REMOVE_IT"
thats a placeholder for variables 👍  like if user has something like this:


```
action(param: "#{some_ruby_thing} asdfg")
```

those will be replaced by a FastfileParser class - and via `to_s`  replaced with "REMOVE_IT".

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +        fl = Fastlane::FastFile.new
done.

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +        @content << "#########################################\n"
well - atleast for me with my setup the linting without support for `import_from_git` is useless - as we only have a 4 line Fastfile per project (3 variables  - and the call to `import_from_git`)

i know that it feels a bit clunky but i think its worth the benefit from supporting `import_from_git`


also i think describing/finding a way to `lint`  git fastfiles is hard. (involves, clone, chdir, ensure appfile and stuff exists, lint)

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      if options_avail.length > 0 && options_avail.first.kind_of?(FastlaneCore::ConfigItem)
thx

2017-01-08 19:32 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +              result = eval(dropper + src_code) # rubocop:disable Lint/Eval
see last comment, mostly because of the need to eval the source code returned by the parser.

2017-01-08 19:39 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +    # rubocop:disable PerceivedComplexity
@KrauseFx  any idea on how to fix it? - i am not sure on how to split the whole thing up without reaching the `PerceivedComplexity`

2017-01-08 19:39 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +require 'parser'
@KrauseFx what is this?

2017-01-17 18:54 UTC, hjanuschka commented
added support for the newly merged #7609 

![bildschirmfoto 2017-01-17 um 19 50 36](https://cloud.githubusercontent.com/assets/2891702/22034940/54b8d712-dcee-11e6-8dc2-cbe6474a0086.png)


i needed to force push, to get the current master into this PR.

this is ready for another review!

2017-01-17 21:23 UTC, mfurtak requested changes
Hey @hjanuschka - I've left a number of small comments about specific things. However, on the larger scale, I wouldn't be in favor of merging this as it currently stands.

Rubocop is not always right, but in this case I agree with the `PerceivedComplexity` warning about `fake_action`. That method is quite large, and does a lot of different things. The `FastfileParser` class as a whole has many responsibilities, and I think it would benefit from being broken up into smaller classes.

So, without trying to prescribe a particular solution, I might suggest having a look through [rubocop](https://github.com/bbatsov/rubocop)'s code, and see how it is organized. One of the things that "feels good" about the Rubocop code is having each check defined by its own class/file. But again, that's just an example, not a requirement :smile:

2017-01-17 21:35 UTC, hjanuschka commented
@mfurtak thx for the feedback, i am going to adress the inline comments, and try to split it up so rubocop does not require exceptions (except the eval).

2017-01-17 22:31 UTC, hjanuschka reviewed
@mfurtak  thx i pushed a new commit with feedback addressed and rubocop in a good mood without `disable`  rule.

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +      command "lint" do |c|
it initially was 'validate-fastlane' - which i didnt get to work with symbol. -> fixed

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +        c.syntax = 'fastlane validate-fastfile /path/to/Fastfile'
thx

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +        c.option '--platforms STRING', String, 'Comma seperated list of platforms (ios, mac, android) of actions to validate (others will be skipped)'
awesome thats nice, didn't know! 🚀

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
> +          if File.exist?(file_path)
thx

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/commands_generator.rb
>        command :trigger do |c|
thx

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      # Suppress UI output
removed it

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      UI.important("ACTION: #{@original_action.inspect} 1") if $verbose
removed all the unnecessary debug outputs

2017-01-17 22:31 UTC, hjanuschka commented on fastlane/lib/fastlane/fastfile_parser.rb
> +      # Get the importet file
thx

2017-02-23 16:05 UTC, mfurtak commented
I think this is an interesting idea, but probably one that should be explored outside of _fastlane_ itself. 👍

2017-02-23 16:05 UTC, closed without merging