[spaceship] adopt to new API protocol for 2FA
fastlane/fastlane pull request #7575
Opened 2016-12-19 08:25 UTC by hjanuschka

API seems to have changed.

should fix: https://github.com/fastlane/fastlane/issues/7556

2016-12-19 10:09 UTC, meyskens requested changes

2016-12-19 10:09 UTC, meyskens commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Hash)
`trustedPhoneNumbers` is an array, so this check will fail. In my test code `r.body["trustedPhoneNumbers"][0].kind_of?(Hash)` worked so an extra check on the array and the first element may be nice (soon all elements? not sure how Apple will change this)

2016-12-19 10:16 UTC, hjanuschka commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Hash)
@meyskens thx for the feedback, i did a commit to handle the array, can you re-test it?

2016-12-19 10:17 UTC, meyskens approved these changes
That should work

2016-12-19 10:20 UTC, hjanuschka commented
@meyskens can you run it and verify it?

2016-12-19 10:25 UTC, meyskens commented
Works fine now 😄

2016-12-19 10:29 UTC, hjanuschka commented
@meyskens awesome, thx for your help!

2016-12-19 19:50 UTC, mpirri commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
What is the importance of checking `"trustedPhoneNumbers"` here? It doesn't appear that we ever use the value, or the hash it contains.

Also, should we be checking the existence/type of `response.body["securityCode"]`, which is now used on line 51 below?

2016-12-19 20:57 UTC, meyskens commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
Apple has changed the response to have multiple phone numbers listed for 2FA. See #7562

2016-12-19 21:16 UTC, mpirri commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
But these values in the body are never actually used, right?  So couldn't we just delete these tests here, or else update the test to check `r.body["securityCode"]` in order to support line 51 below?  (previously this line was testing the response to see if line 51 could execute properly)

2016-12-19 21:18 UTC, meyskens commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
To answer that I don't know enough about the internals of Fastlane.

2016-12-20 00:09 UTC, akaralar commented
I want to test this, how do I do that? I followed the steps in toolsanddebugging.md but somehow I get errors when I try `bundle update` in my project root folder

2016-12-20 06:33 UTC, hjanuschka commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
@mpirri true point - i just tried to fix it, so should we just check on  `securityCode` 
i am just not sure if this is enough - can we have some more 👀  on this one?

2016-12-20 10:07 UTC, KrauseFx commented
@akaral You didn't tell us what kind of errors

2016-12-20 10:18 UTC, KrauseFx commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
We still use `phoneNumberVerification` in the `handle_two_factor` method, shouldn't we check for this?

2016-12-20 10:38 UTC, hjanuschka reviewed
.

2016-12-20 10:38 UTC, hjanuschka commented on spaceship/lib/spaceship/two_step_client.rb
> +      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array) && r.body["trustedPhoneNumbers"].first.kind_of?(Hash)
@KrauseFx `phoneNumberVerification` is not used anymore, its changed in favor of: `trustedPhoneNumbers`

2016-12-20 16:55 UTC, akaralar commented
@KrauseFx sorry I was in a hurry to upload a build, cheated fastlane and uploaded with Xcode in the end :D To summarize my problem:

- I clone the fastlane library with `git clone`
- I cd into the cloned folder, run `bundle install`, finishes successfully
- I run `bundle exec rspec` to make sure everything is working correctly, no erros no issues.
- I copy the `Gemfile` from `.assets` folder in the cloned repo, and paste it to my Xcode project root folder.
- I change the `local_fastlane_path` to be `local_fastlane_path = "~/Development/github/fastlane"`, which points to the cloned directory.
- I run `bundle update` and get the error: `The path `/Users/akaralar/Development/github/fastlane_core` does not exist.`
It shouldn't exists at this location since it is looking for `fastlane_core` 1 level above the repo's root directory.

- If I change the `local_fastlane_path` to point to the `fastlane` directory inside the cloned directory, (ie `local_fastlane_path = "~/Development/github/fastlane/fastlane"`), then I get the error: `The path `/Users/akaralar/Development/github/fastlane/fastlane/fastlane_core` does not exist.`

I hope that clears up things a bit, sorry for not elaborating on this earlier.

2016-12-20 19:07 UTC, mpirri approved these changes

2016-12-20 19:07 UTC, merged