Add new xcodebuild options for skip-testing and only-testing to scan
fastlane/fastlane pull request #7601
Opened 2016-12-20 19:22 UTC by arifken

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [X] Run `bundle exec rspec` from the root directory.
- [X] Run `bundle exec rubocop -a` to ensure the code style is valid
- [X] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

This PR adds options to Scan to specify specific test bundles/test suites/test cases to be run using the new -only-testing and -skip-testing options in Xcode 8's version of xcodebuild. More info on the actions can be found in the wwdc talk on [Advanced Testing and Continuous Integration](https://developer.apple.com/videos/play/wwdc2016/409/)

2016-12-20 19:42 UTC, ohwutup commented
Hey @arifken! Thanks for submitting the PR, as a matter of fact, we had a bunch of discussion about this a little while back on another issue https://github.com/fastlane/fastlane/pull/7131 and we did not notice any speed increases or efficiency using the new options.

2016-12-21 00:17 UTC, arifken commented
@ohwutup no worries! This is actually for different new options (I did see the issue #7131 ). That issue discusses the build-for-testing or test-without-building options. this is only-testing and skip-testing which are for when you want to run scan, but exclude some tests that you don't want to run/report on. I find this useful if we have a job that just runs one particular suite of tests to generate a slather report just for a single component. But if you don't see value in adding this now, that's totally fine too

2016-12-21 16:57 UTC, ohayon requested changes
Hey @arifken! Apologies for mixing up the purpose of the two PRs! xcodebuild has so many options!

There is definitely value in getting this merged in. Currently rubocop is failing because the available options array is too complex, I believe that is because of the verify blocks.

Would you mind trying to clean that up a bit and we can get this merged in! 🚀

2016-12-21 16:57 UTC, ohwutup commented on scan/lib/scan/options.rb
> +                                       end
Could you pull all of this logic into a method to call in both verify_blocks? It looks to be the same right?

2017-01-25 20:26 UTC, mfurtak commented
We carried this forward in #8002 👍

2017-01-25 20:26 UTC, closed without merging