credentials-manager: Fetch port, path, protocol for new internet passwords
fastlane/fastlane pull request #7628
Opened 2016-12-21 18:45 UTC by olegoid

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

DESCRIPTION:

In case if user want to supply internet passwords added by
credentials-manager with additional metadata(port, path, protocol)
he/she can set environment variables which then will be fetched
in 'add_to_keychain' method passed to security tool.

List of env variables used:
* FASTLANE_PATH - path
* FASTLANE_PORT - port
* FASTLANE_PROTOCOL - protocol

2016-12-22 08:13 UTC, KrauseFx commented
Hey @olegoid, thanks for that pull request. I'm not sure I'm 100% following, what's the exact use-case for that? Or is it something you want to use internally for Xamarin?

2016-12-22 16:41 UTC, olegoid commented
Hello @KrauseFx, thanks for your response. I was going to use this change internally for Xamarin integration.

Please take a look at [this document] for more details about how this change will be used by Xamarin. Unfortunately, I can't share this info in Github comments.

2016-12-29 20:02 UTC, KrauseFx requested changes

2016-12-29 20:02 UTC, KrauseFx commented on credentials_manager/lib/credentials_manager/account_manager.rb
> +      Security::InternetPassword.add(server_name, user, password, options)
I'd love to not pass any options if none of the environment variables are set

2016-12-29 20:02 UTC, KrauseFx commented on credentials_manager/lib/credentials_manager/account_manager.rb
> +      Security::InternetPassword.add(server_name, user, password, options)
I'd love to not pass any options if none of the environment variables are set

2016-12-29 20:02 UTC, KrauseFx commented on credentials_manager/lib/credentials_manager/account_manager.rb
> +    def options
Please add some documentation on what this is used for 👍

2016-12-29 23:46 UTC, KrauseFx approved these changes

2016-12-29 23:46 UTC, merged

2016-12-29 23:46 UTC, KrauseFx commented
Cool, thanks for updating the PR, looks good now 👍