Finish platform support for cert & sigh
fastlane/fastlane pull request #7730
Opened 2017-01-04 06:30 UTC by kdubb

## PR  not complete ##
This PR is not yet complete.  I created it since I saw other changes in the area and wanted to coordinate if somebody else was already going down this road.

Currently this correctly generates, or downloads existing, development & production certificates for an iOS & macOS application set, including both signing and provisioning profiles.

## Sigh
Fixes search for certificates by types using the `platform` option. Also, fixes the lookup of application ids by passing the `mac` flag; again using the `platform` option.

## Cert
Adds a `platform` option (allows only `macos` or `ios`). Using the `platform` option it can now determine the correct certificate type.

## Spaceship
Certificate creation uses `mac` flag (identical to most other methods) to target the correct certificate portal section and create certificates for the correct platform.

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [ ] Run `bundle exec rspec` from the root directory.
- [ ] Run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2017-01-05 05:39 UTC, kdubb commented
@KrauseFx After fixing all issues I read the guidelines which _suggest_ a PR for each tool changed.  As I didn't know this prior to the PR and that these are interdependent changes, I'm hoping this PR is acceptable as is.

2017-01-05 09:53 UTC, KrauseFx commented
@kdubb having this as one PR sounds ok to me 👍

2017-01-09 18:47 UTC, asfalcone commented on cert/lib/cert/runner.rb
> +      when 'ios', 'tvos'
Is it possible for this value to be 'tvos'? It looks like it is restricted to macos or ios [by this code](https://github.com/fastlane/fastlane/pull/7730/files#diff-7c141e2c870b0117f0dba21896620e39R71).

2017-01-09 22:05 UTC, kdubb commented on cert/lib/cert/runner.rb
> +      when 'ios', 'tvos'
This is for developer signing certificates only.  As far I know `tvos` isn't a valid type for developer signing.

FYI, for `sigh` (aka provisioning profiles) both `ios` and `tvos` are supported; as well as `macos`.

2017-01-10 18:14 UTC, kdubb commented
@KrauseFx @asfalcone Is there anything else I need to do get this PR promoted?

2017-01-17 23:37 UTC, kdubb commented
@KrauseFx @asfalcone Any plans for merging this? I'd love to stop maintaining our own fork 😬

2017-01-19 09:07 UTC, lacostej requested changes

2017-01-19 09:07 UTC, lacostej commented on cert/lib/cert/options.rb
> +                                     is_string: false,
any reason why this isn't a string? I see we have to `to_s` this config value everywhere.

2017-01-19 17:07 UTC, kdubb commented on cert/lib/cert/options.rb
> +                                     is_string: false,
In PR #6169 @KrauseFx requested the platform be made a symbol instead of a string.  I followed suite. Should these be strings?

2017-01-19 17:11 UTC, kdubb commented on cert/lib/cert/options.rb
> +                                     is_string: false,
FYI the suggestion from @KrauseFx  was followed in commit 6df6ff1d4b29b88382e0d0be1ad5c56a133afb58 and it is currently a symbol for `sigh`.

2017-01-19 23:08 UTC, lacostej approved these changes

2017-01-19 23:09 UTC, lacostej commented on cert/lib/cert/options.rb
> +                                     is_string: false,
Fine with symbol then!

2017-01-20 07:49 UTC, merged

2017-01-20 07:50 UTC, lacostej commented
@kdubb merged! Thank you a lot for your contribution! 👍