[supply] Added support for google service account credentials via environment variable
fastlane/fastlane pull request #7748
Opened 2017-01-05 01:59 UTC by VenkataMutyala

[supply] Added support for google service account credentials via environment variable

Existing github issue: https://github.com/fastlane/fastlane/issues/7715

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

2017-01-05 19:38 UTC, asfalcone commented
@VenkataMutyala Thanks for the PR! I am hesitant to add an undocumented environment variable for this. I'd like to see another [option](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb) added to _supply_ that would automatically support an environment variable and conflicting option detection. You could name it something like `:json_key_data` to distinguish that this param contains the key data not the file path. What do you think?

2017-01-06 08:19 UTC, VenkataMutyala commented
@asfalcone I agree that is a good idea! I just updated this PR so its now an option. Please let me know what you think.

2017-01-06 11:21 UTC, lacostej commented
An argument isn't in my mind much safer than a file on disk. It will be visible a on `ps` output.

The whole concept of protecting secrets is complicated to do right. It depends a lot on your concerns. There are many areas to look at and it is something that in my mind should be carefully looked into. For example, fastlane doesn't sanitize environment variables in sub processes.

I am not aware of a simple solution to this to implement a safe secret manager accros all fastlane tools. The CredentialsManager is a good step but is Mac only right now. As for CI integration, I think every system has (or should have) some kind of mechanism to pass the secrets safely to the build machine. A third party solution, there are interesting projects like https://www.vaultproject.io/ but I didn't delve into any of them.

2017-01-06 16:11 UTC, VenkataMutyala commented
@lacostej I agree protecting secrets is really complicated and its unlikely there is a simple solution. As you mentioned it does depend on the security concerns and in the case of this PR supply no longer requires the service account json to be stored at rest.

FWIW, I have seen a demo on VaultProject and its **really cool** and it probably has the most comprehensive feature. A member of the Hashicorp team told me their biggest internal use case is using it as a transient backend where they just encrypt/decrypt data on the fly for their web apps. A few other interesting solutions I have come across for secret management are:
https://square.github.io/keywhiz/
https://lyft.github.io/confidant/

2017-01-06 16:22 UTC, asfalcone requested changes

2017-01-06 16:22 UTC, asfalcone commented on supply/lib/supply/client.rb
> +    def initialize(path_to_key: nil, issuer: nil, path_to_service_account_json: nil, service_account_json: nil)
Could this be simplified to only accept the `service_account_json` and do the `File.open` in `make_from_config`?

2017-01-06 16:22 UTC, asfalcone commented
This is looking great. I left 1 more comment about simplifying the code!

2017-01-06 21:49 UTC, VenkataMutyala commented on supply/lib/supply/client.rb
> +    def initialize(path_to_key: nil, issuer: nil, path_to_service_account_json: nil, service_account_json: nil)
sounds good

2017-01-06 21:56 UTC, VenkataMutyala commented
@asfalcone please let me know what you think.

2017-01-07 01:55 UTC, asfalcone commented
@VenkataMutyala 💯 This is great! Thank you for the contribution!

2017-01-07 01:55 UTC, asfalcone approved these changes

2017-01-07 01:56 UTC, merged