[WIP] dotenv: load from either fastlane folder or parent, instead of fastlane folder or current. In practice, almost the same, but more explicit and repeatable for those running from random directories
fastlane/fastlane pull request #7897
Opened 2017-01-17 22:10 UTC by lacostej

2017-01-17 22:22 UTC, mfurtak commented on fastlane/spec/lane_manager_spec.rb
> +        def ensure_dot_env_value2(parent_dir, expected_value)
suggested name with more meaning: `ensure_dot_env_value_from_parent_only`

2017-01-17 22:23 UTC, mfurtak commented on fastlane/spec/lane_manager_spec.rb
> +        def ensure_dot_env_value1(parent_dir, expected_value)
suggested name with more meaning: `ensure_dot_env_value_from_fastlane_or_parent`

2017-01-17 22:24 UTC, mfurtak commented
Got ahead of myself before noticing it was WIP :smile: I'll hold off for now

2017-01-18 07:28 UTC, lacostej commented
@mfurtak please review.

I marked it as WIP because I didn't want it to be merged as is but reviewed more.

There are some areas that I think deserve more review (e.g. this one which touches areas I might not be aware of) and I don't know how to stress that as part of the process. So I used WIP

2017-01-18 15:54 UTC, mfurtak reviewed
This looks good to me. I think @joshdholtz had a hand in this stuff originally. Maybe he can give a final +1?

2017-01-18 16:05 UTC, joshdholtz requested changes

2017-01-18 16:05 UTC, joshdholtz commented on fastlane/lib/fastlane/lane_manager.rb
>        # search for dotenvs in either fastlane or the current dir
I think this comment should change to `# search for dotenvs in either fastlane folder or parent`

2017-01-18 18:28 UTC, lacostej commented on fastlane/lib/fastlane/lane_manager.rb
>        # search for dotenvs in either fastlane or the current dir
changed the comment, hopefully more informative now

2017-01-18 22:09 UTC, lacostej commented
Meh, I am having a test failure on circleci while everything is green locally. I even upgraded to ruby 2.3.1. Weird.

2017-01-18 23:19 UTC, joshdholtz commented
@lacostej I pulled down your branch and it fails locally for me (same error as CircleCI)

2017-01-18 23:27 UTC, joshdholtz commented
@lacostej It is failing because you didn't commit the "fastlane" directory in `./fastlane/spec/fixtures/dotenvs/withoutFastfiles/parentonly`. You didn't put a file in there so git won't put that directory in version control 😇  So either manually add that directory to git or put an empty text file in that directory saying why its empty

2017-01-19 00:05 UTC, joshdholtz commented
lol at `.keepme`

2017-01-19 00:05 UTC, joshdholtz approved these changes

2017-01-19 00:09 UTC, merged