Add the option to export simulator device logs
fastlane/fastlane pull request #7906
Opened 2017-01-18 22:29 UTC by lyndsey-ferguson

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
This adds support for the `snapshot` action to output simulator device logs.

### Motivation and 
@hjanuschka can you provide the motivation? Also, can you test this out locally with your `snapshot` setup?

2017-01-18 22:29 UTC, lyndsey-ferguson commented
This is not yet ready

2017-01-19 19:14 UTC, lyndsey-ferguson commented
@hjanuschka can you take a look, and if all is good, merge this change?

2017-01-19 19:42 UTC, hjanuschka requested changes
thx for your contribution, looking good to me, just a couple of comments left.

2017-01-19 19:42 UTC, hjanuschka commented on fastlane/spec/fixtures/plist/Info.plist
> +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
is that by accident or does newer xcode generate it without Computer?

2017-01-19 19:42 UTC, hjanuschka commented on snapshot/spec/runner_spec.rb
> +        end
please remove the block.
`allow(FileUtils).to receive(:cp).with(anything, anything)` should do it.

2017-01-19 19:43 UTC, lyndsey-ferguson commented on fastlane/spec/fixtures/plist/Info.plist
> +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
Must have come from Xcode 8.1

2017-01-19 19:50 UTC, lyndsey-ferguson commented
@hjanuschka comments addressed. Ready to go! 🚀

2017-01-19 20:16 UTC, hjanuschka commented on fastlane/spec/fixtures/plist/Info.plist
> +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
thx - i think if it is not required for the PR it should be in original state. thx for reverting.

2017-01-19 20:16 UTC, hjanuschka approved these changes

2017-01-19 20:17 UTC, merged

2017-01-19 20:17 UTC, hjanuschka commented
many thx for this PR!

2017-01-27 06:21 UTC, russbishop commented
I would suggest `xcrun simctl spawn booted log collect`. The output will be written to `$(xcrun simctl getenv booted SIMULATOR_SHARED_RESOURCES_DIR)/system_logs.logarchive`

As more and more things move to `os_log` the old text log file may become less useful. Some debugging information is already stored in an in-memory ring buffer.

2017-01-27 06:41 UTC, hjanuschka commented
@russbishop that sounds awesome, i am ready to go for it. 

just to make sure i got it:
  * launch snapshot, doe tests on simulator
  * collect screenshots
  * run `xcrun simctl spawn booted log collect`
  * get log folder via `xcrun simctl getenv booted SIMULATOR_SHARED_RESOURCES_DIR`
  * copy over `path/system_logs.logarchive`

does this include the "normal" NSLog, or do we need to fetch the `system.log` too to get them?

would love to hear back on this.

2017-01-27 10:58 UTC, hjanuschka commented
@russbishop  carried on in https://github.com/fastlane/fastlane/pull/8033 maybe you can have a look at the code.

2017-01-28 06:21 UTC, russbishop commented
@hjanuschka Yes, that's correct. The new system captures Syslog, Apple System Logger, and the new `os_log` messages all in one place. I would expect everything to switch to the new logging system over time.

I updated the env var; I should have spelled the word "directory" out fully.