Gemfile resolution in Action.shell_out_should_use_bundle_exec (#7925)
fastlane/fastlane pull request #7926
Opened 2017-01-20 01:20 UTC by jcayzac

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
This fixes #7925 by reimplementing `Action.shell_out_should_use_bundle_exec`
is a way that closely matches how Bundler resolves the location of the
Gemfile.

### Motivation and Context
Fixes #7925. Now, invoking e.g. `cocoapods(use_bundle_exec: true)` will properly invoke `bundle exec pod…` even if the Gemfile is found in an ancestor of the current directory or if fastlane itself was invoked using `bundle exec fastlane`.

2017-01-20 01:24 UTC, jcayzac commented
Note: I had to reset my Xcode preferences for the tests to pass. The test `Scan Scan::DetectValues fetches the path from the Xcode config` makes a pretty strong assumption on the normal location of derived data and I believe this is a bug (of the test itself).

My Xcode preferences usually set the derived data to lie in the `build` folder relative to the current project, and the *Advanced* location settings request non-unique, custom build paths (`intermediates` and `products`). With those enabled, fastlane's tests fail:

```
Scan Scan::DetectValues fetches the path from the Xcode config
     Failure/Error: expect(derived_data).to match(%r{/.*Xcode/DerivedData/app-\w*$})

       expected "/Users/jcayzac/github/fastlane/fastlane/scan/examples/standard/build" to match /\/.*Xcode\/DerivedData\/app-\w*$/
       Diff:
       @@ -1,2 +1,2 @@
       -/\/.*Xcode\/DerivedData\/app-\w*$/
       +"/Users/jcayzac/github/fastlane/fastlane/scan/examples/standard/build"

     # ./scan/spec/detect_values_spec.rb:11:in `block (3 levels) in <top (required)>'
```

2017-01-20 07:21 UTC, hjanuschka commented
@jcayzac nice catch! thx for the PR. could you please add a unit test for it to prevent regression's?
somwhere in `fastlane/spec/action_spec.rb`

2017-01-20 08:40 UTC, jcayzac commented
@hjanuschka probably not until next week, and it will be a learning experience (I'm quite new to Ruby actually) :)

2017-01-20 09:11 UTC, hjanuschka commented
@jcayzac no worries, it should be something like this.


```ruby
describe "shell_out_should_use_bundle_exec?" do
      it "should return false on contained version" do
        expect(FastlaneCore::Helper).to receive(:contained_fastlane?).and_return(true)
        expect(Fastlane::Action.shell_out_should_use_bundle_exec?).to eq(false)
      end
      it "should return true if no GEMFILE set" do
        with_env_values('BUNDLE_GEMFILE' => "someGemfile") do
          expect(Fastlane::Action.shell_out_should_use_bundle_exec?).to eq(true)
        end
      end
      it "should return true if Gemfile can be found" do
        with_env_values('BUNDLE_GEMFILE' => nil) do
          expect(File).to receive(:file?).and_return(true)
          expect(Fastlane::Action.shell_out_should_use_bundle_exec?).to eq(true)
        end
      end
      it "should return false if not contained, BUNDLE_GEMFILE not set and Gemfile could not be found" do
        with_env_values('BUNDLE_GEMFILE' => nil) do
          allow(File).to receive(:file?).and_return(false)
          expect(Fastlane::Action.shell_out_should_use_bundle_exec?).to eq(false)
        end
      end
    end
```

2017-01-27 22:57 UTC, segiddins commented on fastlane/lib/fastlane/action.rb
> +          filename = File.join(current, "Gemfile")
Note that `gems.rb` is also a valid Gemfile name

2017-02-08 23:25 UTC, endocrimes requested changes
This should be good to go when also supporting `gems.rb`

2017-02-09 00:15 UTC, KrauseFx commented on fastlane/lib/fastlane/action.rb
> +          filename = File.join(current, "Gemfile")
Great point, thanks @segiddins, @jcayzac there is a method in `bundler` that allows you to easily get the name for the Gemfile in the current directory, let me know if you need any help 👍

2017-02-15 07:16 UTC, jcayzac commented
@DanToml @segiddins @KrauseFx @hjanuschka I'm terribly sorry for the long delay. I think I got all the comments covered for now. `gems.rb` is handled and there are unit tests. Let me know if anything else is needed.

2017-02-15 08:00 UTC, jcayzac commented
Actually I don't quite understand the raison d'être of `Action.shell_out_should_use_bundle_exec`. Why do you prevent actions from calling `bundle exec` when their options ask them to? It goes to the shell anyway.

If that's to lock users in with the versions of some gems that are in the contained version, then perhaps a better approach would be to not shell the commands out but call the gems programmatically instead, from the current ruby environment?

I'm not really happy with my pull request replicating Bundler's file resolution, when Bundler would do it just fine on its own if the `bundle exec` shell command was not being vetoed.

2017-03-13 07:26 UTC, jcayzac commented
@segiddins @DanToml is there anything else required to land this in `master`?

2017-03-13 16:11 UTC, KrauseFx commented
> This fixes #7925 by reimplementing Action.shell_out_should_use_bundle_exec in a way that closely matches how Bundler resolves the location of the Gemfile.

Is there any way we can **use** Bundler's implementation? `bundler` is already a dependency of _fastlane_, so we could call its methods directly.

2017-03-13 16:39 UTC, segiddins commented
`Bundler.default_gemfile`?

2017-05-01 19:08 UTC, KrauseFx commented
Thanks @segiddins 👍 

Hey @jcayzac, it looks like this is a great patch you have, but it should be updated to use the method @segiddins mentioned. Do you have the time to update the PR to make use of it? 

Thanks for all your contribution 🚀

2017-05-10 00:24 UTC, jcayzac commented
Hi @KrauseFx!
Sorry for the long delay in getting back. Unfortunately I'm working on Android projects right now which are consuming all my time. I think @segiddins's suggestion makes total sense and should be trivial to implement but I can't commit to do that any time soon. Hopefully when things get less crazy at work I'll have some time 😬
I'd also love more information regarding my question in [this comment](https://github.com/fastlane/fastlane/pull/7926#issuecomment-279942147), if you don't mind. I can't help thinking something might be wrong and `shell_out_should_use_bundle_exec` should not exist to begin with.

2017-05-10 00:25 UTC, jcayzac commented
Actually, now this project is CLA-encumbered and I have no intent on signing that, I'll close the PR.

2017-05-10 00:25 UTC, closed without merging

2017-05-10 17:32 UTC, taquitos commented
@jcayzac I'd love to understand your thoughts on the CLA. If there is something that needs to change, or should be made better, we can suggest updates to the lawyers. I see you're really busy right now, but if you ever get a chance to give us feedback, I'd be happy to follow up. You can reach me in our slack I'm @taquitos there too.

2017-05-13 09:20 UTC, jcayzac commented
Hi @taquitos,
I have nothing against this particular CLA (I haven't read it), but I am not willing to sign a legally-binding agreement or any sort to simply notify an open-source project's authors that they can exercise their rights to take my changes to the project's source code, as the license already allows them. CLA are a cancer.