Frameit percentage padding
fastlane/fastlane pull request #8032
Opened 2017-01-27 10:57 UTC by futuretap

This PR adds percentage-based padding as requested in #7343. As requested in #7334 review, I isolated the parts in separate PRs. This is one of them.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

2017-02-02 16:28 UTC, mpirri commented
@futuretap Looks like this PR has the same structure change to `config_parser.rb` as #8034 (now merged). Can you rebase off `master` to resolve the conflicts? Thanks!

2017-02-02 17:47 UTC, futuretap commented
I (force-)updated my branch to be based off `master`.
Btw, that's why I had one bigger PR because the structure change was needed for two of the features ;)

2017-02-02 19:24 UTC, mpirri commented
Examples of this in use. First is `padding = 50`, second is `padding = "10%"`.
![iphone6-testexample-d41d8cd98f00b204e9800998ecf8427e_framed_1](https://cloud.githubusercontent.com/assets/1190389/22564658/4ae2c646-e953-11e6-9e00-df26da20a372.png)
![iphone6-testexample-d41d8cd98f00b204e9800998ecf8427e_framed](https://cloud.githubusercontent.com/assets/1190389/22564657/4ae27448-e953-11e6-9b27-880fb615325d.png)

2017-02-02 19:24 UTC, mpirri requested changes

2017-02-02 19:24 UTC, mpirri commented on frameit/lib/frameit/config_parser.rb
> +              UI.user_error! "padding must be type integer or pair of integers of format 'AxB' or a percentage of screen size"
Can we keep the parenthesis in the call to `user_error!`? I realize this is valid, but it does not match the style of the rest of the file.

Also, can you add parens on the call to `user_error!` on line 87 below (in the `font_scale_factor` code)?

2017-02-02 20:04 UTC, futuretap commented
I've force pushed the change.

2017-02-03 15:43 UTC, mpirri commented on frameit/lib/frameit/config_parser.rb
> +            UI.user_error!("font_scale_factor must be numeric" unless value.kind_of?(Numeric))
I think this closing parenthesis is in the wrong place?  Should be after closing quote, and before the `unless`. This seems to be why CI is complaining.

2017-02-03 16:08 UTC, futuretap commented on frameit/lib/frameit/config_parser.rb
> +            UI.user_error!("font_scale_factor must be numeric" unless value.kind_of?(Numeric))
Of course, silly me! Updated.

2017-02-03 16:14 UTC, mpirri approved these changes

2017-02-03 16:14 UTC, merged