WIP: proof of logarchive extraction in snapshot
fastlane/fastlane pull request #8033
Opened 2017-01-27 10:58 UTC by hjanuschka

*DO NOT MERGE*
as reffered in https://github.com/fastlane/fastlane/pull/7906, also extract the logarchive from the simulator.

@russbishop
currently i have the following problem:
```
xcrun simctl getenv booted SIMULATOR_SHARED_RESOURCES_DIR
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=53):
Error returned in reply: Connection interrupted
Software caused connection abort
```

todo:

  - [ ] cleanup paths
  - [ ] check why `getenv` fails

```ruby
lane :os_coll do
        snapshot(
                project: "snapshot/example/Example.xcodeproj",
                scheme: "Example",
                output_simulator_logs: true,
                languages: ["en-US", "de-DE"],
                devices: ["iPhone 6", "iPhone 6s"]

        )
end

```

2017-01-27 19:13 UTC, KrauseFx commented on snapshot/lib/snapshot/runner.rb
> +
please remove extra space

2017-01-27 19:15 UTC, KrauseFx commented on snapshot/lib/snapshot/runner.rb
> +        UI.header("Collecting system logs #{device_name} - #{language}")
Is this information important enough to be a header?

2017-01-27 19:19 UTC, hjanuschka commented on snapshot/lib/snapshot/runner.rb
> +        UI.header("Collecting system logs #{device_name} - #{language}")
i think so.

2017-01-27 19:23 UTC, hjanuschka commented
@KrauseFx  i was working on it while you reviewed, i think i am finished now, and feed back has been addressed, see updated pr description too.

we should do the same to scan, once this PR is done.

2017-01-28 06:15 UTC, russbishop commented
@hjanuschka Sorry, the proper name of the env var is `SIMULATOR_SHARED_RESOURCES_DIRECTORY`.

2017-01-29 19:54 UTC, hjanuschka commented
this one is ready for review it refactors the system.log extraction, to use the newer `logarchive` format suggested by @russbishop  (the env works now many thx).


@lyndsey-ferguson as you intitially did the system.log copy stuff, could you please have a look this PR?

2017-01-29 21:11 UTC, lyndsey-ferguson requested changes
I've made some suggestions

2017-01-29 21:11 UTC, lyndsey-ferguson commented on snapshot/lib/snapshot/runner.rb
> +      components = [launch_arguments_index].delete_if { |a| a.to_s.length == 0 }
Also, a question, is not each launch argument a string?

2017-01-29 21:14 UTC, lyndsey-ferguson commented
Also, your test seems to be failing because `FastlaneCore::CommandExecutor.execute` is failing? You may need to mock a successful response and a failing response to make sure that both actions can handle such responses.

2017-01-30 08:21 UTC, hjanuschka reviewed
@lyndsey-ferguson thx for taking the time to look at this, feedback addressed.
i moved the tests to the other spec file, as we have the static simulator id's there. and tests should pass now.

2017-01-30 14:30 UTC, lyndsey-ferguson approved these changes

2017-01-30 14:30 UTC, lyndsey-ferguson commented on scan/spec/test_command_generator_spec.rb
> +    end
beautiful

2017-02-01 10:25 UTC, lacostej requested changes
Some small things to consider!

2017-02-01 10:25 UTC, lacostej commented on scan/lib/scan/runner.rb
> +    def output_simulator_logs
maybe name it `include_simulator_logs` instead.

Output makes me think they will be pasted to the output.

2017-02-01 10:25 UTC, lacostej commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_src) if File.exist?(logarchive_src)
This is a bit redundant maybe. `rm_rf` ought to be enough as it handles the not `exist?`.

2017-02-01 10:25 UTC, lacostej commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_dest) if File.exist?(logarchive_dest)
same?

2017-02-01 10:31 UTC, lacostej commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_dest) if File.exist?(logarchive_dest)
As this code is very much shared with snapshot's would there be an interest in moving the shared functionality into FastlaneCore?

2017-02-01 13:45 UTC, lyndsey-ferguson commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_dest) if File.exist?(logarchive_dest)
I like that idea

2017-02-01 13:47 UTC, lyndsey-ferguson commented on scan/lib/scan/runner.rb
> +    def output_simulator_logs
The name `include_simulator_logs` doesn't feel right. If `output` feels like the logs will be printed to the console, maybe a better name would be `copy_simulator_logs_to_output_directory` or something along those lines 😉

2017-02-01 13:48 UTC, lyndsey-ferguson commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_src) if File.exist?(logarchive_src)
That's true

2017-02-01 15:03 UTC, hjanuschka commented on scan/lib/scan/runner.rb
> +        FileUtils.rm_rf(logarchive_dest) if File.exist?(logarchive_dest)
going to put it into fastlane core tonight 👍

2017-02-01 18:50 UTC, hjanuschka commented
@lacostej, @lyndsey-ferguson feedback addressed its not part of `FastlaneCore::Simulator`.
also i renamed the output... methods to `copy_simulator_logs`

2017-02-01 19:01 UTC, lyndsey-ferguson commented on fastlane_core/lib/fastlane_core/device_manager.rb
> +        FileUtils.rm_rf(logarchive_src) if File.exist?(logarchive_src)
I think that @lacostej was suggesting that it isn't necessary to check if the file exists as the `rm_rf` will delete it if it does and not complain if it does not.

2017-02-01 19:01 UTC, lyndsey-ferguson reviewed
This is looking very nice. Reminded about the `rm_rf` change that was suggested

2017-02-01 19:01 UTC, lyndsey-ferguson commented on fastlane_core/lib/fastlane_core/device_manager.rb
> +        FileUtils.rm_rf(dest) if File.exist?(dest)
Same here

2017-02-01 19:09 UTC, hjanuschka commented
also fixed the rm thing, i missed that one 😢

2017-02-02 14:09 UTC, lacostej commented on fastlane_core/lib/fastlane_core/device_manager.rb
> +        # if logarchive already exists it fails as the .logarchive is a directory, so delete it. to be sure its gone
this one needs to be moved just above the `rm_rf`

2017-02-02 14:16 UTC, lacostej approved these changes

2017-02-02 14:30 UTC, merged