[Sigh] download_all name file using profile UUID instead of application bundle identifier
fastlane/fastlane pull request #8082
Opened 2017-02-02 10:38 UTC by lgaches

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description
download_all action needs to name every mobile provision with an unique name.

### Motivation and Context
A team can have several mobile provision for the same application bundle identifier but with a different name. Naming the file with the application bundle identifier doesn't allow to download all the mobile provision from a specific team because the last one downloaded will replace all the previous. By using the profile UUID, we'll be sure that all mobile provision are downloaded.

2017-02-02 12:52 UTC, hjanuschka requested changes

2017-02-02 12:52 UTC, hjanuschka commented on sigh/lib/sigh/download_all.rb
> +      profile_name = "#{type_name}_#{profile.uuid}.mobileprovision" # default name
can you please add the   `profile.app.bundle_id` too -  so that we see the bundle id in the filename too.

2017-02-02 21:44 UTC, hjanuschka approved these changes
nice change, thx for your contribution! 🚀

2017-02-02 21:44 UTC, merged

2017-03-01 02:08 UTC, elianfish commented
We have the following command to create a profile file

Fastlane sigh -a com.ysl.apple -u ysl@163.com -n apple_appstore

Finally, the local storage name is InHouse_com.ysl.apple.mobileprovision

But when we updated the profile and execute the download command:

Fastlane sigh download_all -u ysl@163.com

Its local storage name becomes InHouse_41939ba6-6190-4024-a7d7-e69922752778_com.ysl.apple.mobileprovision

Excuse me, create a new profile and re-download the profile, the storage name can be consistent?