Frameit: Provide option to stack keyword on top of title
fastlane/fastlane pull request #8098
Opened 2017-02-03 00:54 UTC by lopper

### Checklist
- I've successfully run bundle exec rspec frameit
- I've successfully run bundle exec rubocop -a frameit

### Description
I've add an option,"stack_title" , to frameit so that they keyword can be displayed above the title instead of to the side.

2017-02-03 06:46 UTC, hjanuschka commented
@lopper thx for your contribution - can you please add a screenshot of the results with and without your options?

2017-02-03 20:51 UTC, mpirri commented
@lopper When testing this with a `padding` value of `50`, I got some nice output:
![iphone6-testexample-d41d8cd98f00b204e9800998ecf8427e_framed](https://cloud.githubusercontent.com/assets/1190389/22607992/7b561f96-ea28-11e6-89d0-5a702fc8c0fd.png)


However, when testing with smaller `padding` values, things looked less good (this is with `"padding": 0`):
![iphone6-testexample-d41d8cd98f00b204e9800998ecf8427e_framed](https://cloud.githubusercontent.com/assets/1190389/22607968/59866682-ea28-11e6-90e6-4e08f3807c4f.png)

Any thoughts on how to fix this when running with small `padding` values?

2017-02-03 20:52 UTC, mpirri requested changes
Please address zero-padding layout issue and also resolve conflicts with new options added to `frameit` layout.

2017-02-03 22:46 UTC, lopper commented
@mpirri I'll resolve the issue and push the fix.

2017-02-06 19:45 UTC, lopper commented
Hi @mpirri, can the pull request be accepted? Is there anything else I need to resolve?

2017-02-06 19:48 UTC, mpirri commented
@lopper I will do my best to take a look later today - I've been traveling and haven't yet had the time to do my due diligence. Thanks for the quick feedback response!

2017-02-08 04:17 UTC, mpirri approved these changes

2017-02-08 04:17 UTC, merged