Fixes tvos sigh profile name
fastlane/fastlane pull request #8123
Opened 2017-02-03 19:51 UTC by cgoldsby

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
When downloading a profile`sigh` will now append `_tvos` to the file name.

### Motivation and Context
Fixes #8122. This fixes a problem where `match` can not fetch a tvos profile from a repo because the profile name is not found. Feel free to tweak or discard. Or, let me know if you would like me to make any changes. ❤️

2017-02-03 20:17 UTC, hjanuschka requested changes
awesome, good explanation in the issue, nice catch,  thx for your contribution, i left a  note. once that done i think we are good to merge.

2017-02-03 20:17 UTC, hjanuschka commented on sigh/lib/sigh/runner.rb
> +      UI.important "Creating new provisioning profile for '#{Sigh.config[:app_identifier]}' with name '#{name}' for '#{Sigh.config[:platform]}' platform"
❤️

2017-02-03 20:17 UTC, hjanuschka commented on sigh/lib/sigh/runner.rb
> +      profile_name ||= "#{profile_type.pretty_type}_#{Sigh.config[:app_identifier]}"
can we append the .mobileprovision directly in the `|| =`  above?
as right now it seems to be appended anyway 

the prev. implementation also was not 100% right, i think

2017-02-03 20:30 UTC, cgoldsby commented on sigh/lib/sigh/runner.rb
> +      profile_name ||= "#{profile_type.pretty_type}_#{Sigh.config[:app_identifier]}"
@hjanuschka, thank you for the review. We need '_tvos' just before .mobileprovision. So, I am not sure if we can append it to [line 219](https://github.com/fastlane/fastlane/pull/8123/files#diff-e9e7336e24f66a051f7c7e07128efd8fR219). 

Would something like this work for you? Or, did you have something else in mind.

```diff ruby
profile_name ||= "#{profile_type.pretty_type}_#{Sigh.config[:app_identifier]}"
if Sigh.config[:platform].to_s == 'tvos'
    profile_name += "_tvos"
end
- profile_name += '.mobileprovision' unless profile_name.include? 'mobileprovision
+ profile_name += '.mobileprovision'
```

2017-02-03 20:42 UTC, hjanuschka commented on sigh/lib/sigh/runner.rb
> +      profile_name ||= "#{profile_type.pretty_type}_#{Sigh.config[:app_identifier]}"
ok good point, yep thats fine, i was just curious about the infact usless unless 👍

2017-02-03 20:47 UTC, cgoldsby commented on sigh/lib/sigh/runner.rb
> +      profile_name ||= "#{profile_type.pretty_type}_#{Sigh.config[:app_identifier]}"
😎 

✓ Done.

2017-02-03 20:49 UTC, KrauseFx commented on sigh/lib/sigh/runner.rb
> +      profile_name += '.mobileprovision'
Shouldn't this also need ` unless profile_name.include? 'mobileprovision'` like we've had before?

2017-02-03 20:55 UTC, hjanuschka commented on sigh/lib/sigh/runner.rb
> +      profile_name += '.mobileprovision'
ohhh .... i request to remove this, as i thought its not needed as it is always true - @KrauseFx  you mean there is a case where profile_name could already contain `.mobileprovision` - i didn't see any possibilities for that. (in sigh/runner)

2017-02-03 20:59 UTC, hjanuschka commented on sigh/lib/sigh/runner.rb
> +      profile_name += '.mobileprovision'
as `profile_name` is created and only used in the `download_profile` method.

2017-02-06 00:53 UTC, KrauseFx commented on sigh/lib/sigh/runner.rb
> +      profile_name += '.mobileprovision'
Sounds good to me

2017-02-06 07:54 UTC, hjanuschka approved these changes

2017-02-06 07:54 UTC, merged

2017-02-06 07:54 UTC, hjanuschka commented
@cgoldsby many thx for your contribution!