Fixes: Arabic frameit imagemagick issue #7522 and similar
fastlane/fastlane pull request #8131
Opened 2017-02-05 09:49 UTC by iMokhles

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

##### Describe your changes in detail

add rechaper.rb from [ShadyAbuKalam/Ruby-Arabic-Reshaper](https://github.com/ShadyAbuKalam/Ruby-Arabic-Reshaper)
and added it to frameit to reshape arabic text 

### Motivation and Context

##### Why is this change required? What problem does it solve?
solves wrong arabic texts encoding from imagemagick 

##### If it fixes an open issue, please link to the issue here.
[issue #7522](https://github.com/fastlane/fastlane/issues/7522)

##### Please describe in detail how you tested your changes
used MindNode frameit example from [MindNode/screenshots](https://github.com/fastlane/examples/tree/master/MindNode/screenshots)

### Screenshots proves it  works well and don't effect English language as well

<img src="https://cloud.githubusercontent.com/assets/1247248/22625202/20c77f16-eb90-11e6-9c33-84d9ecb624ac.png" width="320" height="550"> <img src="https://cloud.githubusercontent.com/assets/1247248/22625203/20fc7928-eb90-11e6-8925-2ff790634144.png" width="320" height="550">

2017-02-05 19:33 UTC, hjanuschka requested changes
i really would love to see #7522  fixed.
however i am unsure about the introduction to a new dep.

also there are a couple of rubocop issues,  that would need to get addressed.

@KrauseFx, @mfurtak  hows your view on the introduction of a new dependencie?

2017-02-05 19:33 UTC, hjanuschka commented on sigh/lib/assets/resign.sh
> +
that happend by accident?

2017-02-06 06:56 UTC, iMokhles commented on sigh/lib/assets/resign.sh
> +
i had modified version to sign dylibs in main bundle pull request #6364 so i set it to the original version

2017-03-23 13:17 UTC, hjanuschka commented
@iMokhles you see any chance to find a solution without the new gem dependencies? (as most of the fastlane users are not in the need of arabic letters, i guess) and bringing in new deps. is always crucial.

2017-03-25 04:43 UTC, KrauseFx commented
Agreed with @hjanuschka, we can't introduce a new dependency for this unfortunately

2017-04-04 13:38 UTC, mfurtak commented
I'm going to close this for now, but we can always reopen it if we can make more forward progress :+1:

2017-04-04 13:38 UTC, closed without merging