[scan] support toolchain parameter
fastlane/fastlane pull request #8172
Opened 2017-02-08 07:45 UTC by hjanuschka

fixes: https://github.com/fastlane/fastlane/issues/8167

2017-02-08 23:15 UTC, endocrimes requested changes
Couple of test changes, but looking good :+1:

2017-02-08 23:15 UTC, DanToml commented on scan/spec/test_command_generator_spec.rb
> +      end
there should be a newline here

2017-02-08 23:15 UTC, DanToml commented on scan/spec/test_command_generator_spec.rb
> +      it "Supports toolchain" do
This should be a part of the `:toolchain` `describe`, and should maybe be `passes the toolchain option to xcodebuild`

2017-02-09 07:51 UTC, hjanuschka commented on scan/spec/test_command_generator_spec.rb
> +      end
fixed

2017-02-09 07:52 UTC, hjanuschka commented
@DanToml feedback addressed, thx!

2017-02-09 09:29 UTC, endocrimes approved these changes

2017-02-09 10:11 UTC, merged