Provide detailed error message when gym fails #6292
fastlane/fastlane pull request #8173
Opened 2017-02-08 12:03 UTC by thiagofelix

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

I am adding the field `error_info` to FastlaneError class intended to contain detailed information about the error along side with the error message itself. 
The new field can be specified using the UI.user_error `options` parameter, same way the `show_github_issues` works.

### Motivation and Context

Currently if you have a problem with the gym execution the `error` block will receive only a friendly message saying that you build or package command didn't work. The idea here is to extend the error class so the user can get access to the whole xcodebuild output and use that information when reporting the problem. 

One use case would be sending a slack message with the build output as attachment so everyone in the room can quickly scan and see what went wrong.

### Usage Example

**Badly behaving lane:**

```ruby
lane :build  do
    gym(..)
end

error do |lane, exception|
    slack(
       # message with short human friendly message
       message: exception.to_s, 
       success: false, 
       # Output containing extended log output
       payload: { "Output" => exception.error_info.to_s } 
    )
end
```

**Slack Message:**
![image](https://cloud.githubusercontent.com/assets/117622/22717931/f1dc4d34-ed84-11e6-8c17-145d3fee1975.png)

It would be even better if xcodebuild given us exactly what broke the build (file, line number, etc), this way the error_info would be more precise showing the problem versus just dumping the whole process output.

The original issue/discussion can be found here #6292

2017-02-08 14:39 UTC, lyndsey-ferguson commented on fastlane_core/lib/fastlane_core/ui/interface.rb
> +      attr_reader :error_info
Just a thought, but as we will receive an 'exception', could the instance variable could just be `:info`?

2017-02-08 15:13 UTC, thiagofelix commented on fastlane_core/lib/fastlane_core/ui/interface.rb
> +      attr_reader :error_info
I agree with you, *error_*  is redundant inside the exception, good catch.
The reason behind error_Info was to follow with [SpaceShip similar error class](https://github.com/fastlane/fastlane/blob/e02b5d15ec6606bad0ad954b0fb62fea144f39b2/spaceship/lib/spaceship/client.rb#L72) which also expose property named `error_info`

2017-02-08 18:11 UTC, KrauseFx commented on gym/README.md
> +    slack(
This should be 2 spaces 👍

2017-02-08 18:50 UTC, thiagofelix commented on gym/README.md
> +    slack(
Fixed =) tks

2017-02-08 19:50 UTC, KrauseFx commented on gym/README.md
> +      # message with short human friendly message
That still needs to be updated 👍

2017-02-08 20:54 UTC, thiagofelix commented on gym/README.md
> +      # message with short human friendly message
Ops sorry, fixed again 😂

2017-02-08 23:09 UTC, endocrimes requested changes
A few points but this is a nice change :+1:

2017-02-08 23:09 UTC, DanToml commented on fastlane_core/lib/fastlane_core/ui/interface.rb
> +      attr_reader :error_info
I'd keep the `error_info` property as is, for consistency, and because you're showing an underlying error.

2017-02-08 23:09 UTC, DanToml commented on fastlane_core/lib/fastlane_core/ui/interface.rb
> +      options = { show_github_issues: false, error_info: nil }.merge(options)
You should be able to pass `options` straight through, as both of these are the same as the default values.

2017-02-08 23:09 UTC, DanToml commented on fastlane/docs/README.md
> +
rm extra new line

2017-02-08 23:09 UTC, DanToml commented on fastlane/docs/README.md
> +You can get more information about the error using the field `error_info`.
maybe "using the `error_info` property."?

2017-02-08 23:09 UTC, DanToml commented on gym/README.md
> +in case you want to display the error in 3rd party tools such as slack.
"the `error_info` property" and "Slack"

2017-02-08 23:19 UTC, thiagofelix commented on fastlane_core/lib/fastlane_core/ui/interface.rb
> +      options = { show_github_issues: false, error_info: nil }.merge(options)
Good call Dan, thanks!

2017-02-08 23:23 UTC, thiagofelix commented on fastlane/docs/README.md
> +You can get more information about the error using the field `error_info`.
Fixed =)

2017-02-09 00:56 UTC, endocrimes approved these changes

2017-02-09 00:56 UTC, DanToml commented
This is great, thank you @thiagofelix!

2017-02-09 00:56 UTC, merged