[supply] only set apk path when none is given
fastlane/fastlane pull request #8256
Opened 2017-02-15 16:49 UTC by koenpunt

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Description

only set apk path when none is given

### Motivation and Context

User options should always have precedence, and if for some reason multiple apks are generated, it should still be possible to only use one.

2017-02-16 09:59 UTC, lacostej reviewed
@koenpunt do you think you could try adding some tests?

2017-02-16 09:59 UTC, lacostej commented on fastlane/lib/fastlane/actions/supply.rb
> +        unless params[:apk_paths].present? || params[:apk].present?
I think the change is OK, but we should really consider
* adding tests. There are too many ways to set up the paths.
* go towards removing the use of `params[:apk]` at least internally. For example we could do something like

```ruby
params[: apk_paths] = [ Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] ] if Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
```

2017-02-27 15:49 UTC, mfurtak commented
@koenpunt Do the comments from @lacostej make sense? Do you have a clear path forward for this?

2017-02-28 08:33 UTC, koenpunt commented
@mfurtak I tried to write some tests but walked into some difficulties. I can push what I have, and maybe then you can give me some pointers?

2017-03-03 16:36 UTC, mfurtak requested changes
`present?` is not a method in core Ruby, only in Rails 😄 

I'll work on adapting this and adding tests 👍

2017-03-03 16:37 UTC, closed without merging