Pilot external testing
fastlane/fastlane pull request #8395
Opened 2017-02-28 19:51 UTC by cpk1

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

This is to address https://github.com/fastlane/fastlane/issues/6818
I've added the "betaState" attribute to Spaceship::Tunes:Build
In Pilot::BuildManager I've added the "betaState" status to the builds output.
Additionally I've added the parameter "external_available" to "distribute_build" this will be checked before calling "uploaded_build.build_train.update_testing_status!" 

### Motivation and Context

When building from jenkins and using a post-build action with "fastlane pilot upload distribute_external TRUE" pilot will always return an iTC error because it is impossible to turn on a build for external testing before beta app review, this in turn will cause the job to be marked as failed despite everything occurring as expected - build was uploaded and submitted for beta app review successfully.

https://github.com/fastlane/fastlane/issues/6818

I've uploaded and attempted to distribute for external testers at the same time (fastlane pilot upload distribute_external TRUE) and tried to distribute internally and externally builds that were already uploaded and approved and not approved for external distribution ("fastlane pilot distribute distribute_external TRUE" and "fastlane pilot distribute")

2017-03-07 17:22 UTC, giginet requested changes
Are there tests in this situation?

This logic seems to be complicated. So, you should add some specs.

2017-03-07 17:22 UTC, giginet commented on pilot/lib/pilot/build_manager.rb
> +        work_status = true
I think you should return value here.

2017-03-31 20:50 UTC, gcamp commented
@cpk1 Are you planning to update your pull request? I would be available to fix it if you don't plan on doing it.

2017-04-11 18:26 UTC, cpk1 commented
I'm trying to take a look this week. Sorry for the accidental push!

2017-04-12 05:53 UTC, cpk1 commented
Oh I've noticed the change :). It looks like Pilot was affected quite a bit by todays update.

2017-04-12 14:24 UTC, KrauseFx commented
@cpk1 that's ok, we're in the works on updating spaceship 👍

2017-06-13 15:32 UTC, ohayon commented
I am going to close this because I think these changes have been superseded by the changes we needed to make when Apple rolled out changes to TestFlight a little while ago. thanks for this though @cpk1 !! 🚀

2017-06-13 15:32 UTC, closed without merging