Improve tvos support in deliver
fastlane/fastlane pull request #8414
Opened 2017-03-02 01:58 UTC by tmm1

Previously, finding builds on a universal app would not work.

cc #6480 #7648

2017-03-02 21:47 UTC, ohayon commented
Thanks for this PR @tmm1! Has this been tested for all of the supported platforms? 🐙

2017-03-02 21:51 UTC, tmm1 commented
I only tested uploading a tvos app, but I have no reason to believe it wouldn't work everywhere.

2017-03-02 21:53 UTC, lacostej commented
@tmm1 I see other places in deliver where we don't pass the `platform` option.

E..g `verify_available_languages!`, `UploadScreenshots#upload` for `edit_version` and more for `latest_version`

Have you had a chance to test all those features? (I don't do tvos apps, so can't help there)

2017-03-02 21:54 UTC, lacostej commented
See:
```sh
$ git grep -n -E "(edit|latest)_version" deliver | grep -v ":platform"
deliver/lib/deliver/commands_generator.rb:150:          v = options[:app].latest_version
deliver/lib/deliver/download_screenshots.rb:13:      v = options[:app].latest_version
deliver/lib/deliver/html_generator.rb:41:      @languages ||= options[:app].latest_version.description.languages
deliver/lib/deliver/setup.rb:27:      v = options[:app].latest_version
deliver/lib/deliver/submit_for_review.rb:32:      v = app.edit_version
deliver/lib/deliver/submit_for_review.rb:58:        build = find_build(app.latest_version.candidate_builds)
deliver/lib/deliver/upload_metadata.rb:153:      v = options[:app].edit_version
deliver/lib/deliver/upload_screenshots.rb:37:        v = app.edit_version
deliver/spec/commands_generator_spec.rb:207:      expect(fake_app).to receive(:latest_version).and_return('1.0.0')
deliver/spec/setup_spec.rb:9:      # expect(app).to receive(:latest_version).and_return(version)
```

2017-03-02 21:55 UTC, tmm1 commented
I've used those features in the past with a tvos-only app, but I imagine they would not work as expected with a universal app.

I actually don't have a universal app myself, so if someone else wants to take over this effort I would prefer that.

2017-03-07 17:00 UTC, giginet requested changes

2017-03-07 17:00 UTC, giginet commented on fastlane/lib/fastlane/actions/deliver.rb
> +        [:ios, :appletvos, :mac].include?(platform)
Is this right? In other implementations use `:tvos`.

2017-06-13 16:00 UTC, ohayon commented
Hey @tmm1, just checking in to see if you had seen @giginet 's requested changes, also, have you tested this since the new changes that Apple rolled out to iTC? Would be good to know if it is still a working change.

2017-07-31 15:16 UTC, ohayon commented
Hey @tmm1 - Wanted to bump this PR again just to see if you had a chance to look at @giginet's comments? Since this is a pretty old PR we should try to get this in or closed in the near future 😄 🚀 🐙

2017-07-31 15:19 UTC, closed without merging