Fix : #8430
fastlane/fastlane pull request #8434
Opened 2017-03-03 14:32 UTC by lgaches

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description

### Motivation and Context

2017-03-07 15:37 UTC, giginet approved these changes

2017-03-07 15:44 UTC, mfurtak commented
Will it break anyone's existing workflow to make this change?

2017-03-10 01:11 UTC, KrauseFx requested changes

2017-03-10 01:11 UTC, KrauseFx commented on sigh/lib/sigh/runner.rb
> +      profile_name ||= "#{profile_type.pretty_type}_#{profile.uuid}_#{Sigh.config[:app_identifier]}"
This will break setups where the user assumes the file name

2017-03-10 01:11 UTC, KrauseFx commented on sigh/spec/manager_spec.rb
> +      expect(val).to eq(File.expand_path("./AppStore_uuid_com.krausefx.app.mobileprovision"))
Yes, that's why this change would break existing setups. These tests must keep working without them being changed.

2017-03-20 20:25 UTC, KrauseFx commented
Any updates on this?

2017-05-01 19:06 UTC, KrauseFx commented
I'll go ahead and close this PR for now. Please feel free to submit a new issue, so we can continue the discussion 👍

2017-05-01 19:06 UTC, closed without merging