Adding Carthage cache-builds flag
fastlane/fastlane pull request #8504
Opened 2017-03-13 02:07 UTC by LukeDurrant

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Description

Enabled cache-builds flag

By default Carthage will rebuild a dependency regardless of whether it's the same resolved version as before. Passing the --cache-builds will cause carthage to avoid rebuilding a dependency if it can. See https://github.com/Carthage/Carthage/blob/master/Documentation/VersionFile.md

### Motivation and Context
Carthage has a new cache-builds flag

2017-03-13 02:23 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       description: "By default Carthage will rebuild a dependency regardless of whether it's the same resolved version as before. Passing the --cache-builds will caus
Let's try to avoid having URLs in the description and add them to the `self.details` instead

2017-03-13 02:23 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                         UI.user_error!("Please pass a valid value for cache_builds. Use one of the following: true, false") unless value.kind_of?(TrueClass) || value.kind_of?(FalseCl
I think we already have some kind of solution for boolean verification in _fastlane_

2017-03-13 10:49 UTC, mcfedr commented
Fixes https://github.com/fastlane/fastlane/issues/8384

2017-03-13 17:19 UTC, giginet commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       optional: true),
You should set `default` is `false` rather than `optional` is `true`.

2017-03-13 17:21 UTC, giginet requested changes
You should avoid using `optional` parameter.

2017-03-13 17:21 UTC, giginet commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       optional: true),
You should set `default` is `false` rather than `optional` is `true`.

2017-03-13 23:40 UTC, LukeDurrant commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       optional: true),
Why is that?
I simply followed the rest of the params haven't seen anywhere where it does this?

2017-03-14 07:38 UTC, hjanuschka commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       optional: true),
@giginet i think `optional: true` in combination with `is_string: false`  has the same effect, and is used accross the whole codebase. @KrauseFx  am i wrong?

2017-03-14 22:18 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       optional: true),
I think it's the same, yes 👍

2017-03-15 23:21 UTC, LukeDurrant commented
@giginet?

2017-03-15 23:24 UTC, LukeDurrant commented
I signed it!

2017-03-19 17:12 UTC, giginet approved these changes

2017-03-20 20:45 UTC, KrauseFx submitted a review, later dismissed
Hey @LukeDurrant, thanks for the PR, this is a great change. I added some notes before it's ready

2017-03-20 20:45 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +        cmd << "--cache-builds" if params[:cache_builds] == true
Please remove the `==true` code

2017-03-20 20:45 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       description: "By default Carthage will rebuild a dependency regardless of whether it\'s the same resolved version as before. Passing the --cache-builds will cau
Why not just `'` instead of `\'`

2017-03-20 20:45 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/carthage.rb
> +            cache_builds: true,                             # By default Carthage will rebuild a dependency regardless of whether it\'s the same resolved version as before.
Why the `\'`

2017-03-20 20:45 UTC, KrauseFx commented on fastlane/spec/actions_specs/carthage_spec.rb
> +        end.not_to raise_error
`not_to raise_error` is very generic, can we actually test something here maybe?

2017-03-20 22:50 UTC, LukeDurrant commented on fastlane/spec/actions_specs/carthage_spec.rb
> +        end.not_to raise_error
Suggestion?

2017-03-20 22:51 UTC, LukeDurrant commented on fastlane/lib/fastlane/actions/carthage.rb
> +        cmd << "--cache-builds" if params[:cache_builds] == true
Whys that?

2017-03-20 22:52 UTC, LukeDurrant commented
Accidentally closed reopening!

2017-03-20 22:54 UTC, LukeDurrant commented on fastlane/lib/fastlane/actions/carthage.rb
> +            cache_builds: true,                             # By default Carthage will rebuild a dependency regardless of whether it\'s the same resolved version as before.
Because it needs escaping?

2017-03-20 22:54 UTC, LukeDurrant commented on fastlane/lib/fastlane/actions/carthage.rb
> +                                       description: "By default Carthage will rebuild a dependency regardless of whether it\'s the same resolved version as before. Passing the --cache-builds will cau
Doesn't need escaping here

2017-03-22 16:19 UTC, adomanico commented
Love this, thanks for setting this up.

Going to speed up our daily builds a lot!

2017-03-22 21:12 UTC, mcfedr commented
Yea, been using the for about a week, build times have been halved, its great!

2017-03-22 23:53 UTC, LukeDurrant commented
Yeah build servers across the world will have a .... `sigh` of relief

2017-03-23 04:13 UTC, netbe commented
Can't wait to use it too. Just curious how you handle versions (let's say someone using new fastlane version with this `cache-builds` flag but with older carthage version)

2017-03-23 05:45 UTC, mcfedr commented
In our case, fastlane crashes, and someone asks in the the group chat why its broken, and I say, update carthage :)

2017-03-23 11:07 UTC, hjanuschka commented on fastlane/spec/actions_specs/carthage_spec.rb
> +        end.not_to raise_error
i think the prev. test also covers this. so i am in favor of removing this particular test case.
as i would like to see this PR merged, @KrauseFx  whats your point?

2017-04-03 14:16 UTC, mcfedr commented
Is there still something holding this up?

2017-04-04 13:04 UTC, mfurtak commented on fastlane/spec/actions_specs/carthage_spec.rb
> +        end.not_to raise_error
This is consistent with the tests around it, so we should ship it, IMO. If folks feel strongly, we can always take it back out. 👍

2017-04-04 13:05 UTC, mfurtak approved these changes

2017-04-04 13:06 UTC, merged

2017-04-04 13:07 UTC, mfurtak commented
Thanks for the contribution, @LukeDurrant, and for your testing @mcfedr 🚀