Add git_user_name and git_user_email option to match
fastlane/fastlane pull request #8550
Opened 2017-03-16 08:40 UTC by kouki-dan

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

Add new option to match `git_user_name` and `git_user_email` to set git config to match's git repository.

### Motivation and Context

If using useConfigOnly option (and global name or email settings is not set) in gitconfig, match fails to commit to git repository
Add new two option for name and email and fix it.

The reason which the git option needs is follow [this page](https://collectiveidea.com/blog/archives/2016/04/04/multiple-personalities-in-git)

2017-03-16 08:41 UTC, kouki-dan commented
I signed it!

2017-03-16 08:43 UTC, kouki-dan commented
I signed it!

2017-03-16 17:34 UTC, KrauseFx requested changes

2017-03-16 17:34 UTC, KrauseFx commented on match/lib/match/options.rb
> +                                     description: "git user name to commit",
Maybe that's just a small detail, but by `user name` many people understand the nickname (in my case `KrauseFx`), however in git it's recommended to use the full name as far as I know (in my case `Felix Krause`). Maybe we should rename the `key`, `env_name` and `description` to clarify this?

2017-03-16 17:35 UTC, KrauseFx commented
Hey @kouki-dan, thanks for taking the time to submit this PR, a great change, and I can totally see the use case for this 👍

2017-03-17 02:24 UTC, kouki-dan commented on match/lib/match/options.rb
> +                                     description: "git user name to commit",
Thank you for your review. I understand.
I will replace `user name` to `full name` and push this.

2017-03-17 02:50 UTC, KrauseFx commented on match/lib/match/git_helper.rb
> +      UI.message "Add git user config to local git repo..." unless commands.empty?
Maybe you can prepend this with a line that's just
```ruby
return if commands.empty?
```

2017-03-17 02:54 UTC, kouki-dan commented on match/lib/match/git_helper.rb
> +      UI.message "Add git user config to local git repo..." unless commands.empty?
Ah, okay. That's better I think.

2017-03-17 03:34 UTC, KrauseFx approved these changes
This looks great 🎷

2017-03-17 03:34 UTC, merged

2017-03-17 03:34 UTC, KrauseFx commented
Thanks for your contribution @kouki-dan 👍

2017-03-17 06:48 UTC, hjanuschka commented
i think that fixes: https://github.com/fastlane/fastlane/issues/8450

2017-03-17 06:55 UTC, kouki-dan commented
Yes, I got a same error as #8450.

Thank you for your reviewing and merging. I support Fastlane project :+1:

2017-05-03 18:41 UTC, kylejm commented
This is an awesome improvement! This problem got me for ages. I had to keep changing my gitconfig back and forth which was error prone. Thank you!

However, I'm not sure why, but this isn't working for me. I'm running fastlane `2.28.7`.

Tried:

```shell 
$ fastlane match nuke distribution --skip_confirmation -a my.app.id --git_full_name 'Fastlane Match' --git_user_email 'match@fastlane.tools'
```

and 

```ruby
#Fastfile
match(app_identifier: identifier,
          readonly: readonly,
          type: type,
          shallow_clone: 1,
          git_full_name: 'Fastlane Match',
          git_user_email: 'match@fastlane.tools')
```

Any idea as to what I'm doing wrong?

2017-05-03 20:37 UTC, KrauseFx commented
@kylejm that's how you should use it. Can you submit a new issue with the output? Is it not working?

2017-05-07 09:16 UTC, kylejm commented
Hey @KrauseFx, sorry for the slow response. Issue create ☝️.