Add "--new-comment" / "--base" / "--head" support to Danger action
fastlane/fastlane pull request #8574
Opened 2017-03-17 18:52 UTC by duck8823

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

I added [Danger parameters](https://github.com/danger/danger/blob/v4.2.2/lib/danger/commands/runner.rb#L56-L61) that are not  supported yet.

### Motivation and Context

I want to use `--new-comment` option on fastlane Danger action :D

2017-03-17 19:01 UTC, duck8823 commented
I signed it!

2017-03-17 23:46 UTC, mgrebenets approved these changes

2017-03-19 17:02 UTC, giginet commented on fastlane/lib/fastlane/actions/danger.rb
> +                                       optional: true,
I think it is not needed because `default_value` is set.

2017-03-22 15:11 UTC, ohayon requested changes
This looks good! Just one small style change if possible! 🐙

2017-03-22 15:11 UTC, ohayon commented on fastlane/lib/fastlane/actions/danger.rb
> +        cmd << "--base=#{base}" if base
Could we try to keep this consistent by just checking `if params[:base]` and `if params[:head]`?

2017-03-22 15:32 UTC, duck8823 commented on fastlane/lib/fastlane/actions/danger.rb
> +        cmd << "--base=#{base}" if base
Yes, 
```
base = params[:base]
cmd << "--base=#{base}" if base
```
could be replaced to
``` 
cmd << "--base=#{params[:base]}" if params[:base]
```

2017-03-22 15:55 UTC, duck8823 commented on fastlane/lib/fastlane/actions/danger.rb
> +        cmd << "--base=#{base}" if base
I changed it ! :D

2017-03-22 17:09 UTC, ohayon commented
Oh! @duck8823 Im so sorry! I think I missed the point of why you had the `head` and `base` variables, and you were right the first time! 😳. Would you mind reverting that last commit? Sorry for the back and forth!! 🐙

2017-03-22 17:26 UTC, duck8823 commented
@ohayon It's Okay. I reset last commit.
Thank you for your review :D

2017-03-22 17:27 UTC, ohayon approved these changes

2017-03-22 17:28 UTC, ohayon commented
Thanks @duck8823 this is great! 🚀

2017-03-22 17:28 UTC, merged