Add feature to set env variables on Fastfile
fastlane/fastlane pull request #8577
Opened 2017-03-19 11:48 UTC by giginet

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

Introduce new feature to set environment variables on `Fastfile`.

You can use `env` to define environment variables on DSL.

```ruby
env 'FASTLANE_TEST_ENV_GLOBAL', 'foobar'

lane :echo do
  puts 'global'
end

platform :ios do
  env 'FASTLANE_TEST_ENV_PLATFORM', 'ios'

  lane :echo do
    puts 'ios'
  end
end

platform :android do
  env 'FASTLANE_TEST_ENV_PLATFORM', 'android'

  lane :echo do
    puts 'android'
  end
end
```

### Motivation and Context

If we want to set environment variables, we should use `before_all`.

```ruby
before_all do
  ENV["FASTLANE_HIDE_CHANGELOG"] = "1"
end
```

It is not readable.
For example, you can set the environment variable like following.

```ruby
env 'FASTLANE_HIDE_CHANGELOG', '1'
```

2017-03-20 15:10 UTC, mfurtak commented
This is an interesting idea. 👍  What happens if someone uses `env` inside of a lane?

2017-03-20 21:00 UTC, KrauseFx requested changes
Great idea, I added some comments. Also this needs to be documented somewhere too, where do you think is the best spot to so?

2017-03-20 21:00 UTC, KrauseFx commented on fastlane/lib/fastlane/fast_file.rb
> +      @runner.add_env(self.current_platform, name, value)
Should we do some input verifications here? Maybe define `env` with no parameters and print out an error that tells the user how to provide parameters?

2017-03-20 21:00 UTC, KrauseFx commented on fastlane/lib/fastlane/runner.rb
> +            ENV[name] = key
Let's also `UI.verbose` the `name` and `key` so that in verbose mode the user can see that the environment variable is being set 👍

2017-03-20 21:00 UTC, KrauseFx commented on fastlane/spec/fixtures/fastfiles/FastfileEnv
> +end
I'd love to have the tests also cover the case where the user adds the `env` call inside a lane

2017-03-29 01:36 UTC, KrauseFx commented
Hey @giginet, I was just talking with @mfurtak that we really like this change, let us know when you had some time to update the PR 👍 Thanks

2017-03-29 01:36 UTC, KrauseFx commented
If you want, I can write the documentation for it 👍

2017-05-01 19:06 UTC, KrauseFx commented
Hey @giginet, what's the status on this PR? Do you want me to write the documentation for this feature, or do you do it? 👍

2017-05-01 20:42 UTC, KrauseFx commented
Also, did you have time to address `What happens if someone uses env inside of a lane?` by @mfurtak?

2017-05-25 21:52 UTC, KrauseFx commented
I'll close this PR for now, but feel free to re-open whenever you're ready 👍

2017-05-25 21:52 UTC, closed without merging