Fix actions install on device
fastlane/fastlane pull request #8582
Opened 2017-03-20 02:42 UTC by rafaelsachetto

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Escape ipa path to compile using ios-deploy at action install on device

### Motivation and Context
My app name consists of two words and it was necessary to escape the same to use the function (action) install on device

2017-03-20 08:50 UTC, giginet requested changes
Thank you contribution.

Your suggestion is good. however, some codes should be fixed.

2017-03-20 08:50 UTC, giginet commented on fastlane/lib/fastlane/actions/install_on_device.rb
> +          params[:ipa].gsub(/ /, '\ ')
Use `shellescape` instead

`params[:ipa].shellescape`

2017-03-20 08:50 UTC, giginet commented on fastlane/lib/fastlane/actions/install_on_device.rb
> +          params[:ipa].gsub(/ /, '\ ')
`ipa` param seems to be optional.

So you have to check nil.

https://github.com/fastlane/fastlane/pull/8582/files#diff-cec084ffdd8e2b1d290fbc3ba9bacb06R55

2017-03-20 08:50 UTC, giginet commented on fastlane/spec/actions_specs/install_on_device_spec.rb
> +        expect(result).to eq("ios-deploy  --bundle demo\\ app.ipa")
Why does it have two spaces?

I think this behavior is strange. it should be fixed.

2017-03-20 14:57 UTC, rafaelsachetto commented on fastlane/lib/fastlane/actions/install_on_device.rb
> +          params[:ipa].gsub(/ /, '\ ')
But it is not, it will always pass the bundle once it is needed for compilation.

2017-03-20 15:00 UTC, rafaelsachetto commented on fastlane/spec/actions_specs/install_on_device_spec.rb
> +        expect(result).to eq("ios-deploy  --bundle demo\\ app.ipa")
I tried to solve this "problem" but I saw that it would be an unnecessary disorder. Feel free to settle.

2017-03-20 18:26 UTC, KrauseFx commented on fastlane/lib/fastlane/actions/install_on_device.rb
> +          params[:ipa].gsub(/ /, '\ ')
Please replace this with shellescape as instructed by @giginet 👍

2017-03-20 20:24 UTC, KrauseFx approved these changes
Thanks for the pull request and also adding a test 👍

2017-03-20 20:24 UTC, KrauseFx commented on fastlane/spec/actions_specs/install_on_device_spec.rb
> +        expect(result).to eq("ios-deploy  --bundle demo\\ app.ipa")
It seems like the double space issue is not related to this PR, but has something to do with a `nil` value in `params[:extra]`, maybe something that should be fixed in a separate PR?

2017-03-20 20:28 UTC, rafaelsachetto commented on fastlane/spec/actions_specs/install_on_device_spec.rb
> +        expect(result).to eq("ios-deploy  --bundle demo\\ app.ipa")
@KrauseFx I have an idea how to fix, I'll create a new PR to clean this.

2017-03-21 05:16 UTC, giginet approved these changes

2017-03-21 18:21 UTC, merged

2017-03-21 18:21 UTC, KrauseFx commented
Looks great, thanks @rafaelsachetto 👍