Add custom error handling for react-native projects with no bundle identifier set
fastlane/fastlane pull request #8605
Opened 2017-03-22 00:42 UTC by KrauseFx

This PR also moves out 2 method calls that shouldn't be part of the `begin rescue` block

2017-03-22 01:59 UTC, mfurtak commented
It would be good to have tests to cover this new functionality, and ensure it stays working :+1:

2017-03-24 00:55 UTC, KrauseFx commented
@mfurtak added tests for the 2 cases I added in this PR 👍

2017-03-24 01:55 UTC, giginet commented on fastlane/lib/fastlane/setup/setup_ios.rb
> +      ask_for_apple_id
Why did you move them from inside `begin` block?

2017-03-24 05:04 UTC, KrauseFx commented on fastlane/lib/fastlane/setup/setup_ios.rb
> +      ask_for_apple_id
Because we don't access iTunes Connect or the Dev Portal at this point yet, so it's better ot not be inside the `begin`, see also the PR body 👍

2017-03-24 06:10 UTC, giginet approved these changes

2017-03-24 10:22 UTC, mfurtak requested changes
Looking good! Just a few small things, then we can :ship:!

2017-03-24 10:22 UTC, mfurtak commented on fastlane/lib/fastlane/setup/setup.rb
> +        UI.important("Detectedj react-native app. To set up fastlane, please run")
Typo in "Detected"

2017-03-24 10:22 UTC, mfurtak commented on fastlane/lib/fastlane/setup/setup_ios.rb
> +      return unless File.exist?(package_json)
I think it would be better if this method always returned `true` or `false`, instead of sometimes returning `nil`, for these checks. :+1:

2017-03-24 14:42 UTC, KrauseFx commented on fastlane/lib/fastlane/setup/setup_ios.rb
> +      return unless File.exist?(package_json)
Ah, great point 👍

2017-03-24 21:40 UTC, KrauseFx commented
@mfurtak Addressed the feedback 👍

2017-03-24 21:41 UTC, KrauseFx commented
Also resolved merge confclits

2017-03-25 01:58 UTC, mfurtak approved these changes
👍

2017-03-25 02:09 UTC, merged