allow to provide required info for beta review
fastlane/fastlane pull request #8614
Opened 2017-03-22 15:46 UTC by SAVeselovskiy

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Description

New option for pilot action, that allows to provide required contact information for testflight beta review. Now you can call pilot as follows:
```
pilot(changelog: testflight_changelog,
      beta_app_description:appDescription,
      distribute_external: true,
      beta_app_feedback_email: "mail@gmail.com",
      review_contact_info: {
         review_first_name: "MyTestAccount",
         review_last_name: "MyTestAccount",
         review_phone_number: "+12345678901",
         review_contact_email: "mail@gmail.com"
      })
```
### Motivation and Context

Pilot raise error when trying to submit new build for testflight beta app review without required contact information. Issue #7085 

https://github.com/fastlane/fastlane/issues/7085

I tested my changes on my application by executing fastlane action. Now iTC doesn't raise error. When i run `bundle exec rspec` on fastlane right after git clone it raises error ```Scan Scan::DetectValues Xcode config handling fetches the path from the Xcode config
     Failure/Error: expect(derived_data).to match(%r{/.*Xcode/DerivedData/app-\w*$})```. But there is no changes yet. After editing files i get the same error. I think it's not about my changes.

2017-03-22 15:52 UTC, SAVeselovskiy commented
I signed it!

2017-03-22 16:15 UTC, SAVeselovskiy commented
Can't find out how to fix this CircleCI error
![2017-03-22 19 14 24](https://cloud.githubusercontent.com/assets/7031311/24208121/d6f66f38-0f33-11e7-9f46-049e5fed7c40.png)

2017-03-23 01:02 UTC, pav1790 commented
These changes are incomplete for someone using Spaceship. Please add the following three build_info : reviewUserName, reviewPassword, reviewAccountRequired.  
[  reviewAccountRequired = true when length(reviewUserName > 0 ) && length(reviewPassword) > 0  ]

2017-03-23 20:30 UTC, ohayon commented
@SAVeselovskiy thanks for the PR! Would you mind adding some tests? 👍 🐙

2017-03-24 00:23 UTC, KrauseFx requested changes
Hey @SAVeselovskiy, thanks for taking the time to submit this PR, that's an extremely useful feature for _pilot_ as part of _fastlane_, great job! 

Have you tested this locally on your machine for some of your apps? As @ohayon mentioned, we'd need at least one test case covering this new feature, so that we ensure it keeps working in the future.

Thanks for all this ❤️

2017-03-24 00:23 UTC, KrauseFx commented on pilot/lib/pilot/options.rb
> +                                     env_name: "PILOT_BETA_APP_CONTACT_REVIEW_LAST_NAME",
This shouldn't be called `LAST_NAME`

2017-03-24 00:23 UTC, KrauseFx commented on pilot/lib/pilot/options.rb
> +                                     description: "Provide the beta app contact information review_last_name when uploading a new build to beta review"),
This line would need some more information on how and what data to provide 👍

2017-03-24 00:23 UTC, KrauseFx commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +          firstName: {
Why do we have so many white space changes here?

2017-03-24 00:25 UTC, KrauseFx commented
Mh, the failure is weird, can you try pushing another commit and see if that works? Seems like Circle can't find your commit

2017-03-26 11:36 UTC, giginet commented on pilot/lib/pilot/options.rb
> +                                     short_option: "-y",
What do it mean `-y`?

2017-03-26 11:38 UTC, giginet commented on pilot/lib/pilot/options.rb
> +        FastlaneCore::ConfigItem.new(key: :review_contact_info,
you should add `type` parameter.

`type: Hash,`

2017-04-22 11:51 UTC, KrauseFx commented
It seems like this needs to be re-written to work with the latest iTunes Connect, right? 😢

2017-05-01 19:04 UTC, KrauseFx commented
Yeah, unfortunately, we have to close this PR, as it conflicts with our other recent changes to TestFlight.

2017-05-01 19:04 UTC, closed without merging

2017-05-01 19:04 UTC, KrauseFx commented
Thanks for your contribution @SAVeselovskiy, feel free to fork the current `master` branch and apply the changes there, if necessary