Do not change or generate README.md after running rspec
fastlane/fastlane pull request #8629
Opened 2017-03-23 18:42 UTC by nafu

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

Do not change or generate README.md after running rspec.
If anybody knows better way for handling this, please feedback to this PR. 🙏 

### Motivation and Context

After running rspec, it generates some README.md on my machine that is not needed without this patch.

2017-03-24 00:12 UTC, KrauseFx requested changes
I noticed those files too, and thought it's related to my machine somehow. Instead of adding those workarounds, can we just not generate those files at all instead? Maybe just mock the method that writes out the file?

2017-03-24 00:12 UTC, KrauseFx commented on fastlane/spec/cli_tools_distributor_spec.rb
> +      `git checkout fastlane/README.md`
That seems like a hack, can we just not generate the file in the first place instead?

2017-03-24 00:12 UTC, KrauseFx commented on fastlane/spec/commands_generator_spec.rb
> +    FileUtils.rm(File.join(fastlane_folder, 'README.md'))
Same here

2017-03-24 00:12 UTC, KrauseFx commented on fastlane/spec/lane_manager_spec.rb
> +          allow(FastlaneCore::FastlaneFolder).to receive(:path).and_return(fastlane_folder)
Same here

2017-03-24 00:59 UTC, KrauseFx commented on fastlane/spec/commands_generator_spec.rb
> +    allow(FastlaneCore::Env).to receive(:truthy?).with('FASTLANE_SKIP_DOCS').and_return(true)
Should we set this for all tests inside the spec_helper?

2017-03-24 00:59 UTC, nafu commented on fastlane/spec/cli_tools_distributor_spec.rb
> +      allow(FastlaneCore::Env).to receive(:truthy?).with('FASTLANE_SKIP_DOCS').and_return(true)
There is 3 duplication codes, so it is better to define helper in `fastlane_core/spec/spec_helper.rb` or `fastlane/spec/spec_helper.rb`?

2017-03-24 01:05 UTC, nafu commented on fastlane/spec/commands_generator_spec.rb
> +    allow(FastlaneCore::Env).to receive(:truthy?).with('FASTLANE_SKIP_DOCS').and_return(true)
Yes 👍

2017-03-24 01:11 UTC, nafu commented on fastlane/spec/commands_generator_spec.rb
> +    allow(FastlaneCore::Env).to receive(:truthy?).with('FASTLANE_SKIP_DOCS').and_return(true)
@KrauseFx Uhh, no after all. I tried to define these in spec_helper, and it had other problems to cause test failure.

2017-03-26 10:01 UTC, giginet requested changes
I think this solution is strange.

You should not stub this environment variables.

It's natural to skip executing DocsGenerator.run in testing.

https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/fastlane/lib/fastlane/lane_manager.rb#L64-L64

```
Fastlane::DocsGenerator.run(ff) if !Helper.test? && !FastlaneCore::Env.truthy?("FASTLANE_SKIP_DOCS")
```

2017-03-28 13:03 UTC, nafu commented
Hmm, CircleCI select Xcode 7.0 😓 

![image](https://cloud.githubusercontent.com/assets/932290/24406116/35d7004e-1402-11e7-8048-19d0c2b52ee1.png)


https://circleci.com/gh/fastlane/fastlane/8447

2017-03-29 00:43 UTC, nafu commented
@KrauseFx @giginet 
I addressed the feedbacks, could you review again?

2017-03-29 00:51 UTC, KrauseFx approved these changes
Looks great :+1: Thanks @nafu

2017-03-30 17:40 UTC, giginet approved these changes

2017-03-30 17:41 UTC, giginet commented
@nafu Sorry for my late reply.
You can merge it 😄

2017-04-01 05:44 UTC, nafu commented
@KrauseFx @giginet Thanks 🚀

2017-04-01 05:44 UTC, merged