Add custom error message when receive an internal server error
fastlane/fastlane pull request #8696
Opened 2017-03-29 02:29 UTC by KrauseFx

Unfortunately I couldn't find a way to test this. I did receive the following stack traces:

**error message (body)**
```
**<HTML><HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD><BODY>
<H1>Internal Server Error - Read</H1>
The server encountered an internal error or misconfiguration and was unable to
complete your request.<P>
Reference&#32;&#35;3&#46;7a6533b8&#46;1490604875&#46;742473b8
</BODY></HTML>
```
**stack trace**
```
fastlane-2.19.3/spaceship/lib/spaceship/client.rb:453:in 
fastlane-2.19.3/spaceship/lib/spaceship/tunes/tunes_client.rb:339:in 
fastlane-2.19.3/spaceship/lib/spaceship/tunes/app_version.rb:183:in 
fastlane-2.19.3/spaceship/lib/spaceship/tunes/application.rb:111:in `edit_version'
```

I'd be ok with merging this without having a way to reproduce this locally, and see if that fixes the issue, and see if still get people reporting this issue. 

By showing a more clear error message, it should make sense for the user that the issue isn't related to their setup, but has something to do with the web-services.

2017-03-29 02:34 UTC, mfurtak requested changes
We should make a different custom error type to represent a 500 response. This is different than a timeout error, IMO.

2017-03-29 02:35 UTC, KrauseFx commented
Okay, besides that the change would be ok from your side?

2017-03-29 02:35 UTC, KrauseFx commented
I was surprised to see that we didn't have a TemporaryServerError yet

2017-03-29 02:45 UTC, mfurtak commented
Yep, fine with me otherwise :+1: timeout just feels too specific

2017-03-29 02:45 UTC, mfurtak approved these changes

2017-03-30 01:36 UTC, KrauseFx commented
@mfurtak I added the custom error type 👍

2017-03-30 03:06 UTC, mfurtak commented
:+1:

2017-03-30 19:52 UTC, merged