[frameit] Added font_height_factor
fastlane/fastlane pull request #8703
Opened 2017-03-30 04:16 UTC by chandlerhuff

Added `font_height_factor` that allows the title and keyword heights to be a set value so that the devices line up across shots of the same device. Should fix #6116.

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description
Added `font_height_factor` which if defined in the config uses a factor of the calculated font size as the text height instead of calculating the text height which makes the text height equal across all shots of the same device.

### Motivation and Context
If a title that has a lower case g/q/y/j or some other characters is used in one shot but not in another 
 even when using `font_scale_factor` to ensure the same font sizes it results in the example below where the devices don't line up like in issue #6116.
 
![example](https://cloud.githubusercontent.com/assets/701665/24487358/fa257d4c-14dc-11e7-81a6-bc00ae3b8ea0.png)

2017-03-30 13:30 UTC, ohayon requested changes
Hey @chandlerhuff this is a great fix. Just a little question about rubocop. 🚀

2017-03-30 13:30 UTC, ohayon commented on frameit/lib/frameit/config_parser.rb
> +    # rubocop:enable Metrics/PerceivedComplexity
Is there anything we can do to avoid having to disable rubocop around here?

2017-03-30 13:49 UTC, chandlerhuff commented on frameit/lib/frameit/config_parser.rb
> +    # rubocop:enable Metrics/PerceivedComplexity
@ohayon I don't think so adding the additional switch case increased the complexity to 19.

2017-03-31 02:45 UTC, closed without merging

2017-04-05 10:53 UTC, AndriyGo commented
Is there any chance this feature could find its way into _frameit_? I am facing the exact same problem and I think that the lack of fixed height titles is really bad. If we look at the screenshots of the best apps for iOS they all have devices positioned at exactly the same spot regardless of the text in them.