[gym] hard error on xcode 8.3 with legacy api
fastlane/fastlane pull request #8747
Opened 2017-04-03 06:39 UTC by hjanuschka

hard error if xcode >= 8.3 is used and `use_legacy_build_api` is set.

error message modeled after this https://github.com/fastlane/fastlane/issues/8672#issuecomment-290544806

2017-04-03 08:01 UTC, nafu commented
These changes are not enough?
https://github.com/fastlane/fastlane/pull/8692 https://github.com/fastlane/fastlane/pull/8717

2017-04-03 09:35 UTC, hjanuschka commented
@nafu  they only trigger on packaging errors, not if for example an ipa is uploaded and later on rejected on apple servers. - i think we should start (with 8.3) to hard disallow legacy api, to protect users from following errors, and therefore keeping issue impact low.

2017-04-03 21:19 UTC, KrauseFx commented on gym/lib/gym/options.rb
> +      UI.important "If you run into a code signing error, please check out our troubleshooting guide and common issue and how to solve them."
Should be

> If you run into a code signing error, please check out our troubleshooting guide for more information on how to solve the most common issues

2017-04-03 21:20 UTC, KrauseFx requested changes
This is a great change for sure, could you add a test for this too? Just that `use_legacy_build_api` causes a user error. Should be simple to add 👍

2017-04-04 07:50 UTC, hjanuschka commented on gym/lib/gym/options.rb
> +      UI.important "If you run into a code signing error, please check out our troubleshooting guide and common issue and how to solve them."
done

2017-04-04 07:50 UTC, hjanuschka commented
@KrauseFx  spec's added

2017-04-04 22:09 UTC, KrauseFx approved these changes
Looks great, one small things, and feel free to merge. Thank you ❤️

2017-04-04 22:09 UTC, KrauseFx commented on gym/lib/gym/options.rb
> +                                         Gym::Options.legacy_api_note
At fastlane very often we use `method_name!` with a `!` to clarify that this is either modifying the object, or raising an exception if something goes wrong, could you rename the method?

2017-04-05 07:42 UTC, merged

2017-04-05 09:42 UTC, nafu commented
Nice! 🚀