Bump podspec version fix
fastlane/fastlane pull request #8762
Opened 2017-04-03 21:42 UTC by Antondomashnev

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ x I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
The change is a update of regex in `VersionBumpPodspec` action to support non semantic versions such as `1.2.3.4.5`. The more detailed description is given here #8722 

### Motivation and Context
It solves the problem of setting a new version of Podspec while the previous version was not a semantic. 

The linked issue is #8722 

The spec was updated to test the action against a not semantic version.

2017-04-03 21:44 UTC, Antondomashnev commented
I signed it!

2017-04-04 14:17 UTC, ohayon requested changes
Hey @Antondomashnev, this is a great PR! Thanks for adding/modifying all of the tests! One question: Should we have a test for bumping the newly-added `appendix` number as well?

2017-04-04 17:44 UTC, Antondomashnev commented
> Should we have a test for bumping the newly-added appendix number as well?

Hey, @ohayon thanks for the review it's a good point, but I'm not sure if this is a valuable addition. Because `appendix` is supposed to be any suffix from in version after the `PATCH` part. So imagine the edge case example: `1.2.3.4.5.6` and here appendix is `4.5.6`, to my mind the developer will unlikely decide to change it or if she wants eventually I think it's easier to just set the version instead of bump. Don't you agree? 😄

2017-04-04 18:04 UTC, ohayon commented
@Antondomashnev I do agree for sure, but I also think that because we are exposing the appendix in the regex, we should make sure that if someone does try to do it programmatically that they are successful, maybe its less of a "bump" and more of a setting of the appendix. Curious to hear your thoughts! 🐙

2017-04-04 19:11 UTC, Antondomashnev commented
@ohayon I'm afraid if we eventually make it's less clear for the developers if it's not there yet 😄 
What if we add an exception when you want to `bump` an `appendix` and add an additional method to set an `appendix`?

2017-04-05 15:39 UTC, ohayon commented
@Antondomashnev thats a great idea! 🚀

2017-04-05 18:14 UTC, Antondomashnev commented
@ohayon you can check, now we have a `set_version_appendix` which basically allows a developer to change appendix, but it was developed with the `bump_version` logic in mind, so the developer has to call `update_podspec` to apply changes. It seems better now 😉

2017-04-05 19:12 UTC, ohayon approved these changes

2017-04-05 19:31 UTC, merged

2017-04-05 19:31 UTC, ohayon commented
Thanks for the PR @Antondomashnev, this is great!