Add nice error message when crashlytics action can't find its .framework
fastlane/fastlane pull request #8807
Opened 2017-04-07 01:21 UTC by KrauseFx

This happened when the user didn't have Crashlytics set up for their app

<img width="1001" alt="screen shot 2017-04-06 at 6 19 41 pm" src="https://cloud.githubusercontent.com/assets/869950/24781623/c8b91092-1af5-11e7-9f58-451d1ff8af63.png">

2017-04-07 01:26 UTC, ohayon approved these changes
Just switch up the file name and then 🚀

2017-04-07 01:26 UTC, ohayon commented on fastlane/lib/fastlane/helper/crashlytics_helper.rb
> +            UI.user_error!("Couldn't find Crashlytics.framework in current directory. Make sure to add the 'Crashlytics' pod to your 'Gemfile' and run `pod update`")
`Podfile` instead of `Gemfile` right?

2017-04-07 01:27 UTC, KrauseFx commented on fastlane/lib/fastlane/helper/crashlytics_helper.rb
> +            UI.user_error!("Couldn't find Crashlytics.framework in current directory. Make sure to add the 'Crashlytics' pod to your 'Gemfile' and run `pod update`")
Yess, nice catch 👍

2017-04-07 01:57 UTC, mfurtak approved these changes

2017-04-07 02:44 UTC, ohayon requested changes

2017-04-07 02:44 UTC, ohayon commented on fastlane/lib/fastlane/helper/crashlytics_helper.rb
> +            UI.user_error!("Couldn't find Crashlytics.framework in current directory. Make sure to add the 'Podfile' pod to your 'Gemfile' and run `pod update`")
Change `Podfile` to `Crashlytics` and `Gemfile` to `Podfile` 😄

2017-04-08 00:28 UTC, KrauseFx commented on fastlane/lib/fastlane/helper/crashlytics_helper.rb
> +            UI.user_error!("Couldn't find Crashlytics.framework in current directory. Make sure to add the 'Podfile' pod to your 'Gemfile' and run `pod update`")
ok, I was definitely too tired to code yesterday. I'll try my best to do it right this time

2017-04-09 21:55 UTC, ohayon approved these changes

2017-04-09 23:04 UTC, merged