Infinite loop on deliver
fastlane/fastlane pull request #8827
Opened 2017-04-08 17:18 UTC by 0x5e

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Raise error when multiple iTunes Connect teams found, request to choose one, but running in non-interactive shell.

### Motivation and Context
Fix #8824

2017-04-08 18:39 UTC, KrauseFx requested changes

2017-04-08 18:39 UTC, KrauseFx commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        raise "Running in non-interactive shell" if UI.interactive? == false
I very much like the intent of this PR, however _spaceship_ doesn't have access to `FastlaneCore::UI`, as they're in separate subfolders, at least until now. Definitely something we could change, as we'd also need this for `credentials_manager`, at both points we don't fail the build if it's not interactive.

2017-06-13 20:56 UTC, ohayon requested changes

2017-06-13 20:56 UTC, ohayon commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        raise "Running in non-interactive shell" if UI.interactive? == false
a `UserInterface` class has been added to _spaceship_ so you can change this line to be 
```
raise  "Running in non-interactive shell" unless UserInterface.interactive?
```

2017-06-14 20:50 UTC, ohayon commented
For some reason this PR is failing in CI but not locally. I am going to push something else up just to force another build because hitting rebuild on Circle is not seeming to work.

2017-06-16 08:46 UTC, lacostej requested changes
We should fix it in both places

2017-06-16 08:46 UTC, lacostej commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        raise "Running in non-interactive shell" unless UI.interactive?
We have the same problem under spaceship/lib/spaceship/portal/ui/select_team.rb

2017-06-16 08:58 UTC, lacostej commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        raise "Running in non-interactive shell" unless UI.interactive?
and there the `interactive?` is redefined

2017-06-16 15:14 UTC, ohayon commented on spaceship/lib/spaceship/tunes/tunes_client.rb
> +        raise "Running in non-interactive shell" unless UI.interactive?
Good call @lacostej! I didnt realize we had most of this in two places.

2017-07-31 15:20 UTC, ohayon commented
Hey @0x5e - wanted to bump this PR to see if you had a chance to look at the comments on here. Let us know if there is anything we can help with!

2017-08-01 02:55 UTC, 0x5e commented
@ohayon  I left my company several month ago, now I don't have code & enviroment to test with. Really sorry about this.😔

2017-08-07 20:21 UTC, KrauseFx commented
Migrated over to https://github.com/fastlane/fastlane/pull/9981 👍 Thanks again @0x5e for your contribution ❤

2017-08-07 20:21 UTC, closed without merging