change `push_to_git_remote` default tag flag to `false`
fastlane/fastlane pull request #8888
Opened 2017-04-14 05:37 UTC by d-date

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
the default `tags` parameter which is one of the `push_to_git_remote` was changed from `true` to `false`.

### Motivation and Context

Sometimes `push_to_git_remote` is used for version bumping to upload adhoc binary to Fabric/Crashlytics with different build version. But when run `push_to_git_remote` with no option, the `tag` will be pushed automatically for remote. It causes action failed when same tag is already exist on remote repo, and It's difficult to notice the `tag` option is false on default for beginners.

You can check this change on running `push_to_git_remote` with no `tags` parameter.

2017-04-14 07:22 UTC, hjanuschka requested changes
hey 🤚 
thx for your contribution, and nice catch, however i think we cannot simply change a default parameter - as it may break or lead to unexpected behaviour on users already using this action.

do you see any other solution, like catching the error and printing a nice description text on how to solve it by setting the value of `tags`  to `false`?

2017-04-14 07:51 UTC, d-date commented
@hjanuschka 
Hi 😀
Thank you for your comment, and I see your point.
I think it is natural with no tag pushing and it is happened no error with no tag pushing,
so how about notify to user who is no using `tags` param like below?

```
"[Info] When you want to push to git with tag,`push_to_git_remote` requires `tags: true` on your Fastfile from v2.xx.x." 
```
 (I'm Japanese and not good at English, so if you have better comment, please tell me.)

2017-04-14 08:21 UTC, giginet reviewed
I have no idea that should we modify default behavior 🤔 

I think we can merge this as long as we inform this changes.

2017-04-14 08:21 UTC, giginet commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> +                                       description: "Wether tags are pushed to remote. Defaults to false",
I found typo 👀 

`Whether`.

2017-04-14 08:35 UTC, d-date commented on fastlane/lib/fastlane/actions/push_to_git_remote.rb
> +                                       description: "Wether tags are pushed to remote. Defaults to false",
@giginet thx, so I made another PR. https://github.com/fastlane/fastlane/pull/8889

2017-04-14 08:40 UTC, d-date commented
@hjanuschka  @giginet OK. Thank you for your review, so I'll show messege for user who are using `tags` as default. 

```
"[INFO] If you don't want to push with tag, please specify `tags` to `false` on your Fastfile."

Then, we should discuss about default behavior on issue (I'll make it later)

How about this one?

2017-04-14 08:41 UTC, giginet commented
@KrauseFx How do you think about?

2017-04-14 08:52 UTC, nafu requested changes
Thank you @d-date for contribution 👋 

The default behaivior of tags is at least before monorepo.
Changing the default behavior has big impact on existing users.

I think it would  be better to

1. Output message to inform 'tags: false' if tags error occur (same as @hjanuschka said)
2. Push again with 'tags: false' if the user want

2017-04-14 09:01 UTC, hjanuschka commented
@nafu but keep in mind that "if user wants" needs to be a solution that works even if the user does not have a interactive terminal (e.g: CI)

2017-04-14 09:16 UTC, nafu commented
@hjanuschka Rightt 👍

2017-04-14 18:11 UTC, KrauseFx requested changes
I'm also skeptical on changing the default behavior, we should try to avoid this. I'd be ok with showing a message when the command fails that the parameter is available 👍

2017-04-15 02:04 UTC, d-date commented
@KrauseFx @hjanuschka @nafu @giginet
OK. Thank you for your comment.
I'lol try to show message💪

2017-06-13 16:12 UTC, ohayon commented
Hey @d-date, wanted to check in on the status of this PR, it looks like there was a merge commit that caused a lot of files to change that are not relevant to your change. Would you mind cleaning that up so it is just your change and that way we can have a more clear discussion and decide if it should be merged? Thanks! 🚀 🐙

2017-07-03 07:55 UTC, KrauseFx commented
Hey @d-date, thanks for your contribution 👍  I'll close the PR for now, as there are some changes included that probably shouldn't be part of this PR. Feel free to submit a new PR any time ❤️

2017-07-03 07:55 UTC, closed without merging