[match] add `disable_encryption` option to skip encryption
fastlane/fastlane pull request #8919
Opened 2017-04-19 19:00 UTC by hjanuschka

when used with many many app's 1000+ match seems to be slow - and git repo's grow way to much - per run.

for the normal user this should never be used, but from a enterprise point of view - it seems to be a requirement to atleast have the option to turn off encryption.

Related: #8793 and #8917

2017-04-20 02:16 UTC, KrauseFx commented
Interesting... before doing that, we should ask the user that reported the problem with the repo size if that would be a feasible solution to them, and if they'd use it.

2017-04-20 08:31 UTC, adamtester commented
@hjanuschka nice!
@KrauseFx for us, it would be fine, however large corporate companies would probably not be allowed to use it

I'll test it today and see how well it works and report back!

2017-04-20 12:31 UTC, hjanuschka commented
@adamtester thx for testing *BUT PLEASE KEEP IN MIND TO DO A BACKUP OF YOUR REPO BEFORE*

2017-04-21 16:42 UTC, adamtester commented
Looks good, didn't test on the CI server but created a similar setup on my mac and used a copy of the certificates repo.

2017-04-25 14:26 UTC, GandjaFuzz commented
When release?

2017-05-02 05:42 UTC, hjanuschka commented
@KrauseFx you see a chance of this getting merged?

2017-05-02 08:03 UTC, KrauseFx requested changes

2017-05-02 08:03 UTC, KrauseFx commented on match/lib/match/options.rb
> +                                     description: "Disable encryption, certificates including keys and profiles won't be encrypted! be sure that your git repo is safe!",
`Be` should be upper case. Could you extend the description to mention here that this can't be changed once _match_ is set up?

2017-05-02 08:03 UTC, KrauseFx commented on match/lib/match/options.rb
> +                                     description: "Disable encryption, certificates including keys and profiles won't be encrypted! be sure that your git repo is safe!",
In general, I'm wondering if we can show an error message if you run _match_ without encryption, but for an encrypted repo, and the other way around. How does _match_ currently behave in that situation?

2017-05-02 11:41 UTC, hjanuschka reviewed
@KrauseFx typo's fixed.
and i added a way to detect encryption state and print out notice's if run is impossible due to encryption enabled or disabled.

also added specs for this. and updated PR body to provide a sample to test this pr without destroying a real repo 👍

2017-05-02 17:31 UTC, KrauseFx commented on match/lib/match/git_helper.rb
> +        if GitHelper.crypted?(@dir) && disable_encryption == true
Why the `== true`?

2017-05-02 17:31 UTC, KrauseFx commented on match/lib/match/git_helper.rb
> +        if !GitHelper.crypted?(@dir) && disable_encryption == false
Why the `== false` instead of `!disable_encryption`

2017-05-02 17:33 UTC, KrauseFx commented on match/lib/match/git_helper.rb
> +      UI.user_error!("remote_encrypted")
`Encryption disabled, but remote repository is currently encrypted`

2017-05-02 17:34 UTC, KrauseFx submitted a review, later dismissed

2017-05-02 17:34 UTC, KrauseFx commented on match/lib/match/git_helper.rb
> +    def self.crypted?(workspace)
`encrypted?`

2017-05-09 23:35 UTC, GandjaFuzz commented
Do we guys ever see a release?)) Git grows very very much

2017-05-10 07:55 UTC, KrauseFx commented
Hey @GandjaFuzz, we're working on it, but first we want to be sure everything works perfectly 👍 
@hjanuschka Thanks for updating the PR so fast. There is 2 more comments from my side above that need to addressed before we can merge 🚀  Thanks

2017-05-10 12:33 UTC, hjanuschka commented
@KrauseFx for whatever reason i missed the comments, changes made - thx!

2017-05-25 23:38 UTC, GandjaFuzz commented
=)

2017-05-26 02:49 UTC, taquitos reviewed
This looks great to me. I'd like one more person to review, though, as I'm not as familiar with this code. 
Great job at catching all the complexities around migration! 🥇

2017-05-26 08:07 UTC, hjanuschka commented
@taquitos thx, at first i thought we should ship the migration code, but i guess its to much code to maintain further on - and too large regression surface..

2017-06-11 17:54 UTC, GandjaFuzz commented
up

2017-06-13 17:26 UTC, ohayon requested changes
This is great @hjanuschka! I would still love to get @KrauseFx's 👀  on here one more time before merging. I left a bunch of comments mostly about spelling and some style. Looking forward to hearing your thoughts and getting this merged in!

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/encrypt.rb
> +    def no_encryption_note
nitpick: Can this be called something like `show_no_encryption_note`?

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +      end
This method is pretty long with a lot of special cases, could we extract some stuff out into separate, methods that could be tested? That might also allow us to remove the rubocop perceived complexity warning suppression as well.

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +        # repo is crypted but user requested to run match in disabled_encryption mode
"repo is *en*crypted"

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +        # repo is not crypted, but match is run with enabled encryption
"*en*crypted"

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +          UI.user_error!("remote_decrypted")
Can we just call `UI.user_error!" here with the message above?

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +      UI.user_error!("remote_encrypted")
I think the message can just be put into this `UI.user_error!` call.

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +      path = File.join(workspace, "match_crypted.txt")
Could this file be called `match_encrypted.txt`?

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +      is_crypted = File.read(path).chomp
`is_encrypted`

2017-06-13 17:26 UTC, ohayon commented on match/lib/match/git_helper.rb
> +        File.write("match_crypted.txt", (!disable_encryption).to_s)
`match_encrypted.txt`

2017-06-22 07:43 UTC, GandjaFuzz commented
up

2017-09-14 22:20 UTC, dtweston commented
@hjanuschka: Is there any help I can offer to get this PR finished up?

2017-09-19 10:01 UTC, KrauseFx commented
Okay okay, hey everybody, we'll talk more about this, since this is a problem we'll have to fix. Instead of disabling encryption all-together, maybe it makes more sense to just don't re-encrypt all files on every run? We could easily detect what files were modified, and only encrypt those again? This way, we're fully backwards compatible, and the repo is still fully encrypted. 

What do y'all think?

2017-09-19 10:08 UTC, GandjaFuzz commented
That sounds good

2017-09-19 20:44 UTC, GandjaFuzz commented
and need don't need decrypt and encrypt all files. need decrypt and encrypt only files needed for project. it is really make ?

2017-09-25 15:40 UTC, KrauseFx commented
Hey everyone, sounds good, I'll take on this task for this week, so I'll work on a cleaner solution that doesn't require un-encrypted repos :)

2017-10-02 17:01 UTC, closed without merging