showBuildSettings does not require to call clean
fastlane/fastlane pull request #8921
Opened 2017-04-19 21:09 UTC by punty

### Checklist
- [x ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I've updated the documentation if necessary.

### Description
In show building settings, don't call xcodebuild clean, because it's not a necessary workaround anymore. 

### Motivation and Context
This change will allow the user to do not clean the build (unless specified in the following commands). 
Previously for example event setting clean: false, will result in callling clean because of the generated  
xcodebuild clean -showBuildSettings

As stated in the comment this was a workaround for an xcodebuild bug. But this bug has being fixed in 8.3 so it's not necessary anymore. https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html
As huge benefit, I can keep using fastlane with my CI, and for example, caching pod builds, and reduce my build time significantly. 
 
This pull request also fixes https://github.com/fastlane/fastlane/issues/8099

2017-04-20 06:19 UTC, hjanuschka requested changes
🚀  looking promising, left a couple of comments
many thx for your contribution @punty

2017-04-20 06:19 UTC, hjanuschka commented on fastlane_core/spec/project_spec.rb
> +        if FastlaneCore::Helper.xcode_higher_than_8_3?
i think this should be splitted up into 2 tests. with mocked return of `xcode_atleast` on time with `false` and one time with `true`  to be sure that it works on old and new xcodes.

the current variation is depending on the local xcode installation.

2017-04-20 06:19 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/helper.rb
> +    def self.xcode_higher_than_8_3?
can we rename this to: `self.xcode_atleast?(version)`

2017-04-20 06:19 UTC, hjanuschka commented on fastlane_core/lib/fastlane_core/helper.rb
> +      Gem::Version.new(v) >= Gem::Version.new('8.3.0')
and use it here: `Gem::Version.new(v) >= Gem::Version.new(version)`

2017-04-20 06:19 UTC, hjanuschka commented on gym/lib/gym/xcode.rb
> +        FastlaneCore::Helper.xcode_higher_than_8_3?
then use `FastlaneCore::Helper.xcode_atleast?("8.3")`

2017-04-20 09:40 UTC, punty commented
@hjanuschka I implemented the changes you requested! Much better!

2017-04-20 13:05 UTC, hjanuschka commented on fastlane_core/spec/project_spec.rb
> +      unless FastlaneCore::Helper.xcode_atleast?('8.3')
can we get rid of the unless, and mock the result of xcode_atleast to 8.1?
removing the unless and turning the `allow` to an `expect` should do it, the allow should also be changed in the above test. so we always no matter which local xcode is installed verify it works on 8.1 and 8.3

or i am i wrong?

thx for your patience.

2017-04-20 13:06 UTC, hjanuschka commented
@punty awesome, looking solid 👍  thx for your work and patience, one comment left.

2017-04-20 13:14 UTC, punty commented on fastlane_core/spec/project_spec.rb
> +      unless FastlaneCore::Helper.xcode_atleast?('8.3')
I am not sure about this. According to the official Apple documentation, the XCode bug has being fixed in 8.3, so if we are running this test, by mocking the call to return true, we will end up calling showBuildSettings without the clean command (even for XCode < 8.3). So in this case there is a risk this command will hangs? 
According to Apple this happens only if the project contains Core Data. But I still think we should include test for scenarios that are not possible.

2017-04-20 13:23 UTC, punty commented on fastlane_core/spec/project_spec.rb
> +      unless FastlaneCore::Helper.xcode_atleast?('8.3')
Allow is used for Mocking, https://www.relishapp.com/rspec/rspec-mocks/v/2-14/docs/method-stubs  so when I call that method i return true or false

2017-04-20 13:24 UTC, hjanuschka commented on fastlane_core/spec/project_spec.rb
> +      unless FastlaneCore::Helper.xcode_atleast?('8.3')
the command is not really run in the tests.
`expect(FastlaneCore::Project).to receive(:run_command).with(command.to_s, { timeout: 10, retries: 3, print: false }).and_return(File.read("./fastlane_core/spec/fixtures/projects/build_settings_with_toolchains"))` mocks it.

the goal should be to test the following two scenarios.

## user has xcode < 8.3
  *  force `xcode_atleast?("8.3") ` to return `false`
  * expect the resulting command, to include `clean`

## user has xcode >= 8.3
  *  force `xcode_atleast?("8.3") ` to return `true`
  * expect the resulting command, to NOT include `clean`

by forcing the result we bypass the local installation interfering the unit test.

2017-04-20 13:26 UTC, punty commented on fastlane_core/spec/project_spec.rb
> +      unless FastlaneCore::Helper.xcode_atleast?('8.3')
thanks for the clarification. I will have a look at that!

2017-04-20 13:48 UTC, punty commented
@hjanuschka thanks again for your suggestions! I implemented the changes you requested

2017-04-20 19:27 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/helper.rb
> +    def self.xcode_atleast?(version)
`xcode_at_least?`

2017-04-20 19:27 UTC, KrauseFx commented on fastlane_core/spec/project_spec.rb
> +      it "SUPPORTED_PLATFORMS should be iphonesimulator iphoneos on XCode >= 8.3" do
`Xcode`

2017-04-20 19:27 UTC, KrauseFx submitted a review, later dismissed

2017-04-20 19:27 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/project.rb
> +      if FastlaneCore::Helper.xcode_atleast?('8.3')
Could you reference in a command on why this was added, when it was fixed, etc.

2017-04-20 20:37 UTC, hjanuschka approved these changes

2017-04-20 20:49 UTC, punty commented
@KrauseFx thanks for your feedback. I just implemented the changes you requested.

2017-04-21 17:48 UTC, merged

2017-04-21 17:49 UTC, hjanuschka commented
@punty 🚀  merged, many thx for your contribution 🎉