Fix `pilot distribute`
fastlane/fastlane pull request #9005
Opened 2017-04-26 22:45 UTC by tmm1

This makes `fastlane pilot distribute --distribute_external` work again on my app.

2017-04-26 22:49 UTC, tmm1 commented
@googlebot I signed the CLA

2017-04-26 23:11 UTC, taquitos requested changes
This is looking great so far, could you update the PR to use the PR template: https://github.com/fastlane/fastlane/blob/master/.github/PULL_REQUEST_TEMPLATE.md
I'd like to understand more about motivation, testing, etc.

2017-04-26 23:19 UTC, tmm1 commented
Sorry, but I'm not sure what else there is to say.

I encountered a bug preventing me from distributing builds and I fixed it. I provided context as to the source of the bug in my PR and commit messages.

2017-04-27 13:13 UTC, ohayon commented on pilot/lib/pilot/build_manager.rb
> +    def distribute(options, build = nil)
Would be great to change this method over to have named parameters rather than just setting the default value!

2017-04-27 15:48 UTC, taquitos approved these changes

2017-04-27 17:29 UTC, tmm1 commented on pilot/lib/pilot/build_manager.rb
> +    def distribute(options, build = nil)
Sure.

2017-04-27 17:47 UTC, ohayon commented
Thanks @tmm1 !!! 🚀

2017-04-27 17:47 UTC, merged