Provided an option to restrict fastlane version to a fixed version in addition to minimum version check
fastlane/fastlane pull request #9007
Opened 2017-04-27 09:12 UTC by karthik-krishnan

…ver and above minimum version check

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Currently we can mandate minimum version of fastlane required for the project.  However, if the teams want to be able to mandate a very specific version of fastlane in the environment, there is no way out for them.

### Description
I have now enhanced the fastlane_version action to allow an option to specific if fastlane should lock to a specific version.   For instance, instead of 

> fastlane_version 1.3

one can mention 
> fastlane_version 1.3, :lock => true

I have updated the unit tests as well.

2017-04-27 09:40 UTC, karthik-krishnan commented
I signed it!

2017-04-27 09:47 UTC, karthik-krishnan commented
Build as well as rubocop is successful locally.  How do I go about re-trigerring the build now?

2017-04-27 14:00 UTC, KrauseFx requested changes
Thanks for taking the time to submit this PR, great work. However, I don't think that's the right approach, to have more control over the _fastlane_ version, you should make use of a Gemfile, check out our [docs on how to use a Gemfile](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile) 👍  Let me know if that helps

2017-05-01 19:11 UTC, closed without merging

2017-05-02 08:35 UTC, karthik-krishnan commented
Thanks Felix.  I was also thinking to use Bundler and gemfile.lock eco
system to control the gem version treating fastlane gem like any other gem
in the environment.

On another note, I am not sure what happens with the "update_fastlane" call
inside the script.  My understanding is update_fastlane is happening inside
of the script execution context and was not sure if the subsequent script
code is running on the latest version of fastlane(which could be greater
than the gemfile.lock version)


Best regards,
Karthik Krishnan.
http://karthiks.in

On Tue, May 2, 2017 at 12:41 AM, Felix Krause <notifications@github.com>
wrote:

> Closed #9007 <https://github.com/fastlane/fastlane/pull/9007>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/pull/9007#event-1064378252>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAXe6oO74pnd4Ci2VHqBLiK9K2z3H7Baks5r1i5SgaJpZM4NJ8iN>
> .
>

2017-05-02 08:41 UTC, KrauseFx commented
If you use a Gemfile, you should probably not use the `update_fastlane` action, but run `bundle update` from time to time instead. This way your builds are reproducible 👍

2017-05-02 11:57 UTC, karthik-krishnan commented
Got it Thanks Felix.

Best regards,
Karthik Krishnan.
http://karthiks.in

On Tue, May 2, 2017 at 2:11 PM, Felix Krause <notifications@github.com>
wrote:

> If you use a Gemfile, you should probably not use the update_fastlane
> action, but run bundle update from time to time instead. This way your
> builds are reproducible 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/pull/9007#issuecomment-298558125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXe6qTAcMiRH2sFIX3FGNYaJ7a449jRks5r1uxDgaJpZM4NJ8iN>
> .
>