Enhancing app_store_build_number action’s build number sort
fastlane/fastlane pull request #9153
Opened 2017-05-12 10:30 UTC by sinoru

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I'm using build number as x.y format, and app_store_build_number doesn't support that.
So... This will fixes #1178

### Description

I use Gem::Version to sort build numbers as semver, after that it will convert to string.

2017-05-12 10:32 UTC, sinoru commented
@googlebot I signed it!

2017-05-12 19:55 UTC, hjanuschka requested changes
@sinoru many thx for your contribution, this is super awesome 🚀  ❤️ .

can you please add a spec for the action so that it verify's that normal integer build numbers are still sorted correctly.

and non semver, non-integer builds atleast not crash?

let me know if you need help on anything.

2017-05-13 00:49 UTC, sinoru commented
@hjanuschka I would be happy to add a spec for the action, but I don't know how to do with action which should get information from iTunes Connect.. I can't find any other action specs to reference...

Anyway, This must be work in normal integer build numbers which is worked with Gem::Version which is used to solving gemspecs.

And according to [apple docs](https://developer.apple.com/library/content/technotes/tn2420/_index.html#//apple_ref/doc/uid/DTS40016603-CH1-NUMBERING_CONVENTIONS) build number must be integer or/and `dot` which should compliance semver(-ish).

2017-05-13 00:59 UTC, sinoru commented
Uhm.. On the other hand, Combination of `latest_testflight_build_number` + `increment_build_number` which will call `app_store_build_number` may be has issue due to now it returns string than integer.
e.g:
```ruby
increment_build_number({
  build_number: latest_testflight_build_number + 1
})
```

Should I return as integer if it can representable in integer, and otherwise return as string?

2017-05-13 17:35 UTC, hjanuschka commented
yeah this is why i thought a spec for the change would help.

i am right now using sorta this code on all my production apps.:

```
   last_tf = latest_testflight_build_number
   increment_build_number(build_number: last_tf + 1)
```


i have the following concerns:

  * return type should be INTEGER - otherwise current setups will definitily break, and i bet most of the users use integer based build numbers instead of semver style. so the regression seems to be not worth it.

  *  we'd need to find a way to convert a semver string (according to docs the simple ones like `x.y.z`- without the full semver features like `build` etc..) into a reliable integer? 


  * verify - via spec - that sorting with the help of `Gem::Version.new` does really work on simple-integers.


i really would love to see this merged, but we'd need to keep an eye on existing setups.
  

let me know if you'd need some help, i am trying to find a spec sample. but it'll take me some time :/

2017-05-14 09:48 UTC, sinoru commented
I thinks.. It is hard to represent semver as integer. According to Apple docs, `CFBundleVersion` can be any dots and integer combination in eight characters. So some people can use it as x.y.z.f like that..

So, Uhm..
And, even x.y can not be represented in integer.. It can only in float.. Uhm..

So I have some candidates to solve this problem:
1. If just integer return as integer, If version is float than return as float, If version only can presented in string, than return as string.
2. Get options to return always in string, like (string: true), and otherwise only return as integer.

How about those candidates?

2017-05-14 20:46 UTC, hjanuschka commented
@sinoru here is a sample on testing the action.:


`fastlane/spec/actions_specs/app_store_build_number_spec.rb`
```ruby
require 'spec_helper'

describe Fastlane::Actions::AppStoreBuildNumberAction do
  it "Should return latest build" do

    # Mock Builds
    build1 = OpenStruct.new
    build1.build_version = "3"

    build2 = OpenStruct.new
    build2.build_version = "2"

    builds = OpenStruct.new
    builds.builds = [build1, build2]

    # Mock App with Buildtrain
    spec_app = OpenStruct.new
    spec_app.build_trains = {
      "1.0" => builds
    }

    # Mock Spaceship
    expect(Spaceship::Tunes).to receive(:login).and_return(true)
    expect(Spaceship::Tunes).to receive(:select_team).and_return(true)
    expect(Spaceship::Application).to receive(:find).and_return(spec_app)

    result = Fastlane::FastFile.new.parse("lane :test do
      app_store_build_number(username:'demo@demo.com', app_identifier: 'demo.app', live: false, version: '1.0')
    end").runner.execute(:test)

    expect(result).to eq(3)
  end
end

```


run it with: `rspec fastlane/spec/actions_specs/app_store_build_number_spec.rb` (with `bundle exec` if you are using bundler)

this should do it as a boilerplate to test new concepts 👍 




how about returning a custom type (shipped inside of app_store_build_number.rb?)
and check if it is a simple integer or a `x.y.z`  and provide `+` && `to_s` method for easy incrementing and outputing?

```ruby

module Fastlane
  module Actions
  class AppStoreBuildNumberType
      attr_reader :version
      attr_reader :semver
      def initialize(value)
        if value.include?(".")
          @version = value
          @type = :semver
        else
          @version = value
          @type = :integer
        end
      end
      def to_s
        @version.to_s
      end
      def +(other)
          if @type == :integer
            return @version.to_i+other
          else
            components = @version.split(".")
            components[-1] = components[-1].to_i+other
            @version = components.join(".")
            return @version
          end
      end
  end
end
end


# Create a Semver style AppStoreBuildNumberType
semver_style = Fastlane::Actions::AppStoreBuildNumberType.new("1.1.1")

# increment it by 2 
incremented = semver_style+2

# results in "1.1.3"
puts incremented


# Use the usual integer build names
simple_style = Fastlane::Actions::AppStoreBuildNumberType.new("100")

# increment by 3
incremented = simple_style+3

# results in "103"
puts incremented


```


let me know what you think.

2017-05-15 03:05 UTC, KrauseFx commented
Thanks for the review @hjanuschka 👍  Thanks for the PR @sinoru 👍

2017-06-04 09:56 UTC, sinoru commented
How about this?
I add custom type for that, which follows Apple's rule (only dots and number), convertible to int, string, can be sumed and can be sorted.

2017-06-04 14:44 UTC, sinoru commented
Additional fixing is done.

2017-06-04 18:25 UTC, hjanuschka commented
@sinoru ohh wow thats a huge thing! - still trying to fully understand it.

what is in the case there is a build `433`  (latest uploaded)  - and an exsiting version `4.4.4` (older upload) - would `433`be returend, or is that a case that does not work?

2017-06-04 18:34 UTC, sinoru commented
@hjanuschka 433 should be returned.
Actually, this split it by dots, compares as array.
e.g:
```ruby
irb(main):001:0> [[443], [4,4,4]].sort
=> [[4, 4, 4], [443]]
```

2017-06-08 09:53 UTC, sinoru commented
I added more specs just for Custom types that should works well.

2017-08-03 17:43 UTC, ohayon commented
Hey @sinoru - sorry I am late to this party, but would it be possible to map the values to `Gem::Version.new` rather than introducing a new class which does almost the same thing? 💎  🚀

2017-08-25 01:19 UTC, sinoru commented
@ohayon I'm sorry about I also late to respond.
Uhm.. Gem::Version can be used.... But for legacy, Lot's of people uses like:
```
build = app_store_build_number + 1
```


But, If return as Gem::Version, This will breaking changes, and should be used as:
```
build = app_store_build_number.to_s.to_i + 1
```
which is not that good.

2017-08-28 19:41 UTC, ohayon commented
Hmmmm @sinoru do you think we could subclass or monkey patch `Gem::Version` to add the addition function?

2017-09-11 16:38 UTC, ohayon commented
Hey @sinoru, just saw your comment on [this issue](https://github.com/fastlane/fastlane/issues/9392) related to this PR. Did you have a chance to consider my comment above?

2017-10-24 18:19 UTC, ohayon commented
Hey everyone, I am going to close this PR for now as it hasnt been active for quite some time. @sinoru - please feel free to continue discussion and/or reopen this or another PR, but I think it would be great to talk through the changes so that we can make sure we are all on the same page 😄 ! 🚀  🐙

2017-10-24 18:19 UTC, closed without merging