Implement Reports Generator for Screengrab
fastlane/fastlane pull request #9213
Opened 2017-05-18 20:59 UTC by maszin

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
! some tests, not related to feature, were not passing
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

In this feature you will find implementation of Report Generator for `Screengrab`. It is based on similar implementation of reports for `Snapshot`. 

https://github.com/fastlane/fastlane/issues/9161

I tested it on 2 different devices (Nexus 5X and Samsung S6) and on emulator. I was using project `example` from `screengrab` module. 

### Description

I used implementation of reports from `Snapshot` and adapted it to `Screengrab`.
- modified `screengrab/lib/screengrab.rb` to import reports
- created `screengrab/lib/screengrab/reports_generator.rb` which contains implementation of reports
- modified `screengrab/lib/screengrab/runner.rb` to run reports, after screenshots are created
- updated Android files

2017-05-18 21:02 UTC, maszin commented on screengrab/lib/screengrab/runner.rb
>        open_screenshots_summary(device_type_dir_name)
Should we skip opening screenshots in picture browser (since reports are implemented)?

2017-05-18 21:26 UTC, maszin commented
I signed it! :)

2017-05-19 17:06 UTC, mfurtak requested changes
This is looking great! After addressing these couple things, we should be ready to go 🚀

2017-05-19 17:06 UTC, mfurtak commented on screengrab/lib/screengrab/runner.rb
>        open_screenshots_summary(device_type_dir_name)
Yes, sounds good :+1:

2017-05-19 17:10 UTC, mfurtak commented on screengrab/lib/screengrab/reports_generator.rb
> +require 'fastimage'
One more thought - I don't know what this `require 'fastimage'` is for. It appears to work without it, so let's remove :+1:

2017-05-22 17:35 UTC, mfurtak approved these changes
Sweet - thanks for the contribution! 🚀

2017-05-22 17:35 UTC, merged