Slack: Fixed crash when defining FL_SLACK_DEFAULT_PAYLOADS
fastlane/fastlane pull request #9217
Opened 2017-05-19 12:31 UTC by liamnichols

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I never actually want to use any of the default payloads in my project when sending Slack message so to clean up my `Fastfile` I attempted to define `FL_SLACK_DEFAULT_PAYLOADS` as an empty string so that I could remove the parameter each time I used `slack` however this appeared to crash with the following error:

```
NoMethodError: [!] undefined method `join' for "":String
```  

(The env var parsed as a `String` and not an `Array` as expected)

### Description

This PR simply updates the `:default_payloads` config item and sets its `type` to `Array` so that [`auto_convert_value`](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/configuration/config_item.rb#L133) can correctly parse the environment variable rather than failing and just returning the original string.  

I wasn't sure if a simple one line config item change warranted any unit tests so haven't added any yet but let me know if you think it does (and a heads up on how to approach testing this in a nice way would also be appreciated as well) ✌️

2017-05-19 17:06 UTC, joshdholtz requested changes
@liamnichols Great find 🔍  I have actually ran into this myself a while back but thought it was a user error 😝 

I would suggest writing a test (like the sample one I wrote below) that tests the parsing of `default_values` from a comma delimited string

```rb
it "parses default_payloads from a comma delimited string" do
  channel = "#myChannel"
  message = "Custom Message"
  lane_name = "lane_name"

  Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::LANE_NAME] = lane_name

  require 'fastlane/actions/slack'
  arguments = Fastlane::ConfigurationHelper.parse(Fastlane::Actions::SlackAction, {
    slack_url: 'https://127.0.0.1',
    message: message,
    success: false,
    channel: channel,
    default_payloads: "lane,test_result",
  })

  notifier, attachments = Fastlane::Actions::SlackAction.run(arguments)

  fields = attachments[:fields]

  expect(fields[0][:title]).to eq('Lane')
  expect(fields[0][:value]).to eq(lane_name)
  
  expect(fields[1][:title]).to eq('Result')
  expect(fields[1][:value]).to eq('Error')
end
```

2017-05-21 16:31 UTC, liamnichols commented
Thanks for that @joshdholtz! I didn't even realise that you'd be able to pass them in via regular arguments so that makes things nice and easy 😀.  

I've updated the branch with the suggested test and some corrections from rubocop. Let me know if you need anything else 👍

2017-05-22 14:18 UTC, joshdholtz commented
@liamnichols Can you try rebasing from fastlane's new master? There was a fix put in for CircleCI tests failing like this - https://github.com/fastlane/fastlane/pull/9222

2017-05-22 17:03 UTC, liamnichols commented
@joshdholtz ahh awesome, all sorted now 👌

2017-05-23 13:22 UTC, joshdholtz approved these changes

2017-05-23 13:22 UTC, merged

2017-05-23 13:22 UTC, joshdholtz commented
@liamnichols Thanks for the contribution ❤️