List produce enabled_features options in config item
fastlane/fastlane pull request #9223
Opened 2017-05-19 17:45 UTC by joshdholtz

Fixes #9209

Its "wordy" but helpful 😇 

```sh
-P, --enabled_features [VALUE] Array with Spaceship App Features (e.g. app_group,apple_pay, associated_domains, data_protection,
game_center, health_kit, home_kit, wireless_accessory, icloud, in_app_purchase, inter_app_audio, passbook, push_notification, siri_kit,
vpn_configuration) (PRODUCE_ENABLED_FEATURES)
```

2017-05-19 18:58 UTC, mfurtak commented
Is there any place in code where we have values for these defined? It'd be nice if we could compute this list from an authoritative place, so we don't have to worry about it getting out-of-date.

2017-05-19 19:06 UTC, taquitos commented on produce/lib/produce/options.rb
> +                                     description: "Array with Spaceship App Features (e.g. app_group,apple_pay, associated_domains, data_protection, game_center, health_kit, home_kit, wireless_access
Needs space between these two: `app_group,apple_pay`

2017-05-25 18:35 UTC, KrauseFx approved these changes
Great work on this, I added 2 comments that should be addressed before merging 👍

2017-05-25 18:35 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/configuration/config_item.rb
> +    def initialize(key: nil, env_name: nil, description: nil, short_option: nil, default_value: nil, verify_block: nil, is_string: true, type: nil, optional: nil, conflicting_options: nil, conflict_b
Wohoo, so many, can we split those up in one key/value per line?

2017-05-25 18:35 UTC, KrauseFx commented on fastlane_core/lib/fastlane_core/configuration/config_item.rb
> +      @display_in_shell = display_in_shell
Can we merge this with line 92 to be in one line?

2017-05-26 14:44 UTC, joshdholtz commented
@hjanuschka Do you mind taking a look at this too since you originally created this `enabled_features` feature? 😇

2017-05-26 17:32 UTC, hjanuschka approved these changes
@joshdholtz awesome work, i like the new `display_in_shell` option. PR LGTM 💯

2017-05-26 20:12 UTC, KrauseFx requested changes
One little change I requested

2017-05-26 20:52 UTC, joshdholtz commented on fastlane_core/lib/fastlane_core/configuration/config_item.rb
> +      @display_in_shell = display_in_shell
@KrauseFx It was pretty ugly to combine into one line so I changed the default value in the method definition to `true` 😇  I think this was the cleanest way of doing it?

2017-05-26 22:48 UTC, KrauseFx approved these changes

2017-05-30 14:10 UTC, merged