Update license copyright to Google Inc
fastlane/fastlane pull request #9274
Opened 2017-05-25 13:52 UTC by alexsinger

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Google suggested the change now that fastlane is part of Google Inc

### Description
Associated the fastlane copyright to Google Inc

2017-05-25 15:12 UTC, KrauseFx commented
I'll do some research if that's okay to do, as we'd change the license of code that was contributed before the Google CLA was introduced.

2017-05-25 17:54 UTC, taquitos approved these changes
~🐑 it~ Sorry, just saw your comment Felix!

2017-05-25 18:05 UTC, hjanuschka requested changes
can you clarify what that means  for all pre-CLA commits - to every single contributor?

2017-05-26 13:07 UTC, alexsinger commented
@hjanuschka we asked for clarification on this from the OSS team at Google. This change doesn't affect contributor's ownership over their contributions.

2017-05-26 13:17 UTC, mfurtak commented
nit: does legal require the capital "F" in _fastlane_? 😄

2017-05-26 15:40 UTC, KrauseFx commented on LICENSE
> +Copyright (c) 2015-present the fastlane Authors
Shouldn't authors also be lower case?

2017-05-26 15:43 UTC, alexsinger commented on LICENSE
> +Copyright (c) 2015-present the fastlane Authors
Was following legal's spelling "the Fastlane Authors", but then lower cased "fastlane" for branding reasons.

2017-05-26 15:52 UTC, mfurtak approved these changes

2017-05-26 15:54 UTC, KrauseFx commented on LICENSE
> +Copyright (c) 2015-present the fastlane Authors
I'd probably go with `authors`

2017-05-26 17:27 UTC, hjanuschka approved these changes

2017-05-30 02:26 UTC, merged