Catch errors with app names
fastlane/fastlane pull request #9282
Opened 2017-05-25 18:28 UTC by ohayon

2017-05-25 18:33 UTC, KrauseFx requested changes

2017-05-25 18:33 UTC, KrauseFx commented on deliver/lib/deliver/upload_metadata.rb
> +        end
Could you provide some more context for this change? In particular, why do we not re-raise the exception if the error message isn't one of the 2 messages we check for?

2017-05-25 18:34 UTC, lacostej submitted a review, later dismissed

2017-05-25 18:34 UTC, lacostej commented on deliver/lib/deliver/upload_metadata.rb
> +        end
missing `raise` when not matching?

2017-05-25 18:34 UTC, ohayon commented on deliver/lib/deliver/upload_metadata.rb
> +        end
Was moving too fast. should have done that!

2017-05-25 18:35 UTC, lacostej commented on deliver/lib/deliver/upload_metadata.rb
> +        end
:)

2017-05-25 18:40 UTC, KrauseFx commented
This change makes a lot of sense, however I'm worried adding more of those checks to the _fastlane_ code base. We can keep adding those `if/else`, which results in noise/smell across the classes. How do we decide on when we should make a specific check? In the example of spaceship, almost every interaction with iTunes Connect / Developer Portal might fail because of one of these reasons. 

Can we think of a simpler approach that would still help us solve the problem? Would it help if we tag all spaceship response exceptions somehow automatically?

2017-05-25 18:44 UTC, ohayon commented
I think as of now, we are just making decisions about when to add these checks based on frequent crashes that we are seeing in the crash reporter, for example, this crash has happened 102 times in the past week, so it feels like something we should be guarding against. You do make a good point that we don't want to add conditional checks all over the place, but we do want to make sure that we know when there is a crash because of a user error versus a crash because iTC is down.

2017-05-25 21:17 UTC, lacostej commented
I there a way to better distinguish the errors at a different place, maybe in the client.

E.g. ITC down should definitively result in a class or errors different from user errors.

I don't remember the API and how we wrap it though. But turning everything into a `ITunesConnectError` sounds like we might be losing some information.

2017-05-26 13:35 UTC, ohayon commented
@lacostej I think it would be a good chunk of work to introduce different error types on the client. I totally agree that iTC being down should have a different type of error, I think the major issue is that its hard for us to determine why a call to iTC is failing (is it a bad request, is their service down?) because they often don't properly use error codes to represent failures.

Also, I do think we should be handling the error in `upload_metadata.rb` as it feels more appropriate to use `UI` in that class versus in the `AppDetails` model object or the client itself.

2017-06-13 20:16 UTC, KrauseFx approved these changes

2017-06-13 21:08 UTC, merged