6875 deliver: also use --force as a way to overwrite metadata
fastlane/fastlane pull request #9307
Opened 2017-05-29 08:50 UTC by lacostej

Deliver requires a specific environment variable to overwrite metadata
Users expect --force to work. We add support for it, while keeping backward compatibility.
Documentation isn't updated as the env. variable wasn't made public.

2017-05-29 23:23 UTC, KrauseFx approved these changes
Looks good to me, thanks @lacostej. Have you tested this locally?

2017-05-31 16:54 UTC, KrauseFx commented
@lacostej :)

2017-05-31 17:33 UTC, ohayon commented
This PR is related to https://github.com/fastlane/fastlane/issues/9306 right?

2017-06-01 17:20 UTC, lacostej commented
@ohayon #9306 is another issue that I intend to look at at some point.

2017-06-02 09:38 UTC, lacostej commented
@KrauseFx I had managed to have a bug in it... I now fixed it and tested it on a live project. Also added more tests.

2017-06-02 14:28 UTC, ohayon requested changes

2017-06-02 14:28 UTC, ohayon commented on deliver/lib/deliver/commands_generator.rb
> +      res ||= UI.confirm("Do you want to overwrite existing metadata on path '#{File.expand_path(path)}'?")
Can we add an `if UI.interactive?` to the end of this line to make sure it doesn't crash in CI?

2017-06-02 16:22 UTC, lacostej commented on deliver/lib/deliver/commands_generator.rb
> +      res ||= UI.confirm("Do you want to overwrite existing metadata on path '#{File.expand_path(path)}'?")
Fixed. Good catch. I thought `confirm` was doing nothing when in `interactive` but it crashes instead :)

2017-06-02 18:33 UTC, ohayon commented on deliver/lib/deliver/commands_generator.rb
> +      res ||= UI.confirm("Do you want to overwrite existing metadata on path '#{File.expand_path(path)}'?") unless UI.interactive?
I think this should be `if` not `unless` right?

2017-06-02 18:42 UTC, lacostej commented on deliver/lib/deliver/commands_generator.rb
> +      res ||= UI.confirm("Do you want to overwrite existing metadata on path '#{File.expand_path(path)}'?") unless UI.interactive?
Doh....

2017-06-05 15:50 UTC, lacostej commented
@ohayon finally revised the patch with the proper boolean logic (and fixed the tests)

2017-06-07 08:50 UTC, lacostej commented
@ohayon ping! :)

2017-06-12 13:38 UTC, ohayon approved these changes

2017-06-12 15:32 UTC, merged