iOS 11 Subtitle iTunes Connect support
fastlane/fastlane pull request #9396
Opened 2017-06-07 11:11 UTC by javibm

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Giving support to the new iOS 11 subtitle field in iTunes Connect.

* bundle exec rspec
* Execute spaceship playground to test Subtitle on iTunes. (Save and Read)
* Execute deliver to init and upload subtitle to iTunes.

### Description

* Added subtitle hash attribute to app_details.rb in spaceship.
* Added subtitle parameter to LOCALISED_APP_VALUES in deliver upload_metadata.rb
* Added subtitle option in deliver options.
* Modified Summary html to preview subtitle in deliver.

2017-06-07 11:16 UTC, javibm commented
I signed it!

2017-06-08 19:08 UTC, KrauseFx requested changes
This is great, thanks for your contribution @javibm, could you also add this to `Deliverfile.md`, like we did on https://github.com/fastlane/fastlane/pull/9370/files#diff-e1066502265354bca343df7ab8a244c0R182

2017-06-08 19:08 UTC, KrauseFx commented on deliver/lib/deliver/options.rb
> +                                     is_string: false),
This will need a verify block like https://github.com/fastlane/fastlane/pull/9370/files#diff-cec46a69540d57cbb9c8631d43a7a89bR262

2017-06-08 19:12 UTC, KrauseFx commented
Also, welcome to the fastlane community @javibm 🚀

2017-06-09 06:38 UTC, javibm commented
@KrauseFx Thanks for the welcome and the feedback! I have done all the changes 😊

2017-06-09 19:05 UTC, KrauseFx approved these changes
Wohooo, thanks for updating the PR, this is great, and will be in the next release 🚀

2017-06-09 19:07 UTC, merged

2017-06-12 18:04 UTC, shenoyroopesh commented
Immediate release would be nice, since we need to start getting subtitles in.