Commit version bump bug fix and enhancements
fastlane/fastlane pull request #9423
Opened 2017-06-10 00:43 UTC by jdee

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This is motivated by Issue #9341. The problem is that the `:settings` option to `commit_version_bump` doesn't work if the Settings.bundle is in a group in the Xcode project. This option has been there for some time, but it was broken when I first tried to use it. I "fixed" that bug at some point, resulting in the faulty code that's there now. This originally showed up as a bug in my settings_bundle plugin. That has been fixed but not yet released, pending resolution of the issue with `commit_version_bump`.

To produce the bug, clone https://github.com/jdee/settings-bundle and check out the `commit-version-bump-bug` branch. Edit the Gemfile and remove the line reading

```ruby
gem 'fastlane', git: 'https://github.com/jdee/fastlane', branch: 'commit-version-bump-bug'
```

Then

```
bundle install
bundle exec fastlane group_test
```

Note that `bundle exec fastlane test` will succeed (if you comment out or modify the commit_version_bump line, which uses a newly-added option). The difference between SettingsBundleExample and SettingsBundleGroupExample is that in the former, the Settings.bundle is at the root of the project in Xcode, but in the latter it's under the SettingsBundleGroupExample group. The `#path` method used [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/commit_version_bump.rb#L220) returns a value relative to the group, not the project root.

But a bigger issue is that this logic belongs in the plugin, not in this action. I suggested two options in the issue. I've implemented both. There are three stages to the fix, represented by different commits.

1. Fix the broken logic in 'settings_bundle_file_path`.
2. Add an `:include` option to specify arbitrary files to include.
3. Add `lane_context[SharedValues::MODIFIED_FILES]` and `Actions::add_modified_files`.

If only some of these changes should be merged, they can easily be reverted or removed.

### Description

1. Fix the broken logic in `settings_bundle_file_path`:
  Use the `#real_path` method, which returns the absolute path to the file. This fixes the original
  bug with a tiny change.
2. Add an `:include` option to specify arbitrary files to include.
  This allows explicit inclusion of an array of relative file paths. This has the virtue that there is no
  mystery if a file is included, but more parameters are required, and the correct path has to be
  explicitly supplied. There is already an `:ignore` parameter. This parameter seems to complement
  it.
3. Add `lane_context[SharedValues::MODIFIED_FILES]` and `Actions::add_modified_files`.
  This allows any action that modifies files to be included in a commit to pass them directly to
  the `commit_version_bump` action via the lane_context. It allows the context to accumulate
  the unique results of all actions. It eliminates the need for any additional parameters to support
  plugins that make modifications to include in a version bump. It could easily be used to support
  Android as well, rewrite `commit_version_bump` and obviate the `:xcodeproj` and `:settings`
  parameters.

I mentioned in the issue that it's possible for a settings bundle to have a custom name other than Settings.bundle. This is and isn't true. It's possible to create such a thing, but it doesn't show up in the Settings app unless the name is Settings.bundle. So that's not a concern, and the first commit is enough to fix the issue and probably put the question of settings bundles to rest.

But it seems plausible that there may be other cases where a lane might modify files other than the Xcode project and Info.plist as part of a version bump. Or I might have to fix another bug in my plugin and have to change `commit_version_bump` again. A more extensible approach seems like a good idea. The other two options are presented for consideration.

To try out these options, use the `commit-version-bump-bug` branch in the plugin repo above. See the [Fastfile](https://github.com/jdee/settings-bundle/blob/commit-version-bump-bug/fastlane/Fastfile) there, which has three lanes that demonstrate the three different methods.

Using the `:include` option:
```
bundle exec fastlane test
```

Using the corrected `:settings` option:
```
bundle exec fastlane group_test
```

Using the lane_context (no `:include` or `:settings` option):
```
bundle exec fastlane library_test
```

Note: `git reset --hard HEAD^` erases the last commit in the current branch and is useful for testing this action.

2017-06-10 00:48 UTC, jdee commented
@googlebot I signed it.

2017-06-10 02:18 UTC, jdee commented
There are now two branches in the settings-bundle repo: `commit-version-bump-bug` and `commit-version-bump-bug-fixed`. The new options are used in the second branch. The original instructions above have been updated.

2017-06-14 19:04 UTC, ohayon requested changes
Hey @jdee, thank you so much for this PR! I would really like to merge just the first commit/change that you made and then address the second and third in other PRs if that is possible. Would you mind opening up other PRs as those kind of change/add some functionality where it appears that the first really just fixes the bug? Let us know if you have any questions! 🚀

2017-06-14 19:04 UTC, ohayon commented on fastlane/lib/fastlane/actions/commit_version_bump.rb
> +          File.join settings_bundle.real_path, settings_file_name
Could you put parentheses in here?

2017-06-14 20:33 UTC, jdee commented
@ohayon: Done. The first commit broke a unit test, fixed by the third. I also fixed the parentheses and added examples of the current usage of the `:settings` option, which I neglected to do the last time around. Would you prefer one PR or two for the enhancements?

2017-06-14 20:35 UTC, ohayon approved these changes
Thanks for making those changes @jdee !! 🚀

2017-06-14 20:35 UTC, ohayon commented
@jdee - I think one PR for the enhancements would be great! Thanks so much for being flexible!

2017-06-14 20:45 UTC, merged