[gym] Remove legacy build API
fastlane/fastlane pull request #9463
Opened 2017-06-13 22:43 UTC by KrauseFx

It's about time

2017-06-13 22:46 UTC, taquitos approved these changes
🆗 🙏 🐑 it!

2017-06-13 22:48 UTC, ohayon requested changes
This is so amazing. I just did a quick pass, and the one question I have other than the little typo is: should we show people a message that this has been removed?

2017-06-13 22:48 UTC, ohayon commented on gym/lib/gym/generators/package_command_generator_xcode7.rb
> +      # Wrap xcodebuild to work-around ipatool dependecy to system ruby
*dependency

2017-06-13 23:52 UTC, KrauseFx commented
@ohayon Great question. Looking at the diff, we warned people angrily to stop using it for the last year, and since about 6 months or so, the legacy API doesn't work at all, so I think we should be fine

2017-06-14 00:20 UTC, ohayon approved these changes

2017-06-14 00:21 UTC, ohayon commented
👍 Grrreat!

2017-06-14 00:55 UTC, KrauseFx commented
Let's wait for a few days before merging and see if someone has a concern 👍

2017-06-14 21:01 UTC, lacostej commented on gym/lib/gym/options.rb
> -        FastlaneCore::ConfigItem.new(key: :provisioning_profile_path,
Sorry for delay, this got stuck in github 'start a review' mode :)

2017-06-15 22:24 UTC, KrauseFx commented on gym/lib/gym/options.rb
> -        FastlaneCore::ConfigItem.new(key: :provisioning_profile_path,
Yeah it will fail, _fastlane_ will tell the user that this option isn't available.

2017-06-23 06:49 UTC, KrauseFx commented
Alright, should we merge this now? :)

2017-06-23 13:23 UTC, ohayon commented
@KrauseFx YEAH! \o/

2017-06-28 21:34 UTC, merged

2017-06-30 21:34 UTC, ryanwiesjahn commented
@KrauseFx So I was actually using the `provisioning_profile_path` option of `gym`. I knew it was deprecated, but I'm in a situation where I can't use `match` or `cert` and `sigh`, because those all seem to require admin access to the Apple Developer account which I do not have. What is the proper way to specify signing cert and provisioning profile files that I am providing to Fastlane?

2017-07-01 00:39 UTC, KrauseFx commented
Sorry we probably broke your setup @ryanwiesjahn, it was necessary though, as Xcode doesn't support that option any more. Instead, please follow our [code signing guide](https://docs.fastlane.tools/codesigning/getting-started/), in particular the Xcode setup 👍 Please submit a new issue if you have any questions :)