Make upload_symbols_to_crashlytics fail with a more descriptive error message.
fastlane/fastlane pull request #9478
Opened 2017-06-14 19:30 UTC by lalunamel

See https://github.com/fastlane/fastlane/issues/9477 for details.

2017-06-14 19:31 UTC, lalunamel commented
Looks like legal needs to be involved here.
Will be back in N days when that's resolved.

2017-06-14 19:32 UTC, ohayon requested changes
This is awesome! Thanks so much for making this PR @lalunamel!! Just one small change and we should be good to 🚀

2017-06-14 19:32 UTC, ohayon commented on fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb
> +        UI.user_error!("Failed to upload find Fabric's upload_symbols binary at /Applications/Fabric.app/**/upload-symbols or ./Pods/**/upload-symbols. Please specify the location of the binary expli
Failed to find Fabric's....

2017-06-14 19:45 UTC, ohayon approved these changes

2017-06-14 21:29 UTC, lalunamel commented
Howdy.
Legal says I've been added to the group CLA for my company, Pivotal, so you can remove the `cla: no` label.

2017-06-21 04:13 UTC, willnorris commented
One of your commits is authored with your pivotal email, the other is with your gmail.  Please amend the second to also use your pivotal email.

2017-06-22 14:51 UTC, lalunamel commented
There you go!

2017-06-22 15:19 UTC, willnorris commented
sorry, one more minor thing.  could you add your pivotal.io [email to your github account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/)? (Fortunately, all of this is just a one-time setup... future contributions should go much more smoothly, I promise)

2017-06-23 14:29 UTC, lalunamel commented
done :)

2017-06-23 14:29 UTC, lalunamel commented
nice job googlebot! what a nice robut. so halpful!

2017-06-23 14:45 UTC, ohayon commented
Thanks for your patience and going through all of the CLA stuff @lalunamel !!! We really appreciate the change! 🚀

2017-06-23 14:45 UTC, merged