Pilot: Allow '~' in ipa path
fastlane/fastlane pull request #9481
Opened 2017-06-14 20:44 UTC by NicholasFFox

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context

Fixes #9480

2017-06-14 20:48 UTC, ohayon reviewed
Thanks for the PR @NicholasFFox! This is definitely a great change! I just left one comment about the methods in the `IpaFileAnalyser` class. Let me know what you think? 🐙

2017-06-14 20:48 UTC, ohayon commented on fastlane_core/lib/fastlane_core/ipa_file_analyser.rb
> +      path = File.expand_path(path)
Should this be happening in the methods above too? Or maybe at the call site for all of these methods?

2017-06-14 21:30 UTC, NicholasFFox commented on fastlane_core/lib/fastlane_core/ipa_file_analyser.rb
> +      path = File.expand_path(path)
@ohayon I _really_ wanted to make the change in `fastlane_core/lib/fastlane_core/configuration/config_item.rb` by changing `auto_convert_value` to do this: 
```
    def auto_convert_value(value)
      return nil if value.nil?

      if data_type == Array
        return value.split(',') if value.kind_of?(String)
      elsif data_type == Integer
        return value.to_i if value.to_i.to_s == value.to_s
      elsif data_type == Float
        return value.to_f if value.to_f.to_s == value.to_s
      elsif data_type == String && allow_shell_conversion
        return value.map(&:to_s).map(&:shellescape).join(' ') if value.kind_of?(Array)
        return value.map { |k, v| "#{k.to_s.shellescape}=#{v.shellescape}" }.join(' ') if value.kind_of?(Hash)
      elsif data_type == String && value.include?("~/") # <- new case here
        return File.expand_path(value)
      else
        # Special treatment if the user specified true, false or YES, NO
        # There is no boolean type, so we just do it here
        if %w(YES yes true TRUE).include?(value)
          return true
        elsif %w(NO no false FALSE).include?(value)
          return false
        end
      end

      return value # fallback to not doing anything
    end
```
That fix broke a number of tests though that had `~/` in various paths, so I opted for the less global fix.

2017-06-14 21:33 UTC, NicholasFFox commented
@ohayon updated all methods in IpaFileAnalyser to expand paths.

2017-06-15 14:34 UTC, ohayon requested changes
Hey @NicholasFFox, thanks for making those changes!  And sorry I am asking one more thing, but I'm curious to hear your thoughts on the one comment I left. 💯

2017-06-15 14:34 UTC, ohayon commented on pilot/lib/pilot/build_manager.rb
> +      ipa_path = File.expand_path(config[:ipa])
Any chance you would want to move this into the `generate` method on `IpaUploadPackageBuilder` to let that method handle the expansion?

2017-06-15 18:14 UTC, NicholasFFox commented
@ohayon completely agree with the comment and made the requested change 👍

2017-06-15 19:14 UTC, KrauseFx commented
Hey everyone, randomly jumping in here. I agree with @ohayon, this ends up with lots of duplicate code. An easy solution for that would be to do it once in `gym/manager.rb` right after printing the tables (as we don't necessarily want to display a really long path in the summary table) by setting it once:

```ruby
Gym.config[:ipa_path] = File.expand_path(Gym.config[:ipa_path])
```

or similar :)

2017-06-16 23:13 UTC, NicholasFFox commented
@KrauseFx @ohayon - I reverted my previous changes (with the exception of the ipa parameter's verify block), and added a `create_config` method in Pilot's CommandsGenerator. This offers a central place to perform similar operations on Pilot parameters in the future. Does this address the previous concerns?

2017-06-18 00:23 UTC, KrauseFx approved these changes
Looks 💯

2017-06-22 20:47 UTC, NicholasFFox commented
@ohayon anything else that I need to do here?

2017-06-22 21:09 UTC, ohayon approved these changes

2017-06-22 21:21 UTC, merged

2017-06-22 21:21 UTC, KrauseFx commented
Thanks for reminding us @NicholasFFox, this is merged now and will be in the next release 👍 Thanks for contributing.