Add last_git_commit_hash to git_helper
fastlane/fastlane pull request #9524
Opened 2017-06-19 20:13 UTC by jvaladez

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Adding the last git commit to the slack message provides useful information to those seeing the message. It identifies the exact commit by its identifier than just the commit message (ex: a1b2c3 vs "hot fix")

### Description

1. I added a last_git_commit_hash function to the git_helper. If given a boolean true it returns the short hash of the last commit, if not, it returns the full hash. 
2. Used the last_git_commit_hash to add the short hash to the default slack function message.

2017-06-19 20:17 UTC, jvaladez commented
I signed it!

On Mon, Jun 19, 2017 at 4:13 PM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If your company signed a CLA, they designated a Point of Contact who
>    decides which employees are authorized to participate. You may need to
>    contact the Point of Contact for your company and ask to be added to the
>    group of authorized contributors. If you don't know who your Point of
>    Contact is, direct the project maintainer to go/cla#troubleshoot.
>    - In order to pass this check, please resolve this problem and have
>    the pull request author add another comment and the bot will run again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/pull/9524#issuecomment-309560381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AH3rLIABLC74BwtLJVROd6hcskxCtn1Iks5sFtZzgaJpZM4N-u43>
> .
>

2017-06-21 20:37 UTC, getaaron requested changes

2017-06-21 20:37 UTC, getaaron commented on fastlane/lib/fastlane/actions/slack.rb
> +            value: Actions.last_git_commit_hash(true),
I think it would be more readable to call this with the named argument:

```ruby
Actions.last_git_commit_hash(short: true)
```

2017-06-21 20:37 UTC, getaaron commented on fastlane/lib/fastlane/helper/git_helper.rb
> +    def self.last_git_commit_hash(short)
I think this is a bit more readable:

```ruby
format_specifier = short ? '%h' : '%H'
string = last_git_commit_formatted_with(format_specifier).to_s
return string unless string.empty?
return nil
```

2017-06-21 20:53 UTC, jvaladez commented
@getaaron made the requested changes. Thanks!

2017-06-23 17:50 UTC, mpirri approved these changes
This looks great!  Thanks so much for your contribution! 🚀

2017-06-23 17:50 UTC, merged