Update README to call out what operating systems can run fastlane
fastlane/fastlane pull request #9721
Opened 2017-07-11 21:07 UTC by taquitos

We want to make it more obvious what operating systems are currently supported so people don't spend a bunch of time trying to get it to work on unsupported platforms.

2017-07-11 21:17 UTC, ohayon requested changes

2017-07-11 21:17 UTC, ohayon commented on README.md
> +**Note:** If you'd like to add support for your favorite platform, feel free to [contribute a PR](https://github.com/fastlane/fastlane/tree/master/YourFirstPR.md)!
A little nervous about offering to entertain this PR but it would be nice to support Windows and I think in the long run we should.

2017-07-11 21:17 UTC, ohayon commented on README.md
> +Currently _fastlane_ is officially supported on macOS. Support for other operating systems is limited and untested at this point in time. _fastlane_ uses system apis that may not be implemented on ot
Maybe APIs instead of apis?

2017-07-11 21:17 UTC, ohayon commented on README.md
> +## Where can fastlane run?
How about "System Requirements"

And I think we could put this up under Quick Start for more visibility.

2017-07-11 21:23 UTC, alexsinger commented on README.md
> +Currently _fastlane_ is officially supported on macOS. Support for other operating systems is limited and untested at this point in time. _fastlane_ uses system APIs that may not be implemented on ot
"Currently,"

2017-07-11 21:26 UTC, alexsinger commented on README.md
> +Currently _fastlane_ is officially supported on macOS. Support for other operating systems is limited and untested at this point in time. _fastlane_ uses system APIs that may not be implemented on ot
Maybe "Currently, _fastlane_ is officially supported to run on macOS."?

2017-07-12 08:37 UTC, KrauseFx commented on README.md
> +Currently, _fastlane_ is officially supported to run on macOS. Support for other operating systems is limited and untested at this point in time. _fastlane_ uses system APIs that may not be implement
> for example, we use the Ruby `fork` method for sub-process managements, which isn't available on Windows

2017-07-12 08:38 UTC, KrauseFx approved these changes
That's great, one little comment, ready to be merged whenever from my side 👍

2017-07-12 13:58 UTC, ohayon approved these changes

2017-07-12 21:40 UTC, KrauseFx approved these changes

2017-07-12 21:42 UTC, taquitos commented
This is a doc update for #8800

2017-07-12 22:12 UTC, merged