Added command to create external beta tester groups
fastlane/fastlane pull request #9828
Opened 2017-07-21 21:01 UTC by JeffreyGreenII

### Checklist
- [Y] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [Y] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [Y] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [Y] I've updated the documentation if necessary.

### Motivation and Context
This change allows Pilot to ability to add external beta tester groups. Since iTunes no longer comes with default external tester groups, it's important to maintain an ability to add these groups manually to allow developers to setup their apps and those apps tests without accessing ITC's UI. This also opens up the possibility to have dynamic groups of external testers for specific builds and specific users.
I typed out the edge cases that would cause a problem (no input, missing input, invalid input, incorrect input) and test for all cases I suspected could happen.

### Description
I created a new manager class in Pilot called GroupManager with the single responsibility of handling groups, as TesterManager and BuildManager didn't feel apt for such a role. I added a command to the commands_generator in Pilot called "group". I also updated Spaceship's client to have the ability to access TestFlight's Groups API endpoint to POST a group name to a specific application. I accessed this new client function by adding static functionality to the Spaceship::TestFlight::Group class to handle a new group.

2017-07-21 21:04 UTC, JeffreyGreenII commented
I signed it!

2017-07-21 21:08 UTC, JeffreyGreenII commented
I signed it!

2017-07-24 13:07 UTC, JeffreyGreenII commented
I signed it!

2017-10-24 18:38 UTC, ohayon requested changes
Hey @JeffreyGreenII ! Thanks for this PR this would definitely be great to have in fastlane! Just one comment above, would be curious to hear your thoughts!

2017-10-24 18:38 UTC, ohayon commented on pilot/lib/pilot/options.rb
> +                                     description: "The name of the group being made for external testers",
Could we maybe make a more specific name and description for this option? Just dont want people to confuse it with the `:groups` option above.

2017-12-04 20:27 UTC, ohayon commented
Hey @JeffreyGreenII, I am going to close this PR for now as we have made a bunch of changes to how pilot works because of some more changes that Apple made to TestFlight and I'm not sure that this PR is necessary anymore. I definitely could be mistaken here, so please feel free to comment here and reopen it if necessary! Thanks! 🚀

2017-12-04 20:27 UTC, closed without merging