[match] Update the error message so it describes better what's going to happen
fastlane/fastlane pull request #9895
Opened 2017-07-28 18:46 UTC by agisilaos

I liked one of the suggestions of @getaaron so this error message can describe better what will happen next so that's why I opened a PR to implement that. With that said, this is my first contribution to Fastlane and I would love to know your thoughts for this change. 

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
 If you check out #9889 issue many users are "scared" of the current situation of the context of the error message. So this change can bring more clarity to them as users of fastlane.
 #9889
 

### Description

I changed the context of the error message to 'UI.error "Warning: The :app_identifier value will be ignored - this will delete all distribution profiles for all your apps!" if had_app_identifier'. This change can make users feel "safer" and understand what is going to be deleted if they decide to do so.

2017-07-28 18:58 UTC, agisilaos commented
I signed it

2017-07-28 19:45 UTC, agisilaos commented
I think I made all the appropriate changes regarding CLA

2017-07-28 20:00 UTC, agisilaos commented
Now I think I fixed all the errors related to CLA

2017-07-28 20:02 UTC, agisilaos commented
yes I fixed them

2017-07-28 20:05 UTC, agisilaos commented
I signed it

2017-07-28 22:45 UTC, getaaron requested changes

2017-07-28 22:45 UTC, getaaron commented on match/lib/match/nuke.rb
> +          UI.error "Warning: The :app_identifier value will be ignored - this will delete all distribution profiles for all your apps!" if had_app_identifier
This change will make it incorrectly always say "distribution" if you are deleting non-distribution profiles

2017-07-31 21:16 UTC, KrauseFx commented on match/lib/match/nuke.rb
> +          UI.error "Warning: The :app_identifier value will be ignored - this will delete all distribution profiles for all your apps!" if had_app_identifier
Yeah, depending on if you run `nuke distribution` or `nuke development` 👍

2017-08-01 14:26 UTC, agisilaos commented on match/lib/match/nuke.rb
> +          UI.error "Warning: The :app_identifier value will be ignored - this will delete all distribution profiles for all your apps!" if had_app_identifier
Thank you for the comments! Will re evaluate & check it again, for the time being I need to figure out how to fix this cla thing.

2017-10-24 18:58 UTC, ohayon commented
Hey @agisilaos - dont worry about the CLA situation, you are good to go, sometimes it gets into a bit of a weird state. Let us know if you have a chance to make those changes that @getaaron and @KrauseFx mentioned above. Thanks!! 🚀

2017-12-04 20:33 UTC, ohayon commented
Hey @agisilaos, I am going to close this PR for now as it's been a while since there has been any activity on it. But please feel free to add commits and continue conversation here and we can reopen it! 😄 🚀 🐙

2017-12-04 20:33 UTC, closed without merging