Add pem option current_active_days_limit
fastlane/fastlane pull request #9924
Opened 2017-08-02 07:35 UTC by luikore

So user can specify how many days before current push certificate
expires should fastlane pem generate a new one.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I have many push certificates to renew.
And I need them renew before 32 days of expiry (just more than the longest month).

### Description
Added an option current_active_days_limit and the default value is same as previous hard-coded 30 days.

2017-08-02 14:54 UTC, ohayon requested changes
Hey @luikore, thanks so much for the PR! Welcome to the _fastlane_ community! ❤️  This is a good change I think. I just left a couple comments about the language we should use and what we should call the key and environment variable. Would love to hear your thoughts! 🚀  🐙

2017-08-02 14:54 UTC, ohayon commented on pem/lib/pem/options.rb
> +                                     description: "If current one is active for no more than this number of days, generate a new one. Default value is 30",
Could we change this description to say "If the current certificate is active for less than this number of days, generate a new one. Default value is 30 days."

2017-08-02 14:54 UTC, ohayon commented on pem/lib/pem/options.rb
> +        FastlaneCore::ConfigItem.new(key: :current_active_days_limit,
Can we change this key name to be something like `:active_days_limit` or something else that is a bit more self-explanatory?

2017-08-03 02:17 UTC, luikore commented on pem/lib/pem/options.rb
> +                                     description: "If current one is active for no more than this number of days, generate a new one. Default value is 30",
Sure. but, you know, the trailing `.` is not allowed in description.

2017-08-03 02:35 UTC, luikore commented on pem/lib/pem/options.rb
> +        FastlaneCore::ConfigItem.new(key: :current_active_days_limit,
OK, but I don't have a better name than `:active_days_limit`

2017-08-03 14:57 UTC, ohayon approved these changes

2017-08-03 14:59 UTC, ohayon requested changes
Hey @luikore, sorry I missed one thing in my initial review of this PR, just want to compare the value as a number rather than converting it to a string in the verify block. Thanks! 👑

2017-08-03 14:59 UTC, ohayon commented on pem/lib/pem/options.rb
> +                                       UI.user_error!("Value of active_days_limit must be a positive integer or left blank") if value.to_s !~ /\A\d*\z/
Can we check here `if value <= 0` instead of doing the string conversion and comparing against a regex?

2017-08-04 02:15 UTC, luikore commented on pem/lib/pem/options.rb
> +                                       UI.user_error!("Value of active_days_limit must be a positive integer or left blank") if value.to_s !~ /\A\d*\z/
OK

2017-08-04 14:58 UTC, ohayon approved these changes
Thanks @luikore 👍  🚀 !

2017-08-04 15:07 UTC, merged