Readme: Group toolchain list
fastlane/fastlane pull request #9957
Opened 2017-08-04 11:30 UTC by janpio

### Checklist
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
As a new user it took a bit of time to wrap my head around all the different tools available in fastlane's awesome toolchain. I was missing a list of what belongs where and is used for what, especially for tools that I don't need right now but could be useful down the lane (*ka-ching).

### Description
I took the list that was already part of the readme and grouped it by OS, then by "subject" of the tools. This way it is a lot easier for newcomers to "classify" all the tools of the fastlane toolchain.

2017-08-04 15:37 UTC, ohayon requested changes
Hey @janpio, thanks for this PR! This is a great organizational change. Just one comment about the position of _spaceship_, but otherwise 💯

2017-08-04 15:37 UTC, ohayon commented on README.md
> +- [`spaceship`](https://github.com/fastlane/fastlane/tree/master/spaceship): Ruby library to access the Apple Dev Center and iTunes Connect
Can we keep this one up with certificates and provisioning profiles for now?

2017-08-04 16:07 UTC, janpio commented on README.md
> +- [`spaceship`](https://github.com/fastlane/fastlane/tree/master/spaceship): Ruby library to access the Apple Dev Center and iTunes Connect
Sure - felt "wrong" here anyway. (Although: Spent most time of the PR thinking about a headline for this... :1st_place_medal: )

2017-08-04 16:52 UTC, KrauseFx requested changes
.

2017-08-04 16:54 UTC, ohayon commented
Hey @janpio, after a bit of discussion with the team, we are going to hold off on merging this change as we are going to be doing some work on our docs in the near future and going to take this type of thing into consideration 😄  Thank you so much for your contribution though and we are really happy to have you in the community! 🚀  🐙  🏎

2017-08-04 16:54 UTC, closed without merging

2017-08-04 17:04 UTC, janpio commented
Ok. If I am confused again I can look at the readme at my `patch-1` now ;)

2017-08-04 23:18 UTC, KrauseFx commented
Hehe :)

2017-08-29 11:39 UTC, janpio commented
Did anything happen in the last month regarding this topic?